### ISSUE TITLE
FidoDevices endpoint searching on wrong LDAP server

### ISSUE THREAD

**Issue by jajmo** [GluuFederation/oxAuth#1001]
Querying `/identity/restv1/scim/v2/FidoDevices` always searches the server configured in Cache Refresh (remote server), as opposed to the server where the FIDO authenticator data actually is (local server).

**Comment by willow9886** [comment]
This isn't the right repo for this issue. The /identity endpoint is exposed by oxTrust. Can you open a ticket with more details on https://support.gluu.org please? We will troubleshoot there and determine if it is a big. If so we will open on the correct repo and resolve. 

Thanks for your input.
