### ISSUE TITLE
Admin login after loggin out second time in same browser

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxAuth#1002]
Description:
Logout is not happening after user logouts second time in the same browser. Please refer below to reproduce 

1. Login to Gluu with admin credentials
2. Click on Logout
3. Click "Sign in Again' button
4. You are asked to provide credentials, enter username/password
5. Click on Logout
6. Click "Sign in Again' button

**Expected behavior**
User should be asked to provide credentials again as asked in Step 4 above

**Actual behavior**
User is logged in without being asked to login

 - OS: Ubuntu16.04LTS
 - Gluu version 3.1.6
 - Browser [ALL]

**Comment by willow9886** [comment]
Confirmed this is an issue in 3.1.6. Can we incorporate the fix into 3.1.6 @yurem ?

**Comment by sahiliamsso** [comment]
Thanks @syntrydy - Thought It has something to do with logout button.

**Comment by syntrydy** [comment]
@sahiliamsso this is  available just in 3.1.6

**Comment by yurem** [comment]
Fixed
