### ISSUE TITLE
Allow to refresh `ID Token` with grant_type refresh_token

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1003]
## Describe the issue
`refresh_token` grant type is for refreshing access token. However it's possible to refresh `id_token`. This is feature to allow refresh also `id_token`. Just the `iat` and `exp` claims should be updated per
[Referesh Token Response](https://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse)

## Steps To Reproduce
Refresh token at Token Endpoint. 

## Expected behavior
`id_token` is refreshed too.

## Actual behavior
`access_token` is returned.

**Comment by nynymike** [comment]
Ok, fine. Let's do it.

**Comment by miltonbo** [comment]
Ok, `/token` endpoint could also return a new `id_token` with `iat` and `exp` claims updated.
Should I include a flag to activate/deactivate this behaviour?

**Comment by miltonbo** [comment]
Current implementations allows `/token` endpoint returns an `id_token` with `iat` and `exp` updated. Considerations to generate it:
- `openidScopeBackwardCompatibility` json property should be true
- Scopes should contain `openid`

Here an example of the new generated `id_token` when client calls to `/token` endpoint with `refresh_token` grant type.

![image](https://user-images.githubusercontent.com/32613743/81820451-a2134f80-94fe-11ea-838a-e75f3223340b.png)

Here is shown the `id_token` generated in `/authorize` endpoint.

![image](https://user-images.githubusercontent.com/32613743/81820552-c40cd200-94fe-11ea-80f7-c64bbc4455b3.png)

**Comment by yuriyz** [comment]
Lets add also configuration property whether generate `id_token` or not `idTokenOnRefreshTokenEnabled` with false by default (since it's not defined in spec). 
Re: `openid`, it's ok since it's Connect, just add note about it in docs.

**Comment by yuriyz** [comment]
I've just looked into code and it looks like Yura already implemented it here https://github.com/GluuFederation/oxAuth/commit/547a56c267dd5109fe2a17ef8478b1fbead0ecbb

Lets leave it as is, closing this ticket.

**Comment by miltonbo** [comment]
After talking and reviewing it with @yuriyz we decided to close this issue, since there is a way to do this, which was mentioned by me before.
