### ISSUE TITLE
Adjust passport scripts to conform to new configuration structure

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#1020]
passport_social script reads some config from LDAP, and passport_saml from filesystem

We need to adjust scripts to correctly parse the newer config structure: https://github.com/GluuFederation/oxCore/issues/113

**Comment by jgomer2001** [comment]
Pending docs. I'll do a thorough revision on inbound identity docs when  https://github.com/GluuFederation/oxTrust/issues/1531 is finished.

**Comment by shmorri** [comment]
Documented [here](https://gluu.org/docs/ce/4.0/authn-guide/passport/#passport-configuration)

**Comment by sahiliamsso** [comment]
passport strategies are still not shown on login page.

**Comment by jgomer2001** [comment]
you reported it was working recently, so closing the issue
