### ISSUE TITLE
Move attributes mapping logic out of passport scripts

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#1021]
We will centralize attribute mapping at a single place: the node code. This will bring us better organization, will simplify our custom scripts, and at the same time offer more flexibility to specify custom logic when applying mappings. Transformation of data will also benefit from this.

Adjust the scripts and reorganize the node code accordingly.

**Comment by shmorri** [comment]
Documented here: https://gluu.org/docs/ce/4.0/tutorials/passport-attributes-mapping/
