### ISSUE TITLE
Regular expression validation should work on password expiry script

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxAuth#1027]
## Describe the issue
Password expiry script pages are old and the password renew don't validate regular expression assign to attribute.

## Steps To Reproduce
1. Add the password expiry custom script to Gluu server (https://github.com/GluuFederation/oxAuth/tree/master/Server/integrations/basic.password_expiration)
2. Enable that custom script
3. Set it as default authentication method
4. register the attribute **oxPasswordExpirationDate**
5. Register a use with that attribute set to to+90 days
6. try to login with that user

## Expected behavior
The UI should be well design and the attribute validation should work
## Actual behavior
none of these is working

## Screenshots

![image](https://user-images.githubusercontent.com/7513418/53476828-98293c00-3a73-11e9-979b-4691fdfe10ce.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/53507803-d72db080-3ab8-11e9-9f63-d592e461a8b1.png)

**Comment by sahiliamsso** [comment]
@syntrydy @willow9886 
Currently user is redirected to change password page without any notification, Should we display message that User password is expired and ask to reset
