### ISSUE TITLE
Not redirecting to application post logout on two instances and login on one

### ISSUE THREAD

**Issue by mogluu** [GluuFederation/oxAuth#1039]
> 
    - Log in to instance #1 of app in tab #1 with user A (successful)
    - Open a 2nd tab to instance #2 of our app in tabl #2 with user A (no authentication required)
    - Log out of instance #1 in tab #1 (release gluu token)
    - Both instances/tabs are redirected to the Gluu login page
    - In instance #1/tab #1, enter credentials to log in with user A (successful)
    - In instance #2/tab #2, enter credentials to log in with user A (success, but never redirected back to application)

[Associated to this ticket](https://support.gluu.org/authentication/6769/multiple-logins-to-different-urls-using-same-gluu-server-can-lead-to-no-redirections-back-to-our-application/#at46174)

**Comment by yurem** [comment]
There is same issue with 4.0 scope: https://github.com/GluuFederation/oxAuth/issues/1029
