### ISSUE TITLE
Move to PKCS #11 for signing

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxAuth#104]
currently the private key is stored unencrypted in the oxauth config ldap entry. This should be two-way encrypted and decrypted once upon startup or key regeneration and kept in memory. @yurem perhaps you can assess this and determine whether you can take it or if we should assign it to someone else.

**Comment by nynymike** [comment]
I think the answer to this is to add a [Soft HSM](https://www.opendnssec.org/softhsm) component to the Gluu Server, and update the OpenID Connect OP to use the PKCS #11 interface for signing operations.
