### ISSUE TITLE
Client authorization live in LDAP forever. Need to move it under client entity to clean it up

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1042]
## Describe the issue
Currently client authorizations are stored under `user` entity e.g. `inum=@!2128.9AFB.B310.EB30!0001!690B.5F8F!0000!B1F3.AEAE.B798,ou=people,o=@!2128.9AFB.B310.EB30!0001!690B.5F8F,o=gluu` and are NEVER removed.

If configuration sets to store it in LDAP then database grows and slow downs. We have to move client authorizations under client.

## Steps To Reproduce
Enable client authorizations with persistence to ldap and run it a lot

## Expected behavior
Client authorizations must be removed if client is removed.

## Actual behavior
Client authorizations are never removed

**Comment by yuriyz** [comment]
Fixed in master, now client authorizations are stored under client entity (not under user/people entity).

**Comment by yuriyz** [comment]
reopened, we reverted this change. After discussion it seems to be good idea to keep it under user entity.

**Comment by yuriyz** [comment]
We need : 1) cleaner to go over client authorizations 2) add property whether we want to keep authorization even if client expired (@willow9886 propose to keep it because it can be useful)

**Comment by nynymike** [comment]
Should this be closed? And it's unclear what was actually done! It was done, then reverted...?

**Comment by yuriyz** [comment]
Closing it. Yes, it was done (moved under client and cleared on expiration) and then reverted. According to Will we should keep client authorizations even if client expired because it's useful.
