### ISSUE TITLE
Resource Owner Password Credential Grant Interception Script Buggy Logic

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxAuth#1052]
According to [the docs](https://github.com/GluuFederation/docs-ce-prod/blob/3.1.5/docs/source/admin-guide/custom-script.md#resource-owner-password-credentials) , when there is at least one RO PW Interception script active , authentication should work this way : 

1. If within the script the `authenticate(self, context)` function sets the user to `null` with `context.setUser(None)`, then authentication is supposed to fail (40x HTTP response) 
2. If within the script the `authenticate(self, context)` function returns `true` (regardless of what the user is set to) , then authentication succeeds (200 HTTP response).

Scenario 1 isn't working , as setting the user to `null` and returning `False` still generates an HTTP 200K.

How to reproduce the issue 
===============================

1. Add a RO PW Grant Interception script 
2. Implement the `authenticate(self, context)` function like this 
     ```python
      def authenticate(self, context):
         context.setUser(None)
         return False
     ```
3. Using valid credentials , send a RO PW Grant OAuth Request using an OAuth client. 
4. The Server responds with an HTTP 200 OK instead of an HTTP 40x Unauthorized 

Fix 
===================================

The fix is contained  [here](https://github.com/uprightech/oxAuth/commit/57440c83b28c6a2b9de5b54ed1054d1c19688f45). Can I send a pull request @yurem  ?

**Comment by yuriyz** [comment]
I will check.

**Comment by yuriyz** [comment]
@shmorri please move 3.1.6 changes to 4.0. (docs commits above).

**Comment by yuriyz** [comment]
Fixed in master.
