### ISSUE TITLE
URL-Encoding problem when retrieving value of custom param of authz request?

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#1058]
Suppose the following authorization request URL
`https://...host.../oxauth/restv1/authorize?response_mode=query&response_type=code&client_id=5b4c961a-754c-4b14-a420-56ca60f1fae9&scope=openid%2Bprofile%2Bemail%2Buser_name&redirect_uri=http%3A%2F%2Fpassport-saml-demo-app.example.com%3A3000%2Fprofile%2F&preselectedExternalProvider=eyJzYWx0IjoiUnpGS3MiLCJwcm92aWRlciI6InNhbWwtaWRwIn0%3D&state=5290204928&nonce=6424031266&acr_values=passport_saml`

![encoding](https://user-images.githubusercontent.com/5444180/56508700-98313f80-64ea-11e9-881e-a8ea16608ee9.png)

where `preselectedExternalProvider` is a custom param for authz requests added via oxTrust.

Here the actual value passed for `preselectedExternalProvider` is `eyJzYWx0IjoiUnpGS3MiLCJwcm92aWRlciI6InNhbWwtaWRwIn0=`.  Due to url-encoding, it looks this way in the URL address bar: `eyJzYWx0IjoiUnpGS3MiLCJwcm92aWRlciI6InNhbWwtaWRwIn0%3D` 

If I try to retrieve this value from a cust script doing `sessionAttributes.get("preselectedExternalProvider")` I'm getting `eyJzYWx0IjoiUnpGS3MiLCJwcm92aWRlciI6InNhbWwtaWRwIn0%3D` and not `eyJzYWx0IjoiUnpGS3MiLCJwcm92aWRlciI6InNhbWwtaWRwIn0=`. 

Am I supposed to do the conversion my own, or is it a conversion problem on oxAuth side?

**Comment by qbert2k** [comment]
Hello @jgomer2001 ,

For this kind of requests it is recommended to use Base64url Encoding instead of just Base64 Encoding.

You can use the functions at org.gluu.oxauth.model.util.Base64Util

https://github.com/GluuFederation/oxAuth/blob/master/Model/src/main/java/org/gluu/oxauth/model/util/Base64Util.java#L23

**Comment by jgomer2001** [comment]
Sounds good @qbert2k , closing...
