### ISSUE TITLE
[Bug]"Double authentication" during OIDC workflow. Some legacy code's leftovers?

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#106]
I'm unsure what actually happens and how to describe this properly.

Preconditions:
1. Better use latest Firefox as browser. If you have used it to log in to ce-release before, open its "Clear history" tool, check "Active logins" option in the list, select "Everything" in the "Time range to clear" drop-down, click "Clear now"
2. Remove all ce-release cookies from browser's cookies jar
3. A test client registration for SF's oidc client was created at ce-release by me, it's named salesforce-test. Its settings provided on the picture below: ![clnt-reg](https://cloud.githubusercontent.com/assets/11802046/11790595/a9b19bcc-a2ad-11e5-910d-3d2b2c74e59d.png)
4. Examples in reproduction section use 2 test users as examples. (**Do not use these accounts when trying to reproduce**. I can't even remove them due to another bug). Another 2 new (never used before) accounts were created at ce-release by me, their creds are "testusr3 / 1q2w3e" and "testusr4 / 1q2w3e4r", use testusr3 where testusr1 mentioned, and testusr4 instead of testusr2. You also can create your own 2 new accounts.
5. No need to complete the full oidc workflow exists, to see what happens it's enough to follow their staging url: https://login.salesforce.com/services/auth/test/00D28000001318JEAQ/thisisatest2

Steps to reproduce:
1. Put the staging url into Firefox's address bar and hit "Enter". In case you have been taken straight to the ce-release's login page - **do not login there!** Try to follow this url again and again, until you've got a pop-up window shown on the picture "oxauth-popup.png" below. In case you still can't get this pop-up after several attempts, try to remove all ce-release cookies from browser's jar, and follow the url again. ![oxauth-popup](https://cloud.githubusercontent.com/assets/11802046/11790284/086a1df8-a2ac-11e5-938f-1f9c3989db17.png)
2. After pop-up has appeared, put the creds of the first test user in there. You should become authenticated and immediately sent back to SF's callback url (i.e., you won't be asked to authorize release of requested scopes!). As you can see on the picture "1st-usr-loggedin-noauthz.png" below 
![1st-usr-loggedin-noauthz](https://cloud.githubusercontent.com/assets/11802046/11790384/836adb6e-a2ac-11e5-8258-93de194d20ff.png) login workflow was completed successfully (without user's authorization) and claims were sent to RP. Another strange thing is how HTTP GET request to ce-release looks like, as shown on picture "req-http-authz.png":![req-http-authz](https://cloud.githubusercontent.com/assets/11802046/11790403/9efb4f76-a2ac-11e5-9f0b-212993b524b7.png) It contains user1's credentials in "Authorization:" header, what, as far my understanding goes, doesn't quite fit any usual Gluu's login/request workflow.
3. This step is somewhat tricky. Without clearing browser's history and cookie jar, you need to again follow the staging url. There are 2 possible outcomes: you either will get the same results displayed on picture above (depicting successful login of the first user), or you'll be taken to ce-release login page, it's, like, 50/50, I can't see any pattern here(though sometimes it almost looks like they are presented one after another). You need the later result, the login page. When you have reached it, login with credentials of 2nd test user. You'll be sent back to SF's callback url, as before, but claims displayed there will still belong to the 1st user. It's not just about incomplete login workflow, it was the same when I tested a complete sequence before - it will always be the first user you are logged as at RP, despite you use creds of the 2nd user when logging in at Gluu. The oxauth.log on ce-release also reveals intresting details (check [a fragment of it](https://github.com/GluuFederation/oxAuth/files/61578/oxauth-testusr2-login.txt)): you can see that login process is initiated for testusr2, but half-way into it testusr1 suddenly pops out.

If you would ignore that "oxauth pop-up" initially and would log in at login page as first test user, then your OIDC workflows would have worked as they should. So it's most likely not an issue on SF's side.

**Comment by willow9886** [comment]
@aliaksander-samuseu do you know if this issue has been resolved?

**Comment by aliaksander-samuseu** [comment]
@willow9886, no, haven't heard anything about it from @yuriyz

**Comment by yuriyz** [comment]
@aliaksander-samuseu @willow9886 issue was fixed as part of another issue here https://github.com/GluuFederation/oxAuth/commit/622a7a09ac6af920aad4281442ed3ff0c94cf158
