### ISSUE TITLE
Configure Supported algorithms

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1062]
Some organizations may have preferences about which algorithms they want to allow. It would be better if the supported algorithms were stored in the JSON properties, rather then hard coded. There are supported algorithms for discovery, but are clients prevented from registering these algorithms? 

Also see: https://github.com/GluuFederation/oxTrust/issues/1626

**Comment by miltonbo** [comment]
I reviewed the current implementation and I saw that we already have many algorithms as json properties, for instance some of them are `userinfoSigningAlgValuesSupported`, `userinfoEncryptionAlgValuesSupported`,  `idTokenEncryptionAlgValuesSupported` and others.

Also we can change which algorithms are supported and which are not from oxTrust, here a screenshot of some of them:
![image](https://user-images.githubusercontent.com/32613743/80488154-e8c44f80-892b-11ea-8e70-4620b8e2d2cd.png)

Could you give me more detail about this task? Thanks in advance.

**Comment by nynymike** [comment]
I believe this is used for discovery, but does not actually control which algorithms a client can register.

**Comment by miltonbo** [comment]
Ok, got it. I just tested this case in my local env with the lastest version and yes, we have json properties to configure those algorithms, but we are accepting algorithms supported and those that are not supported according to the json configuration.
I will add that validation in client registration endpoint then.

**Comment by miltonbo** [comment]
Algorithm validation method has been implemented according to the json configuration.
