### ISSUE TITLE
NPE in oxauth with couchbase: Unable to access Admin UI after few days of usable when backend is couchbase

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxAuth#1065]
## Describe the issue
I setup Gluu 4.0 latest with CouchBase on Friday, work with it Saturday and Sunday but when I start the VM on Monday and try to log into admin UI, I get **oops** screen

## Screenshots

![image](https://user-images.githubusercontent.com/7513418/57212069-6cc64e80-6fda-11e9-9723-c5a0097360f9.png)

## Trace
[oxauth.txt](https://github.com/GluuFederation/oxTrust/files/3146906/oxauth.txt)

**Comment by mbaser** [comment]
oxauth starts before couchbase. On Ubuntu 18, all services are started via systemd scripts, but on CentOS7 couchbase is started via systemd, and oxauth started via init.d scripts.

**Comment by mbaser** [comment]
This issue is moved to https://github.com/GluuFederation/community-edition-setup/issues/532
Hence closing.
