### ISSUE TITLE
Check if oxauth-client 4.0 JSON is compatible with oxauth-server 3.1.x

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1066]
In 4.0 we implemented major update https://github.com/GluuFederation/oxAuth/issues/811
In oxAuth in many places we build JSON manually using JSONObject and JSONArray. Are there tests which can check automatically if older server can work with new client? Maybe we need to add tests with hard-coded JWT, JSON to check compatibility. The main part which we need to test enum, JSONArray <-> JSON conversion. These tests will be also useful during resolving https://github.com/GluuFederation/oxAuth/issues/1064 issue.

**Comment by yuriyz** [comment]
we run oxd 4.0 tests (which behind the scene is using oxauth-client 4.0) and all tests are passed against oxauth-server 3.1.6. It does't cover all cases, but most important should be covered.

![image](https://user-images.githubusercontent.com/2013070/61119536-b8e2b300-a4a3-11e9-95b4-b935ee160400.png)

**Comment by qbert2k** [comment]
The change of the JSON lib does not affect compatibility between old 3.1.6 version and new 4.0 version.
There is one code change that is not backward compatible #950. But is is because the way the address claim is returned, not because the change in the JSON lib.

**Comment by yurem** [comment]
Thank you for checking this
