### ISSUE TITLE
Claims from "memberOf" ldap atribute

### ISSUE THREAD

**Issue by mgrzybowski** [GluuFederation/oxAuth#107]
Hi
  Gluu-server24 (2.4.0-2) do not present "memberOf" user ldap attribute as claim ( or claims ) to RP.

Steps to reproduce:
 - add few "memberOf" attributes to user, Gluu gui do not support add or delete multiple attributes of the same name, so You need to add them by hand or import:
```
dn: inum=@!AB0C.0D5D.4748.501D!0001!77A6.F669!0000!5624.5FFB,ou=people,o=@!AB0C.0D5D.4748.501D!0001!77A6.F669,o=gluu
changetype: modify
add: memberOf
memberOf: bleble1,ou=xxx
memberOf: bleble2,ou=yyy
```
 - add "memberOf" to "profile" scope
 - log in to RP as user, request "profile" scope , check claims ( no "memberOf" )

Lack of this functionality, prevent to use apache mod_auth_openidc as in place replacement for mod_authnz_ldap when used with "require ldap-group"  .

**Comment by nynymike** [comment]
Please open this issue on https://support.gluu.org with more information on oxAuth configuration--did you register this attribute, did you add it to a scope? Was the the scope released to the client?
