### ISSUE TITLE
Enrolled Super Gluu Devices Get Deleted

### ISSUE THREAD

**Issue by uprightech** [GluuFederation/oxAuth#1070]
## Issue Description
After enrolling a super-gluu device to a user , if the user logs out , approximately five minutes (600 seconds) after logging in  and tries to login back , he is asked to enroll a new device as if he didn't do that previously.  A look at the enrolled devices for the user with an ldap browser shows the device(s)  was(were) deleted.

## Steps To Reproduce
Here is how to reproduce the issue
1. Enable super-gluu authentication on Gluu Server 
2. Login using a user without a device enrolled. 
3. Logout after about 5 minutes 
4. Login again , you will be presented yet again with the device enrollment screen.

## Origin Of The Problem 
The problem appears to stem from  `org.gluu.oxauth.service.CleanerTimer`. 
When it is enabled , and with the log level set to the lowest (TRACE) , one can clearly see the CleanerTimer being triggered and deleting entries under 
`ou=fido,inum=<user_inum>,ou=people,o=gluu` if they exist (a.k.a enrolled super-gluu devices).

Also , the issue ceases once cleanServiceInterval is set to a negative value (i.e. the CleanService is disabled). Which further points to said class as the culprit. 
Logs can be provided if needed. 

## Test System 
 - OS:  Ubuntu16.04 LTS
 - Gluu Version 4.0

**Comment by uprightech** [comment]
Upon further review, I noticed the cleanup timer will cleanup items when two  attributes
 have a certain value:
1. `oxDeletable` which must be set to true 
2. `oxAuthExpiration` which is when the entry should expire. And it should be equal to or less than the current time. 
That said @yurem , would it not be good if at least by default `oxDeletable` set to `false` for super-gluu devices to be consistent with pre-existing behaviour ?

**Comment by yuriyz** [comment]
Lifetime of registration device is set to 90 seconds. While in use case above you've tested it with 5 minutes which is more then 90 seconds. 
@yurem is there any background for 90 seconds lifetime?

**Comment by uprightech** [comment]
@yuriyz the 5 minutes , corresponds to the 600 seconds (5 minutes) default when the CleanerTimer is triggered , irrespective of the device registration lifetime. 
Also, based on what you just said , am I correct to assume that once the a device is enrolled/registered , it will remain so only for 90 seconds ? Which in my opinion is an inconvenience as it pushes clients to re-register their devices at least every 90 seconds or so.

**Comment by yuriyz** [comment]
Correct, since device registration lifetime is 90 seconds it's removed.

**Comment by yuriyz** [comment]
Device registration is removed even after successful registration.

**Comment by yuriyz** [comment]
Fixed in master.
