### ISSUE TITLE
Move tokens, RPT, (authorization grants) to ou=client_token (outside client entry)

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1073]
We are trying to split static/dynamic entries to allow us map them properly to right bucket types.

clients are pretty static, but tokens are not. Can we move tokens and other entries with short lifetime to `ou=client_token` ? For exple:
ou=client_token
 |-ou=token
   |-inum=client_inum
     |-uniqueIdentifier=316ade53-13e6-402b-84cb-40e3eced49c6 (token entry)

Also there is similar question about `clientAuthorizations`.

If you think it's not possible in 4.0 please, move it to 4.1.

**Comment by yuriyz** [comment]
It's not just moving but changing behavior. Right now when we keep client related data under client entry if client is expired, we can remove client entry and all related data are dropped automatically. We got it for free with LDAP. With couchbase we don't have such handling, do we ? We should handle it on application layer. So when we move client childs outside then it should be properly dropped if client is removed.

**Comment by yuriyz** [comment]
It's done already in 4.0.
