### ISSUE TITLE
Check expiration of JWT encoded profile used in passport flows

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#1078]
Not only do we need to check the signature of the received JWT-encoded profile data but the expiration time. If expired, authentication should be denied

Some background here: https://support.gluu.org/single-sign-on/6669/jwt-expiration-validation/#at48536

**Comment by yurem** [comment]
Fix for this: https://github.com/GluuFederation/oxAuth/commit/378f5fe617b190362b7936f445eee744c48096a3

**Comment by jgomer2001** [comment]
I think this wasn't QA'd, the following is always shown in oxauth_script.log `"Exception: The JWT does not have 'exp' attribute"` (python `datetime` was not imported)

**Comment by jgomer2001** [comment]
fixed in 4.1/4.2
