### ISSUE TITLE
Session API should log error message only on real error

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1080]
We need to review all scenarios where we print error message in Session part. For example this message 
`org.xdi.oxauth.service.SessionIdService: Faces context returns null for http request object.` is not real error because user still can log in.

This message can be result of another problem. In Rest endpoints FacesContext not exists. Hence session API should know which context object to use JSF or Rest to get cookies, etc..

More details are here: https://support.gluu.org/maintenance/7093/verbose-logging/#at48670

**Comment by yuriyz** [comment]
Corrected in master for `SessionIdService`.
