### ISSUE TITLE
`invalidateSessionCookiesAfterAuthorizationFlow=true` leads to authorization failure 

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1083]
## Describe the issue
The bug is reproducible. Problem is that after cookies invalidation, server unable to identify session and as result internal `identity` is not set which is considered as not authenticated user. As result user is redirected to login page all the time.

Issue reported on https://support.gluu.org/authentication/7115/issue-with-invalidatesessioncookiesafterauthorizationflow/

## Steps To Reproduce
1. Set invalidateSessionCookiesAfterAuthorizationFlow=true
2. Login to any RP (e.g. oxtrust).

## Expected behavior
User should be redirected to RP after successful login.
## Actual behavior
User is redirected to login after successfull login.

## Desktop (please complete the following information):
 - OS: Ubuntu16.04LTS
 - Gluu version 3.1.6

**Comment by yuriyz** [comment]
Fixed in `version_3.1.6.sp2` and `master` branches.

**Comment by sahiliamsso** [comment]
still able to reproduce on latest 4.0 build

**Comment by yuriyz** [comment]
Tested this on `ce-dev5.gluu.org` with `identity`. I can successfully login after `invalidateSessionCookiesAfterAuthorizationFlow=true`, hence it works.

![image](https://user-images.githubusercontent.com/2013070/61647585-5022e400-acb6-11e9-8dab-78a35f40254a.png)
