### ISSUE TITLE
Barcode for otp verification is showing.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxAuth#1087]
!

 Describe the issue
Not able to login through otp verification due to the absence of barcode in second step.
## Steps To Reproduce
1. Go to Configuration > Manage Custom Scripts
2. Click on the Person Authentication tab
3. Find the OTP script
4.Enable the script by checking the box
5. Scroll to the bottom of the page and click Update.
6. Then go to Navigate to Configuration > Manage Authentication
7. Select the Default Authentication Method tab
8. In the Default Authentication Method window you will see two options: Default acr and oxTrust acr. change both fields to OTP.  
9. Logout and try to login.
10. See the error.

Expected behavior
Barcode should be there and user should be able to login

Actual behavior
Black space is shown in place of barcode.

Desktop (please complete the following information):
 - OS: Ubuntu 18
 - Gluu version 4.0
 - Browser Mozilla Firefox
 

![Screenshot from 2019-06-03 22-06-42](https://user-images.githubusercontent.com/34593983/58896415-95458380-8713-11e9-8a5f-426a2e6b3160.png)

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/59084139-f460ef00-88f1-11e9-94ab-b60c17e542e7.png)
