### ISSUE TITLE
JWT header typ must be JWT

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxAuth#109]
See tickets:

https://support.gluu.org/view/integrations/aspnet-error-jwt-header-type-specified-must-be-jwt-type-received-jws/2265

https://support.gluu.org/view/integrations/net-relying-party-receiving-invalid-jwt-header-typ-es/2261

**Comment by yurem** [comment]
Can you merge this into master. I will update 2.4.1after that and rebuild it.

**Comment by qbert2k** [comment]
There was merging issues, now they are fixed and merged into master branch.

**Comment by ciaranj** [comment]
Thank you, I'll test as soon I see a package :)
