### ISSUE TITLE
Passport login page is not looking good after js/css library update

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxAuth#1094]
We applied an update to JS/CSS library and that lead to some UI/UX issue on some login page.
The most affected is the passport login page.

We have to update it.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/59292383-dfc78280-8c74-11e9-9192-c574ce38c2df.png)

**Comment by sahiliamsso** [comment]
If you provide incorrect password, then alignment breaks
![image](https://user-images.githubusercontent.com/21104811/59641852-e5b7da80-9130-11e9-857e-4e2c5efa6da6.png)

**Comment by syntrydy** [comment]
@sahiliamsso the changes aren't available in the latest package. Wait for next package.

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/59850548-6b6e9c80-9362-11e9-9948-78f95327ec68.png)

![image](https://user-images.githubusercontent.com/7513418/59850616-9953e100-9362-11e9-8c58-1581f3f43b14.png)
