### ISSUE TITLE
Remove tokens update on authorization grant list update

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1097]
We need to try to update code to not try to search using secondary keys after entry persistence during at least 200 ms after persistence.

Current code has flow which we can remove or rewrite. `AuthorizationGrant.save()` do search for tokens by secondary key `oxAuthGrantId`. We call this methods twice. First time on create and second time on id_token generation. Duration between id_token generation and it creation can be less than 200 ms. As result search by `oxAuthGrantId` will return nothing.This led to issue. Token(s) will have missing attributes or out of date issues.

I've applied 2 changes to set all token properties during first persistence:
https://github.com/GluuFederation/oxAuth/commit/6dee10b961fd91047cd7586e9f4c716ccb764a5b
and
https://github.com/GluuFederation/oxAuth/commit/b092079140e65601d07d3762c71abea8ec3bf638

This resolve token issues. But we still have question. Why `AuthorizationGrant.createIdToken` call authorization grant `save()` and consequent tokens update? Can we remove tokens update here?

Please, review commits which I put into issue description.

**Comment by yuriyz** [comment]
I think these 2 commits are right. It comes from `AuthorizationGrantLdap` and at that time idea was to save it asynchronously. Sync data seems to come to us from svn. But now, when we don't have grant object on persistence layer, such operations looks redundant to me. I will check.

**Comment by yuriyz** [comment]
Removed redundant save() during id_token creation. We don't have such calls during other tokens creation. So we should be good now.
