### ISSUE TITLE
Store tokens under ou=tokens

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1106]
Instead of storing tokens under ou=clients we need to store tokens under ou=token.
This will increase performance because we can do search by dn/key instead of using filter like `oxAuthTokenCode=HashedToken(code))`

Instead of code as RDN we need to use HashedToken(code). This should not led to data collisions because code is UUID. And  HashedToken(UUID) should be unique as well.

**Comment by yuriyz** [comment]
We are going to drop UUID and rely on token code only in DN.

**Comment by yuriyz** [comment]
done in master
