### ISSUE TITLE
Cleaner for couchbase : re-use TTL

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1107]
## Describe the issue
Couchbase has built-in auto-expiration. We should try to re-use it

https://developer.couchbase.com/documentation/server/3.x/developer/dev-guide-3.0/doc-expiration.html

**Comment by yurem** [comment]
I think we can move this to 4.1. What do you think?

**Comment by yuriyz** [comment]
Moved but I think I will be able to include it into 4.0, lets see.

**Comment by yuriyz** [comment]
This feature is already implemented in 4.1.1.

**Comment by yuriyz** [comment]
https://github.com/GluuFederation/oxCore/issues/127
