### ISSUE TITLE
UMA 1.0.1 : use signed JWT RPT

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#111]
UMA 1.0.1 : use JWT RPT

**Comment by yuriyz** [comment]
publish whether PAT/AAT are JWT on /.well-known/uma-configuration

**Comment by yuriyz** [comment]
RPT can be both JWT or access_token. It should be configurable via oxauth configuration.

**Comment by yuriyz** [comment]
Support to issue RPT as JWT is added:
1) RPT manager issue JWT or generated string depending on oxauth configuration
2) publish rpt_as_jwt=true/false on /.well-known/uma-configuration
3) corrected oxtrust json schema https://github.com/GluuFederation/oxTrust/commit/9b482056b154664cbaac47413fead47da33f706e
4) decision is performed based on oxauth configuration

**Comment by nynymike** [comment]
How is the RPT signed? Should the RPT signing algorithm also be specified in /.well-known/uma-configuration ?

**Comment by yuriyz** [comment]
@nynymike it is signed based on client information for ID Token: 
http://openid.net/specs/openid-connect-registration-1_0.html#RegistrationRequest
* id_token_signed_response_alg
* id_token_encrypted_response_alg
* id_token_encrypted_response_enc

I've stick to ID Token signing&encryption info. Do we want to keep that separately for RPT? If yes then we need to add it to dynamic client registration.

* rpt_signed_response_alg
* rpt_encrypted_response_alg
* rpt_encrypted_response_enc

**Comment by nynymike** [comment]
Let the client register specifying signing for the id_token--we can just re-use for the rpt. But I think we should explicitly list this in uma discovery so its clear.

**Comment by yuriyz** [comment]
reopened the issue : we need to add signing&encryption info explicitly to uma discovery.

**Comment by yuriyz** [comment]
We have to publish on uma discovery following:
* rpt_signing_alg_values_supported
* rpt_token_encryption_alg_values_supported
* rpt_encryption_enc_values_supported

**Comment by yuriyz** [comment]
Done in https://github.com/GluuFederation/oxAuth/commit/cb5d08e451c92f9616bdc8ff3901cda68a581b8e
