### ISSUE TITLE
Add ability to take acr with higher level when multiple values are in `acr_values`

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1111]
## Describe the issue
Add ability to take acr with higher level when multiple values are in `acr_values`.
It must be configurable.

Related to
https://github.com/GluuFederation/community-edition-setup/issues/431#issuecomment-506349684

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/58
