### ISSUE TITLE
Add OpenID Connect front channel logout custom interception script

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1113]
On front channel OpenID Connect logout, oxAuth loads the grant, finds all the clients assosciated with it, and then renders this response:

```
            html += "<script>" +
                    "window.onload=function() {" +
                    "window.location='" + postLogoutUrl + "'" +
                    "}" +
                    "</script>";
        }

        html += "<title>Gluu Generated logout page</title>" +
                "</head>" +
                "<body>" +
                "Logout requests sent.<br/>" +
                iframes +
                "</body>" +
                "</html>";

```
We should introduce a new interception script that enables the admin to change or override this response.

**Comment by yuriyz** [comment]
Support tickets related to it:
https://support.gluu.org/single-sign-on/4060/single-logout-is-using-hard-coded-html/
https://support.gluu.org/customization/6606/customization-of-the-logout-process/

**Comment by yuriyz** [comment]
Added interception script for front channel logout in 4.2.
