### ISSUE TITLE
Gluu 4.0 QA - Duo script failing due to jquery

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxAuth#1117]
Steps to reproduce:
1. Enable DUO script and try to login

Expected result : After providing password, user should be asked for DUO login 
Actual: No screen is displayed after providing username and password

![image](https://user-images.githubusercontent.com/21104811/60846735-6016d000-a1ae-11e9-81e5-2f8d30442e65.png)

Logs
![image](https://user-images.githubusercontent.com/21104811/60846748-6f961900-a1ae-11e9-8d22-6b86cc2dbe87.png)

Environment: Gluu4.0 CentOs7.3 with couchbase as DB

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/61215407-b6ca5f80-a702-11e9-96b2-484fbf31d1a7.png)
