### ISSUE TITLE
Save generated sub when paiwiseidtype is set to algorithmic.

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxAuth#1119]
## Describe the issue
There are cases where save the generated **sub** value for pairwise id is important.

When the **pairwiseidtype** setting in oxauth json configuration is set to **algorithmic** we need have to save the computed value as we do for **persistent** type.

**Comment by nynymike** [comment]
If you want to save the pairwise id, that's when you'd use persistence pairwise identifiers.
