### ISSUE TITLE
Authentication against LDAP backend stops working properly when 2nd (failover) server is added and connection to the 1st one is lost.

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#112]
Please refer to the picture for additional details:
![oxauth-2srvs 1](https://cloud.githubusercontent.com/assets/11802046/11959565/1988887a-a8df-11e5-9ba9-70c8267732e2.png)
1. Configure CR to pull user data from some LDAP backend and oxauth to authenticate against it
2. Try to log out/log in for several times in a row. It should work okay
3. On the "Manage authentication" page add 2nd LDAP server (with exactly the same user base, i.e. another DC of the same AD domain)
4. Try to log out/log in for several times in a row. It should work okay. You can switch it to SSL-ess communications and use wireshark to monitor what happens on the link, it should show that authentication happens against 1st LDAP server in the list on the "Manage authentication" page.
5. Simulate outage for the 1st server (disable its network connection or pause the vm). You should observe oxAuth behavior passing through the next stages:
   1. Somewhat prolonged interruption of login functionality for the first time you will try to log in after 1st server "went down". Login form just hangs in a loop, wireshark shows it still tries to contact 1st LDAP server in the list. You may try to refresh the page to speed the things up
   2. Now it finally switches to the 2nd server and usually will allow you to log in once. Log out from it after that.
   3. Try to log in again. It may work one more time, but usually it won't and for a many subsequent login attempts/for a significant amount of time it just responds that your credentials aren't correct. At the same time java error trace starts to appear in the wrapper.log (see [a fragment](https://github.com/GluuFederation/oxAuth/files/67869/oxauth-2srvs.1.txt) of it), interrupting the login workflow right after the search in internal db (using "uid" attribute as local key) happens. Wireshark and wrapper.log also show that both searches against backend and internal LDAP result in a success, exactly the same way as in a case of normal, uninterrupted login workflow. Something bad happens after that step.

I'm not sure what makes it work again, it just will allow you to log in again after some time/or mb number of failed attempts. If you'll log out after that, the issue will most likely occur again.

**Comment by willow9886** [comment]
@aliaksander-samuseu What version is this? Has this issue been resolved?

**Comment by aliaksander-samuseu** [comment]
@willow9886 , that was for 2.4.0-x , can't quite remember (really should start to specify exact version for each report, it actually has to be this way, sorry). I know nothing about its status, will need to check.

**Comment by willow9886** [comment]
@aliaksander-samuseu can we recheck this?

**Comment by aliaksander-samuseu** [comment]
@willow9886 Yes, it's still the case. After first server is taken out, there are huge problems with logging in to the web UI. Sometimes (under unclear circumstances) it allows to log in, but most times it does not. Restarting service doesn't help. After 1st server is added back to setup it starts to work normally again (after oxauth has detected that it's now available and switched back to using the 1st server again)

**Comment by aliaksander-samuseu** [comment]
@willow9886 I even have got impression this switch from one server to another won't even happen correctly without a restart. In any case, this feature still needs some attention.

**Comment by nynymike** [comment]
Assigned to @shekhar16 to verify and fix if its a confirmed problem.

**Comment by shekhar16** [comment]
can u please share me the complete process to create Ldap server?

**Comment by nynymike** [comment]
Its not cache refresh, its under manage authentication. Look in the first screenshot attached to this issue: you'll see that there are two servers.

**Comment by aliaksander-samuseu** [comment]
@willow9886  @nynymike @shekhar16 I'm sorry, I was sure I commented there too, but instead my comment went to the 2nd ticket me and Shekhar work together on.
A quick updated: Shekhar is trying to configure Gluu for backend authentication atm, so he would become able to verify and start fixing it.
@nynymike , Shekhar needs to understand how to configure CR so he would be able to setup his Gluu CE instance to authenticated against 2 identical backends, to reproduce and then find the cause of this bug. We are working on it.

**Comment by nynymike** [comment]
I'm closing this issue. If it's discovered as a bug during new QA, a new issue should be raised or this one re-opened.
