### ISSUE TITLE
[Manage authentication] A purpose of the "Activate/Deactivate" button and "Enabled" checkbox on the page needs to be clarified.

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#113]
It seems that purpose of the feature to disable "something" on the "Manage Authentication" page needs clarification, or even new implementation. At the moment the feature doesn't work at all (throws an error). @yurem believes that this feature should switch off backend connection completely, reverting to auth against internal db. If I got him right, it should not remove the backend's configuration, but just allow to temporarily "fall back" to authentication against already configured internal LDAP directory. Then you could unset this flag and your already fully-setup backend configuration should appear again, ready to be applied.
There also could be another meaningful purposes for this, like it could allow to temporarily disable all SSO request serving, and, possibly, even prevent users from logging in to oxTrust through oxAuth web login form, except for members of admin group (with optional ability to instantly log out all currently logged in users). Something like maintenance/lockout mode for the case of emergency.
Or 2 buttons implementing both functionalities could be added here.

**Comment by willow9886** [comment]
@nynymike has opened a new issue for this the oxTrust repo: https://github.com/GluuFederation/oxTrust/issues/190
