### ISSUE TITLE
Make front-channel logout page customizable

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1136]
The page where iframes for front-channel logout are rendered seems to be hardcoded into oxAuth. It's been requested a few times by users for this page to become customizable (to allow adding some logo, an animated spinner while iframes are processed etc).

**Comment by yuriyz** [comment]
Agreed, we already have it scheduled here https://github.com/GluuFederation/oxAuth/issues/535
