### ISSUE TITLE
UMA 2 : allow PCT persistence on updated without Claims-Gathering flow

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1139]
## Describe the issue
UMA 2 : allow PCT persistence on updated without Claims-Gathering flow
See https://support.gluu.org/other/7378/use-of-pct-in-a-pushed-claims-flow/

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/54
