### ISSUE TITLE
NATIVE cache increase gluu bucket load and led to 4% errors in jmeter benchmarking test

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1144]
With IN_MEMORY cache:
![Screenshot_2019-09-02 Couchbase Console Enterprise Edition 6 0 2 build 2413 - cb-dev(2)](https://user-images.githubusercontent.com/6104200/64131163-854f4580-cdcf-11e9-97cb-2fbb49f1217f.png)

With NATIVE_PERSISTANCE cache:
![Screenshot_2019-09-02 Couchbase Console Enterprise Edition 6 0 2 build 2413 - cb-dev(3)](https://user-images.githubusercontent.com/6104200/64131195-add73f80-cdcf-11e9-8509-73828b825211.png)

**Comment by yuriyz** [comment]
Checked code, in case of NATIVE_PERSISTENCE we perform redundant queries because we skip putting object into cache since cache and DB is the same, so actual caching is redundant in this case (duplicate same object in db). Indeed redundant queries reduce performance. Fixing it ....

**Comment by yuriyz** [comment]
I've introduced `T getWithPut(String key, Supplier<T> loadFunction, int expirationInSeconds)` which in `NATIVE_PERSISTENCE` case skips cache layer and calls persistence directly (in this way omits redundant calls to `gluu_cache`). We should use in all cache calls `getWithPut()` instead of `get()`.

**Comment by yuriyz** [comment]
For now I moved attributes, scopes and client to use new method. Scheduled separate ticket to move all other parts of oxauth in 4.1. It's bad time to do it now in 4.0 due to release impact. 

https://github.com/GluuFederation/oxAuth/issues/1150
