### ISSUE TITLE
Cookie is missing security based flag

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxAuth#1145]
Visiting the application, the “secure” attributes were missing from the cookies we received. The affected cookie is org.gluu.i18n.Locale.

The “Secure” flag would ensure that the cookie will always be passed encrypted from the client to the server.

The feature request is to Enable the “Secure” attribute.

**Comment by yurem** [comment]
https://github.com/GluuFederation/oxAuth/commit/f164ad5816e2d34122daec7161d192f68e343070
