### ISSUE TITLE
Separate code from customizations

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#115]
We should not use an exploded war file deployment--this makes it really hard to update the version of code. All customizations should be stored in LDAP, and rendered to the file system as necessary. We want to avoid file system customization in general, because they are hard to detect and replicate in the clustered deployment.

**Comment by willow9886** [comment]
@yurem Should we also move registration page customizations outside the war file as well?

**Comment by yurem** [comment]
We can open similar oxTrust issue too. We can reuse oxAuth approach in oxTrust.

**Comment by yurem** [comment]
Fixed
