### ISSUE TITLE
oxAuth login - upon wrong credential - both fields should be cleared away

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#1151]
Attempting wrong credential in oxAuth login only clearing 'Username' field. It should clear both 'Username' and 'Password' fields. 
![4logincred](https://user-images.githubusercontent.com/7156097/64787823-ecd76480-d536-11e9-9284-e27fc596508b.gif)

**Comment by willow9886** [comment]
@mzico What build number? Which backend?

**Comment by yuriyz** [comment]
I will take over

**Comment by yuriyz** [comment]
Corrected in latest 4.0.
