### ISSUE TITLE
Make active scripts more visible on "Manage custom scripts" page

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1157]
Package: gluu-server-4.0-82.rc1.centos7 (Backend: OpendDJ)

After the "Manage custom scripts" page was redesigned, it's become a bit hard to quickly assess which scripts are currently active, and which aren't. In previous packages the active scripts were highlighted by green colour. In 4.0 now the only way is to select each script, one by one, and check its "Enabled" property.

I would suggest to somehow highlight all active scripts on the vertical selector pane to the left (marked with large green rectangular on the picture):
![Selection_033](https://user-images.githubusercontent.com/11802046/65288697-5ca9a880-db50-11e9-95a5-4f6e55d51afe.jpg)
Highlighting could be just a green bulb next to it (as shown on the picture), or the whole underlying plate changing colour. Additionally, scripts which are currently in an invalid state, could be highlighted in red there.

Same goes for scripts in other categories as well.

**Comment by aliaksander-samuseu** [comment]
Chose wrong repo for this one, moving to oxTrust..

**Comment by yuriyz** [comment]
@aliaksander-samuseu there is "Transfer issue" link on the right side to move it.

**Comment by aliaksander-samuseu** [comment]
@yurem 
oops, didn't notice it, thanks for the tip. I've already re-created it manually in oxTrust repo..
