### ISSUE TITLE
New Fido2 registrations appear every time a user logs login

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#1164]
Environment:
CE4.0 rc2 couchbase on centos7

Steps to reproduce
Enable  and configure fido2 
Set fido2 as authentication mechanism in oxtrust
Make a Login attempt (a new entry with `"objectClass": "oxFido2RegistrationEntry"` appears)
Log out
Relogin and present your previously enrolled key  (a new entry with `"objectClass": "oxFido2RegistrationEntry"` appears again)

Screenshot
![repeated](https://user-images.githubusercontent.com/5444180/65787910-9fa2e780-e11f-11e9-8c6f-0402fd864396.png)

**Additionally**. Enrollment and authentication are working even if no mds access token is supplied and the fido2 endpoint is disabled

**Comment by yurem** [comment]
Can you specify DB type?

**Comment by jgomer2001** [comment]
> CE4.0 rc2 couchbase on centos7

`couchbase-server-enterprise-6.0.2-centos7.x86_64.rpm`

**Comment by yurem** [comment]
Fixed in rc3
