### ISSUE TITLE
Supergluu's ads removal feature doesn't seem to work

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1169]
## Environment:
gluu-server-3.1.6-1-10~trusty

## Description
Ads removal feature described in [this doc](https://gluu.org/docs/supergluu/admin-guide/#ad-removal) doesn't seem to work.

## Steps To Reproduce
Follow the official doc referenced above.

## Expected behaviour
After a device is enrolled at Gluu Server where a valid Supergluu license file is referenced from its custom script's properties, Supergluu app installed on it should become free from ads.

## Actual behaviour
Ads are still being displayed.

**Comment by nynymike** [comment]
I think we should just remove ads from Super Gluu
