### ISSUE TITLE
Support custom parameters in request object

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1171]
Custom parameters cannot be currently placed in the request object JWT.  Any extra claims are ignored by oxAuth.  These claims should be available in the authentication context.

**Comment by miltonbo** [comment]
Current implementation supports custom parameters, but only for query params, when client sends some custom parameters in the request object, they are not considered according to `authorizationRequestCustomAllowedParameters` json property.

Those parameters should be also processed and then they should be send to all person authentication interception scripts.
