### ISSUE TITLE
Implement OpenID Connect offline access

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1172]
We should make a global configuration setting that requires the `offline_access` scope in order to enable a client to use the refresh_token grant type. The default value should be set to `true`, to defalt to protecting privacy. This change may not be backwards compatible for deployments that expect more lax policy around obtaining the refresh token. 

`offline_access` is defined in the OpenID Connect spec.

https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

```
    offline_access
            OPTIONAL. This scope value requests that an OAuth 2.0 Refresh Token 
            be issued that can be used to obtain an Access Token that grants access 
            to the End-User's UserInfo Endpoint even when the End-User is not present 
            (not logged in).
```

**Comment by yuriyz** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/802c350fb77ecaf01de3c2fb352ae755e5dc59fa

**Comment by yuriyz** [comment]
Implemented in 4.2.

**Comment by sahiliamsso** [comment]
This is my request `https://<host>/oxauth/restv1/authorize?client_id=xxxxxx&scope=openid+offline_access&response_type=code&redirect_uri=<url>`. But I don't see refresh token being generated in the output.
```
{
    "access_token": "20d64542-0db8-46ad-b883-ef1d7acb691c",
    "scope": "openid",
    "id_token": "eyJraWQiOiI4ZDkyNWE5MC0yYjk3LTRmNWYtOGZhMi1lYzZkZjU0MThlOWFfc2lnX3JzMjU2IiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJhdF9oYXNoIjoiQW9nN0w3TjlkQmVwN1ItMk5ybnhWdyIsImF1ZCI6IjM4NmZkNjAzLTQzM2ItNGEwNi1hOThiLTc5ZWI5NDVhNjMwMSIsImNfaGFzaCI6Ill1TEJTaVpIRGgxMmkxSU96c25wSUEiLCJzdWIiOiJFeXFlMlRNTng4Yy02ZW5HS3RJQTZaN0x6MUcxU1RaZEdIZlRYQXlCUm5VIiwiYXV0aF90aW1lIjoxNTkxNzQ3MTQ4LCJpc3MiOiJodHRwczovL2F1dG9xYS5nbHV1Lm9yZyIsImV4cCI6MTU5MTc1MTc4MywiaWF0IjoxNTkxNzQ4MTgzLCJzaWQiOiI3ZTZkYjc1Zi02NmMzLTQ2OWItYTY5My1jYTM5ZTAzOGI5YjMiLCJveE9wZW5JRENvbm5lY3RWZXJzaW9uIjoib3BlbmlkY29ubmVjdC0xLjAifQ.wodaVc2XseA85nWwast3RJJcrr-oK_1jNZTJ3Sap-9JobSoh3cxp0oK4ZzTSrjOIwuKDkBr5WvyyS6h5dnQbmIJazpaBNfsjoJsao7wiOGXHmgW5m09V15xjwzr0eLjN1izrquLdtkPn4Zkk8itlGRHfoko5zJmrpE1bls5grTxc87h34QrtiCByohpjSuW3REkg61W9CEFt4iiKNxkOX_locv7gLLzlTZfcnGafi73dCOioRCNjcO6gabqxwsf4e_fp8Azy64m0L1bZm1XDBvWjYoWCwBRLUtSirS_R_XBRHRvkkYc4eyMgqidU88P_RitUtMIbZguXA10B4veXGA",
    "token_type": "bearer",
    "expires_in": 299
}
```

**Comment by yuriyz** [comment]
@sahiliamsso did you add `offline_access` scope to your client (as well as `refresh_token` grant type)?
I've checked it on jenkins-ldap.gluu.org (where we have latest oxauth) and refresh token is returned.
