### ISSUE TITLE
OIDC implicit flow doesn't seem to return requested claims in id token

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#118]
How it's mentioned in [this section](http://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims) of oidc specification, "The Claims requested by the profile, email, address, and phone scope values are returned from the UserInfo Endpoint, as described in Section 5.3.2, when a response_type value is used that results in an Access Token being issued. However, **when no Access Token is issued (which is the case for the response_type value id_token), the resulting Claims are returned in the ID Token**".
That doesn't seem to be the case, as can be seen in [this capture](https://github.com/GluuFederation/oxAuth/files/70074/oidc-implicit-flow.txt). For your convenience, here is a decoded claim segment of resulting id token's jwt:

{
"iss":"https://alex.gluu.org",
"aud":"@!BD4F.C866.5F5A.EF67!0001!1CBF.52EE!0008!A366.E2C9",
"exp":1450811755,
"iat":1450808155,
"nonce":"Txq9CZjKOWYZ6WBSvSFfLfJx3BayNrFMTYEjmCuliWY",
"auth_time":1450805158,
"oxValidationURI":"https://alex.gluu.org/oxauth/opiframe",
"oxOpenIDConnectVersion":"openidconnect-1.0",
"inum":"@!BD4F.C866.5F5A.EF67!0001!1CBF.52EE!0000!746D.CCBD",
"sub":"@!BD4F.C866.5F5A.EF67!0001!1CBF.52EE!0000!746D.CCBD"
}

When using a "code" workflow I'm able to acquire mentioned claims successfully for that user.

**Comment by nynymike** [comment]
I'm not sure this is a bug or a misunderstanding, but Javier can comment.

**Comment by aliaksander-samuseu** [comment]
Just a note: it may be because of how authorization-related settings were set for client. I remember I was asked for my consent to release scopes only once, then it probably just were reusing it again and again. So after I've changed my set of claims later, this initial authorization could conflict with a new set. Please ignore this report for now, I'll retest again tomorrow and update it.

**Comment by willow9886** [comment]
@aliaksander-samuseu I'm going to close this. Let's use gluu support app or trello to track internal support questions / issues.
