### ISSUE TITLE
oxAuth doesn't utilize changes done to authentication LDAP settings

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1180]
## Environment
gluu-server-4.0-centos7

## Describe the issue
Even if a remote server is specified on "Manage authentication" page, oxAuth still somehow uses default LDAP settings instead.

## Preconditions
1. Instance used for the test is already have Cache Refresh configured and some users imported from remote LDAP directory

## Steps To Reproduce
1. Log in to web UI
2. Move to "Manage authentication -> Manage LDAP auth" page and change default LDAP server and properties to the one used as CR source in your setup
3. Restart "oxauth" service to ensure configuration is updated
4. Try to log in as a user that belongs to remote LDAP server

## Expected behavior
You are able to log in as imported user

## Actual behavior
Log in with imported user doesn't work. Yet you still can log in as default admin user of this instance, what proves that it still uses default LDAP settings somehow, despite the fact `oxIDPAuthentication` attribute of `ou=configuration,o=gluu` entry contains updated configuration. The user who initially reported it claimed that he did `tcpdump` captures, and was able to confirm remote LDAP server isn't contacted during login attempt after changes to that configuration.

**Comment by yuriyz** [comment]
@aliaksander-samuseu it's sovled as discussed in chat. Let us know if anything else is needed within this ticket.
