### ISSUE TITLE
Store inum instead of uid in token/session entries

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1183]
We need to use real persistent user identifier in all temporary objects to avoid issues like this:
https://support.gluu.org/identity-management/7628/after-changing-default-admin-uid-oxtrust-fails-if-user-does-not-log-out/

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/48
