### ISSUE TITLE
Expired tokens are accepted at clientinfo endpoint

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1184]
Environment:
gluu-server-3.1.7-1-11~trusty+Ub14.04

## Describe the issue
Originally was reported in ticket 6717. oxAuth keeps accepting access token issued during client credentials grant flow even after its expiration time has passed (i.e. while it's still lingering in LDAP db waiting for a token clean up batch job to remove it)

## Steps To Reproduce
1. On "OpenID Connect  -> Clients" page add a new client to use in client credentials grants flow in the coming test; make sure it meets next conditions:
  - Has secret
  - "Scopes" contain at least "clientinfo"
  - "Response Types": "token"
  - "Grant Types": "client_credentials"
2. Run next command to get access token (use your client creds and hostname): `# curl -k -u 'CLIENTID:CLIENTPASS' -d 'grant_type=client_credentials&scope=uma_protection+clientinfo' https://your.gluu.server/oxauth/restv1/token`
3. Use next command to access `/clientinfo` endpoint to confirm your token is correct: `# curl -k -G -H 'Authorization: Bearer YOUR-ACCESS-TOKEN' https://your.gluu.server/oxauth/restv1/clientinfo`
4. Find your access token in LDAP server (it will be somewhere under your client's entry) and note time in its `oxAuthExpiration` attribute: `# /opt/opendj/bin/ldapsearch -h 127.0.0.1 -p 1636 -s sub -T -Z -X -D 'cn=directory manager' -j '/tmp/.dpw' -b 'o=gluu' -z 10 '&(objectclass=oxauthtoken)'`
5. Wait until the expiration time is reached plus 1-2 minutes, and re-run the command from step 3)

## Expected behavior
On step 5) your request is rejected as the access token has already expired (even though it still hasn't been purged out from LDAP)

## Actual behavior
Until the token is actually removed from LDAP, oxAuth still will return a valid response from `/clientinfo` for requests containing it (usually for 5-7 extra minutes).

For reference:

Example request to the endpoint:
```
GET /oxauth/restv1/clientinfo HTTP/1.1
Host: some.host.org
Authorization: Bearer 28fd8030-bc18-4df2-8c73-0c4f6c9ad58f
```

Example token entry:
```
dn: uniqueIdentifier=a5682cf3-cf07-4725-86e9-42935c3f1fc1,oxAuthGrantId=155e7f48-9731-4b85-bdf1-f4801034e730,inum=@!2123.B616.542F.E632!0001!18C4.24C4!0008!4E2E.B2A5.B546.6697,ou=clients,o=@!2123.B616.542F.E632!0001!18C4.24C4,o=gluu
objectClass: top
objectClass: oxAuthToken
oxAuthScope: profile uma_protection email
oxAuthCreation: 20191028192339.891Z
uniqueIdentifier: a5682cf3-cf07-4725-86e9-42935c3f1fc1
oxAuthTokenType: access_token
oxAuthGrantType: client_credentials
oxAuthClientId: @!2123.B616.542F.E632!0001!18C4.24C4!0008!4E2E.B2A5.B546.6697
oxAuthGrantId: 155e7f48-9731-4b85-bdf1-f4801034e730
oxAuthTokenCode: {sha256Hex}3bb4bf49f6691456736ef368f0582607bdac0f6103f7da59809946cf88364877
oxAuthExpiration: 20191028192839.891Z
```

**Comment by yuriyz** [comment]
Fixed in 3.1.5.sp3, 3.1.7 and master. 
@aliaksander-samuseu would you be so kind to validate it?
