### ISSUE TITLE
Layout issues in custom pages for several 2fa methods

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#1185]
In small screens (vertical resolution) the box that is supposed to surround all form fields looks a bit odd, for instance:

![otp_overlap](https://user-images.githubusercontent.com/5444180/67890867-7fe85000-fb1f-11e9-85ae-fb7f97af84b3.png)

As far as I can see it is happening in otp, twilio_sms, smpp; probably others.

Also there are still horizontal centering problems.

**Comment by nynymike** [comment]
If this is really a problem, the organization implementing can write better xhtml pages.
