### ISSUE TITLE
Support Amazon DocumentDB persistance mechanism

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1190]
We need to support: `https://aws.amazon.com/blogs/aws/new-amazon-documentdb-with-mongodb-compatibility-fast-scalable-and-highly-available/`

There is JAVA SDK with example how to use it: `https://docs.aws.amazon.com/documentdb/latest/developerguide/connect.html`

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/47
