### ISSUE TITLE
Super Gluu should support communtiction with web application on desktop

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1191]
There is BT browser API which we can use to implement this functionality. Here is table which browsers supports this API now: https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API#Browser_compatibility

Also Google is using Bluetooth on the phone to make the phone into a FIDO token. We need to investigate how it works.

**Comment by nynymike** [comment]
This is not a super high priority. Also, it would require the corresponding enhancement to Super Gluu.

**Comment by nynymike** [comment]
This feature would be dependent on Super Gluu support, so I'm closing it because there is no way to test right now.
