### ISSUE TITLE
Authorization endpoint should not use session_id unless admin allowed to use it

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1195]
This parameter gives high privileges:
https://github.com/GluuFederation/oxAuth/blob/113fa3e8a3b5b99dd8e4bd9a97cd5575cc97fb9e/Server/src/main/java/org/gluu/oxauth/authorize/ws/rs/AuthorizeRestWebService.java#L214

We need to turn of it by default

**Comment by yuriyz** [comment]
oxtrust: fed496b3aafb7a9594f46c2f344891e6341771ec

**Comment by yuriyz** [comment]
Done in 4.2.
