### ISSUE TITLE
Session cookies should support domain parameter

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1196]
Her is example with domain support
 "session_id=<session_id>; domain=.gluu.info; Path=/; Secure; HttpOnly; Expires=Fri, 08 Nov 2019 18:52:39 +0000;;HttpOnly"

We need to allow admin to enable domain support. This is need for case when RP get session_id from `password` grant flow

**Comment by yuriyz** [comment]
Duplicate of https://github.com/GluuFederation/oxAuth/issues/1209
