### ISSUE TITLE
Support "prompt=consent" parameter

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1197]
## Environment
gluu-server-3.1.7-1-10.centos7

## Describe the issue
When "Persist Client Authorization" or "Pre-Authorization" features are enabled for a client, oxAuth seems to ignore "prompt=consent" parameter included in initial OIDC request

## Steps To Reproduce
1. Create a client using the code grant, with "Persist Client Authorization" or "Pre-Authorization" features enabled
2. For "Persist Client Authorization", run its flow once first, to confirm release of the claims, so it could persist it
3. Start a flow, making sure "prompt=consent" parameter is added to url query string

## Expected behavior
The url query string parameter should override the client's options:
>The Authorization Server SHOULD prompt the End-User for consent before returning information to the Client. If it cannot obtain consent, it MUST return an error, typically consent_required.

## Actual behavior
The parameter is ignored and server returns the code immediately. Is this parameter supported, and do we need it supported?

**Comment by yuriyz** [comment]
Done in 4.2
