### ISSUE TITLE
Add JSON configuration property to control removal of offline access refresh tokens

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1198]
https://github.com/GluuFederation/oxAuth/issues/1172  introduces the idea that `offline_access` scope  delegates control of the refresh token to the subject. That's good, but we should also create a system level property that provides a default behavior with regard to removing refresh tokens on logout.  The default value should for `removeRefreshTokensForClientOnLogout` should be `true`

**Comment by yuriyz** [comment]
Implemented in 4.2.
