### ISSUE TITLE
Pre-populate login form with login_hint

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#120]
If there is a login_hint, prepopulate the form with this username.

**Comment by leponen** [comment]
Hello, I'm asking about the situation of this feature. It is marked low priority, but from user's point of view, especially in situations such as e-mail verification, makes a big difference. In our system, we currently have many places that could utilize this feature. Is there any hope on getting this to Gluu soon?

**Comment by nynymike** [comment]
No ETA. If you want to get enhancement prioritization, you need a support contract. Gluu is **Free** Open Source. Enhancements are driven by customers that help fund development.

**Comment by leponen** [comment]
Thanks, Mike, for the answer. I'll return to this with another media :)
