### ISSUE TITLE
Add OpenID Connect session state for Authz

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#121]
I think we should be able to reproduce it in 2.4.1 too. We need to open issue about this in git. In our code once user log in we set session state to AUTHENTICATED. But in AuthenticationFilter if session state AUTHENTICATED we do session authentication. Hence their workflow is correct. I think we need to add third session state like AUTHORIZATION or add other flag to indicate that if we need to show consent dialog.

More details in [support issue])(https://support.gluu.org/view/other/possibility-to-circumvent-authorization-check/2255)

**Comment by yurem** [comment]
I prefer third session state "AUTHORIZATION". 2 sessions variable have many combinations which can led to errors

**Comment by qbert2k** [comment]
The right link to support ticket:
https://support.gluu.org/other/possibility-to-circumvent-authorization-check-2255/

**Comment by yurem** [comment]
We need to verify if issue described in customer report still exist. We changed this part some time ago, probably there is no this issue now.

**Comment by qbert2k** [comment]
The bug can be reproduced in current version 2.4.5

**Comment by nynymike** [comment]
Is this issue resolved?

**Comment by qbert2k** [comment]
I am still working to fix it
