### ISSUE TITLE
 Pass Logout Conformance Tests

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1213]
There are new logout OpenID logout Conformance tests.

Details are here:
https://openid.net/certification/logout_op_testing/

Results are here:
  https://openid.net/certification/#Logout_OPs

**Comment by yuriyz** [comment]
https://github.com/GluuFederation/oxAuth/issues/498#issuecomment-575285490

**Comment by yuriyz** [comment]
Test instance https://op.certification.openid.net:62152/

**Comment by yuriyz** [comment]
Back-channel logout test fails. We asked Roland for help to understand why `sid` is not recognized by test. However we didn't get explanation yet.

From email to Roland
```
We need your help with Backchannel test. Logout token contains `sid` with valid Session ID but test failed with "Uknown Session Id".

https://op.certification.openid.net:62152/test_info/OP-BackChannel-RpInitLogout


If follow by link it's possible to see all details of test run. Would you be so kind to help understand why test refuseed `sid` inside Logout Token?

Trace:  File "/usr/local/lib/python3.6/dist-packages/oidctest-0.9.1-py3.6.egg/oidctest/op/oper.py", line 790

```

**Comment by yuriyz** [comment]
@miltonbo on https://openid.net/certification/ there are 2 samples of cert passed for `Back-Channel OP`. Please download these 2 zips and try to trace down `sid` value in their cases.

**Comment by yuriyz** [comment]
Finally we found out that reason was that `sid` was not included as claim into `id_token`.

**Comment by miltonbo** [comment]
Since we are using fapiCompatibility flag, I had to setup a new test instance: https://op.certification.openid.net:62175

**Comment by yuriyz** [comment]
Done in 4.2. Resources are sent to Connect for certification. We are waiting for result.
