### ISSUE TITLE
Front-channel logout breaks when cache type is set to redis or memcached.

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1217]
## Describe the issue
If "cacheProviderType" is set to "Memcached" or "Redis", frontchannel logout page won't render iframe elements for all RPs that have used oxAuth session for SSO since it was created. This doesn't happen when "IN_MEMORY" mode is used.

## Preconditions
1, Three OIDC RPs are configured  and use code flow and rely on SSO (no "login=prompt" in requests); oxTrust can be used as one of RPs to simplify setup
2. Corresponding OIDC clients are registered at Gluu, with "Frontchannel logout URI" properties are set

## Steps To Reproduce
1. Clear all cookies related to all services involved
2. In web UI, make sure that "cacheProviderType" is set to "Memcached" or "Redis" on "Configuration -> JSON Configuration -> Cache provider" page
3. Choose one of the 3 RPs as the one that will spawn the session at oxAuth and start OIDC flow from it
4. Start OIDC flows from the rest of two RPs
5. Start logout from  ( call to `/end_session`) from one of the RPs **that were not used to spawn the oxAuth's session**

## Expected behavior
On the intermediary page displayed after oxAuth's session is killed three iframe elements are present, related to each of the involved RPs

## Actual behavior
Only two iframes are rendered after the step 5) - one for the RP that initiated creation of oxAuth session, and the other is for RP that called `/end_session`. If the same RP that started the session is ending it, it will only render its own iframe. Everything works as it should when "IN_MEMORY" cache mode is used.

**Comment by yuriyz** [comment]
@aliaksander-samuseu did you perform oxauth restart after cache provider was changed? New cache type is applied only after server restart. If yes, please attach full `oxauth.log` in TRACE log level for cases when it doesn't work.

**Comment by aliaksander-samuseu** [comment]
Results were provided to Yuriy via internal chats. We are still investigating this issue.

**Comment by aliaksander-samuseu** [comment]
Changed milestone to 4.0.1 as I was able to reproduce it in 4.x as well.
@yuriyz please still note we should back-port the fix to 3.1.6 / 3.1.7 as well.

**Comment by yuriyz** [comment]
There were 2 places in Authorization Endpoint where session object was updated but not pushed to cache. As result it worked only with in-memory because it had explicit references to object in map.

Fixed in `version_4.0.1`, `master` and back-ported to `version_3.1.8`.
@aliaksander-samuseu please validate and confirm that it works.
