### ISSUE TITLE
Write script to facilitate multiple test email address against one valid address 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#1220]
Write a jython authentication script to allow facility like: http://www.codestore.net/store.nsf/unid/BLOG-20111201-0411

**Comment by nynymike** [comment]
Can you clarify what you mean here? It looks like a feature of gmail more then something you need to implement on the OP.

**Comment by zaphod72** [comment]
The OP should see each distinct "test" email address as a separate account. I should be able to authenticate distinct accounts with usernames like
- myaccount+testA@gmail.com
- myaccount+testB@gmail.com
etc.

Evernote and other sites with email usernames support this. It is the email service that sees these as all the same account (not just Google FYI).

**Comment by nynymike** [comment]
So the `+` is the delimeter, and evrerything after the `+` is ignored?

**Comment by zaphod72** [comment]
Gmail:
Everything addressed to `myaccount+.*@gmail.com` goes to `myaccount@gmail.com`. They are all the same account.

Most online services see 
```
myaccount@gmail.com
myaccount+testA@gmail.com
myaccount+testB@gmail.com
```
as distinct accounts.

**Comment by mzico** [comment]
>> So the + is the delimeter, and evrerything after the + is ignored?

In my understanding, yes.. that's what it is. 

But the question is... where should we store/map those attributes? i.e. proper Email Address can be: "mail == myaccount@gmail.com"; but how should we save "mail == myaccount+abcdefgh@gmail.com" one? Something like this? 

```
mail = myaccount@gmail.com
mail2 = myaccount+testA@gmail.com
mail3 = myaccount+testB@gmail.com
```
In above case, what will happen if there is 'email uniqueness' implemented in Gluu Server ( which is most common from n1ql and ldap as well ).

**Comment by zaphod72** [comment]
Email uniqueness is the correct behavior, imo.
We should allow users to create register multiple accounts using these `+` variations on their email address.
It's up to the service provider to decide on limiting the # of registrations from any one ip address.

In your case the owner of `myaccount@gmail.com` could register all three of those email variants to create three distinct accounts, with no mapping or linking between them. As far as we are concerned they are completely different emails.

**Comment by nynymike** [comment]
`mail` can be multivalue. Store it like this

```
dn: inum=1234,ou=people,o=5678,o=gluu
mail: myaccount@gmail.com
mail: myaccount+testA@gmail.com
mail: myaccount+testB@gmail.com
```
