### ISSUE TITLE
u2f enrollment & authn failing in latest firefox

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#1223]
**Environment**
CE 4.1 rc3 on Stretch + ldap database
browser FF 71.0 on Windows (checking about:config I see it has `security.webauth.u2f = true`)

**Steps to reproduce**

Enable u2f script
Set oxtrust acr = u2f
logout
Attempt to login
After supplying usr + pwd there is a javascript error in the console (see image)

![u2f_enroll](https://user-images.githubusercontent.com/5444180/71450802-3b4fee00-2737-11ea-9452-92c731b8a42f.png)

I tried changing line 16 of u2f-api.js with `if (!u2f){ u2f = {}; }` but more different JS errors arose

*Note:*
Out of the box u2f worked for me with chrome and opera

**Comment by jgomer2001** [comment]
@yurem I also tried:

- Enroll u2f key in Chrome (success)
- Then use FF to authenticate (it fails due to javascript error)

**Comment by maduvena** [comment]
![image](https://user-images.githubusercontent.com/12072533/71610067-e0454d80-2bb3-11ea-9b0e-1cab98b3d509.png)

**Comment by maduvena** [comment]
![image](https://user-images.githubusercontent.com/12072533/71610986-9f513700-2bbb-11ea-8ee0-c94c9a1a8479.png)

**Comment by jgomer2001** [comment]
I just discovered the following!
The key starts blinking around 1 minute after the enrollment attempt is made.... After the key is touched, it concludes successfully

Very weird!

**Comment by yurem** [comment]
I've update for recent Firefox. But how we test this in Chrome? I can't find U2F extension anymore for Chrome...

**Comment by nynymike** [comment]
FIDO is now built-in to Chrome automatically.

**Comment by yurem** [comment]
Fixed. It works well in FF, FF Dev Edition, Chrome now.
