### ISSUE TITLE
FAPI test fail because oxAuth should reject when response_type is only code

### ISSUE THREAD

**Issue by miltonbo** [GluuFederation/oxAuth#1228]
## Issue
**Test validation:** This test uses response_type=code in the authorization request, which (as a JARM response has not been requested) is not permitted in FAPI-RW - only the hybrid flow ('response_type=code id_token') is allowed. The authorization server should show an error message that the response type is unsupported or the request is invalid (a screenshot of which should be uploaded) or the user should be redirected back to the conformance suite with a correct error response.

I would say that for FAPI R/W, oxAuth should reject code response type.

**Authorization Request:**
`https://ce-ob.gluu.org/oxauth/restv1/authorize?request=eyJraWQiOiJmYXBpLWNsaWVudCIsImFsZyI6IlBTMjU2In0.eyJhdWQiOiJodHRwczpcL1wvY2Utb2IuZ2x1dS5vcmciLCJzY29wZSI6Im9wZW5pZCIsImNsYWltcyI6eyJpZF90b2tlbiI6eyJhY3IiOnsidmFsdWUiOiJ1cm46bWFjZTppbmNvbW1vbjppYXA6c2lsdmVyIiwiZXNzZW50aWFsIjp0cnVlfX19LCJpc3MiOiJmYXBpLWNsaWVudC0xIiwicmVzcG9uc2VfdHlwZSI6ImNvZGUiLCJyZWRpcmVjdF91cmkiOiJodHRwczpcL1wvd3d3LmNlcnRpZmljYXRpb24ub3BlbmlkLm5ldFwvdGVzdFwvYVwvZ2x1dS10ZXN0XC9jYWxsYmFjayIsInN0YXRlIjoiSHpFSGFuZTJvbyIsImV4cCI6MTU3OTAwNDU4Nywibm9uY2UiOiJPOVFvNWZCNVdRIiwiY2xpZW50X2lkIjoiZmFwaS1jbGllbnQtMSJ9.MvgbVYSNTQSyGxkN4TNI-NycNqqyvYhtgNrDDW4XpMxPk0scy8ib2MSbW2XjOpbu6BsgD8PL23QlVyGwpsacIhn8-iED58SJuMV4_1AsD8ngADxHNL5OgnpchMBmRObu2Y1q3oaCAWJoLJoZjridXcaPPi3FxDsJrXN0SC2d7PI7vMEpAoTCmf8W5K7Hy2GpLTaBqn094_3SHPuicZlTnshRH-hYRuQ0_W84LW8CAw0tzhXhRFKAt-41-V_fyjxM4p3P7UxHrL17z-7-XtoIPeYhSlyRjgEvWlFJtnVmgwaB7KEOcjD4lUutZXFXeXCGIXOSy4T5cEMOPUps-TH0lQ&client_id=fapi-client-1&redirect_uri=https://www.certification.openid.net/test/a/gluu-test/callback&scope=openid&response_type=code`

**Logs of the test:**
`https://www.certification.openid.net/log-detail.html?log=GoqzppaYcy&public=true`

Related documentation:
`https://openid.net/specs/openid-financial-api-part-2-ID2.html#rfc.section.5.2.2`

**Comment by nynymike** [comment]
This has to be configurable.  Most non-FAPI deployments of Gluu will definitely want to support `code` only resonse_type.

**Comment by yuriyz** [comment]
@nynymike oxauth change behavior when `fapiCompatibility` is set to true (it is false by default).
@miltonbo Fixed, re-test.
