### ISSUE TITLE
Cluster: CM rotates keys but oxauth is not aware of it. Keystore is loaded only at start up.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1231]
## Describe the issue
CM rotates keys but oxauth loads keystore only at start up. This leads to updated keys in LDAP but outdated in jks file which at the end leads to failure of issuing JWT.

**Comment by yuriyz** [comment]
Fixed in master, 4.1 and created patch for 4.0.

**Comment by padawarmik** [comment]
Hi.
I am still struggling with this issue on version 4.1.
New keys are in LDAP but the local Keystore is outdated. 
4 servers in cluster

**Comment by yuriyz** [comment]
Make sure you are using latest CM and oxauth, it was tested and it works.
