### ISSUE TITLE
Don't insert ou=pairwiseIdentifiers tree node into DB which not supports tree model

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1233]
We don't need to create tree node in couchbase DB like `ou=pairwiseIdentifiers,inum=e2ff78ac-a5d8-40ff-ae1c-c05460919a06,ou=people,o=gluu`. Here is example:
![image](https://user-images.githubusercontent.com/6104200/72916813-c088eb80-3d53-11ea-886e-9f1bfe672ebc.png)

In `persistenceEntryManager` there is method `hasBranchesSupport(primaryKey)` which we should use to add or not this tree node.

**Comment by yuriyz** [comment]
Done in 4.1 and merged to master.
