### ISSUE TITLE
Implement Sliding Lifetime for Refresh Tokens

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1234]
You can reduce the security risk of long lived refresh tokens by adding a "sliding lifetime" on top of the absolute lifetime. This allows for scenarios where a refresh token can be silently used if the user is regularly using the client, but needs a fresh authorize request, if the client has not been used for a certain time. In other words, they auto-expire much quicker without potentially interfering with the typical usage pattern.

For example, you could have a property "AbsoluteRefreshTokenLifetime" and "SlidingRefreshTokenLifetime" in the global or client settings.

**Comment by yuriyz** [comment]
https://github.com/GluuFederation/oxAuth/issues/1235

**Comment by nynymike** [comment]
duplicate
