### ISSUE TITLE
FAPI test fail because we are including headers that shouldn't be sent

### ISSUE THREAD

**Issue by miltonbo** [GluuFederation/oxAuth#1238]
## Issue
Authorization endpoint is including some headers that shouldn't be included.

Headers that shouldn't be included:
1. acr_values
2. scope
3. session_id

## Response:
![image](https://user-images.githubusercontent.com/32613743/73323710-ac932d00-421e-11ea-891f-1a82e304625c.png)

## Conformance suite logs url:
https://www.certification.openid.net/log-detail.html?log=mhKV0fgHbs&public=true

**Comment by yuriyz** [comment]
@miltonbo fixed. Please re-deploy and re-test.
