### ISSUE TITLE
id_generate_endpoint 404 / move to scim-configuration

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#124]
ID generation endpoint

    "id_generation_endpoint": "https://lake.gluu.info/oxauth/seam/resource/restv1/id"

1. This endpoint is returning 404 - I would expect 403 (unauthorized) 
2. The discovery info should be moved to https://<host>/.well-known/scim-configuration

**Comment by yuriyz** [comment]
@nynymike shifted it to 2.4.3, need to take care about #137 for 2.4.2

**Comment by yuriyz** [comment]
this one is already done, endpoint is now presented by .well-known/gluu-configuration
