### ISSUE TITLE
Change session_id after user authentication

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1242]
Right now the `session_id` cookie is issued with the `HTTPOnly` and `Secure` flags. This forces the browser to send the cookie only via https and not to allow access to it from JavaScript. Also in the new version of Chrome, `SameSite=Lax` will prevent access of the cookie from images and iframes.

We need to implement additional security, updating the session_id identifier on session authentication. This behavior should be controlled by an oxAuth JSON config property. When enabled, oxAuth should change the `session_id` after the user logs in.

**Comment by yuriyz** [comment]
Re-scheduled to 4.2, it's better to make such change in feature release instead of bugfixing one.

**Comment by yuriyz** [comment]
Added `changeSessionIdOnAuthentication` configuration property. It's true by default. When it's true then session_id is changed on authentication. Done in 4.2.
