### ISSUE TITLE
Write sample script to automatic user grouping based on domain name.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxAuth#1243]
## Description
Whenever user register to oxtrust by providing details on  register page its must be automatically grouped based on email domain. 

Let us take example of two domain gmail.com & yahoo.com
1. If any user register with gmail.com , a group with gmail.com must be created and all the users with gmail.com must be placed in that group.
2. Similarly with yahoo.com, a separate group must be created and all user auto grouped to yahoo.com group.

please refer to this support ticket for further clarification

https://support.gluu.org/customization/7892/email-domain-based-group-assignments-in-self-registration/

**Comment by nynymike** [comment]
We are not enhancing any IDM features in oxTrust.  Per my previous statements, oxTrust should not be Internet facing. All these features like registration and password reset should be phased out.
