### ISSUE TITLE
FAPI tests fail because we are not validating that exp and scope must be present in the request.

### ISSUE THREAD

**Issue by miltonbo** [GluuFederation/oxAuth#1244]
## Issue
For FAPI RW implementation, we have to check that the request jwt must include `exp` and `scope` fields. There are two test that have the same validation issue.

#### Request 1 (Without exp field)
`eyJraWQiOiJmYXBpLWNsaWVudCIsImFsZyI6IlBTMjU2In0.eyJhdWQiOiJodHRwczpcL1wvY2Utb2IuZ2x1dS5vcmciLCJzY29wZSI6Im9wZW5pZCIsImNsYWltcyI6eyJpZF90b2tlbiI6eyJhY3IiOnsidmFsdWUiOiJ1cm46bWFjZTppbmNvbW1vbjppYXA6c2lsdmVyIiwiZXNzZW50aWFsIjp0cnVlfX19LCJpc3MiOiJmYXBpLWNsaWVudC0xIiwicmVzcG9uc2VfdHlwZSI6ImNvZGUgaWRfdG9rZW4iLCJyZWRpcmVjdF91cmkiOiJodHRwczpcL1wvd3d3LmNlcnRpZmljYXRpb24ub3BlbmlkLm5ldFwvdGVzdFwvYVwvZ2x1dS10ZXN0XC9jYWxsYmFjayIsInN0YXRlIjoiN2RSV0thb0x3biIsIm5vbmNlIjoickwwRGZkVjNHSSIsImNsaWVudF9pZCI6ImZhcGktY2xpZW50LTEifQ.Wk9HL3-2ZxZAam52xQqQRU5yavEfTy7gmOBWyqbSeTC1UYXoTFlFD1DU61kjq2ypWiyOpiAKYBNzCHAyvjl7ApG8hj8LqQBwcc2XmL1NEkAPw5ZkQxc_2UVkjmQSS2tjwGRT-mMZEbk1LGk7ofteKx4tTy6okkq4Gpt7oY-uLIYHpYr86im6hd3af7adXY8z00V1p2PHcUj3y0S-moni37lmXMsAu6UyeKZlHt3Fg4jdSD5YyXwM1zC-ptwV-8MJCeegKMHCSytcAYxZK9RNVSgC3D5q-EHQskZpLfJt8QUNmQrPsy4Iv0QmW0JXPi5H1k5YggQ_1VdxuL2II4z4IA`

#### Request 2 (Without scope field)
`eyJraWQiOiJmYXBpLWNsaWVudCIsImFsZyI6IlBTMjU2In0.eyJhdWQiOiJodHRwczpcL1wvY2Utb2IuZ2x1dS5vcmciLCJjbGFpbXMiOnsiaWRfdG9rZW4iOnsiYWNyIjp7InZhbHVlIjoidXJuOm1hY2U6aW5jb21tb246aWFwOnNpbHZlciIsImVzc2VudGlhbCI6dHJ1ZX19fSwiaXNzIjoiZmFwaS1jbGllbnQtMSIsInJlc3BvbnNlX3R5cGUiOiJjb2RlIGlkX3Rva2VuIiwicmVkaXJlY3RfdXJpIjoiaHR0cHM6XC9cL3d3dy5jZXJ0aWZpY2F0aW9uLm9wZW5pZC5uZXRcL3Rlc3RcL2FcL2dsdXUtdGVzdFwvY2FsbGJhY2siLCJzdGF0ZSI6InV2WnV2OERUMUsiLCJleHAiOjE1ODA4MjI3NzEsIm5vbmNlIjoiV1c1aGF5UTBaMCIsImNsaWVudF9pZCI6ImZhcGktY2xpZW50LTEifQ.TaCxl8ARmPPA9KfY7kqnUZu9GGXWyk68uBjSK8mRkMW2ZUUsT2HJv9Sy9wOIjlLYVU8axehDL1IaExhTVz7RBDeQpMsPRNapoiKFpeoEYjtvXLoUiLV3UCv26_YJXvXtsT4fPLucBAGi56e7EVB7Oa2ig41OVOfYK8hHCH_eEUraWG6EcGaCKK2yd0koh_8beLXfQHZUIeJun27GYNCGzLsF2EXQIEkdWKd3Mq9vgSlq9HoWrzbbMV4fpwwepgy7u97S_gxbZHZ9zyl8e6Jm9BaHlCQB3uAB1AXU2oM_de_UAfVgbaSAqrWzGekT09_2B01ZZNflemM0tU3Gk1KaXg`

## Conformance suite logs:

**Case 1: ** https://www.certification.openid.net/log-detail.html?log=2xd5hqFE5e&public=true
**Case 2: ** https://www.certification.openid.net/log-detail.html?log=LFsSAt83w9&public=true

**Comment by miltonbo** [comment]
We also need to validate `nonce` field.

#### Request (Without nonce field)
`eyJraWQiOiJmYXBpLWNsaWVudCIsImFsZyI6IlBTMjU2In0.eyJhdWQiOiJodHRwczpcL1wvY2Utb2IuZ2x1dS5vcmciLCJzY29wZSI6Im9wZW5pZCIsImNsYWltcyI6eyJpZF90b2tlbiI6eyJhY3IiOnsidmFsdWUiOiJ1cm46bWFjZTppbmNvbW1vbjppYXA6c2lsdmVyIiwiZXNzZW50aWFsIjp0cnVlfX19LCJpc3MiOiJmYXBpLWNsaWVudC0xIiwicmVzcG9uc2VfdHlwZSI6ImNvZGUgaWRfdG9rZW4iLCJyZWRpcmVjdF91cmkiOiJodHRwczpcL1wvd3d3LmNlcnRpZmljYXRpb24ub3BlbmlkLm5ldFwvdGVzdFwvYVwvZ2x1dS10ZXN0XC9jYWxsYmFjayIsInN0YXRlIjoid0VQYVEwWXR4UCIsImV4cCI6MTU4MDgyNTA0MiwiY2xpZW50X2lkIjoiZmFwaS1jbGllbnQtMSJ9.QRThBn3w3ikkAynSVebqkgrfBNQSpMH_gzUF6u5MA9LeBN78VlROR5r7JyDm8iQ42hCXlI9mOWnnmvgsNhSmbpupp_y4TZMD3PgG5nUUQL9Ss89RqozkKF_9nl8qWpRCLcQnqdXFcIHdCvDs2uMc92rNGggU3oKkKIX8Hj1sRd8vTqLNDdEf27h4rQLepaDOIh0MWH26hdschqUKJNjKPgzzIlLNtFJGroCQ4Vp6d-CTCS9FkiKA7DMsyVDQXjM_dHaetfAdHnJeg-BtUXwBUOEAz64h7N-H0uVCdZ6OVHhcSvjStvV5xPgnUa2w2igKp-eZG1tJRjQq367wmsMc9Q`

## Conformance suite log:
https://www.certification.openid.net/log-detail.html?log=1TvsdLdojk&public=true

**Comment by miltonbo** [comment]
We also need to validate `redirect-uri` field.

#### Request (Without redirect-uri field)

`eyJraWQiOiJmYXBpLWNsaWVudCIsImFsZyI6IlBTMjU2In0.eyJhdWQiOiJodHRwczpcL1wvY2Utb2IuZ2x1dS5vcmciLCJzY29wZSI6Im9wZW5pZCIsImNsYWltcyI6eyJpZF90b2tlbiI6eyJhY3IiOnsidmFsdWUiOiJ1cm46bWFjZTppbmNvbW1vbjppYXA6c2lsdmVyIiwiZXNzZW50aWFsIjp0cnVlfX19LCJpc3MiOiJmYXBpLWNsaWVudC0xIiwicmVzcG9uc2VfdHlwZSI6ImNvZGUgaWRfdG9rZW4iLCJzdGF0ZSI6ImN0dksyWXlSbW8iLCJleHAiOjE1ODA4MjU0MDksIm5vbmNlIjoiYU83Y1pVMlBLMCIsImNsaWVudF9pZCI6ImZhcGktY2xpZW50LTEifQ.FdpzcuBF3Y1TT7_6r_CgNne7hsqBVxDoR8XZu6bmLX2J10nD3rkeG9zwXsS_UzI-Bwday8fSuZnmFcuQjPLz3jmWQbXGOlscOrdM5pCyG1VPHLGc1NlX5WA54L4rLhM03u7tzXuVQqUwldOqf-WyyVLZ880_ua1zeXab7lolUXc0H713i4OX73gAXLOlxMu9mT9Op_zIbACV2p02dVg0ffw8lx-iI5SlPE2iP8CWfo5abCK34d_bbK7Vyi8FsjwQDo_8tZ-ZuHr2wcWmBcvd8ejN7vZql91J2VhQMKyYjgbIfYOlU9PNMJXKODDOM7ohCzgdPmVOHByfMlozLjqxag`

## Conformance suite log:
https://www.certification.openid.net/log-detail.html?log=sLFia70Fhk&public=true

**Comment by yuriyz** [comment]
Fixed in 4.2. Related FAPI tests are passed.
