### ISSUE TITLE
FAPI test fail because we are not validating that request object must be present.

### ISSUE THREAD

**Issue by miltonbo** [GluuFederation/oxAuth#1245]
## Issue
For FAPI RW implementation, we have to check that request object is present. Current implementation is processing query params.

#### Authorization url:
`https://ce-ob.gluu.org/oxauth/restv1/authorize?client_id=fapi-client-1&redirect_uri=https://www.certification.openid.net/test/a/gluu-test/callback&scope=openid&claims=%7B%22id_token%22:%7B%22acr%22:%7B%22value%22:%22urn:mace:incommon:iap:silver%22,%22essential%22:true%7D%7D%7D&state=jGFCmhb1jP&nonce=cvN9SY7W3C&response_type=code%20id_token`

## Conformance suite log:
https://www.certification.openid.net/log-detail.html?log=3Ux0hI8EsG&public=true

**Comment by yuriyz** [comment]
Fixed in 4.2, oxauth re-built and available on maven, please re-test.
