### ISSUE TITLE
Gluu 4.1 QA - Super Gluu sending push notification to different device for an admin user

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxAuth#1246]
## Describe the issue
After successful Suprer Gluu registration for a non-admin user, when admin user (unregistered) is trying to login then push notification is being sent to non-admin user's device. 

## Steps To Reproduce
1. Setup oxtrust acr = super_gluu
2. Enroll your Super Gluu app with a user other than admin
3. Logout, and login with admin user

## Expected behavior
Admin user should be asked to enroll device.

## Actual behavior
Push notification is being sent to non admin user.

Version: Gluu 4.1 RC8

**Comment by yurem** [comment]
We didn't reproduce it during our testing
