### ISSUE TITLE
FAPI : swap clients - test fail because we are sending an unexpected kind of error

### ISSUE THREAD

**Issue by miltonbo** [GluuFederation/oxAuth#1248]
## Issue
In token endpoint we are sending an unexpected kind of error, we are sending `invalid_grant`, but it should be `invalid_client`.

#### Response
`{ "reason": "Unable to find grant object for given code.", "error_description": "The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.", "error": "invalid_grant" }`

#### Conformance suite log:
https://www.certification.openid.net/log-detail.html?log=CXvzSTdNL5&public=true

**Comment by yuriyz** [comment]
Fixed in 4.2, please re-deploy and re-test.

**Comment by miltonbo** [comment]
@yuriyz Three tests reported that were failed now are passing sucessfully, but this the test reported here is not passing again.

#### Conformance suite log
https://www.certification.openid.net/log-detail.html?log=LD1MaL8BDE&public=true

**Comment by yuriyz** [comment]
right, that what I've told in chat. OK, I will check what we can be done.

**Comment by yuriyz** [comment]
@miltonbo please validate on latest build and close if fixed.

**Comment by miltonbo** [comment]
@yuriyz Let you know that there is the issue:

![image](https://user-images.githubusercontent.com/32613743/74358244-82517b80-4d97-11ea-879b-cc1c051dbd9d.png)

#### Conformance suite log:
https://www.certification.openid.net/log-detail.html?log=HtwJGL6DXI&public=true

**Comment by yuriyz** [comment]
@miltonbo in description of the ticket it was told
```
In token endpoint we are sending an unexpected kind of error, we are sending invalid_grant, but it should be invalid_client.
```
And now for client mismatch is says that we send `invalid_grant` but we send `invalid_client`. What is the difference ?

**Comment by miltonbo** [comment]
Yeah, I think there are special cases for every one.
First case reported here is another test, in that case it is swapping to another client. This last test is another test and here it is not swapping and it is just verifying authorization endpoint.

#### First test: fapi-rw-id2-ensure-client-id-in-token-endpoint
`https://www.certification.openid.net/log-detail.html?log=CXvzSTdNL5&public=true`

#### Last test: fapi-rw-id2-ensure-authorization-code-is-bound-to-client
`https://www.certification.openid.net/log-detail.html?log=HtwJGL6DXI&public=true`

Yesterday we had three different tests that were not passing, now we have only one of them that is not passing, but two of them just passed with your latest change.

I think that is the difference, but I'm not really sure.

**Comment by yuriyz** [comment]
in this last comment is says `Client mismatch`, so it should be `invalid_client`. I don't understand why they expect `invalid_grant`. I will try to investigate tomorrow to check what `client_id` is inside our grant.

here https://www.certification.openid.net/log-detail.html?log=HtwJGL6DXI&public=true

**Comment by yuriyz** [comment]
In oxauth we got `client.getClientId().equals(authorizationCodeGrant.getClientId())` = false, that's why mistmatch occurred.

**Comment by yuriyz** [comment]
@miltonbo OK, here is the flow (based on `https://www.certification.openid.net/log-detail.html?log=HtwJGL6DXI&public=true`)
```
https://ce-ob.gluu.org/oxauth/restv1/authorize?request=eyJraWQiOiJmYXBpLWNsaWVudCIsImFsZyI6IlBTMjU2In0.eyJhdWQiOiJodHRwczpcL1wvY2Utb2IuZ2x1dS5vcmciLCJzY29wZSI6Im9wZW5pZCIsImNsYWltcyI6eyJpZF90b2tlbiI6eyJhY3IiOnsidmFsdWUiOiJ1cm46bWFjZTppbmNvbW1vbjppYXA6c2lsdmVyIiwiZXNzZW50aWFsIjp0cnVlfX19LCJpc3MiOiJmYXBpLWNsaWVudC0xIiwicmVzcG9uc2VfdHlwZSI6ImNvZGUgaWRfdG9rZW4iLCJyZWRpcmVjdF91cmkiOiJodHRwczpcL1wvd3d3LmNlcnRpZmljYXRpb24ub3BlbmlkLm5ldFwvdGVzdFwvYVwvZ2x1dS10ZXN0XC9jYWxsYmFjayIsInN0YXRlIjoiVmJxSWxqNTZMTiIsImV4cCI6MTU4MTUyNjk3MSwibm9uY2UiOiJjNmRSdGhFUFNPIiwiY2xpZW50X2lkIjoiZmFwaS1jbGllbnQtMSJ9.M0hZ6DbKMhnTIjSy_XSP8MkSxV_K4BYBs5gLjj3YmWHzOi3CPhINJ8cQP1m4BlIBcO-p5YEuR6k6Ik-Eg0PT8X4hVoK_PT2VecoBipR9c592FIUNlR98x5Xjrr1iADxlmOetdoGyvOnCxiPnSJAWphBoeil6DkeECdWI_hBqvfpljmv09LWdUVG1vowBcSzw0oaVh2TB9_gqm_RCfSXYRrSbF6_XGPfUTXQo9KQssHJGOxv4LqpFYbrCss3yLBtIVaryy54PP4unL_3BSjourDCsvY6PK_TQFui4krZLxbRQryT0_yzhuhfpFhN-revtLp7tgScpSH1rGwUi5CfujA&client_id=fapi-client-1&redirect_uri=https://www.certification.openid.net/test/a/gluu-test/callback&scope=openid&response_type=code%20id_token
```

Got back code `2bafa695-7e54-4279-a0a9-02fdb851d0b3` (so it's bound to client `fapi-client-1`).

Then the send that code to Token Endpiont with `grant_type=authorization_code&code=2bafa695-7e54-4279-a0a9-02fdb851d0b3&redirect_uri=https%3A%2F%2Fwww.certification.openid.net%2Ftest%2Fa%2Fgluu-test%2Fcallback&client_id=fapi-client-2`

As we can clearly see it's client mismatch and thus `invalid_client`.

It seems we have to post issue got FAPI Suite gitlab with all these details and conflicting requirements.

**Comment by miltonbo** [comment]
I understand that clients are different, but they are trying to use the same code for both. I'll post the issue then.
Great job.

**Comment by miltonbo** [comment]
I just created the issue from their side:
https://gitlab.com/openid/conformance-suite/issues/728

**Comment by yuriyz** [comment]
According to FAPI Suite developers explanation we should match also certificate to particular client. Even if certificate is valid but it's from another client then we should return `invalid_client`. I've just added check on client_id for certificate. So now we should correctly return `invalid_client` error. @miltonbo please test.

**Comment by miltonbo** [comment]
Last changes fixed the error response that was expected by the conformance suite.
