### ISSUE TITLE
FAPI test is not passing because refresh token issued to a client can be used with another client

### ISSUE THREAD

**Issue by miltonbo** [GluuFederation/oxAuth#1249]
## Issue
Conformance suite is using a refresh token issued to client 2 with the client 1 and it is working, but It shouldn't, because is another client.

#### Conformance suite logs:
https://www.certification.openid.net/log-detail.html?log=5JGmaGCpRg&public=true

**Comment by yuriyz** [comment]
Fixed in 4.2. Please re-test.
