### ISSUE TITLE
Update OpenID Connect Discovery for Claims

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#125]
### Add oxScopeType for OpenID and UMA scopes in oxTrust

When an OpenID scope is added through oxTrust, it should have the value "openid" for attribute    

    oxScopeType: openid

UMA scopes should have 

    oxScopeType: uma

###  Fix OpenID Connect Discovery 

i.e. GET to `/.well-known/openid-configuration`, 

The `claims_supported` values should only reference claims that are associated with a `oxScopeType=openid`. If a claim is `active`, but its not available through any scope, it doesn't make sense to reference it. I recommend doing a SET union function.

### Fix scope to claims mapping:

Currently scope_to_claims_mapping is like this 

    "scope_to_claims_mapping": [
        {
            "scope": "last_name",
            "claims": ["sn"]
        },
        {
            "scope": "profile",
            "claims": ["photo1"]
        }
    }

It would be better if the scope was the key.

**Comment by shekhar16** [comment]
Added oxScopeType for OpenID and UMA scopes in oxTrust and the code is commited.

**Comment by zamilskhan** [comment]
@shekhar16 is this done?

**Comment by shekhar16** [comment]
1st and 3rd points are done.
2nd is in progress.

**Comment by shekhar16** [comment]
All are Fixed.

**Comment by yurem** [comment]
Fixed
