### ISSUE TITLE
FAPI test fail because we are using state query param but we shouldn't

### ISSUE THREAD

**Issue by miltonbo** [GluuFederation/oxAuth#1250]
## Issue
Conformance suite is sending the state param in the url as a param and they are not sending the state in the request object, considering this case we shouldn't use the query param, because the documentation says only parameters inside the request object should be used.

Also s_hash shouldn't be returned in Authorization endpoint.

#### Conformance suite log:
https://www.certification.openid.net/log-detail.html?log=uEBeaOUWVF&public=true

**Comment by yuriyz** [comment]
Fixed in 4.2.
