### ISSUE TITLE
Dynamic registration: do not add fallback response_type or grant_type.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1252]
## Describe the issue

Mike:
So I think this code is too specific to OpenID Connect, and now we are seeing use cases for Gluu as an OAuth server for API access mgt, not just user authentication. We need to add a property for dynamic client config… something like `client_reg_default_to_code_flow_with_refresh`  to maintain the behavior
but IMHO, default behavior should be no resonse_type and no grants.

**Comment by nynymike** [comment]
agreed.

**Comment by miltonbo** [comment]
Added `clientRegDefaultToCodeFlowWithRefresh` json property in order to switch on/off default behaviour.
