### ISSUE TITLE
Change behavior of `default` scope

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1253]
## Describe the issue

Default scopes mean that I can get them if I ask for them not that I should always get them…
scopes should always be granted explicitly. Default scopes should not be automatically provisioned.

**Comment by nynymike** [comment]
I added the non-backwards-compatible flag because developers may rely on this code. We need to add a JSON property to maintain the old behavior if necessary.

**Comment by yuriyz** [comment]
I will take over this ticket.

**Comment by yuriyz** [comment]
Issue was already fixed within https://github.com/GluuFederation/oxAuth/issues/1109 .
