### ISSUE TITLE
FAPI test fail because we don't check aud field correctly

### ISSUE THREAD

**Issue by miltonbo** [GluuFederation/oxAuth#1255]
## Issue
FAPI test is checking if `aud` field is checked when they send any value, but that field should contain the identificator of the client according to the documentation.

#### Request Object
`eyJraWQiOiJmYXBpLWNsaWVudCIsImFsZyI6IlBTMjU2In0.eyJhdWQiOiJodHRwczpcL1wvd3d3Lm90aGVyMS5leGFtcGxlLmNvbVwvIiwic2NvcGUiOiJvcGVuaWQiLCJjbGFpbXMiOnsiaWRfdG9rZW4iOnsiYWNyIjp7InZhbHVlIjoidXJuOm1hY2U6aW5jb21tb246aWFwOnNpbHZlciIsImVzc2VudGlhbCI6dHJ1ZX19fSwiaXNzIjoiZmFwaS1jbGllbnQtMSIsInJlc3BvbnNlX3R5cGUiOiJjb2RlIGlkX3Rva2VuIiwicmVkaXJlY3RfdXJpIjoiaHR0cHM6XC9cL3d3dy5jZXJ0aWZpY2F0aW9uLm9wZW5pZC5uZXRcL3Rlc3RcL2FcL2dsdXUtdGVzdFwvY2FsbGJhY2siLCJzdGF0ZSI6InR0c281VXkwRE0iLCJleHAiOjE1ODEzNTIyNjQsIm5vbmNlIjoiNG9RM29PSExRSSIsImNsaWVudF9pZCI6ImZhcGktY2xpZW50LTEifQ.V1rVj9lydtc5Ic2rzBD-Q2Vo0qsF6_ZweLFfhxwYryiY37wdhSB10o99QmcYlw5UhtM-FxXHqST5qr22O0T7qrdfEtx6keteAlw85oJpn9dYFUOp4ohOQs8bH8Psm2t0WfxNhDVxBDXPVeaEYWDbm9tXnrplrc_QayZn1k47tcFoNTB8luxPCstsRJ5uCWtgIlZs9MEvja5cCJLf_4yUSG576oLsruQt4GknDG3DriaJNUhcS9tqRDHa24FdtRBdtWAei1hh0ioo1i_NCcFJomOgCQH2GO0Uu6fG1MyiLWAM-UGss1u2LOFjy2hh2Ae5qU-D_SUkCjylM21gzbuqUw`

#### Documentation:
The client obtains the aud element from the JWT and checks whether it matches the client id the client used to identify itself in the corresponding authorization request. If the check fails, the client MUST abort processing and refuse the response.

#### Value sent in `aud` field:
`https://www.other1.example.com/`

#### Conformance suite log:
https://www.certification.openid.net/log-detail.html?log=udQOSPy0Hr&public=true

**Comment by yuriyz** [comment]
Fixed in 4.2. Please re-test.
