### ISSUE TITLE
Two English resource files?

### ISSUE THREAD

**Issue by iafan** [GluuFederation/oxAuth#1257]
I see that there are two slightly different English resource files in the Server component:

1) https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/resources/oxauth.properties
2) https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/resources/oxauth_en.properties

Do you know which one is actually being used, and why there are two? We need to pick the right source for localization purposes.

**Comment by yuriyz** [comment]
It's standard java resource bundle handling with default properties file. You may want to read some bundle totorial, e.g. https://docs.oracle.com/javase/tutorial/i18n/resbundle/index.html

**Comment by iafan** [comment]
@yuriyz I understand what a default properties file is and how per-language overrides work. I guess my question why do you need an English override file on top of the English default one (when you could have just one)?

**Comment by yuriyz** [comment]
It's convenient, default is developer file. While translation can be made by native (or known) person. Yes-yes, developer English may differ from real English (quite often).
