### ISSUE TITLE
oxAuth composes wrong header for id_token when certain state of its keyset is reached

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1258]
## Environment
Gluu Server 4.0, oxAuth 4.0.Final.patch1

## Describe the issue
When a certain composition of keys is achieved in oxAuth's JWKS and JKS file on disk, it starts to compose `id_token` incorrectly when at least HS256 algo is used for its signing

## Steps To Reproduce

1. Create a client entry that will be used for testing and make sure it uses HS256 algo for id_token's signature; it's better to use implicit flow as `id_token` is easier to capture this way; an example of client entry that can be imported with `ldapmodify` (redirect_uri are defined in sector id in this case):
```
dn: inum=52702820-08bd-458c-8bea-a0ae59bfa0a0,ou=clients,o=gluu
objectClass: top
objectClass: oxAuthClient
oxAuthLogoutSessionRequired: false
oxAuthTrustedClient: true
oxAuthIdTokenSignedResponseAlg: HS256
oxAuthResponseType: code
oxAuthResponseType: token
oxAuthResponseType: id_token
oxAuthTokenEndpointAuthMethod: client_secret_basic
oxAuthRequireAuthTime: false
oxAccessTokenAsJwt: false
oxPersistClientAuthorizations: true
oxAuthGrantType: authorization_code
oxAuthGrantType: implicit
oxAuthGrantType: client_credentials
inum: 52702820-08bd-458c-8bea-a0ae59bfa0a0
oxAttributes: {"tlsClientAuthSubjectDn":null,"runIntrospectionScriptBeforeAccessTokenAsJwtCreationAndIncludeClaims":false,"keepClientAuthorizationAfterExpiration":false}
oxAuthAppType: web
oxAuthClientSecretExpiresAt: 21200210000000.000Z
oxDisabled: false
oxIncludeClaimsInIdToken: false
oxRptAsJwt: false
displayName: Test-client for oxAuth keys-issue
oxAuthClientSecret: Ehk511XqZZNitL2SjDsZnsmHdiuXq6sWiggwnwUuPr8=
oxAuthSubjectType: pairwise
oxLastAccessTime: 20200210203811.493Z
description: Some description
```
2. Configure an RP that will use the client entry above and confirm that the flow is functional and `id_token` has correct header
4. Stop "oxauth" service
5. Import the oxAuth's keys shared by an user which experienced it first (key were provided to @yuriyz directly as they are too sensitive data to share here); don't forget to update password used to access the keystore file
6. Start the service
7. Start the flow and confirm that `id_token` contains a confusing header now

## Expected behavior
Regardless of what is in oxAuth's keyset atm, if HS algos are used for a flow it shouldn't be affected

## Actual behavior
oxAuth sends an incorrect JWT header at step 7 that confuses clients as they cannot figure out what key to use to validate its signature. Example:
```
{"kid":"e901deb7-4c4d-4c7f-9072-3411f519dece_sig_rsa-oaep","typ":"JWT","alg":"HS256"}
```
A normal header when HS256 is used:
```
{"typ":"JWT","alg":"HS256"}
```

Even though this happens due to (probably) broken oxAuth's keyset, it still doesn't seem right it may affect algos that don't rely on it this way, so it's a separate issue.

**Comment by yuriyz** [comment]
Fixed in 4.1 and in master.
