### ISSUE TITLE
Support PKCE to protect authorization code

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#126]
PKCE is defined in [RFC 7636](https://tools.ietf.org/html/rfc7636)

The Gluu Server should optionally support PKCE either on a per client basis.

This IETF Draft [OAuth 2.0 for Native Apps](https://tools.ietf.org/html/draft-wdenniss-oauth-native-apps-00) recommends that native apps register a custom URI schema, and use the system browser on the mobile device for authentication. 

    6.2.  Protecting the Authorization Code
     A limitation of custom URI schemes is that multiple apps can   
     typically register the same scheme, which makes it indeterminate as   
     to which app will receive the Authorization Code Grant.  This is not   
     an issue for HTTPS redirection URIs (i.e. standard web URLs) due to   
     the fact the HTTPS URI scheme is enforced by the authority (as   
     defined by [RFC3986]), being the domain name system, which does not   
     allow multiple entities to own a single domain.   
     
     If multiple apps register the same scheme, it is possible that the   
     authorization code will be sent to the wrong app (generally the   
     operating system makes no guarantee of which app will handle the URI   
     when multiple register the same scheme).  Figure 1 of [PKCE]   
     demonstrates the code interception attack.  This attack vector   
     applies to public clients (clients that are unable to maintain a   
     client secret) which is typical of most installed apps.   
     
     While Section 5.2.2 mentions ways that this can be mitigated through   
     policy enforcement (by being able to request that the offending app   
     is removed), we can also protect the authorization code grant from   
     being used in cases where it was intercepted.   
     
     The Proof Key for Code Exchange by OAuth Public Clients (PKCE) [PKCE]   
     standard was created specifically to mitigate against this attack.   
     It is a Proof of Possession extension to OAuth 2.0 that protects the   
     code grant from being used if it is intercepted.   
     
     Both the client and the Authorization Server MUST support PKCE [PKCE]   
     to use custom URI schemes.  Authorization Servers SHOULD reject   
     requests that use a custom scheme in the redirection URI if the   
     required PKCE parameters are not also present, returning the error   
     message as defined in Section 4.4.1 of [PKCE]   
     
     PKCE provides proof of possession by the client generating a secret   
     verifier which it passes in the initial authorization request, and   
     which it must present later when redeeming the authorization code   
     grant.  An app that intercepted the authorization code would not be   
     in possession of this secret, rendering the code useless.

**Comment by yuriyz** [comment]
Implemented

**Comment by yuriyz** [comment]
@nynymike  @qbert2k As part of "OAuth 2.0 for Native Apps" spec I've disabled checks on "http" and "localhost" for native apps redirect_uris.

https://github.com/GluuFederation/oxAuth/commit/ae3ebc3541bea29a08ed6b1b81fd91c21e968cd9

**Comment by yuriyz** [comment]
@qbert2k is it possible that it breaks some conformance tests?
