### ISSUE TITLE
FAPI test (private key jwt) is failing because we don't consider client_assertion and client_assertion_type params

### ISSUE THREAD

**Issue by miltonbo** [GluuFederation/oxAuth#1260]
## Issue
FAPI test with **private key jwt** variant is failing because in this kind of authentication because we have to consider those new params instead of **client_id** param:
1. client_assertion
2. client_assertion_type

According to the documentation to use a JWT Bearer Token for client authentication, the client uses the following parameter values and encodings. 
The value of the "client_assertion_type" is  "urn:ietf:params:oauth:client-assertion-type:jwt-bearer".
The value of the "client_assertion" parameter contains a single JWT. 
It MUST NOT contain more than one JWT.

The following example demonstrates client authentication using a JWT during the presentation of an authorization code grant in an access token request (with extra line breaks for display purposes only):

```
     POST /token.oauth2 HTTP/1.1
     Host: as.example.com
     Content-Type: application/x-www-form-urlencoded

     grant_type=authorization_code&
     code=n0esc3NRze7LTCu7iYzS6a5acc3f0ogp4&
     client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3A
     client-assertion-type%3Ajwt-bearer&
     client_assertion=eyJhbGciOiJSUzI1NiIsImtpZCI6IjIyIn0.
     eyJpc3Mi[...omitted for brevity...].
     cC4hiUPo[...omitted for brevity...]
```

#### client_assertion param (JWT)
`eyJraWQiOiJmYXBpLWNsaWVudCIsImFsZyI6IlBTMjU2In0.eyJzdWIiOiJmYXBpLWNsaWVudC0xIiwiYXVkIjoiaHR0cHM6XC9cL2NlLW9iLmdsdXUub3JnXC9veGF1dGhcL3Jlc3R2MVwvdG9rZW4iLCJpc3MiOiJmYXBpLWNsaWVudC0xIiwiZXhwIjoxNTgxOTQxNzkzLCJpYXQiOjE1ODE5NDE3MzMsImp0aSI6ImlqRlZjbjBRZ3lZVG5MRVluQ1lvIn0.AR5QPcOFxVpfZRrnMBZsED4OS92Ly2gkUrxJ_SsAFzWabLfO2bLL2-vKYp3xGuFWnOE6L2sK_sVfq4PET3Zb3NywDRr_Oy1hb02J2LQyHRaUobVkJaqbQNBDaM1R86bKCmitqJKyTOWLEctx9iVbekpI-6xqy9MCyqSoWFqj3oz79l_IyIA3Ps4ea8VKXEU5N3qmkR71yYL6WAt84eJywMO7e-RSAikN9cEcKlQ2sg6n8P9Af6lEZxjWBApbXMMYFB2LQvg0mfwpRHLEuK79GDqy3CxB5pFLRbh9pOFQ_rKYV-1Bx8gWYjZISbOGHL1V80_e3JCrB6fb2C2QddqKKw`

![image](https://user-images.githubusercontent.com/32613743/74678857-a09de980-5192-11ea-873e-3ff5eeb266e3.png)

#### Conformance suite log:
https://www.certification.openid.net/log-detail.html?log=KNFpN29azY&public=true

**Comment by yuriyz** [comment]
Unable to reproduce, it seems to fail due to mis-confguration. `fapi-client-1` auth method is set to `tls_client_auth` instead of `private_key_jwt`
