### ISSUE TITLE
Gluu custom logout template

### ISSUE THREAD

**Issue by robin-sylvester** [GluuFederation/oxAuth#1264]
Hi Gluu team,

Related to previous issue
https://support.gluu.org/log-out/4760/custom-logout-page/

I'm doing a web project where in production environment I would like to avoid message "Logout requests sent" while user logout.

I would kindly ask you to change hardcoded logout into custom logout template page in future versions of Gluu project.
[(reference link)](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/gluu/oxauth/session/ws/rs/EndSessionUtils.java)

Regards,
Robin

**Comment by mzico** [comment]
Please open support ticket in support portal ( support.gluu.org ). If required, we can come back to github for any kind of bugfix or feature request.

**Comment by yuriyz** [comment]
@robin-sylvester customization can be done via logout script added in 4.2 https://github.com/GluuFederation/oxAuth/issues/1113

**Comment by robin-sylvester** [comment]
Thank you @yuriyz,

I'm currently using 3.1.6. version for production so sorry for not noticing.
I do fear a little to upgrade to 4.2 'cuz I use a lot of Gluu features:
OAuth (OpenID Connect and UMA with SCIM), 2FA with Totp.

Knowing you haven't changed those in upper versions will definitely help me,

Very grateful for such a fast reply,
Robin

**Comment by robin-sylvester** [comment]
I see, 4.2 is yet to be released.
[Roadmap](https://www.gluu.org/roadmap/)

Have a nice weekend Gluu team,
Robin
