### ISSUE TITLE
Error 404 when calling to the FCM: unsubscribe endpoint

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxAuth#1265]
## Describe the issue
Error 404 when calling to the FCM: unsubscribe endpoint when trying to renew the Instance Token.
After reproduce the error, check the FCM documentation for changes in the endpoint.

## Steps To Reproduce
1. Use branch https://github.com/GluuFederation/oxAuth/compare/CIBA_v4.x
2. Click on Authenticate User button.
3. Complete the authentication steps to return to the ciba page.
4. Click Request Permission button.
5. Click Allow.
6. After a short time you will receive the Instance ID Token.
7. Click Delete Token button to renew the Instance ID Token.
8. Open the JS Console to see the error.

## Expected behavior
Receive a new Instance ID Token and register it using the oxAuth: Device Registration Token.
## Actual behavior
You get a 404 error when calling to the FCM: unsubscribe endpoint.

## Smartphone (please complete the following information if applicable):
After fix please also test with smartphone.

## Additional context
Sub-ticket of #750

**Comment by qbert2k** [comment]
![Screenshot from 2020-02-25 01-07-39](https://user-images.githubusercontent.com/2474616/75217838-966d8380-576e-11ea-9018-4554abe08a75.png)

**Comment by miltonbo** [comment]
There is an issue in the Firebase SDK, so I had to update it to an stable version.
The issue was reported here: https://github.com/firebase/firebase-js-sdk/issues/2469
Therefore, the SDK version was updated.
