### ISSUE TITLE
Detect language based on browser `Accept-Language` header

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1267]
If `ui_locales` is not specified in AuthZ request oxAuth should try to get preffered language from `Accept-Language","value":"en-US,en;q=0.5"` request header.

Additionally we need to add new property to allow enable/disable this. By default OP should use browser header.

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/41
