### ISSUE TITLE
CIBA: Super Gluu Integration

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxAuth#1268]
The FAPI profile of CIBA  is in implementer draft status right now:
https://openid.net/specs/openid-financial-api-ciba-ID1.html

This spec enables a bank to push a notification to a customer's mobile application--for example, when a customer calls in via telephone

As Super Gluu already enables registration of devices, and push notifications, it would be helpful to upgrade Super Gluu to support this new OpenID Profile.

**Comment by qbert2k** [comment]
@yurem wrote:

BTW, in Super Gluu we support 2 push message providers:
1) Firebase/APNS
2) oxNotifyClient -> oxNotifyServer -> AWS -> APNS/APNS_SANDBOX/ADM/GCM/BAIDU/WNS/MPNS

Second approach allows us to use one application for all customers

Without this we have to rebuild application with project_id for each customer

This approach allows us to hide Push service credentials

**Comment by nynymike** [comment]
If we are to hand off this requirement to the Super Gluu developers, we need a much more detailed set of instructions on what they need to do.

**Comment by nynymike** [comment]
Closing this because it should really be an issue in the Super Gluu repo
