### ISSUE TITLE
How to use gluu project to provide identities (OpenID connect) ?

### ISSUE THREAD

**Issue by heditr** [GluuFederation/oxAuth#127]
Can someone provides to me a simple Java example of how to use the gluu project for providing OpenID connect standard identities??

Is gluu implementation is an SDK jar that i can find it in maven repositories or its a deployable package that i must clone it from github and run it to provide identities?

**Comment by willow9886** [comment]
Hi, the best place to open support issues like this is on http://support.gluu.org. 

Thanks.
