### ISSUE TITLE
Logout - RP-Initiated - User Confirmation page (optional, not required by conformance tests)

### ISSUE THREAD

**Issue by miltonbo** [GluuFederation/oxAuth#1273]
## Issue
According to the documentation we SHOULD add a step in the logout endpoint when it is RP-Initiated. That step is to ask to the user whether he wants to log out.

#### Documentation
https://openid.net/specs/openid-connect-session-1_0.html

> At the logout endpoint, the OP SHOULD ask the End-User whether he wants to log out of the OP as well. If the End-User says "yes", then the OP MUST log out the End-User.

#### SHOULD aclaration
According to the [RFC documentation](https://www.rfc-editor.org/rfc/inline-errata/rfc2119.html) SHOULD word is the adjective "RECOMMENDED", means that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course.

**Comment by yuriyz** [comment]
@miltonbo please give test log link

**Comment by miltonbo** [comment]
@yuriyz This is not related to a test in the conformance suite. It's something I read in the documentation and noted in our current flow. In that case it could be done now or not.

**Comment by yuriyz** [comment]
Right, it's not necessary to pass logout tests. Lets keep it as feature request. RP can always ask confirmation before initiating logout at AS thus for me it's not important, it's nice to have.

**Comment by nynymike** [comment]
I agree that we can wait... let's hear from customers that they want this feature.

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/40
