### ISSUE TITLE
Logout test - RP-Initiated - Unexcepted error

### ISSUE THREAD

**Issue by miltonbo** [GluuFederation/oxAuth#1274]
## Issue
Test is sending an unregistered redirect url in the `end_session` endpoint, so it should show an error and stop the logout process. Another platform use invalid_request error code as the response.

#### Current response:
![image](https://user-images.githubusercontent.com/32613743/75503369-d4a3b680-59ab-11ea-963d-bc4e5297e7d4.png)

#### Test:
https://op.certification.openid.net:62152/test_info/OP-RpInitLogout-Unregistered-post_logout_redirect_uri

#### End session url:
https://jenkins-ldap.gluu.org/oxauth/restv1/end_session?post_logout_redirect_uri=https%3A%2F%2Fop.certification.openid.net%3A62152%2Flogout%3Ffoo%3Dbar&state=rHQ6Jr75Zt5dFpYjzoGFzw1zfgp1jmH4&id_token_hint=eyJraWQiOiI0ODJmMGY1ZC0zMjY0LTQ2YzUtOGEwMi04ODI4OWFhNWNmMGNfc2lnX3JzMjU2IiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJhdF9oYXNoIjoiRHZNajhQQTFwdVpvMlN1TXIzUmludyIsImF1ZCI6ImE1OTgxZmE1LTIzYzktNDA0ZC05NTdiLTlhMGQ3ZjFkZTBlNyIsInN1YiI6InlWSWJodDJDOXhqaFQ3Y3BmU0xmYUlFaDZsMzFrNWNYRzRzODNBQm82cUEiLCJzX2hhc2giOiJzYk0tMUlwOEYyaGRxYktZYWdYTUdRIiwiYXV0aF90aW1lIjoxNTgyODU0MTE2LCJpc3MiOiJodHRwczovL2plbmtpbnMtbGRhcC5nbHV1Lm9yZyIsImV4cCI6MTU4Mjg1NzcxOCwiaWF0IjoxNTgyODU0MTE4LCJub25jZSI6IkU1bUFvWUF3VUh2Q1FZeUQiLCJzaWQiOiIzYWQ0MjhiMS1iZDMwLTQ4MTUtOTIwYi1mMzUyMjYxZGMwZDciLCJveE9wZW5JRENvbm5lY3RWZXJzaW9uIjoib3BlbmlkY29ubmVjdC0xLjAifQ.uhpudyrGX3joicPzZSgZ6-kIt6P83zp20DVxXQEW0hSu1qTygy2zsGNUxxRWGVT2IkofQMi8_KdSs-NLdIMq9-mUz5UAs0dv770PcEzubFeQX7gxQZZUVyWMI5-0JhEkYiqi4Gd62WqvJJq-BeGED0jXZdfhu0J-kB6-WfMU3adD8abKR3xTN9xBalQ_N4bE-HF-oJmvyqNf2X_gRRTADwOU606lAtFfaji4n8B3oIehEiSlw0w--Cis8DYYWRplXPNMmHNOTM37QBf8zkk-KwcSGNqWSCv_HDU_Hva9Bbrw5j4dPNUd2YfU90DQMUbVy9K2LfBO6dVjuIs9KBpX9g

**Comment by yuriyz** [comment]
Fixed in 4.2 (during validation make sure allowPostLogoutRedirectWithoutValidation=false).
