### ISSUE TITLE
Connect client : validate the endpoints to avoid malicious endpoint attack

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#128]
I think it's about malicious endpoint attack, right?
http://web-in-security.blogspot.com/2015/10/attacking-openid-connect-10-malicious.html

No, we don't have such check. We can put this check inside authorization client, so it will automatically validate token endpoint against iss/aud returned with redirect_url.

> This specification requires the response from the Authorization Server
> to an successful /authorize call to pass back code=, state= and jwt= (?)
> or individually iss= and aud= as URL parameters on the 302 to the
> redirect_url. This way, before the client issues a call to the /token
> endpoint (with the code), it can verify that the token endpoint is correct.
> 
> If the client doesn't validate the endpoints at this step, then it could
> disclose it's secret to a malicious endpoint. Correct?

**Comment by nynymike** [comment]
Yes, another useful [link](http://self-issued.info/?p=1524)

**Comment by nynymike** [comment]
I don't think this is an oxAuth issue.
