### ISSUE TITLE
Add support for AES in EncryptionService

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#1287]
Currently we support 3DES as cipher, usage will be considered disallowed after 2023.

See https://www.cryptomathic.com/news-events/blog/3des-is-officially-being-retired

> According to draft guidance published by NIST on July 19, 2018, the Triple Data Encryption
> Algorithm (TDEA or 3DES) is officially being retired

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/33
