### ISSUE TITLE
Introduce swagger spec file to oxauth

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1289]
## Describe the issue

We have to :
1) introduce swagger spec file according to master code
2) here we have 2 options : a) include docs as Swagger UI (same as for oxd) b) generate doc and include markdown directly into oxauth docs. Option a) looks more stright-forward.
3) if all goes well, remove all swagger annotations from oxauth code.

https://github.com/GluuFederation/oxAuth/pull/1285

**Comment by pujavs** [comment]
Changes as per review comments and submitted for review
Related PR - https://github.com/GluuFederation/oxAuth/pull/1285

**Comment by nynymike** [comment]
Is this done?

**Comment by yuriyz** [comment]
I've already asked in PR here https://github.com/GluuFederation/oxAuth/pull/1285#issuecomment-611387892

@pujavs would you please clarify ?

I think we should merge it even if it has gaps. We can improve it while we go.

**Comment by yuriyz** [comment]
I've merged PR to master. We should start to support swagger specification. I'm going to remove old swagger annotations from code which are useless now.
