### ISSUE TITLE
Add JSON Configuration properties  to control JWKS endpoint algorithms 

### ISSUE THREAD

**Issue by miltonbo** [GluuFederation/oxAuth#1292]
## Describe the issue
Client needs to control which algorithms are available on the the JWKS endpoint (e.g. https://idp.example.com/oxauth/restv1/jwks)  For example, an organization may not want  `PS*` algorithms.

The plan is to introduce a new JSON property ______ with values ______.

**Comment by miltonbo** [comment]
It could be a param in oxAuth, also we would need to consider the case when they would need to support those algorithms again, so in that case we would need to regenerate those keys.

**Comment by miltonbo** [comment]
Added json config property in oxAuth module:

`
    "jwksAlgorithmsSupported":[
        "RS256",
        "RS384",
        "RS512",
        "ES256",
        "ES384",
        "ES512",
        "PS256",
        "PS384",
        "PS512",
        "RSA1_5",
        "RSA-OAEP"
    ],
`

**Comment by yuriyz** [comment]
Don't forget to add it to oxtrust and documentation.

**Comment by miltonbo** [comment]
All changes were done using 4.2 version:
1. oxAuth: JWKS endpoint.
2. oxTrust: Configuration needed to manage that json config property.
3. community-edition-setup: Template used to install oxAuth json config.
4. docs-ce-prod: Documentation corresponding to this new property.
