### ISSUE TITLE
Remove bootfaces dependency which produce performance degrade

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1293]
## Describe the issue

Performance tests shown that `/login.htm` loading slow down over time. Starting from 200ms it ends up with 20 seconds. After 10K request with 200 threads we starts to get failures due to it.

As experiment I dropped bootfaces and re-tried test. We stopped to get random errors and 20 seconds blockers. Thus we have to drop bootfaces usages.

![image](https://user-images.githubusercontent.com/2013070/77155977-16091c80-6aa7-11ea-8801-bea179e66e86.png)

![image](https://user-images.githubusercontent.com/2013070/77155946-07bb0080-6aa7-11ea-99d3-4aeb6bc99e71.png)

Bootfaces were added here https://github.com/GluuFederation/oxAuth/commit/39b50b0667e52c809fa91e58f4ef5119c7a73a5a

**Comment by syntrydy** [comment]
Fixed
