### ISSUE TITLE
Password-less authentication with Fido2

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#1297]
Fido2 web authentication can be used to implement password-less authentication ( Enter username and then use Fido2 device ). It will be great if we can implement this in Gluu Server. 

https://fidoalliance.org/fido2/fido2-web-authentication-webauthn/

**Comment by yurem** [comment]
Apache can modify cookies in already released versions:
```
        Header edit Set-Cookie ^((opbs|session_state).*)$ $1;HttpOnly;SameSite=None
```

**Comment by yurem** [comment]
There is similar issue: https://github.com/GluuFederation/oxAuth/issues/1270
