### ISSUE TITLE
Mitigate replay of modified JWT from Passport-JS

### ISSUE THREAD

**Issue by malotian** [GluuFederation/oxAuth#1306]
`The issue seems to be in the way that passport communicates the completion of sign-in back to oxAuth when a user logs into a third party provider. The provider sends a saml assertion back to passport, and then passport sends a post with a JWT to oxAuth to assert that the authentication has completed. That JWT is signed, but can attacker an change the signing algorithm to ‘none’ and remove the signature, and then change the expiration time. Using that modified JWT they can replay that to oxAuth at any time later, without the user having completed sign-in at the partner, and it continues the flow sending a saml success back to the RP.`

This may be partially fixed in 4.1 when encryption is included.`

## Possible Solution/Recommendations
Actually - “JWT tokens shall travel over https”, that’s the prerequisite to use JWT and we are doing and recommending so.

But let say theoretically we assume said is possible (man-in-middle), Then at oxAuth can be enhanced to reject JWT, which are without signing algo defined (and can publish a guideline in docs - like shibb says unspecified nameid is not allowed)

**Comment by harrdou** [comment]
The passport JWT is transmitted front-channel via the browser, so it is a trivial exercise for an attacker to forge it and thereby impersonate any valid user.

**Comment by nynymike** [comment]
Feature enhancement is schedule for 4.2. Currently, the risk can be mititaged in an interception script for those who can't wait.

**Comment by harrdou** [comment]
Note that in order to thwart key confusion attacks, the signature algorithm on the JWT needs to be compared to the one configured in /etc/gluu/conf/passport-config.json. Rejecting "none" is not sufficient.

**Comment by nynymike** [comment]
I believe this needs to be implemented in the passport-saml authn interception script.

**Comment by christian-hawk** [comment]
@malotian can you please help me with more detailed reproduction steps?

Thanks!

**Comment by jgomer2001** [comment]
Some questions regarding the solution given to this issue:

- Why is the "attack" blocked in jython?. Isn't it cleaner to revamp `verifySignature` method of oxAuth crypto provider in Java? That way other developers can reuse...
- It only accepts the RS512 algorithm and rejects the rest, why?
- Why were `getAuthenticationMethodClaims` and `getLogoutExternalUrl` methods removed from the script?
- Why was the fix not included in `passport_social` script. Its  flow is basically the same of saml: it also uses `cryptoProvider.verifySignature`
- The solution adds too many lines to an already large script. There are many unnecessary comments and print statements there IMO

Thoughts @yurem @yuriyz @nynymike @christian-hawk

**Comment by yuriyz** [comment]
On oxauth side in 4.2 this attack is already blocked (in `verifySignature `). There is new configuration property `rejectJwtWithNoneAlg` which is true by default. It means that JWT with None algorithm is rejected by default until admin explicitly allows it. Thus I consider this particular issue as fixed.

Re: blocking in script, I guess first it was blocked in script by Chris and then I've added support for  `rejectJwtWithNoneAlg` on oxauth.

**Comment by yuriyz** [comment]
Closing as fixed.
