### ISSUE TITLE
Check flag whether oxauth is under cluster and skip rotation and clean up.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1307]
## Describe the issue
We started to get support tickets which are related to mis-configuration. For example both `key-rotation` pod and built-in oxauth timer rotates keys. Thus idea is to introduce new `oxauth_replicas : <number of pods>` attribute in persistence (`ou=cluster,ou=configuration,o=gluu`) and if oxauth is under cluster skip keys rotation and clean up.
It should help avoid wasting time on support tickets.

**Comment by yuriyz** [comment]
https://github.com/GluuFederation/docker-monitor/issues/1

**Comment by yuriyz** [comment]
Dependent https://github.com/GluuFederation/docker-monitor/issues/1 ticket is not implemented, moving ticket to 4.3.

**Comment by moabu** [comment]
Issue will be addressed here 

https://github.com/GluuFederation/docker-key-rotation/issues/9

**Comment by yuriyz** [comment]
@moabu don't forget to add ticket also for clean up pod. I'm closing this one since we have nothing to do on oxauth side then.
