### ISSUE TITLE
Add oxAuth JSON properties to set logging format 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1308]
It would be nice if we could set the log output to JSON instead of text. There are details here:
https://logging.apache.org/log4j/log4j-2.2/manual/layouts.html

Perhaps we can add a JSON property to allow the format as either `text` or `json` ?

**Comment by miltonbo** [comment]
I tried to get that configuration in a json property, however according to the document and the code already implemented, programmatically we can set the log level, but we can't configure Layouts. I also saw the code already implemented in `oxCore` and I saw the place where is implemented programmatically the log level, but there is no method that we can use to change the Layout, we only can get the Layout, but not change.

I saw the documentation, basically the only way to do this is just changing the xml that we have in `log4j2.xml` file. By default we have `PatternLayout` which is used to put logs in lines. I also tested JSONLayout and I had the expected result. Here is my log output.

![image](https://user-images.githubusercontent.com/32613743/79273125-802b9c00-7e70-11ea-8224-f22bc43bdd15.png)

Therefore, we would need to change that `lo4j2.xml` file according to the requirement (Json or text).

**Comment by nynymike** [comment]
Is there any way to automate a change to log4j.xml, and then to trigger a reload (to avoid the need to re-start)?

**Comment by yuriyz** [comment]
There are not `setLayout` but there is log4j2 configuration builder which allows to change it on the fly (without restart).
https://logging.apache.org/log4j/2.x/manual/customconfig.html
Look at `Programmatically Modifying the Current Configuration after Initialization` section.

**Comment by miltonbo** [comment]
Thanks for your suggestion, I checked that and implemented someting based on that, that code is a way to add a new Appender and therefore change loggers, however we have some mixed configuration now, `log4j2.xml` file and configuration done using that code.

At the end I implemented something to replicate the configuration done in the xml file and create a new Appender using JsonLayout, since there is no way to change a Layout of an existing Appender.

**Comment by miltonbo** [comment]
All changes were done in:
1. oxAuth, configuration needed.
2. oxCore, loggingService where is updated all loggers.
3. oxTrust, to show the new json property.
4. community-edition-setup, templates updated.
