### ISSUE TITLE
Authorization header: "Bearer" should not be case sensitive 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1309]
This issue was raised in the node openid client:
  https://github.com/panva/node-openid-client/issues/248
At the /userinfo endpoint, both should work:
 `Authorization: bearer xxxxxxxx` and `Authorization: Bearer xxxxxxxx`

**Comment by uprightech** [comment]
According to RFC 2617 , the same applies to Basic authentication , so I went ahead and made the required changes.

**Comment by uprightech** [comment]
Fixes in commit 801e1ee1f35e912f50c75675661cc522be6862ef

**Comment by yuriyz** [comment]
@uprightech looks good except alien code which @panva already identified (https://github.com/GluuFederation/oxAuth/commit/801e1ee1f35e912f50c75675661cc522be6862ef#r38850703). I've removed redundant code in 48d8ad919d19e19b9c31916c8b65076b9d95a535 . Ticket can be closed.
