### ISSUE TITLE
Token revocation not working as expected

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxAuth#1312]
Issue:
/oxauth/restv1/revoke not working as expected

1. Generate access token
2. Call /oxauth/restv1/revoke endpoint to revoke the token
3. Although we get  200 OK response from this endpoint but /oxauth/restv1/introspection endpoint response shows token is active (active: true). and logs shows token is not removed as it should.

**Comment by yurem** [comment]
The issue is in next line:
```
grantService.removeAllTokensBySession(authorizationGrant.getTokenLdap().getSessionDn());
```

Not all tokens belongs to the session. As result it not work in some cases.
