### ISSUE TITLE
CIBA: Conformance Testing for FAPI-CIBA

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxAuth#1316]
Sub-ticket of #750

https://openid.net/specs/openid-financial-api-ciba-ID1.html

**Comment by yuriyz** [comment]
@miltonbo Would you please take over while Javier is out?

**Comment by miltonbo** [comment]
I configured `ce-ob.gluu.org` env with FAPI-CIBA profile. Created client certificates and configuration needed for test plan.

Test plan created in OpenId conformance suite: https://www.certification.openid.net/plan-detail.html?plan=LGXZo5OEwx4OX&public=true

**Comment by miltonbo** [comment]
Test plan for MTLS with Ping flow: https://www.certification.openid.net/plan-detail.html?plan=MzYYHCa3FnLaD&public=true

**Comment by miltonbo** [comment]
Test plan for Private Key JWT with Ping Flow: https://www.certification.openid.net/plan-detail.html?plan=UWLmKRd1uDp2p&public=true

**Comment by miltonbo** [comment]
Test plan for Private Key JWT with Poll Flow: https://www.certification.openid.net/plan-detail.html?plan=aDUo6NeCW8Kg1&public=true

**Comment by yuriyz** [comment]
Closing it. 4.2 is FAPI-CIBA certified.

https://openid.net/certification/
https://openid.net/developers/certified/
