### ISSUE TITLE
Add support to store session in htmlLocalStorage as an alternative to cookies

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1326]
Many browsers are blocking third party cookies. Perhaps storage in html5 localstorage is an alternative.  This also provides potentially more space to store information about consent or logout.

**Comment by yuriyz** [comment]
Cookies are sent as header by browser automatically. If we don't save session to cookie then how do we plan to send it from user-agent to AS? As request query parameter?

**Comment by nynymike** [comment]
security issues with localStorage for sessions.
