### ISSUE TITLE
CIBA: Securely store configuration keys.

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxAuth#1327]
See https://github.com/GluuFederation/oxAuth/issues/1319

Sub-ticket of #750

**Comment by miltonbo** [comment]
Where should be stored that data? Which keystore or service do we already have to achieve this target?

**Comment by qbert2k** [comment]
You can check in oxTrust code how it is achieved for oxAuthClientPassword, idpBindPassword, idpSecurityKeyPassword, etc. in its configuration.

**Comment by miltonbo** [comment]
Got it, I implemented this using a service already implemented called `StringEncrypter` that is implemented in `oxCore`. Basically it is using a key already configured in a file. This implementation includes:
1. oxAuth, just to decrypt that `notificationKey` field.
2. oxTrust, to encrypt and decrypt same field.
