### ISSUE TITLE
Set public subject identifier per client

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1336]
It's possible that one application would want email as the public identifier for subject, while another might want username. We should enable the public subject identifier to be set on a per client basis.

**Comment by yuriyz** [comment]
Re-scheduled to 4.3 as agree with Mike.

Issue is going to be solved by new custom script which should allow to customize identifier in different ways.

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/29
