### ISSUE TITLE
Support new localizations without modifying faces-config.xml

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1339]
We need to find a way how to avoid editing: https://github.com/GluuFederation/oxAuth/blob/version_4.1.1/Server/src/main/webapp/WEB-INF/faces-config.xml#L7

And use instead of this list: https://github.com/GluuFederation/community-edition-setup/blob/master/templates/oxauth-config.json#L175
which it's possible to change in oxTrust GUI.

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/28
