### ISSUE TITLE
Support for Encoding claims in the OAuth 2 state parameter using a JWT

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#134]
[https://tools.ietf.org/html/draft-bradley-oauth-jwt-encoded-state-05](https://tools.ietf.org/html/draft-bradley-oauth-jwt-encoded-state-05)

In the OAuth 2.0 Authorization protocol [RFC6749] , the Authorization
   server SHOULD perform an exact string comparison of the
   "redirect_uri" parameter with the "redirect_uri" parameter registered
   by by the client.  This is essential for preventing token leakage to
   third parties in the OAuth implicit flow.

   As a result of this clients can not safely add extra query parameters
   to the "redirect_uri" parameter that encode additional client state
   information.

   The Client MUST use the "state" parameter to encode both Cross Site
   Request Forgery protection and any other state information it wishes
   to preserve for itself regarding the authorization request.

   This draft proposes a mechanism whereby multiple state attributes can
   be encoded into a JSON Web Token JWT [RFC7519] for use as the value
   of the "state" parameter.

**Comment by qbert2k** [comment]
https://github.com/GluuFederation/oxAuth/blob/master/Client/src/test/java/org/xdi/oxauth/ws/rs/EncodeClaimsInStateParameter.java
