### ISSUE TITLE
Front channel logout fails to logout all session participants after a re-authentication

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1341]
## Expected Behaviour

As per the [spec](https://openid.net/specs/openid-connect-frontchannel-1_0.html#OPLogout): "OPs supporting HTTP-based logout need to keep track of the set of logged-in RPs so that they know what RPs to contact at their logout URIs to cause them to log out."

oXauth should keep track of this information until either:
a) the session is explicitly ended by calling the end_session endpoint, or
b) the sessionIdLifetime expires.

## Actual Behaviour
oxAauth loses track of the set of logged-in RPs if a re-authentication is performed as a result of receiving an authentication request specifying prompt=login, or max-age=n where n has expired.

## Steps to Reproduce
1. Log in from RP 1
2. Log in from RP 2 with prompt=login
3. Call the end_session endpoint
4. oxAuth produces a logout propagation page containing an iFrame for RP2, but not for RP1.

**Comment by yuriyz** [comment]
Fixed in 4.2
