### ISSUE TITLE
CIBA: QA doc

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxAuth#1342]
Create a Wiki page on the oxAuth github site: https://github.com/GluuFederation/oxAuth/wiki

1. CIBA Configuration. Explain how to setup ciba using oxTrust UI.

2. CIBA Test. How to tests the CIBA flow (poll, ping, push modes) using oxAuth-RP and alternatively using Postman app.

Sub-ticket of https://github.com/GluuFederation/oxAuth/issues/750

**Comment by miltonbo** [comment]
In order to process tests, I'm implementing all flows (ping, push and poll) in the module called `oxAuth-RP`. Also this module will be used to complete the wiki.

**Comment by miltonbo** [comment]
It's finished first version of `oxAuth-RP` with CIBA flows integrated. Pull request created.

Wiki: https://github.com/GluuFederation/oxAuth/wiki/Client-Initiated-Backchannel-Authentication
