### ISSUE TITLE
Store uid in pairwiseIdentifier entry

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1345]
We need to add to `pairwiseIdentifier` OC `oxAuthUserId` attribute.
Also oxAuth should use this new attribute instead of sub user DN if DB not support tree model.

**Comment by yuriyz** [comment]
Added `oxAuthUserId` to `pairwiseIdentifier` and saved user's `inum`, so it should work now in couchbase too. Done in 4.1.1 and 4.2.
