### ISSUE TITLE
Use personInum attribute instead of oxAuthUserId

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1346]
CE 4.x stores person inum in `oxAuthUserId` attribute in `pairwiseIdentifier` and `oxClientAuthorization` OC.
As result this cause misunderstanding. CE should use `personInum` instead of `oxAuthUserId`  to store perston inum

**Comment by yuriyz** [comment]
I guess in 5.x we should revise our attributes usage in general. Drop oxAuth prefixes and make names shorter. We should consider all ideas we discussed during Key Shortcuter discussions.

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/26
