### ISSUE TITLE
OPENID Connect :  Request for Permission page only shown on second login attempt after 40s  interval.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxAuth#1350]
## Describe the issue
If you perform SSO using OPENID Connect , it will taken to login page then , Request for Permission page , then just logout from client , immediately if you try to login again , it will only prompt the login page while skip request for permission page , but after logout if you wait around 40 second , it will show you that both page.

## Steps To Reproduce
You can use this https://github.com/mcguinness/oidc-rp client to create this scenario.

1. Setup SSO using OPENID Connect with disabled Persist Client Authorizations.
2. On First Page , Perform login authentication 
3. On Second Page, Allow request for Permission 
4. After Successful login  , logout the session.
5. Now try to login again immediately .
 

## Expected behavior
Client must perform Login Authentication and request for permission  Authorization even if the request call immediately after logout.

## Actual behavior
Request for Permission page skip if the second request come less than 40 second.

### Video 
I am attaching video for reference. 

[openidissue-2020-04-14_21.56.42.zip](https://github.com/GluuFederation/oxAuth/files/4616268/openidissue-2020-04-14_21.56.42.zip)

### Version
Gluu version 4.2

**Comment by yuriyz** [comment]
Bug is fixed in 4.2. Issue was that even if "Persist Client Authorization" is false, server put client authorization into cache for 60 seconds.
