### ISSUE TITLE
Security: Block "none" and not signed tokens

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/oxAuth#1358]
## Block "none" and not signed tokens
Accepting (`None`) and **not signed** JWTs is a **vulnerability** issue. 

During the issue #1306 I realized that oxAuth (validateSignature for example) validates `alg:'none'` and empty signature.

See:
- https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/
- https://tools.ietf.org/html/rfc7519
- https://www.softwaresecured.com/security-issues-jwt-authentication/
- https://www.pingidentity.com/en/company/blog/posts/2019/jwt-security-nobody-talks-about.html

As far as I understand, *none alg* tokens should be:
- rejected at all, or
- rejected when a secret-key was used to issue them.

## Steps To Reproduce

1. Create a `inbound-saml` (passport) enviroment with Gluu acting as IDP as well. (both versions 4.1.0)
2. Use a proxy to intercept browser requests (I used BURP Suite)
3. During the authentication, **intercept** `POST` to `postlogin.html` (right after saml assertion post) and change the original token to `alg = 'none'` and delete the encoded - you can use my jwt tool: https://github.com/christian-hawk/my-jwt-tools to do it quickly.

## Expected behavior
Do not allow this kind of attack

## Actual behavior
Allows "none" and without signature, logs in.

**Comment by yuriyz** [comment]
This issue describes validation which is triggered withing Custom Authentication Script `SamlPassportAuthenticator.py`. Thus is can be mitigated within the script. However still it can be useful it forbid `None` signature algorithm globally within oxauth. If `verifySignature()` method is called with `SignatureAlgorithm.NONE` reject it. 
We can introduce global property `rejectJwtWithNoneAlg` with default value `true`.

**Comment by yuriyz** [comment]
Done in 4.2
