### ISSUE TITLE
Login Page blank value error message is not user friendly.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxAuth#1365]
## Describe the issue
Currently if you try to login with blank username and password its showed you "loginForm:j_idt15: Validation Error: Value is required" which customers are complaining is not user friendly.

## Steps To Reproduce
Steps to reproduce the behaviour:
1. Go to login page
2. blank username or password
3. try to login

## Expected behavior
We can give provide more user friendly message "username or password is missing".

## Actual behavior
"loginForm:j_idt15: Validation Error: Value is required" this message is shown.

## Screenshots
![Screenshot from 2020-05-22 21-09-34](https://user-images.githubusercontent.com/34593983/82684661-9b0fde00-9c70-11ea-9165-22b2515ef851.png)

## Desktop (please complete the following information):
 - OS: [e.g. Ubuntu16.04LTS]
 - Gluu version 4.1

**Comment by sahilIT2020** [comment]
![image](https://user-images.githubusercontent.com/21104811/86658002-b3d11a80-bfb6-11ea-83ae-65bb96e84e02.png)
 still happening in 4.2 - 4.2.0-378.centos7

**Comment by shekhar16** [comment]
Fixed . Here is the screenshot.
![image](https://user-images.githubusercontent.com/15937500/166744658-a3a87fa1-b8c6-4b40-9ca9-e251eaa5825c.png)
