### ISSUE TITLE
UMA : claims gathering fixation attack

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#137]
Session Fixation Attack on UMA Trust Elevation Protocol (UMA 1.0.1 Section 3.6.3) #239 

https://github.com/KantaraInitiative/wg-uma/issues/239

**Comment by nynymike** [comment]
As this effects the claims gathering endpoint, do we need to worry about it?

**Comment by yuriyz** [comment]
Till now our main use case was to send RP claims in advance with RPT authorization call
```
org.xdi.oxauth.service.uma.authorization.AuthorizationContext#getRequestClaim()
```
But we still send needs_info without additional parameter to avoid vulnerability. Lets postpone the issue since it's not our main use case and also additional parameter actually breaks compatibility with current UMA 1.0.1 spec. I would expect to see it fixed first in specification.

**Comment by yuriyz** [comment]
Its not called a "Trust elevation" bug, its been re-named to a "claims gathering bug". We need solution in specification first to be fully compatible with it.

**Comment by nynymike** [comment]
Moot with the move to UMA 2.0
