### ISSUE TITLE
Control visibility of OAuth Scopes in configuration endpoint

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1370]
Scopes should have an attribute that enables the admin to specify if it should be published in the openid configuration endpoint (i.e. `.well-known/openid-configuration`).  Alternately, there could be a JSON property with a whitelist of published scopes.

**Comment by yuriyz** [comment]
@miltonbo We started to get test failures after it, I guess default value should be true, so optionally admin can disable advertisement on discovery page. Otherwise it should be handled by test properties to make build successful.

**Comment by yuriyz** [comment]
Also I think we don't need `notShowInDiscovery` attribute, there no need to query persistence by it. Thus it can be removed and use `org.oxauth.persistence.model.ScopeAttributes` instead.

**Comment by miltonbo** [comment]
Clossing this issue since all changes were done in oxAuth and oxTrust.
