### ISSUE TITLE
Migrate Super Gluu from U2F to Fido2

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#1376]
We need to update Super Gluu script and mobile authentication to use Fido2 endpoints instead of U2F

**Comment by nynymike** [comment]
Super Gluu has it's own project. So any thoughts on enhancements need to go there.

**Comment by nynymike** [comment]
I sort of think no... because we don't really want to invest a lot more in Super Gluu. It's not perfect, but it's good at what it's doing right now. Rather then update Super Gluu, I think we should start a new project to re-build from the ground up around a cross-platform single code base.
