### ISSUE TITLE
Correct security alert in test depedency

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1379]
## Describe the issue
We got security alert in test dependency. It doesn't effect oxauth but hanging security alert is not nice. We can't apply auto-fix from github because it breaks our selenium client tests. We have to find out the reason and possibly upgrade selenium to keep it compatible (or otherwise correct tests).

https://github.com/GluuFederation/oxAuth/network/alert/pom.xml/net.sourceforge.htmlunit:htmlunit/open

**Comment by miltonbo** [comment]
I'm closing this issue since last version has the issue fixed, there is no security alert and `dependabot` has closed its PR also.
