### ISSUE TITLE
maven repo for oxauth

### ISSUE THREAD

**Issue by anotherrohit** [GluuFederation/oxAuth#1389]
repo for oxAuth
I have been  trying to build oxAuth in the msAzure ad example using oxAuth, but unable to build oxAuth. The download from repo2.maven.org fails. Below is the error

downloading: http://repo1.maven.org/maven2/org/xdi/oxauth-client/4.0.0-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.xdi:oxauth-client:4.0.0-SNAPSHOT/maven-metadata.xml from/to bouncycastle (http://repo2.maven.org/maven2/org/bouncycastle): repo2.maven.org
[WARNING] Could not transfer metadata org.xdi:oxauth-client:4.0.0-SNAPSHOT/maven-metadata.xml from/to mavencentral (http://repo1.maven.org/maven2): Failed to transfer file: http://repo1.maven.org/maven2/org/xdi/oxauth-client/4.0.0-SNAPSHOT/maven-metadata.xml. Return code is: 501 , ReasonPhrase:HTTPS Required.
[WARNING] Failure to transfer org.xdi:oxauth-client:4.0.0-SNAPSHOT/maven-metadata.xml from http://repo2.maven.org/maven2/org/bouncycastle was cached in the local repository, resolution will not be reattempted until the update interval of bouncycastle has elapsed or updates are forced. Original error: Could not transfer metadata org.xdi:oxauth-client:4.0.0-SNAPSHOT/maven-metadata.xml from/to bouncycastle (http://repo2.maven.org/maven2/org/bouncycastle): repo2.maven.org
[WARNING] Failure to transfer org.xdi:oxauth-client:4.0.0-SNAPSHOT/maven-metadata.xml from http://repo1.maven.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of mavencentral has elapsed or updates are forced. Original error: Could not transfer metadata org.xdi:oxauth-client:4.0.0-SNAPSHOT/maven-metadata.xml from/to mavencentral (http://repo1.maven.org/maven2): Failed to transfer file: http://repo1.maven.org/maven2/org/xdi/oxauth-client/4.0.0-SNAPSHOT/maven-metadata.xml. Return code is: 501 , ReasonPhrase:HTTPS Required.
Downloading: http://repo2.maven.org/maven2/org/bouncycastle/org/xdi/oxauth-client/4.0.0-SNAPSHOT/oxauth-client-4.0.0-SNAPSHOT.pom
Downloading: http://repo1.maven.org/maven2/org/xdi/oxauth-client/4.0.0-SNAPSHOT/oxauth-client-4.0.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.574 s
[INFO] Finished at: 2020-06-09T22:03:25-07:00
[INFO] Final Memory: 10M/24M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project websample: Could not resolve dependencies for project org.xdi:websample:war:4.0.0-SNAPSHOT: Failed to collect dependencies at org.xdi:oxauth-client:jar:4.0.0-SNAPSHOT: Failed to read artifact descriptor for org.xdi:oxauth-client:jar:4.0.0-SNAPSHOT: Could not transfer artifact org.xdi:oxauth-client:pom:4.0.0-SNAPSHOT from/to bouncycastle (http://repo2.maven.org/maven2/org/bouncycastle): repo2.maven.org: Unknown host repo2.maven.org -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

I am using my pom parent as below
project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>websample</artifactId>
    <name>websample</name>
    <packaging>war</packaging>

  <parent>
    <groupId>org.xdi</groupId>
    <artifactId>oxauth</artifactId>
    <version>4.0.0-SNAPSHOT</version>
  </parent>
Any idea what is wrong. This is the sample project
https://github.com/navyasric/active-directory-java-webapp-openidconnect-v2

**Comment by yuriyz** [comment]
Github is used to track bugs. Support tickets should be opened on https://support.gluu.org.

Re: your question, it doesn't look as latest master. It's not clear what branch are you building.
For master you would need:
```
git clone https://github.com/GluuFederation/gluu-core-bom
mvn clean install
git clone https://github.com/GluuFederation/oxauth
mvn clean install
```
