### ISSUE TITLE
Update httpclient on oxauth / oxtrust to at least 4.3.2 so that it properly supports Server Name Indication

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#139]
Affects: gluu-server-2.3.x - 2.4.1, Ubuntu / CentOS

Server Name Indication allows a server to present different SSL certificates depending on the server name requested by the client. It may be used in testing Gluu server on the same machine as other applications, which may have their own SSL certificates.

[Wikipedia Article on Server Name Indication](https://en.wikipedia.org/wiki/Server_Name_Indication)

Testing:

  * Gluu is installed behind a reverse proxy web server (apache or nginx)
web server is configured with multiple SSL certificates on the same IP address. One domain name is assigned to Gluu with the correct certificate (gluu.local). The Gluu certificate is NOT the default.
  * Attempt to login to oxtrust by visiting the Gluu URL (gluu.local).  oxtrust redirects to oxauth and asks for a login upon successful login, oxauth redirects to oxtrust, which goes into a redirect loop
  * Upon investigating the logs, oxtrust fails to connect to the token endpoint due to an SSL error. (see oxtrust-redirect-loop.log)
  * The SSL error is treated as a null token, which makes oxtrust repeat the request again ad infinitum.
  * This is the case even when all SSL certificates of the Gluu server are trusted at the OS level. The problem goes away if you set the Gluu certificate as the default SSL certificate on the web server (but this may not be desired).
  
On further investigation, the client code in this backtrace:

    at org.jboss.resteasy.client.ClientRequest.post(ClientRequest.java:566)
    at org.jboss.resteasy.client.ClientRequest.post(ClientRequest.java:571)
    at org.xdi.oxauth.client.TokenClient.exec(TokenClient.java:303)
    at org.xdi.oxauth.client.TokenClient.execAuthorizationCode(TokenClient.java:112)

Indicates that the code executing the connection is JBoss Resteasy library.

JBoss resteasy currently has an issue supporting Server Name Indication _if httpclient is older than 4.3.2_

https://issues.jboss.org/browse/RESTEASY-1089

A quick search through the /opt/tomcat/ filesystem shows that the default installed httpclient is 4.2.3

    GLUU.root@gluu:/opt/tomcat# find -iname 'httpclient-*'
    ./webapps/oxauth/WEB-INF/lib/httpclient-4.2.3.jar
    ./webapps/identity/WEB-INF/lib/httpclient-4.2.2.jar
    ./work/Catalina/localhost/idp/WEB-INF/lib/httpclient-4.2.5.jar

Can we update the packaged `httpclient` on oxauth / oxtrust to at least 4.3.2 so that it properly supports Server Name Indication?

**Comment by nynymike** [comment]
@madumlao Moved from [https://support.gluu.org/integrations/server-name-indication-support-in-oxauth-oxtrust-2378](Gluu Support)

**Comment by yurem** [comment]
Now oxAuth/oxTrust/oxIdp uses:
httpcore-4.3.3.jar
httpclient-4.3.6.jar
resteasy-*-2.3.7.Final.jar

**Comment by JohnTheodore** [comment]
I have basically the same bug during my install. I followed this guide: https://www.gluu.org/docs/deployment/ubuntu/ .. and everything works fine. Once I replace httpd.cert and httpd.key with my own legitimate certificate, I have a redirect loop. I can load the login page, and my cert is working (the green lock shows, etc, so it's legit). Though after I click login.. I get a redirect loop.

Some of the log output is here: https://gist.github.com/JohnTheodore/ccaf4d3d2950fff2d967

GLUU.root@localhost:/opt# find -iname 'httpclient-*'
./apache-tomcat-7.0.55/work/Catalina/localhost/idp/WEB-INF/lib/httpclient-4.3.6.jar
./apache-tomcat-7.0.55/webapps/identity/WEB-INF/lib/httpclient-4.3.6.jar
./apache-tomcat-7.0.55/webapps/oxauth-rp/WEB-INF/lib/httpclient-4.3.6.jar
./apache-tomcat-7.0.55/webapps/cas/WEB-INF/lib/httpclient-4.2.5.jar
./apache-tomcat-7.0.55/webapps/oxauth/WEB-INF/lib/httpclient-4.3.6.jar
./apache-tomcat-7.0.55/webapps/asimba/WEB-INF/lib/httpclient-4.3.1.jar

Are there still versions of httpclient that are older in the chroot? also these jar files are repeated, wouldn't a symbolic link be better?

**Comment by madumlao** [comment]
@JohnTheodore 

I think we're gonna need more than the apache_vhost_log as this only logs the results of the front webserver, not the oxtrust / oxauth itself.

You need to do a tail on the /opt/tomcat/logs/wrapper.log at the time of the oxtrust login so we can see where the error is coming from. It's possible the httpclient error was already resolved but that you're encountering something else.

**Comment by JohnTheodore** [comment]
@madumlao here is https://gist.github.com/JohnTheodore/ac138c62b2f5c151b466 with a full log loop cycle in /opt/tomcat/logs/wrapper.log. That pattern repeats for as long as my web browser is trying to login.

**Comment by JohnTheodore** [comment]
I noticed here: https://github.com/GluuFederation/docs/issues/7 that it mentions the directory /etc/pki/java/. Do I need to modify certs in /etc/pki? I haven't done that.

Also this page is index by google, but gives me permission denied: https://www.gluu.org/docs/gluu-defaults/ .. it seems to have some documentation on keys/certificates.

**Comment by JohnTheodore** [comment]
According to this post: http://stackoverflow.com/questions/9619030/resolving-javax-net-ssl-sslhandshakeexception-sun-security-validator-validatore

I have to update the java keystore. Which is here: 

GLUU.root@gluu:/usr/java/latest/lib/security# ls -al cacerts
lrwxrwxrwx 1 root root 27 Jan 21 07:22 cacerts -> /etc/ssl/certs/java/cacerts
GLUU.root@gluu:/usr/java/latest/lib/security# file /etc/ssl/certs/java/cacerts
/etc/ssl/certs/java/cacerts: Java KeyStore

**Comment by JohnTheodore** [comment]
hmm, I don't know the java keystore password. The admin password for the webui doesn't work.

GLUU.root@gluu:/usr/java/latest/bin# keytool -list -keystore /etc/ssl/certs/java/cacerts
Enter keystore password:
keytool error: java.io.IOException: Keystore was tampered with, or password was incorrect
GLUU.root@gluu:/usr/java/latest/bin#

**Comment by JohnTheodore** [comment]
In /opt/apache-tomcat-7.0.55/conf/server.xml I discovered that tomcat is using it's own SSL I believe. A connector from that file here: 

  <Connector port="8443" address="localhost"
        protocol="org.apache.coyote.http11.Http11Protocol" scheme="https" secure="true"
        clientAuth="false" sslProtocol="TLS" SSLEnabled="true"
        keystoreFile="/etc/certs/shibIDP.jks"
        keystoreType="JKS" keystorePass="foobar"
        truststoreFile="/etc/certs/shibIDP.jks"
        truststorePass="bazqux" truststoreType="JKS"
        truststoreAlgorithm="DelegateToApplication"
        sslImplementationName="edu.internet2.middleware.security.tomcat7.DelegateToApplicationJSSEImplementation"/>


So I guess tomcat is trying to do it's own SSL with an invalid (self signed) cert?

**Comment by JohnTheodore** [comment]
Should I move this to it's own issue?
