### ISSUE TITLE
Intermittent authentication failure when using multiple oxauth pods

### ISSUE THREAD

**Issue by moabu** [GluuFederation/oxAuth#1395]
There is `authenticator.getFullNumber()` on twillio page which under the hood is calling `identify.getWorkingParameter()` which is `RequestScoped`. Means data is alive during request. Thus failing if another pod is run. 

Description:

- Authentication breaks regardless of backend and cache mechanism used. Provided we have more than one `oxauth` pod running.
- Tried with more than 2 pods and the behavior is the  same.
- Some observations though.
If we start with one pod - `pod A` - things works fine
Now scale the pods to whichever number, say 3 pods, now we have 
```
pod A
pod B
pod C
```
When an authentication call is made, we are not sure which pod will take care of that request.
1. If it happens to be `pod A`, authentication goes through- remember `pod A` was our initial pod.
2. If it happens to be any other pod, say `pod B` authentication fails at first try. Same case with `pod C` - will fail at first try.
3. If a pod is tasked to handle the request the next a user tries to login, it goes through. 
And so on

Associated [ticket](https://support.gluu.org/authentication/8339/intermittent-authentication-failure-when-using-multiple-oxauth-pods/)

[g-oxauth-6c7fdc9679-njjw9.txt](https://github.com/GluuFederation/oxAuth/files/4799690/g-oxauth-6c7fdc9679-njjw9.txt)
[g-oxauth-6c7fdc9679-hb89c.txt](https://github.com/GluuFederation/oxAuth/files/4799691/g-oxauth-6c7fdc9679-hb89c.txt)

**Comment by yuriyz** [comment]
Reference commit https://github.com/GluuFederation/oxAuth/commit/acef099f7616c7d5ff335a0e6436a7263de2b658

**Comment by syntrydy** [comment]
@moabu this issue is fixed only need testing now.

I did a test on 4.1.2 with Shamir and all looks good with the updated twillio script.

I will update 4.2 twillio script tomorrow.

**Comment by moabu** [comment]
Perfect. Thanks @syntrydy !

**Comment by syntrydy** [comment]
@moabu Fixed in 4.1.2 branch and tested. All working well with 3 oxauth pods. No extra volume mounting step.

**Comment by moabu** [comment]
Thank you. We will prepare the images with the release of 4.1.2.

**Comment by moabu** [comment]
Issue seems to still be present. We are re-doing the tests again

**Comment by moabu** [comment]
After using https://github.com/GluuFederation/community-edition-setup/blob/version_4.1.2/static/extension/person_authentication/twilio2FA.py and with the recent fixes. OTP sometimes has to be repeatedly placed. Details are [attached](i have to repeatedly enter the otp)

**Comment by mirr254** [comment]
I came across that. With the message `A text message with a verification code
was sent to UNKNXX USER PHONE.` As seen in the 2nd step picture shown below. By default it's supposed to show part of the phone number 
![Screenshot 2020-07-07 at 21 02 33](https://user-images.githubusercontent.com/13331207/86824358-b7d46980-c096-11ea-94f2-4def9f8bd43a.png)

**Comment by moabu** [comment]
latest [commit](https://github.com/GluuFederation/community-edition-setup/commit/8d5057e6cbf03997519768f8196d7fcd90bbc44b) by @syntrydy passed tests. We will wait for another confirmation and close this issue then.

**Comment by moabu** [comment]
The issue persists for longer periods of time. logs + video of issue can be found [here](https://support.gluu.org/authentication/8339/intermittent-authentication-failure-when-using-multiple-oxauth-pods/#at61942)

**Comment by mirr254** [comment]
Present in `oxauth:4.2.0_02` image. 
screen record link : https://www.dropbox.com/s/upn4ja8ckozkduc/Screen%20Recording%202020-08-06%20at%2009.04.47.mp4?dl=0

Attached are the logs for both pods and their script logs 

[mo-oxauth-7d48c999d5-4ctvq-pod.log](https://github.com/GluuFederation/oxAuth/files/5032996/mo-oxauth-7d48c999d5-4ctvq-pod.log)
[mo-oxauth-7d48c999d5-4ctvq-script.log](https://github.com/GluuFederation/oxAuth/files/5032997/mo-oxauth-7d48c999d5-4ctvq-script.log)
[mo-oxauth-7d48c999d5-556tl-pod.log](https://github.com/GluuFederation/oxAuth/files/5032998/mo-oxauth-7d48c999d5-556tl-pod.log)
[mo-oxauth-7d48c999d5-556tl-script.log](https://github.com/GluuFederation/oxAuth/files/5032999/mo-oxauth-7d48c999d5-556tl-script.log)

**Comment by moabu** [comment]
@syntrydy has the latest commits to 4.1.2 OxAuth been passed down to 4.2? It doesn't look like it https://github.com/GluuFederation/community-edition-setup/blob/version_4.2.0/static/extension/person_authentication/twilio2FA.py
