### ISSUE TITLE
Statistic : login and logout counters does not work correcly.

### ISSUE THREAD

**Issue by dollar007** [GluuFederation/oxAuth#140]
![2016-02-02_1922](https://cloud.githubusercontent.com/assets/10003469/12754009/edef62fe-c9e2-11e5-9594-d6653d1406ca.png)

**Comment by yuriyz** [comment]
It's about counters, not login/logout functionality itself. I've renamed the issue. Problem is that at one login request both counters successful and failed are increased at the same time.

**Comment by willow9886** [comment]
@yuriyz @yurem I believe this has been fixed... can we close this issue?

**Comment by yuriyz** [comment]
As far as I know @dollar007 said that it's fixed. Please reopen if reproducible on your side..
