### ISSUE TITLE
Remove PII from logs

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1402]
Some customers may prefer that the logs don't contain any PII. Information like the `uid` or `inum` would need to be removed. Perhaps we could blowfish encrypt it?

**Comment by emanoelxavier** [comment]
I recommend removing any user name/email but I believe logging inum since it is opaque is ok and probably useful.

**Comment by mtgluu** [comment]
I'm with ^. Obvious PII should be removed from the logs but I think that uid/inum is still appropriate. In larger deployments we still need a way to identify activity of users for security/fraud prevention/troubleshooting purposes. This also kind of ties in to providing more context to the logging about the activities being performed (as opposed to just thousands of log entries that say "user x authenticated successfully". Perhaps also ties into this: https://github.com/GluuFederation/oxAuth/issues/1059

**Comment by martynaslawinska** [comment]
Issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/25
