### ISSUE TITLE
Using 'Email' for authentication not working

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxAuth#1407]
## Describe the Issue :

Using 'Email' for authentication not working

##Step to reproduce :

1. open gluu user login page on web browser. 
2. login to gluu-server using user's email in place of user name.
3. try login.

## Expected Behavior
User must be login to gluu-server.

## Actual Behavior 
User failed to login with message "Failed to Authenticate".    

## Desktop
OS:-Ubuntu 16.04LTS
Gluu-version:- 4.1.x,4.2

**Comment by sahilarora2020** [comment]
https://gluu.org/docs/gluu-server/4.1/operation/faq/#request-email-instead-of-username-for-login

**Comment by MohitMaliFtechiz** [comment]
hi @sahilIT2020 thanks for help , I clicked update button instead to  activate  , closing this issue.
