### ISSUE TITLE
Add Support for OAuth2 Device Flow

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#141]
For devices that don't have a keyboard, there is OAuth2 device flow will enable them to enter a code to approve pairing, and for the device to then obtain an access token.  See this article from Google:

https://developers.google.com/identity/protocols/OAuth2ForDevices?hl=en

There is an example project here https://github.com/aaronpk/TVAuthServer

**Comment by yurem** [comment]
This is desired functionality which should help to popularize Gluu server and improve apps security.

**Comment by yurem** [comment]
I can help Javier to add this authentication method to oxPush2 just for reference or prepare new simple one for demo.

I have one idea.
As far as I remember Android application can allow other applications to call it Intent to do same actions. We can improve oxPush2 to help to developer other application and popularize oxPush2.
Here is workflow:
User mobile application -> oxPush 2 oxAuh Intent -> User open URL, enter code, etc.. -> oxPush 2 (Result of operation) -> User mobile application (Result of operation).

As result User mobile application should just call oxPush2 to execute workflow on oxpUsh2 side.

**Comment by qbert2k** [comment]
Also check: https://tools.ietf.org/html/draft-ietf-oauth-device-flow-03

**Comment by willow9886** [comment]
Still marked as Draft: https://tools.ietf.org/html/draft-ietf-oauth-device-flow-08

**Comment by suyambuganesh** [comment]
There is a new version but it is still marked as draft https://tools.ietf.org/html/draft-ietf-oauth-device-flow-15

**Comment by suyambuganesh** [comment]
Now the spec is rfc8628 https://www.rfc-editor.org/rfc/rfc8628.txt

**Comment by miltonbo** [comment]
Task that should be done:
1. Implement `/device-code` endpoint which should be responsible to create `user_code`, `device_code` and `verification_url`.
2. Verification UI, where user has to put `user_code`, validates it and redirects to authentication and authorization interface.
3. Implement `/activate` endpoint, it allows to Verification UI process the validation.
4. Implement changes in authn and authz flow to process device grant.
4. Implement changes in `/token` endpoint to allow polling flow based on authorization status and generates tokens required.

**Comment by miltonbo** [comment]
@nynymike Based on `RFC8628` specs, section 3.3.1 it's possible to have QR code representation in the verification UI in addition to the input box, however QR is optional, do you think this should be included in the UI implementation?

**Comment by nynymike** [comment]
It seems like this is an implementation detail for the client. Are we writing a test client? Would this be more convenient for testing / demo?

**Comment by miltonbo** [comment]
Yes, you are right, client shows QR, from our side we should support `verification_uri_complete` feature and show just a confirmation UI to the end-user then.

**Comment by miltonbo** [comment]
Finally, device flow is done, all changes:
1. `oxAuth` implementation.
2. `oxTrust` implementation.
3. New json properties added in `community-edition-setup` repo.
4. `oxauth-rp` implementation.
5. Documentation added in `5.0` version in `docs-gluu-server-prod` repo.
