### ISSUE TITLE
JWT Session Support

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#142]
Instead of storing sessions in LDAP, the OP passes all the session
information in an encrypted JWT. This way the server that receives the
token does not have to retrieve the session from LDAP, which can
reduce not only a lot of LDAP reads, but writes and replication
traffic.

Yura's comments: 

I offer to split initial idea into 2 parts:
1) Persist session in similar to JSF way as JWT token in JSF pages during log in.

2) Update other API which requires session functionality.

Moreover after implementing point 1 we should enable it by default.  It would mitigate a possible attack against our server that aims to overload LDAP.

**Comment by yuriyz** [comment]
as discussed with Mike, changing target to 2.4.4 for merging back to master

**Comment by yuriyz** [comment]
we will merge it back to master in 2.4.4 but provide full test and release in 2.4.5.

**Comment by nynymike** [comment]
I think we should pull the plug on this feature.
