### ISSUE TITLE
Performance: switch Client Authorizations from querying to getting by key

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1424]
## Describe the issue

Currently in CB we can see following query:
```
SELECT oxId, oxAuthUserId, oxAuthScope, del, exp, oxAuthClientId, dn FROM `gluu_user` AS gluu_doc WHERE ( ( objectClass = "oxClientAuthorization" ) AND ( oxAuthClientId = "1001.8739a8e4-34cc-4f76-93c3-f9a7e301861a" AND oxAuthUserId = "a580d06f-c939-48a4-854f-7e47d8407ff6" ) )
```
We have many such queries, therefore idea is to switch to key like `user_inum_client_inum` to allow get by key`.

**Comment by yuriyz** [comment]
@jgomer2001 I remember in the past when we changed something in client authorization some of your code was effected. Is it much to adapt on your side given description above?

**Comment by jgomer2001** [comment]
I have 2 types of queries over client authorizations:

- `(oxAuthClientId = "..." AND oxAuthUserId = "...")`
- `(oxAuthUserId = "...")`

If I understand the proposed change, the second bullet would have to be converted into _n_ separate queries (provided there exists _n_  clients). That wouldn't be a problem

AFAIK 4.2.1 should contain bug fixes only. Enhacements would go into 5.0 (unless this is really critical)

**Comment by yuriyz** [comment]
Done in 4.2.1. Introduced separate compatibility flag to keep old queries if needed (`clientAuthorizationBackwardCompatibility` default value false). Flag is present in 4.2.1 only (in 5.0 it's removed).

**Comment by yuriyz** [comment]
@jgomer2001 Both queries you specified above should work after this change. I guess you may want to change your `(oxAuthClientId = "..." AND oxAuthUserId = "...")` query to fetching by key.
