### ISSUE TITLE
Client unable to validate signature of received JWT tokens

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#143]
Per Gluu Support issue [2402](https://support.gluu.org/integrations/net-relying-party-unable-to-validate-signature-of-received-jwt-tokens-2402)

It would seem as though the jwks endpoint is exposing non-optimally sized Modulus Parameters. According to ietf the represented sequence of bytes should be unsigned and big endian.

It appears that when decoded the 'n' parameter's first byte is a null character. This appears to be a very similar issue to the one described here [on stackoverflow](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/42)

When I manually trim off the first byte I can successfully verify the signatures on the tokens that gluu provides me with.

To help I've provided some sample code that I picked apart from inside the Microsoft libraries to replicate the fault:

        // The original 'n' from the gluu jwks endpoint.
        var nFromGluu = "AKl1FARkO66k3D_3M-veO5cPgMKS6cMV9EeUM5bO-ZKa_silf5aQ5YXBCq5N4Xu6f3I6iWjCTBtahw2fCommWlnY9kUk5O5FWh3c-tnMk_TO6Wuwz8f3OaQLEsAULwHriNsqs9y80DUIn9peMP8yOAUJT2Fyq_q33j9RB5PEUGQYRA8C-C7JzwB9MsXWszJdBFzf-MKn60t9x8geD4uuVJnkMmiiuD-GjK7t1ew-Urs-fQSpieDPUZJpKvW1UF7iHwH8X1yFmnxadXz-fljsgyHw5Wy_yChvKa2hgyTiFeJRBPhoB5_fyh_mKNYkoaz6pXeRJPE7NCnpVSgnMawugbs";

        // Trim the first '0'/signing byte from the parameter
        var readBytes = Base64UrlEncoder.DecodeBytes(nFromGluu);
        var editedBytes = readBytes.Skip(1).ToArray();
        var nFromGluuFixed= Base64UrlEncoder.Encode(editedBytes);

        // Switching betweem 'nFromGluuFixed' and 'nFromGluu' swaps from a working signature verifier to a broken one :(
        var nToUse = nFromGluuFixed;

        // This is the result of calling the JWKS endpoint on the gluu server.
        var jwks= new JsonWebKeySet(@"{""keys"": [{
            ""kty"": ""RSA"",
            ""kid"": ""65ab27b1-9a81-411c-b45c-20404d68314e"",
            ""use"": ""sig"",
            ""alg"": ""RS256"",
            ""n"": """ + nToUse + @""",
            ""e"": ""AQAB""
            }]}");
        var tokens = jwks.GetSigningTokens();
        var handler = new JwtSecurityTokenHandler();

        var jwtString =
            @"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjY1YWIyN2IxLTlhODEtNDExYy1iNDVjLTIwNDA0ZDY4MzE0ZSJ9.eyJpc3MiOiJodHRwczovL3BzLWdsdXUtMDEiLCJhdWQiOiJAITE2MDQuMjUxNS43MDMyLjUxNTUhMDAwMSEyNTc4LkQ3MDghMDAwOCExMDI0LjI5QjAiLCJleHAiOjE0NTQ1MTg2ODQsImlhdCI6MTQ1NDUxNTA4NCwibm9uY2UiOiI2MzU5MDExMTg1Mzc1NDM3NTkuTlRobU9XUmtaV1V0T1RKbE1TMDBOMk0wTFRobU4yUXRORGMzTURVd1pqazBNREkwWkRRellURTBOekF0TmpFMU55MDBPVGsxTFRnNVlXSXRaamxtWmpJM056UmlNRGhrIiwiYXV0aF90aW1lIjoxNDU0NTE1MDc1LCJjX2hhc2giOiI0SnI4NkVFQ1lGbjlJdTU5QUtwZEd3Iiwib3hWYWxpZGF0aW9uVVJJIjoiaHR0cHM6Ly9wcy1nbHV1LTAxL294YXV0aC9vcGlmcmFtZSIsIm94T3BlbklEQ29ubmVjdFZlcnNpb24iOiJvcGVuaWRjb25uZWN0LTEuMCIsInVzZXJfbmFtZSI6ImFkbWluIiwibmFtZSI6IkRlZmF1bHQgQWRtaW4gVXNlciIsImZhbWlseV9uYW1lIjoiVXNlciIsImdpdmVuX25hbWUiOiJBZG1pbiIsInN1YiI6ImE0MzI4NzRiLWI4YTEtNGEzMC1hMzAzLTc5NGIwZjJjN2Q4MSJ9.fkGzeLcIxi1AP8UgVO0lUjqw3EGjRRiyVpX8PuoilJUpX8zGHILVpb29BzHKrcofE8dLkcgAXg5LylJDw1xd6UIin8CpbRUr1eFFVLuLMWx-FqpWgyylrjcBSVODobMg2sw58mKT5BUnHEoA5cg3BmfP4pn-P7IHGYMVHz9HMinuFg8gKfrjIh0W3tMLtQ0A0y2Xgi5MxgmvRy8ZyrwSF29VgmUw2wAFLsQdEwR4ucLeIFVI-tuikyG7kwu0NzQdQYik710sGqzQp25ZLfn6mve65SJ-RiEXmh2SUgIpemGHiExC57Q_hxO-0xQZ2XjKNN2TeqMz5zp6s1tt1FlFzw";
        var jwt = handler.ReadToken(jwtString) as JwtSecurityToken;
        byte[] encodedBytes = Encoding.UTF8.GetBytes(jwt.RawHeader + "." + jwt.RawPayload);
        byte[] signatureBytes = Base64UrlEncoder.DecodeBytes(jwt.RawSignature);
        SignatureProvider signatureProvider = new SignatureProviderFactory().CreateForVerifying(tokens[0].SecurityKeys[0], SecurityAlgorithms.RsaSha256Signature);
        if (!signatureProvider.Verify(encodedBytes, signatureBytes))
        {
            throw new Exception("Signature not valid!!");
        }

**Comment by ciaranj** [comment]
Just in case you don't cross-reference, I've isolated where the 'potential problem' creeps in over in the original support forum: https://support.gluu.org/integrations/net-relying-party-unable-to-validate-signature-of-received-jwt-tokens-2402

**Comment by nynymike** [comment]
Sure, the potential 'issue' is introduced in the [RSAPublicKey Class](https://github.com/GluuFederation/oxAuth/blob/e1198ff9e533be03ed87dda88adcef9e1816ce7c/Model/src/main/java/org/xdi/oxauth/model/crypto/signature/RSAPublicKey.java#L66)

[BigInteger.toByteArray()](http://docs.oracle.com/javase/6/docs/api/java/math/BigInteger.html#toByteArray()) returns a twos-complement encoded byte array that includes a signing bit. Since this modulus is meant to be unsigned according to the spec (as I read it) this encoding of the value is incorrect. A quick fix (as I demonstrated earlier) is to drop the first byte before encoding.

I do not know what impact this will have on existing clients however?!!?

**Comment by ciaranj** [comment]
Ty :)
