### ISSUE TITLE
Client-customizable mapping set for OIDC attributes

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#1440]
Current, Gluu Server release standard/official/default name of claims to RP. This feature request will enable Gluu Server to configure and release 'custom naming' for OIDC claims. 

As for example, the OIDC name of attribute "displayName" is "name" and Gluu generate/operate and release this "name" naming to OIDC RPs/apps.  If some RP has special requirement like "ScreenName" naming instead of "name" claim name, there isn't much option at this moment. 

So, it would be good if we could send like below way: 

Attribute LDAP name ( displayName ) --> OIDC name ( name ) --> Custom name ( ScreenName ) to RP. 

Please note that: this attribute's "value" will never change, that means... whatever is there in displayName/name attribute... it will be same in "ScreenName" which is a custom naming. 

Ref. ticket: https://support.gluu.org/feature-request/8605/client-customizable-mapping-set-for-oidc-attributes/

**Comment by martynaslawinska** [comment]
Issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/24
