### ISSUE TITLE
passport_saml and passport_social produces script error after reloading script.

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/oxAuth#1448]
## passport_saml and passport_social produces script error after reloading script.

When script is reloaded (when save/update custom scripts options on oxTrust), the variables are destroyed what raises
`AttributeError: 'PersonAuthentication' object has no attribute 'registeredProviders'`

On` passport_saml` script the issue was resolved on `4.2.x` here: https://github.com/GluuFederation/oxAuth/pull/1413

**Comment by jgomer2001** [comment]
can this be closed then @christian-hawk ?

**Comment by christian-hawk** [comment]
Not yet @jgomer2001

**Comment by christian-hawk** [comment]
closing. @kdhttps all good?

**Comment by kdhttps** [comment]
Yes
