### ISSUE TITLE
Issue new RPT as JWT for each authorization request

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#145]
"If the client did present an RPT in the request, the authorization
server returns the RPT with which it associated the requested
authorization data, which MAY be either the RPT that was in the
request or a new one."

https://docs.kantarainitiative.org/uma/draft-uma-core.html#give-rpt

So idea is to issue each time RPT as JWT for each request.

**Comment by nynymike** [comment]
Will be addressed in UMA 2.0
