### ISSUE TITLE
If there are more then one key for same `alg` and `use` then take key by `èxp` with configurable strategy

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1494]
## Describe the issue
If there are more then one key for same `alg` and `use` then take key by `èxp` with configurable strategy

We need it to work together with cluster key distribution support:

Cluster ticket: https://github.com/GluuFederation/docker-certmanager/issues/11

Related: https://github.com/GluuFederation/oxAuth/issues/1470

**Comment by moabu** [comment]
@yuriyz I think the idea is to use the one with earlier `exp` to allow other keys to be distributed in time. When it expires a new key would be used which would have been distributed previously.

**Comment by yuriyz** [comment]
Thanks for info. Yes, I saw discussion. I'm going to add strategy to get keys by crypto provider. Default will be `older`, however the other possible value would be `newer`, In this way we will be flexible on adding other strategies if needed.

**Comment by yuriyz** [comment]
Possible strategies:
- OLDER (default)
- NEWER
- FIRST

**Comment by yuriyz** [comment]
Implemented in 4.2.2 and jans.
