### ISSUE TITLE
gluu as mattermost authentication provider

### ISSUE THREAD

**Issue by mihai-satmarean** [GluuFederation/oxAuth#1500]
Hello and congratulations for this awesome project,
We came to realise that Gluu might be the one answer to our many questions,
We would like to be able to use Gluu as our Authentication provider for our multi-cloud multi app deployment.
One of the apps we need to authenticate, using any protocol, ldap, openid, etc is Mattermost Team Editions.

Even that the documentation for previous versions are stating: mattermost next, we cannot fing any good reference on how to configure.

Any help would be appreciated.

**Comment by nynymike** [comment]
Please register and open an issue on https://support.gluu.org
