### ISSUE TITLE
Modify the `claims-gathering` script so that it first tries to read claims from PCT before directing to the page to enter claims.

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/oxAuth#1506]
## Describe the issue
Modify the `claims-gathering` script so that it first tries to read claims from PCT before directing to the page to enter claims.
Parent ticket# https://github.com/GluuFederation/gluu-gateway/issues/452

Support ticket# https://support.gluu.org/access-management/9191/uma-tutorial-script-not-saving-claims/#at66355

**Comment by yuriyz** [comment]
@duttarnab add it to jans as well.

**Comment by duttarnab** [comment]
Done in 4.2.2 and jans
