### ISSUE TITLE
Send non-user attributes on jwt_claim `custom-data` though passport

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/oxAuth#1510]
Please check [internal support ticket 8920](https://support.gluu.org/8920) 
## Story
Me as a **customer**
Want to **be able to override id token lifetime**
So I can **control session timeout**

## Use-case
Customer needs to send non-user data (in this case `internal_override_id_token_lifetime`) through **Passport** saml inbound identity flow.

## Other modules involved:
- gluu-passport

## How
As discussed in the support ticket.
1. Passport will receive data from IDP
2. Passport will send JWT to [passport-saml script](https://github.com/GluuFederation/oxAuth/blob/master/Server/integrations/saml-passport/SamlPassportAuthenticator.py) with new `custom_data` claim, including `internal_override_id_token_lifetime` 
3. passport-saml script will decode and store data in session
4. oxAuth will get from session parameters stored by script, and use `internal_override_id_token_lifetime` if it exists in session to get lower id_token lifetime.

As talked to @nynymike this special feature is needed in new 4.3 as main feature requesters will not migrate to 5 right now.

So:
- [ ] Passport needs to be able to receive **new token id lifetime** and send it to custom script on jwt claim `custom_data` (issue created https://github.com/GluuFederation/gluu-passport/issues/187 )
- [ ] [passport-saml script](https://github.com/GluuFederation/oxAuth/blob/master/Server/integrations/saml-passport/SamlPassportAuthenticator.py) will decode it and store to session
- [ ] oxAuth will get from custom data from session and if ``internal_override_id_token_lifetime` exists, will override the id_token lifetime

**Comment by zaphod72** [comment]
Would this allow setting token lifetime on refresh tokens via script? For Passport SAML if the SAML expiry is long (say 30 days) we would want to set that lifetime on a refresh token rather than on the authentication token.

**Comment by nynymike** [comment]
With regard to oxAuth, this issue really boils down to one thing: we need to be able to modify the id_token via an interception script. Opened a new issue to track it: https://github.com/GluuFederation/oxAuth/issues/1523
