### ISSUE TITLE
Persistence extension script still running after disabled

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#1514]
While working on https://github.com/GluuFederation/scim/issues/10 I found  a potential error, so I tried to reproduce using  oxAuth only and got the same behavior. Here is the description:

- Start oxauth (persistence extension must be disabled)
- Create a user (with a password) by means of a custom script. In this case I wrote the logic inside the `init` method of the basic  script for simplicity (code below)
- Enable the persistence extension script
- After some seconds oxauth_script shows its initialization (correct behavior)
- Delete the dummy user from database
- Create a user again, eg. trigger a reload of basic script
- oxauth_script.log shows the extension script is executed and user password is hashed as expected (correct behavior)
- Disable the the persistence extension script
- oxauth_script.log shows the extension script is  destroyed (correct behavior)
- Delete the dummy user from database again
- Create a user once more, eg. trigger a reload of basic script
- oxauth_script.log shows the extension script is still executed and the user password was hashed (**incorrect** behavior)

This applies for 4.2.1 and 4.2.2 beta

Some code for quick insertion of user:

```
    def init(self, customScript,  configurationAttributes):
        print "Basic. Initialization"
        print "Basic. Initialized successfully"
        
        uss = CdiUtil.bean(UserService)
        user = uss.addDefaultUser("ajsmith")
        user.setAttribute("userPassword", "boo")
        uss.updateUser(user)
        print "user created"
        
        return True  
```

**Comment by yurem** [comment]
Fixed

**Comment by jgomer2001** [comment]
https://github.com/GluuFederation/oxCore/commit/b005d8228ebcfe3e813a6f5d4c61ce041df4c88c
