### ISSUE TITLE
FAPI : Dynamic registration - support JWS as payload for POST/PUT operations

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1522]
## Describe the issue
FAPI : Dynamic registration - support JWS as payload for POST/PUT operations

In UK open banking, software statements are wrapped in a outer JWS among other claims. This double singed payload is the actual content for OpenBanking dynamic client registration.

https://openbanking.atlassian.net/wiki/spaces/DZ/pages/1078034771/Dynamic+Client+Registration+-+v3.2#DynamicClientRegistration-v3.2-POST/register

**Comment by yuriyz** [comment]
Openbanking swagger https://github.com/OpenBankingUK/directory-api-specs/blob/master/directory-api-swagger.yaml

**Comment by yuriyz** [comment]
Openbanking swagger https://github.com/OpenBankingUK/directory-api-specs/blob/master/directory-api-swagger.yaml

**Comment by nynymike** [comment]
Move to https://github.com/JanssenProject/jans-auth-server/issues/22
