### ISSUE TITLE
New interceptions script to modify id_token

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1523]
We need a script that is invoked at id_token creation to enable transformation of claims and values.

Corresponding Janssen issue: https://github.com/JanssenProject/jans-auth-server/issues/23

Example use cases:
* Add custom claim to id_token
* Change token expiration
* Change value of `sub`
* Remove nonce

**Comment by yurem** [comment]
7b3d43b799f7adfcffba8ccddd7f2a0b56768f74

**Comment by yurem** [comment]
https://github.com/GluuFederation/oxTrust/commit/b3d9e03c32b7624d8188076e9f3d71ad578025e2

**Comment by yurem** [comment]
Sample script:
```
    def modifyIdToken(self, jsonWebResponse, context):
        print "Update token script. Modify idToken: %s" % jsonWebResponse

        jsonWebResponse.getHeader().setClaim("custom_header_name", "custom_header_value")
        jsonWebResponse.getClaims().setClaim("custom_claim_name", "custom_claim_value")

        print "Update token script. After modify idToken: %s" % jsonWebResponse
        return True
```

[Here](https://github.com/GluuFederation/oxExternal/blob/master/update_token/sample/UpdateTokenSample.py#L33) is full version.

**Comment by yurem** [comment]
Sample result:

![image](https://user-images.githubusercontent.com/6104200/108213525-2eaf0600-7140-11eb-9703-10fbfbb841d8.png)
