### ISSUE TITLE
Whitelist encryption and signing algorithms in JWKS

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1525]
Admins may want to restrict the content of the JWKS to only certain algorithms. There is a parallel issue in Janssen: https://github.com/JanssenProject/jans-auth-server/issues/74

**Comment by yuriyz** [comment]
I'm adding `keyAlgsAllowedForGeneration` configuration property. 

- If it's blank/empty/not set then all keys are generated (current behavior)
- If it's set then only keys with algorithm contained in the property are generated.

@moabu I'm adding support for it on oxauth side (and janssen). We need to support it on cluster as well (key generation pod).

**Comment by yuriyz** [comment]
Implemented in both 4.3 and jans.
