### ISSUE TITLE
multi_auth_script version: 4.2.3 failed to create Ldap connection pool with encoded password. 

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxAuth#1531]
## Describe the issue
Basic multi auth script failed to connect to ldap server with encoded password. 

``` 
2021-04-08 09:18:51,890 ERROR [oxAuthScheduler_Worker-2] [org.gluu.service.custom.script.CustomScriptManager] (CustomScriptManager.java:438) - Failed to initialize custom script: 'org.gluu.persist.exception.operation.ConfigurationException: Failed to create LDAP connection pool! Result code: '49 (invalid credentials)''
```
this break's with the introduction of this import 
```
from org.gluu.oxauth.service.common import EncryptionService
```
for bind password
```
  bindPassword = CdiUtil.bean(EncryptionService).decrypt(connectionConfiguration["bindPassword"])
```

## Steps To Reproduce
Steps to reproduce the behaviour:
1. Create new script in person authentication scripts.
2. follow the steps mentioned in script [script](https://github.com/GluuFederation/oxAuth/tree/version_4.2.3/Server/integrations/basic.multi_auth_conf)
3. encode the bind password using ```/opt/gluu/bin/encode.py```
4. define encoded password in auth_configuration_file
5.  check oxauth_script.log

## Expected behavior
Script must  be able to create ldap connection with LDAP servers.
## Actual behavior
Script failed to create LDAP connection pool.

## Desktop (please complete the following information):
 - OS: Ubuntu 18
 - Gluu version 4.2.3

**Comment by yuriyz** [comment]
Isn't it exactly case which @mzico tested here? 
https://github.com/GluuFederation/oxAuth/issues/1409

**Comment by mzico** [comment]
@yuriyz : Correct. Now.. none working. Not clear text and not encoded one.

**Comment by yuriyz** [comment]
There were no changes in AS for this ticket. It's pure script changes. Assigning it to @mzico and @maduvena

**Comment by yurem** [comment]
Fixed

**Comment by mzico** [comment]
Fixed. Confirmed and closing github issue. New script developed by @yurem.
