### ISSUE TITLE
Add JSON Property to release id_token for password grant

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1533]
Although the password grant is an OAuth flow, not OpenID Connect, some organizations may want to release an `id_token`. We can make a JSON property to enable this behavior, which should be `disabled` by default.

**Comment by yuriyz** [comment]
If set `openidScopeBackwardCompatibility` and `openid` scope is present then id_token is returned for password grant.

**Comment by yuriyz** [comment]
Closing this ticket as done given comment above. Please re-open if we need to add anything else to it (default value of `openidScopeBackwardCompatibility` is false).

**Comment by uprightech** [comment]
@yuriyz  I think @nynymike did mention some time ago that having to specify the `openid` scope may be some form of security vulnerability.
