### ISSUE TITLE
Oxauth-rp service unable to start after fresh installation of 4.3.0

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxAuth#1545]
## Describe the issue
Oxauth-rp service unable to start after fresh installation of 4.3.0

## Steps To Reproduce
1. Install the fresh gluu server 4.3.0
2. During installation select oxauth-rp as component.
3. check status of oxauth-rp service .

## Expected behavior
oxauth-rp must start after fresh installation.
## Actual behavior
oxauth-rp service failed to start.

## Screenshots
![Screenshot from 2021-06-03 21-13-23](https://user-images.githubusercontent.com/34593983/120673203-994a3e80-c4b0-11eb-88f3-23947cbdb8bf.png)

## Desktop (please complete the following information):
 - OS: Ubuntu 20
 - Gluu version 4.3.0

**Comment by yuriyz** [comment]
> Mike: Maybe it's time to remove oxauth-rp from the Gluu Server? It's not really used for much.
> YuriyZ: I agree. If nobody is against it I will drop it in 4.3.0.

I'm going to drop oxauth-rp in 4.3.0. Objections?

**Comment by mbaser** [comment]
I were not be able to replicate.
![Screenshot_2021-06-03_21-40-53](https://user-images.githubusercontent.com/6398752/120695798-7752bb00-c4b4-11eb-8e0a-b8d808588c14.png)

**Comment by MohitMaliFtechiz** [comment]
Hi @yuriyz ,

I don't have any objects on removing oxauth-rp.

Thanks and Regards
Mohit Mali

**Comment by yurem** [comment]
I'm ok with idea to remove it

**Comment by yuriyz** [comment]
Removed rp, rp-demo and rp-spring-boot modules from both oxauth 4.3 and jans.
