### ISSUE TITLE
Consent Gathering Script is not working in 4.3.0 version.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxAuth#1549]
## Describe the issue
Consent Gathering Script is not working in 4.3.0 version.

## Steps To Reproduce
1. Enable the Consent Gathering Script
2. Create Openid client.
3. Try to authenticate via client (in my case https://oidcdebugger.com/)

## Expected behavior
Consent Gathering Screen must prompt after authentication screen.
## Actual behavior
Failed to redirect to any screen due to consent gathering script is failed to intialized.

## Error logs
``` ERROR [oxAuthScheduler_Worker-1] [org.gluu.service.custom.script.CustomScriptManager] (CustomScriptManager.java:438) - Failed to initialize custom script: 'TypeError: init() takes exactly 3 arguments (2 given) ```
## Screenshots
![Screenshot from 2021-06-08 17-07-28](https://user-images.githubusercontent.com/34593983/121179134-f6f9d480-c87c-11eb-9005-3cead1af0c3e.png)

## Desktop (please complete the following information):
 - OS:  Ubuntu 20
 - Gluu version 4.3.0

**Comment by yurem** [comment]
Can you try to apply to script same update: https://github.com/GluuFederation/community-edition-setup/commit/3e05e26bf90789964110c4f2f841c77dc561d290

**Comment by MohitMaliFtechiz** [comment]
hi @yurem ,

this fixed the script but consent gathering screen appear without scope. please check attachment.

![Screenshot from 2021-09-14 17-26-08](https://user-images.githubusercontent.com/34593983/134329280-968b0c6c-e8b7-4ff0-a1f5-cad1dd1e9514.png)

**Comment by yurem** [comment]
Can you try to click Authorize? After that it should show you transaction page with custom claim

**Comment by yurem** [comment]
![image](https://user-images.githubusercontent.com/6104200/134906722-72ce7ae2-f004-4642-b15e-6c73336a0848.png)

**Comment by yurem** [comment]
Fixed. First page shows requested scopes
