### ISSUE TITLE
login_hint not used Authorization Grant (ACR=casa)

### ISSUE THREAD

**Issue by marchharesoftware** [GluuFederation/oxAuth#1551]
login_hint not used Authorization Grant (ACR=casa)

Ubuntu 18, Gluu 4.2.3.  Originally reported this issue here a few weeks ago, but I haven't heard back:
https://support.gluu.org/authentication/9707/login_hint-not-used-authorization-grant-acrcasa/

login_hint is an optional parameter in openid Authorization Grant:
https://gluu.org/docs/gluu-server/4.1/api-guide/openid-connect-api/#parameters_1

I found this old issue, which is fixed ages ago, suggesting that it should work:
https://github.com/GluuFederation/oxAuth/issues/120

I've switched the primary key from uid to mail in oxtrust as per the manual:
https://gluu.org/docs/ce/4.2/operation/faq/#request-email-instead-of-username-for-login

If I pass a valid email address via login_hint it does not appear in the custom login page.  The only change I've made to the template is to switch the label 'username' for 'email address' as suggested in the manual.

what I don't understand is:
- is login_hint implemented?
- does it work with primary key mail?
- does it work with authentication method casa?
- does it work with custom login pages?

my GET URL looks like this:
```
https://gluu.mydomain.com/oxauth/authorize.htm?login_hint=testah%40mydomain.com&amp;scope=openid+profile+email&amp;response_type=token&amp;redirect_uri=https%3A%2F%2Fweb2012.mydomain.local%2Fwebtools%2Fcustomer%2FLogin.aspx&amp;state=820649e7-a0db-4b95-971d-62e6ed7bca50&amp;nonce=86f97528-d914-4f97-af9b-048585610fd8&amp;client_id=7ef24196-3b95-4380-b593-98e300069421&amp;response_mode=form_post
```

I'm assuming that based on issue 120 that it is implemented, but that it doesn't work when I switch the primary key from uid to mail - and I'm assuming it's NOT a CASA issue.  That's a lot to assume I know, but I don't have a development environment set up to test these theories, and I figured it's best to capture the issue while it is still fresh in mind.

**Comment by shmorri** [comment]
This issue is also being tracked in https://github.com/GluuFederation/oxAuth/issues/1556. Thanks for your input and I'm making sure your notes are known by the team.
