### ISSUE TITLE
Error: Failed to persist entry, After passport social login

### ISSUE THREAD

**Issue by kdhttps** [GluuFederation/oxAuth#1552]
## Describe the issue
Trying login using passport social login but oxauth failed to save new user 

## Steps To Reproduce
1. setup any passport social provider e.g. google
2. try to login using google provider
3. when we get back to oxauth with user data, oxauth failed to save new user

## Expected behavior
oxauth should save new user

## Actual behavior
Currently failing with `Failed to persist entry` error, please check attached logs 

## Desktop (please complete the following information):
 - OS: Ubuntu 20.04LTS Server 
 - Gluu version: 4.3.0 installing using `gluu_install.py` script
 
[oxauth_script.log](https://github.com/GluuFederation/oxAuth/files/6817035/oxauth_script.log)
[oxauth.log](https://github.com/GluuFederation/oxAuth/files/6817037/oxauth.log)

**Comment by yuriyz** [comment]
It failed to persist entry due to duplication

```
Caused by: org.gluu.persist.exception.operation.DuplicateEntryException: Entry already exists
```

**Comment by yuriyz** [comment]
Fixed in 4.3 and jans.

**Comment by MohitMaliFtechiz** [comment]
@yuriyz i am attaching the oxauth logs.
[oxauth.log](https://github.com/GluuFederation/oxAuth/files/7234382/oxauth.log)

**Comment by yuriyz** [comment]
Basically we got 2 bugs : 
1. duplicated session entity - fixed [here](https://github.com/GluuFederation/oxAuth/commit/73d2154f3055f5724be7fed9456c636c2358704d)
2. messed attributes onf SimpleUser entity - fixed [here](https://github.com/GluuFederation/oxOrm/commit/6c0a8d5ff4c66f8336e1eec234177b9c3a218e3f)

@MohitMaliFtechiz has to confirm flow works as expected after fixes.

**Comment by yuriyz** [comment]
Fixed, re-tested by @MohitMaliFtechiz
