### ISSUE TITLE
login_hint not appearing.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxAuth#1556]
## Describe the issue
login_hint not working with latest 4.2.3 build.

## Steps To Reproduce
1. Go to admin console 
2. go to openid connect
3. create a client
4. request response on https://...domain.../oxauth/restv1/authorize with login hint.

## Expected behavior
login hint value  must be visible in username/email on login page .
## Actual behavior
No login hint shown on login 

## Desktop (please complete the following information):
 - OS: Ubuntu 20
 - Gluu version 4.2.3

**Comment by nynymike** [comment]
I'm not sure this is necessarily true. We want the `login_hint` to be available in the context. How a workflow decides to use that information (for example, whether to pre-populate it in the form), is up to the implementation of the interception script.

**Comment by mzico** [comment]
@qbert2k : tested in 4.2.3.sp2, not working. https://files.gluu.org/index.php/s/wNoJqb3bzr662wq

**Comment by qbert2k** [comment]
I found the bug with login hint also can be reproduced in the other versions using incognito modes firefox/chrome

https://user-images.githubusercontent.com/2474616/147036303-9bc4e251-31f6-40f2-9eb2-73e43d108941.mp4


https://user-images.githubusercontent.com/2474616/147036312-52e17386-0e72-4b14-a4e1-ae11f117f560.mp4

**Comment by qbert2k** [comment]
Fixed:

https://user-images.githubusercontent.com/2474616/147036805-bc7824d4-0bf0-415b-82ea-0ee78511cc5b.mp4


https://user-images.githubusercontent.com/2474616/147036806-a6d8019a-ddb1-44d4-9c0a-c848e46e3c5d.mp4

**Comment by yuriyz** [comment]
It's in jans master, 4.3.1 and 4.2.1.sp2. We need it also in oxauth master.

**Comment by mzico** [comment]
@yuriyz @qbert2k : can anyone give me the link of patched `4.2.3.sp2.war` please? I am getting 404 for `https://jenkins.gluu.org/maven/org/gluu/oxauth-server/4.2.3.sp2` branch...

**Comment by yuriyz** [comment]
@mzico see https://ox.gluu.org/maven/org/gluu/oxauth-server/4.2.3.sp2/

**Comment by mzico** [comment]
> @mzico see https://ox.gluu.org/maven/org/gluu/oxauth-server/4.2.3.sp2/

Thanks, it's working!
