### ISSUE TITLE
Bug: Clients registering with client credential grant should not also get Implicit

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1561]
When registering a client with “grant_types”: [“client_credentials”]. This triggers `org.gluu.oxauth.model.registration.public.RegisterParamsValidator` and then also requires a `redirect_uri`. I don't think that we want to add implicit grant type where it's not needed.

**Comment by Milton-Ch** [comment]
Currently, `client_credentials` grant type doesn't require `redirect_uri` as long as `redirect_uri` field in the request is empty, however this method could be improved, let me explain cases:
1. In case client sends some value in `redirect_uri`, then irrespective of which grant type it is, AS will validate it.
2. In case client doesn't send any value in `redirect_uri`, then AS will see if it's grant type = `client_credential`, if so then it will return "valid=true".

We could improve it switching order of statements, first AS should validate which grant_type client is trying to register, then if corresponds see what value `redirect_uri` contains, that way AS will always pass `grant_type=client_credentials`, irrespective of `redirect_uri` field.

FYI: @nynymike @yurem @yuriyz @qbert2k

**Comment by yuriyz** [comment]
It goes down to `response_type` and `grant_type` interpretation. We have two rules:
- If `response_type` has `token` or `id_token` -> add `implicit` to `grant_type` (if it's missed)
- If `grant_type` has `implicit` -> add `token` to `response_type` (if it's missed)

@nynymike This built-in "autofix" may confuse, should we add toggle configuration property to turn it off ? (We have this behavior for nearly 4 years.)

**Comment by Milton-Ch** [comment]
@nynymike @yuriyz should we do something here?

**Comment by nynymike** [comment]
I do think the behavior is confusing. I think it should be on the developer to get the `response_type` and `grant_type` right.  Also, what would happen to redirect_uri validation if the client used grant type `client_credentials` to register, and then updates the registration? I hope we're only validating the syntax here, like `scheme://string`.   Also, I wonder why this issue is in oxAuth and not Jans. It seems like this kind of fix should go in Jans. Net-net, I like the suggestion of @yuriyz to add a feature flag to disable the behavior in oxAuth. In Jans, I think we should not try to help the developer. If they don't specify the right response type, their bad.

**Comment by Milton-Ch** [comment]
Added new flag `grantTypesAndResponseTypesAutofixEnabled` to toggle this existing configuration, default false.
