### ISSUE TITLE
Some interleaved login/logout flows fail

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#1566]
Flows 2 and 3 (as in https://github.com/GluuFederation/oxTrust/issues/1474) show error at 2nd logout:

*Flow 2*:

1. Login to app A
1. Login to oxTrust
1. Logout from oxTrust
1. Logout from app A

*Flow 3*

1. Login to oxTrust
1. Login to app A
1. Logout from oxTrust
1. Logout from app A

Error shown at step 4 in both cases is:

```
{
"error_description": "The provided id token (or access token) or session state are invalid or were issued to another client.",
"error": "invalid_grant_and_session"
}
```

Details to reproduce:
- Environment: latest available 4.3
- app A = Casa (uses acr of level 1)

**Comment by yuriyz** [comment]
@jgomer2001 I suppose there no `frontchannel_logout_uri` registered by app A, right ? Otherwise how would we get logout at step 4 ? App A should be already in logout state because at step 3 app A gets `frontchannel_logout_uri` called and thus has to log itself out. I think we already discussed it.
https://github.com/GluuFederation/oxAuth/issues/992#issuecomment-458852171

**Comment by yuriyz** [comment]
From spec
```
frontchannel_logout_uri
OPTIONAL. RP URL that will cause the RP to log itself out when rendered in an iframe by the OP. This URL SHOULD use the https scheme and MAY contain port, path, and query parameter components; however, it MAY use the http scheme, provided that the Client Type is confidential, as defined in Section 2.1 of OAuth 2.0 [RFC6749], and provided the OP allows the use of http RP URIs. An iss (issuer) query parameter and a sid (session ID) query parameter MAY be included by the OP to enable the RP to validate the request and to determine which of the potentially multiple sessions is to be logged out; if either is included, both MUST be.
```

https://openid.net/specs/openid-connect-frontchannel-1_0.html

Closing as invalid, feel free to re-open if needed.
