### ISSUE TITLE
Fido2 and U2f auth script are failing in 4.3.1

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxAuth#1589]
### Describe the issue 

Fido2 and U2f auth script are failing

###  How to reproduce 

1. Go to admin ui 
2. Go to Configuration
3. Go to Person Authntication script
4. Activate Fido2 or u2f script
5. Change the default acr value to fido or u2f
6. check the auhentication in diffrent browser

###  Expected behaviour

if script is running user must be authenticate

###  Actual behaviour 

getting oxauth error 

### Config
Gluu-server 4.3.1

OS ubunut20.04

### logs

[Fido2_&_u2f_error.txt](https://github.com/GluuFederation/oxAuth/files/7538420/Fido2_._u2f_error.txt)

**Comment by jgomer2001** [comment]
related https://github.com/GluuFederation/oxAuth/issues/1597

**Comment by yurem** [comment]
Fixed
