### ISSUE TITLE
State param not returned in postlogout redirect URI

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1590]
When the RP provides a state, oxAuth is returning the `post_logout_redirect_uri` alone.

``` 
https://<GLUUEndpoint>/oxauth/restv1/end_session?id_token_hint=<TokenHint>&state=xxxxxx.xxxx&post_logout_redirect_uri=https://mydomain.com/logoutpage
```

Per [OpenID Connect RP-Initiated Logout 1.0](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout): 
_If included in the logout request, the OP passes `state` back to the RP using the state parameter when redirecting the User Agent back to the RP._

**Comment by yuriyz** [comment]
I will check

**Comment by yuriyz** [comment]
I can't reproduce it in 4.4.0. `state` parameters is present when AS performs redirect back to RP.

See https://github.com/GluuFederation/oxAuth/blob/b65149267d7cde4ed7a37322bdcadbaf23ccd0fb/Server/src/main/java/org/gluu/oxauth/session/ws/rs/EndSessionUtils.java#L66

It's possible to omit state in redirect back to `post_logout_redirect_uri` if provide `end_session` custom script with customized html/java script response.

E.g.
```
<script>
window.onload=function() {
     window.location=postLogoutUrl
}                    
</script>
```

**Comment by yuriyz** [comment]
@MohitMaliFtechiz would you please validate this ticket.

**Comment by MohitMaliFtechiz** [comment]
@yuriyz ok let me check it
