### ISSUE TITLE
U2F: Add TLS Channel ID Binding

### ISSUE THREAD

**Issue by Fred2seul** [GluuFederation/oxAuth#160]
TLS Channel ID support is missing (Channel Binding)

Channel Binding is a great protection against MITM attack.
Implemeting TLS Channel ID binding is an official recommendation inside FIDO specifications (but not mandatory).

On the client Side there is a built-in support inside Chrome browser. 
It would be great if Gluu can implement this protection. (This would make Gluu as the most secure FIDO U2F server implementation I know)
## Overview

Search for "MitM protection" inside:
https://developers.yubico.com/U2F/Protocol_details/Overview.html
You can see that channel ID is part of the hashed info that is signed by the U2F device. 
This is a really great way to reinforce the initial TLS Channel Binding protection that can be implemented outside FIDO U2F. 
## Official specification

Search for [SM-12] inside:
https://fidoalliance.org/specs/fido-u2f-v1.0-nfc-bt-amendment-20150514/fido-security-ref.html
It is not mandatory but makes a real difference regarding security.
(i.e. This option is activated for High Profile google users on their own authentication portal.)
## Server Side

You can see the patches against OpenSSL to implement TLS channel ID here:

https://chromium.googlesource.com/chromium/deps/openssl/+/7e6e6256e2a7c6fd7530394a851c6c656829d00d/openssl/patches/channelid.patch
## 

Frédéric Martin
System and Security Architect

**Comment by nynymike** [comment]
We put this in the queue for version 2.4.3 but it may slip to the version after that.

**Comment by Fred2seul** [comment]
Updated issue description text to add the link to openssl patch

**Comment by yurem** [comment]
`TLS Channel ID` is not widely supported even after 2 years:
- Edge: not supported
- Firefox: not supported
- Safari: not supported

Moreover `TLS Channel ID` is not standardized yet. Only Google supports it. That's why there is reference in U2F client data.

Server side also should support it. There is the path for apache2. But it's not activated yet. And it's not provide Channel ID either via headers or environment variables. Hence we have no proper server side support yet,

Here is very interesting discussion in Chrome forum https://groups.google.com/a/chromium.org/forum/#!topic/net-dev/AjFQjBmaEQE It's looks like they are going to remove it support.

**Comment by yurem** [comment]
Instead of `TLS Channel ID` I offer to use `Token Binding`

**Comment by yurem** [comment]
Here is what we can [implement](https://www.websequencediagrams.com/?lz=dGl0bGUgU3VwZXIgR2x1dSB3aXRoIFRva2VuIEJpbmRpbmcgc3VwcG9ydAoKQnJvd3Nlci0-UlA6IDEuIEFjY2VzcyByZXNvdXJjZSAoVEIxKQpSUC0-ACMHOiAyLiBBdXRoZW50aWNhdGlvbiBSZWRpcmVjdABECm94QXV0aDogMy4gUHJvAE4FQXV0aE4gJgA3BVoAUwUrVEIyKQpub3RlIG92ZXIgAC0INC4gU3RvcmUgVEIyIGluIHNlc3Npb24gKHdlIGNhbiBnZXQgZnJvbSBBcGFjaGUgdmlhIEhlYWRlcikKAHMGLT4AgXUKOiA1LiBTZW5kAIExBSByZXF1ZXN0IChQdXNoIE1lc3NhZ2UgKyAAgQcFAIIrCgCBOQo2ADkFdCBhADgGc3BvbnNlAIJOBmNpZF9wdWJrZXkgKACBNRc3LiBWYWxpZGF0AIE-EQCDEgVoYXNoIG9mAIFjCEZpZG8gVTJGAGYIAGgFAIISESwAg1MLOgCCMAcgc2VuZCBiYXNlNjR1cmwgZW5jbwCDZgVvZiB0aGUgU0hBLTI1NgBoCWEgVEIyAIImCQCDVAk4LiBSZXR1cm4gY29kAG4MUlA6IFIAgjUHaWRfdACESgUAhFQGQjEgKG9wZW5pZC1jb25uZWN0LQAaBS1ib3VuZC1hAIQgDSkK&s=default):
```
title Super Gluu with Token Binding support

Browser->RP: 1. Access resource (TB1)
RP->Browser: 2. Authentication Redirect
Browser->oxAuth: 3. Process AuthN & AuthZ (TB1+TB2)
note over oxAuth: 4. Store TB2 in session (we can get from Apache via Header)
oxAuth->Super Gluu: 5. Send Auth request (Push Message + TB2)
Super Gluu->oxAuth: 6. Sent auth response with cid_pubkey (TB2)
note over oxAuth: 7. Validate TB2 in session with hash of TB2 in Fido U2F auth reponse
note over oxAuth, Super Gluu: oxAuth send base64url encoding of the SHA-256 hash of a TB2
oxAuth->Browser: 8. Return code
note over RP: Request id_token with TB1 (openid-connect-token-bound-authentication)
```

**Comment by yurem** [comment]
For adding token `Token Binding` support we have both sides:
1) There is module which add to apache2 it support. I open [issue](https://github.com/GluuFederation/community-edition-setup/issues/461) to build it for CE.
2) Chrome and Edge has support of it.

**Comment by yurem** [comment]
Where is FAPI spec? There is no java library which support either `Channel ID` or `Token Binding`. There is [approach](https://github.com/pingidentity/java8-token-binding-negotiation) which override system classes. But it's not very good to override java classes.

**Comment by yurem** [comment]
We build CE 3.1.4 beta1 for [Ubuntu 18.04](https://github.com/GluuFederation/community-edition-setup/issues/461). It has enabled token binding module. Now we can resume work on this issue

**Comment by nynymike** [comment]
Don't confuse id_token ssl bonding with FIDO...

**Comment by yurem** [comment]
@nynymike why we need TLS Channel ID Binding ? There is no server/client /browser support of it?

**Comment by nynymike** [comment]
Closing this issue because new development should focus on FIDO 2.
