### ISSUE TITLE
U2F authentication fails after restart

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#163]
U2F authentication works when I first enable it. But after a server restart, it fails.

The apache error log shows:

     [Thu Feb 18 10:36:25 2016] [warn] [client 192.168.88.1] incomplete redirection target of '/identity/' for URI '/' modified to 'https://bonefish.gluu.info/identity/'

Here is the apache httpd access log:

    192.168.88.1 - - [18/Feb/2016:10:28:28 +0000] "GET / HTTP/1.1" 302 289 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
    192.168.88.1 - - [18/Feb/2016:10:28:28 +0000] "GET /identity/ HTTP/1.1" 200 83 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
    192.168.88.1 - - [18/Feb/2016:10:28:29 +0000] "GET /identity/login.htm HTTP/1.1" 302 - "https://bonefish.gluu.info/identity/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
    192.168.88.1 - - [18/Feb/2016:10:28:29 +0000] "GET /oxauth/authorize?scope=openid+profile+email+user_name&response_type=code+id_token&nonce=nonce&redirect_uri=https%3A%2F%2Fbonefish.gluu.info%2Fidentity%2Fauthentication%2Fauthcode&client_id=%40%21D5FB.51B7.280F.7FF1%210001%21B9C2.A11A%210008%21A29B.D034&acr_values=u2f HTTP/1.1" 302 - "https://bonefish.gluu.info/identity/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
    192.168.88.1 - - [18/Feb/2016:10:28:29 +0000] "GET /oxauth/login HTTP/1.1" 302 - "https://bonefish.gluu.info/identity/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
    192.168.88.1 - - [18/Feb/2016:10:28:29 +0000] "GET /oxauth/error.seam?cid=25 HTTP/1.1" 200 733 "https://bonefish.gluu.info/identity/" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
    192.168.88.1 - - [18/Feb/2016:10:28:29 +0000] "GET /oxauth/stylesheet/theme.css HTTP/1.1" 200 14188 "https://bonefish.gluu.info/oxauth/error.seam?cid=25" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
    192.168.88.1 - - [18/Feb/2016:10:28:29 +0000] "GET /oxauth/img/footer_bg.jpg HTTP/1.1" 200 13094 "https://bonefish.gluu.info/oxauth/stylesheet/theme.css" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
    192.168.88.1 - - [18/Feb/2016:10:28:29 +0000] "GET /oxauth/img/msgerror2.png HTTP/1.1" 404 999 "https://bonefish.gluu.info/oxauth/stylesheet/theme.css" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
    192.168.88.1 - - [18/Feb/2016:10:28:32 +0000] "GET /identity HTTP/1.1" 302 - "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
    192.168.88.1 - - [18/Feb/2016:10:28:32 +0000] "GET /identity/ HTTP/1.1" 200 83 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36"
    192.168.88.143 - - [18/Feb/2016:10:28:47 +0000] "GET /index.html HTTP/1.1" 404 277 "-" "Java/1.7.0_95"

All I see in the `oxauth.log` file is one line:

    2016-02-18 10:02:21,152 INFO  [org.xdi.oxauth.auth.Authenticator] Authentication success for Client: '@!D5FB.51B7.280F.7FF1!0001!B9C2.A11A!0008!A29B.D034'

And nothing in `wrapper.log`

**Comment by yurem** [comment]
It's similar to #202 issue.

After server restart oxAuth recovers sessions from LDAP by browser cookie.

**Comment by yurem** [comment]
Fixed:
https://github.com/GluuFederation/community-edition-setup/commit/3f25c2b1b273a7a4f015a9153e6cc6c8ba526127
