### ISSUE TITLE
fix: escape login_hint before rendering

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1657]
## Describe the issue

fix: escape login_hint before rendering

Support: 10394

**Comment by jgomer2001** [comment]
For the interested in patching its Gluu server manually, here are steps:

1. Login to chroot 
1. `cd /opt/gluu/jetty/oxauth/custom/libs && wget https://maven.gluu.org/maven/org/gluu/oxcore-jsf-util2/4.3.2-SNAPSHOT/oxcore-jsf-util2-4.3.2-SNAPSHOT.jar && cd ../..`
1. `cd custom/pages && wget https://github.com/GluuFederation/oxAuth/raw/version_4.3.2/Server/src/main/webapp/login.xhtml  && cd ../..`
1. Edit file `webapps/oxauth.xml`: uncomment the `extraClasspath` section so it looks like `<Set name="extraClasspath">./custom/libs/oxcore-jsf-util2-4.3.2-SNAPSHOT.jar</Set>`
1. Restart oxauth
