### ISSUE TITLE
Dynamic client registration managment DELETE event doesn't make it to oxAuth audit log 

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1658]
**Description:**

First reported in [this ticket](https://support.gluu.org/10365). When dynamically registered OIDC client is deleted via Dynamic Client Registration Management Protocol, corresponding entry won't appear in the `oxauth_audit.log`. Audit log entries will appear correctly for client creation and update meanwhile, meaning this part of functionality is generally covered by audit logging. According to the user who reported it, "action is already defined: [https://github.com/GluuFederation/oxAuth/blob/63e338902cb73d7158ce8a3e77e7e57a8a440aea/Server/src/main/java/org/gluu/oxauth/model/audit/Action.java#L16](https://github.com/GluuFederation/oxAuth/blob/63e338902cb73d7158ce8a3e77e7e57a8a440aea/Server/src/main/java/org/gluu/oxauth/model/audit/Action.java#L16)

..but it's not used here: [https://github.com/GluuFederation/oxAuth/blob/7d49c352a9927f785050820d8613acb26e374e62/Server/src/main/java/org/gluu/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java#L1043](https://github.com/GluuFederation/oxAuth/blob/7d49c352a9927f785050820d8613acb26e374e62/Server/src/main/java/org/gluu/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java#L1043)"

**Preconditions:**

1. Make sure audit logging is enabled: properties "enabledOAuthAuditLogging" and "dynamicRegistrationEnabled" must be set to "true" on "Configuration" > "JSON Configuration" > "oxAuth Configuration" page

**Steps To Reproduce:**

1. Register a client with a `curl` command: `# curl -k -X POST -H "Content-Type: application/json" -d '{"client_name":"test dynreg client","redirect_uris":["https://127.0.0.1:8080/login-redirect"],"response_types":["code","token","id_token"],"grant_types":["authorization_code"],"applicationType":"web"}' 'https://idp.local.host/oxauth/restv1/register'`
2. Check the `/opt/gluu/jetty/oxauth/logs/oxauth_audit.log` to make sure registration even is logged there; if it's not there test env isn't setup correctly
3. Delete the client with command like this (make sure appropriate registration access token and client id are used): `# curl -k -X DELETE -H "Authorization: Bearer a9ba6468-cce8-4572-af59-160f9531ce6f"  'https://idp.local.host/oxauth/restv1/register?client_id=a7bec024-d5f0-4b9a-be19-bb3a947196d7'`
5.  Check the `/opt/gluu/jetty/oxauth/logs/oxauth_audit.log` for the client delete even entry

**Expected behavior**

Client delete event is logged to audit log

**Actual behavior**

The log entry won't appear

**Comment by yuriyz** [comment]
Issue is fixed in 4.4, oxauth master and jans.
