### ISSUE TITLE
Login page doesn't display the correct localized characters

### ISSUE THREAD

**Issue by imShakil** [GluuFederation/oxAuth#1660]
## Behaviour 
On the login page, there are some characters that couldn't able to display properly. 

## Expected:

```
Falha na autenticação.
```

## Result:

```
Falha na autentica&ccedil;&atilde;o.
```

![](https://images2.imgbox.com/ec/fd/YB02tsxV_o.png)

## How to reflect?

I have customized [this](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/resources/oxauth_en.properties) resource file and put into `/opt/gluu/jetty/oxauth/custom/i18n`.

![](https://images2.imgbox.com/44/fd/KPOXOEyr_o.png)

Ref. Tickets: https://support.gluu.org/10241,  https://support.gluu.org/10107

## Gluu Server Info:

- OS: Ubuntu 18
- Version: Gluu 4.3.0
-

**Comment by yurem** [comment]
https://github.com/GluuFederation/oxCore/commit/d358637aca4ab07900125df8cc9b399ea0832e8d

**Comment by yurem** [comment]
![image](https://user-images.githubusercontent.com/6104200/210842807-f3dd5571-2198-45b9-83f5-7c4e451312a5.png)

**Comment by yurem** [comment]
![image](https://user-images.githubusercontent.com/6104200/210842994-b97fee5a-b98c-484a-bdda-aa5aeaf1b546.png)

**Comment by yurem** [comment]
Now we don't call Apache commons method `StringEscapeUtils.escapeHtml4(evaluatedMessage)` because current JSF version correctly do chars escape.

**Comment by yurem** [comment]
Also instead of escaping properties file with ASCII encoding you can use UTF-8 encoding
