### ISSUE TITLE
Upgrade crypto-js lib to 3.2.1 (or later if needed)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1682]
## Describe the issue

Upgrade crypto-js lib to 3.2.1 (or later if needed)

**Comment by Milton-Ch** [comment]
Library was updated in master version and also Gluu version 4.4.1, PRs:
https://github.com/GluuFederation/oxAuth/pull/1686
https://github.com/GluuFederation/oxAuth/pull/1683
