### ISSUE TITLE
Unauthorized Client

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxAuth#171]
While testing version 2.4.2 Beta-3, the following error was faced testing with Apache OpenID Module.

` {"error":"unauthorized_client","error_description":"The client is not authorized to request an access token using this method.","state":"YzNNr34VNG7QscNJedYIlBb3i_w"}`

**Note:** The module is in a separate VM which was used to test against 2.4.2.Beta-2 successfully. The configuration in the OIDC VM remained same, the Gluu Server VM remained same. Beta-2 was uninstalled and Beta-3 was installed before running the test again and this error came up. The error was faced in Chrome and FIrefox.

**Comment by nynymike** [comment]
Its unclear this is a bug. I'm closing this issue. Please open it on support with the respective apache httpd.conf configuration, ldif for the client, and oxauth.og or wrapper.log snippet.
