### ISSUE TITLE
New user is not active

### ISSUE THREAD

**Issue by NazarYavornytskyy** [GluuFederation/oxAuth#172]
When create new user using "https://ce-release.gluu.org/identity/register", new user is created but not active and I can't use his. What is correct behaviour in this case?

**Comment by yurem** [comment]
It's normal behavior because admin should review user.
But in default CE installation there is script: https://github.com/GluuFederation/oxExternal/blob/master/user_registration/sample/SampleScript.py#L42 which allows to enable newly registered users by default.
