### ISSUE TITLE
feat: introduce new UpdateToken methods in oxauth which exist in jans

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#1728]
## Describe the issue

Introduce new UpdateToken methods in oxauth which exist in jans.

Currently in oxauth we have one method: 

- modifyIdToken

In jans we have:

- modifyIdToken
- modifyAccessToken
- modifyRefreshToken
- getRefreshTokenLifetimeInSeconds
- getIdTokenLifetimeInSeconds
- getAccessTokenLifetimeInSeconds

**Comment by yuriyz** [comment]
Re-scheduling this ticket to 4.5.1.

**Comment by maduvena** [comment]
Hi, Need priotity on this issue
We want to be able to modify the scope for an AT (for a customer ticket)
```
    def modifyAccessToken(self, accessToken, context):
              context.overwriteAccessTokenScopes(accessToken, Sets.newHashSet("openid", "mynewscope"))
```

**Comment by yuriyz** [comment]
Agreed, I will work on it next week.

**Comment by yuriyz** [comment]
Reopen, docs are not updated yet

**Comment by maduvena** [comment]
@yuriyz I'll update the docs!

**Comment by yuriyz** [comment]
For docs I've pushed this https://github.com/GluuFederation/docs-gluu-server-prod/commit/42e44bc4dded1b4ff61179cb56e22335f4cf34a8

You are welcome to improve it. Closing ticket as resolved.
