### ISSUE TITLE
Swagger is part of the final war

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#173]
Why we put swagger and it's dependencies in final war?
Should we use it only and build time?

**Comment by yuriyz** [comment]
swagger is used only for documentation. I don't see any reason why do we need it in final war.

**Comment by yuriyz** [comment]
I would propose to declare only swagger-annotation which is the only lib we need to annotate our methods and rest of the libs split into separate  `documentation` profile.

**Comment by yurem** [comment]
maybe we can play with maven scope of this dependencies to exclude it and dependencies from war.

**Comment by yuriyz** [comment]
Swagger libs are excluded from oxauth server (except annotations) with commit https://github.com/GluuFederation/oxAuth/commit/a20f51906c827b74d0e18d3d8187a08f0e26d23f
