### ISSUE TITLE
Upgrade to Seam 2.3.1.Final

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#174]
oxAuth uses Seam 2.2.2.Final. It depends on jsf 1.2_12. It's old version which contains bug:
[The Encrypting client state feature does not work on cluster environment](https://java.net/jira/si/jira.issueviews:issue-html/JAVASERVERFACES-1013/JAVASERVERFACES-1013.html)

According to this issue [ViewState encryption: ByteArrayGuard is not thread safe / Does Not Take Into Account Session Failover](https://java.net/jira/browse/JAVASERVERFACES-2553) there is bug fix for issue in JSF > 2.2.5

**Comment by yurem** [comment]
Hence for proper work session state encryption we need to upgrade to Seam 2.3.1.Final because it depends on JSF 2.1.7

**Comment by yurem** [comment]
@mzico , @nynymike

**Comment by yurem** [comment]
The upgrade process from Seam 2.2.2.Final to Seam 2.3.1.Final will be not hard process because oxAuth not uses richfaces. It have only few JSF pages which should work fine or just requires few small changes.

There is one big problem. These are our server side TestNG tests. Seam 2.3.1.Final requires to use Arquillian testing suite instead of TestNG. I don't offer to convert our TestNG tests to this test suite. We tried to do that in oxTrust. But got big problesm. I think we need to just copy few base Seam test classes from 2.2.2 to allow still use TestNG...

**Comment by mzico** [comment]
Comment test

**Comment by yurem** [comment]
@nynymike

**Comment by yurem** [comment]
JSF 1.2_12 sometimes hangs for 10 minutes at startup:

http://markmail.org/thread/k34dib743meylowp#query:+page:1+mid:k34dib743meylowp+state:results

**Comment by yurem** [comment]
Implemented
