### ISSUE TITLE
Support CORS specification to allow clients that are subjects for same origin policy to access vital pages at OP

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#175]
The issue was first reported via [this ticket](https://support.gluu.org/customization/access-control-allow-origin-header-2490#at8802)
Environment: Ubuntu 64bit 14.04.4 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.4.1-1

Steps to reproduce:
1) Send some valid GET request containing "Origin: https://client.host.name" header for one of the listed urls and study headers of a response:
https://somehost/.well-known/openid-configuration
https://somehost/.well-known/webfinger
https://somehost/.well-known/uma-configuration
https://somehost/.well-known/simple-web-discovery
https://somehost/.well-known/fido-u2f-configuration
https://somehost/.well-known/scim-configuration

Result:
The response doesn't contain `"Access-Control-Allow-Origin: *"` header or/and other headers described in [CORS specification](http://www.w3.org/TR/cors/) what effectively prevents clients fully implemented in javascript ( i.e. those using implicit OpenID flow) from accessing it due to restrictions placed by same origin policy. This will prevent them from accessing OP's configuration metadata using **XMLHttpRequest()** method and will also break dynamic discovery flow for them in that case.

Expected result:
`"Access-Control-Allow-Origin: *"` (and possibly other) CORS header should be included when sending responses to GET requests for those  should-be-universally-accessible urls.
One solution to it could be using Tomcat's standard [CORS filter](https://tomcat.apache.org/tomcat-7.0-doc/config/filter.html#CORS_Filter) which can be configured in /opt/tomcat/conf/web.xml configuration file.
OpenID core specification also states that "The UserInfo Endpoint SHOULD support the use of Cross Origin Resource Sharing (CORS) [CORS] and or other methods as appropriate to enable Java Script Clients to access the endpoint", so it should be supported too (if it isn't yet)

**Comment by nynymike** [comment]
Note: [5.3](http://openid.net/specs/openid-connect-core-1_0.html#UserInfo)  now says CORS support should be supported.

**Comment by nathanhokanson** [comment]
When will this fix be available for general consumption?

**Comment by nynymike** [comment]
2.4.4 end of June.  But it's in progress right now, so it should be available on github if you are building oxAuth yourself.

**Comment by biswas123** [comment]
Has this been fixed, I still get the CORS error while trying to access from implicit login.

**Comment by willow9886** [comment]
@biswas123 best to open a ticket with details and steps to reproduce on https://support.gluu.org
