### ISSUE TITLE
Cannot get/read a custom claim(attribute) I created as part of the profile scope

### ISSUE THREAD

**Issue by swapsheth** [GluuFederation/oxAuth#177]
I added a custom attribute and added it to the profile scope. I see the new authorization in the UI screen, but when I parse the id_token I do not see the new attribute. I am sending openid and profile as scopes to the authorization URL. Is there anything else I am missing?

Thanks!

**Comment by nynymike** [comment]
When you use the access token to retrieve the user claims from the user_info endpoint, do you see it there?

**Comment by swapsheth** [comment]
Nope, don't see it there. I only see a vert few of the attributes that are part of the profile scope.

**Comment by nynymike** [comment]
Too old. Closing.
