### ISSUE TITLE
Redirect Login URI flexibility request

### ISSUE THREAD

**Issue by crazedmeph** [GluuFederation/oxAuth#1777]
I like the feature of allowing the Sector URI to allow the applications and a hosted file to declare what those allowed URI's are, but I believe this should be a feature and not a requirement. Every other IDP out there allows you to add multiple redirect uris right within the openid client page. Forcing this to be external requires a whole new team to be the one to update this value and it breaks the idea of this being all inclusive and might require a developer to create a solution just to get the IDP to work which sounds very counter intuitive. Forcing this (which no other IDP requires) will make things harder to maintain and make other IDP's more appealing. I believe we should allow you the ability to either add multiple login redirects or a single URI. But I do not believe this should be forced as it breaks the idea of a single IDP solution.

**Comment by mzico** [comment]
@nynymike : what do you think?

**Comment by nynymike** [comment]
Maybe this should be an oxTrust issue? There was a bug fix on 4.5 around redirect validation in oxTrust.
