### ISSUE TITLE
Cover JwtUtil methods by tests

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#178]
We need to covert JwtUtil.getPublicKey and JwtUtil.getPrivateKey by tests. In tests we need to generate jwks.json and try to get public and private key from it.

Also we have 2 methods now. I think we need to use method without signatureAlgorithm algorithm if we pass keyId. We need to review places where we call this method.

    public static org.xdi.oxauth.model.crypto.PublicKey getPublicKey(String jwksUri, String jwks, String keyId) {

    public static org.xdi.oxauth.model.crypto.PublicKey getPublicKey(String jwksUri, String jwks, SignatureAlgorithm signatureAlgorithm, String keyId) {

**Comment by yurem** [comment]
Also we can use next pattern if method expects specified algorithm only but useskeyId to get key.
  PublicKey publicKey = JwtUtil.getPublicKey(jwksUri, jwks, keyId);
  if (publicKey.getSignatureAlgorithm != expectedSignatureAlgorithm) {
        throw ...
  }

**Comment by nynymike** [comment]
I don't understand why these tests don't exist. This needs to be addressed asap.
