### ISSUE TITLE
Change response status 200 (Ok) by 201 (Created) for Client Registration

### ISSUE THREAD

**Issue by Milton-Ch** [GluuFederation/oxAuth#1780]
Currently Client Registration response with status 200 (Ok), but in the https://openid.net/specs/openid-connect-registration-1_0.html#rfc.section.3.2 it mentions that it should return 201 (Created).

**Comment by nynymike** [comment]
Add a property to maintain legacy behavior, because this could be breaking for customers.

**Comment by Milton-Ch** [comment]
I can also modify the response to `201` in code and upload the war to the server and deploy it to continue with the `certification`.

What do you think?

**Comment by nynymike** [comment]
Sure

**Comment by yuriyz** [comment]
Done in https://github.com/GluuFederation/oxAuth/pull/1790
