### ISSUE TITLE
Persisting uma_resource_set_permission tickets successively with same DN

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/oxAuth#179]
Error was encountered using:
http://ox.gluu.org/maven/org/xdi/oxauth-server/2.4.2.Final/oxauth-server-2.4.2.Final.war

and also reported in ticket:
https://support.gluu.org/integrations/unexpected-200-behavior-for-scim-user-group-endpoints-2540

Please see attached screenshots:
![entryalreadyexists](https://cloud.githubusercontent.com/assets/16329085/13666115/de07bc4a-e6ea-11e5-87f2-bde57b8c04b6.png)

**Comment by yuriyz** [comment]
Fixed in version_2.4.2
