### ISSUE TITLE
fix(oxauth): MySQL error on redirection in script

### ISSUE THREAD

**Issue by maduvena** [GluuFederation/oxAuth#1792]
## Steps To Reproduce

1. Create a mock redirection to 3rd party usecase on the same lines as - https://gluu.org/docs/gluu-server/4.4/developer-guide/tips-cust-script-pages/#redirecting-to-a-third-party-application-and-back
2. Use Gluu server with MySQL backend
3. Although the front channel flow appears to succeed, the session stays in the `UNAUTHENTICATED` state
4. Debug logs should be enabled
5. See error in oxauth logs
[protected_answer_11075_oxauth.log](https://github.com/GluuFederation/oxAuth/files/10922988/protected_answer_11075_oxauth.log)

**Comment by maduvena** [comment]
Logs:
[2023_03_17.jetty.log](https://github.com/GluuFederation/oxAuth/files/11017956/2023_03_17.jetty.log)

Sample files:
[redirectPerson-auth-script.txt](https://github.com/GluuFederation/oxAuth/files/11017982/redirectPerson-auth-script.txt)

Sample redirect App
```
1. place this html file inside a folder say sample-app inside /root folder

2. run the following command to run an http server- 
    python3 -m http.server 8321

3. Modify redirect URL in appPage.xhtml 
```

[appPage.html.txt](https://github.com/GluuFederation/oxAuth/files/11018016/appPage.html.txt)

**Comment by yurem** [comment]
I didn't find any issues related to MySQL.
In your example you run server without SSL. I put appPage.xhtml to `/var/www/html` to host it on apache2.
