### ISSUE TITLE
username and password default

### ISSUE THREAD

**Issue by jonathanleal** [GluuFederation/oxAuth#180]
installation put the password for the admin user, but can not enter the application. I've tried the user and without success. It has a default username and password?

![tela-login-gluupng](https://cloud.githubusercontent.com/assets/5817167/13672094/0963575c-e6b2-11e5-83a7-337595e2708f.png)

**Comment by nynymike** [comment]
Default user is **admin**
Default password: **# grep ldapPass /install/community-edition-setup/*.last**

**Comment by nynymike** [comment]
Deployment issues need to be raised on https://support.gluu.org
We use github for bug reports... i.e. once we have determined that a certain issue is related to a problem in the code.
