### ISSUE TITLE
Fix: Change invalid_claims_redirect_uri to invalid_client_metadata when registering a client with initiate_login_uri

### ISSUE THREAD

**Issue by Milton-Ch** [GluuFederation/oxAuth#1803]
Change `invalid_claims_redirect_uri` to `invalid_client_metadata` when registering a client with `initiate_login_uri` that is not `https`.

![image](https://user-images.githubusercontent.com/86965029/224463568-e6654852-41e0-4b05-8c3f-2e6172ae787b.png)

**Comment by yuriyz** [comment]
Fixed in https://github.com/GluuFederation/oxAuth/pull/1804
