### ISSUE TITLE
fix: client secret printed on logs.

### ISSUE THREAD

**Issue by mmrraju** [GluuFederation/oxAuth#1811]
### Describe the issue
We notice that client secret printed on `oxauth.log`.

Here is the class path 
https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/gluu/oxauth/token/ws/rs/TokenRestWebServiceImpl.java

## Expected behavior
Plain client secret should not be printed on logs.

## Actual behavior
Plain client secret printed on logs

## Screenshots
![Screenshot-oxauthlog](https://user-images.githubusercontent.com/43112579/227986006-b849ec1c-07fc-4e1e-b2c5-1e8f8799bf86.png)

## Desktop (please complete the following information):
 - OS: [e.g. Ubuntu20.04LTS]
 - Gluu version(4.5)

**Comment by yuriyz** [comment]
Fixed https://github.com/GluuFederation/oxAuth/commit/d9db24d7279330885f1ea3e3b85569d9d4b4accd
