### ISSUE TITLE
fix: isResponseStastusCodeOk check against other status codes

### ISSUE THREAD

**Issue by SafinWasi** [GluuFederation/oxAuth#1813]
## Describe the issue
Reference of https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/gluu/oxauth/service/net/HttpService.java#L247 
`isResponseStastusCodeOk` has a typo, and it only checks against `HttpStatus.SC_OK`, which is code 200. There may be other successful status codes, for example `201 Created`, which is returned by the `/register` endpoint.

## Steps To Reproduce
NA

## Expected behavior
The function should check against successful status codes (according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#successful_responses), codes 200-299 are defined as successful). Alternatively, custom script authors can check status code themselves by `HttpResponse.getStatusLine().getStatusCode()` and so this function can be deprecated.

**Comment by yurem** [comment]
Implemnented.
@yuriyz I added alias with fixed method name to allow do update later

**Comment by yuriyz** [comment]
Nice, thanks
