### ISSUE TITLE
fix: HttpService functions accounting for other status codes

### ISSUE THREAD

**Issue by SafinWasi** [GluuFederation/oxAuth#1814]
## Describe the issue
A number of functions in `HttpService.java` (https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/gluu/oxauth/service/net/HttpService.java) check against status code `200` to be successful. This is not true. Status codes 200-299 are defined to be successful, and functions should check for success in this range.

### Affected functions:
- `isResponseStastusCodeOk()` (related to #1813)
- `consume()`
- `getResponseContent()`

## Steps To Reproduce
NA

## Expected behavior
These functions should check in the range of successful status codes as defined in the [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#successful_responses).

**Comment by yurem** [comment]
Implemented
