### ISSUE TITLE
OAuth 2.0 for Native Apps (PKCE support )

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#184]
https://tools.ietf.org/html/rfc7636
https://tools.ietf.org/html/draft-wdenniss-oauth-native-apps-02

**Comment by yuriyz** [comment]
duplicate of https://github.com/GluuFederation/oxAuth/issues/126

**Comment by nynymike** [comment]
Also see new clients : [Android](http://gluu.co/app-auth-android) and [IOS](http://gluu.co/app-auth-ios)
