### ISSUE TITLE
Support passing custom parameters in the body of POST authorization request

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1860]
## Description

According to @yuriyz , 
>There are 2 ways to pass custom parameters to Authorization Endpoint in oxauth:
>1) via query parameters (directly in url as you shown above)
>2) via signed JWT request. Parameters can be encoded inside JWT

At the same time, [OpenID Core spec](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) mandates that POST method must be supported for accessing authorization endpoint:
>Authorization Servers MUST support the use of the HTTP GET and POST methods defined in RFC 2616 [RFC2616] at the Authorization Endpoint.

As our tests have shown, custom parameters are not passed all the way down to where they can be fetched from inside person authentication scripts if POST method is used for initial request with parameters (including the custom ones) being passed in the body of the request - as apparently they are lost during subsequent redirect to `/authorize.htm` endpoint. Regular parameters (like `redirect_uri` or `acr_values`) are processed correctly. In addition, everything works as expected if GET method is used and the custom parameters are passed via url query string; so the issue is only triggered if POST method is used.

Yuriy is familiar with the issue, as it was discussed with him in the chat.

**Comment by nynymike** [comment]
Did this feature actually get into 4.5.2 ?

**Comment by yuriyz** [comment]
@nynymike it's not done yet, I will take it on next week.

**Comment by yuriyz** [comment]
I've added support to pass custom parameters in the body of POST request.

However it does not solve initial problem of getting user authenticated at Authorization Endpoint with cookie but without redirects and pages.

For this I've added ROPC script support to Authorization Endpoint. By default it's off. 
It can be enabled with `forceRopcInAuthorizationEndpoint=true` AS configuration property.
Also it is required to set user in context in custom script (`context.setUser(<user>)`). Without it authorization will go on in normal way (with pages and redirects).

Fix is available in 4.5.2. War file is ready.
https://jenkins.gluu.org/maven/org/gluu/oxauth-server/4.5.2.Final/oxauth-server-4.5.2.Final.war

@aliaksander-samuseu would you please validate it and confirm it covers case which you initialy raised ?

**Comment by yuriyz** [comment]
Implemented in 4.5.2, 4.6.0. 
Docs updated https://github.com/GluuFederation/docs-gluu-server-prod/commit/605f2516404c34a8051b5717bb405050d11c36f8
