### ISSUE TITLE
Unable to add multiple case sensitive redirect URI 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#1867]
I am trying to add case sensitive multiple redirect URI for Front Channel logout in my client. oxAuth rejecting with below error: 

```
Processing MODIFY request for
inum=47ecec8b-cb23-45eb-8354-b4206115cc54,ou=clients,o=gluu
The LDAP modify request failed: 20 (Attribute or Value Exists)
Additional Information:  Entry
inum=47ecec8b-cb23-45eb-8354-b4206115cc54,ou=clients,o=gluu cannot be modified
because it would have resulted in one or more duplicate values for attribute
oxAuthLogoutURI: https://localhost:8443/Test_logout
```

How to reproduce the issue: 

 - Add a Front channel logout url: https://localhost:8443/test_logout
 - Save client
 - Try to add another logout url: https://localhost:8443/Test_logout
 - Save client
 
 There is not oxTrust error message. 
 
 Retry to do same from LDAP, you will get first error.

**Comment by yuriyz** [comment]
@mzico above error is from LDAP server, isn't it ? 
In schema for `oxAuthLogoutURI` attribute installation puts `EQUALITY caseIgnoreMatch`. Put quality to any value which makes case-exact match, for example `EQUALITY caseExactMatch`. Restart LDAP server and re-try use case.

**Comment by mzico** [comment]
@yuriyz : I can confirm that above modification in schema fix the issue. 
Here is what I did: 

 - Open `101-ox.ldif` 
 - Modify below snippet: 
   ```
      attributeTypes: ( 1.3.6.1.4.1.48710.1.3.160 NAME 'oxAuthLogoutURI'
      DESC 'oxAuth Policy URI'
      EQUALITY caseIgnoreMatch
      SUBSTR caseIgnoreSubstringsMatch
      SYNTAX 1.3.6.1.4.1.1466.115.121.1.15
      X-ORIGIN 'Gluu created attribute' )
   ```
 - To: 
  
     ```
      attributeTypes: ( 1.3.6.1.4.1.48710.1.3.160 NAME 'oxAuthLogoutURI'
      DESC 'oxAuth Policy URI'
      EQUALITY caseExactMatch
      SUBSTR caseIgnoreSubstringsMatch
      SYNTAX 1.3.6.1.4.1.1466.115.121.1.15
      X-ORIGIN 'Gluu created attribute' )
     ```
 - Restart ldap server
 - Output is below: 
 
 
![Screenshot from 2023-10-25 19-58-12](https://github.com/GluuFederation/oxAuth/assets/7156097/07cc45e0-0934-4c65-8d21-bb882862596c)
