### ISSUE TITLE
Unable to update scopes via client update 

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#188]
It's not possible to update scopes via client update.

**Comment by nynymike** [comment]
The client should only be able to add scopes if these scopes are "default". For example, if I have a scope called "dateOfBirth" that is not default, only the admin of the domain should be able to release the scope to a client.

**Comment by yurem** [comment]
Can we close this issue&

**Comment by yuriyz** [comment]
Lets move it to next release. 
@nynymike do you mean that at initial registration we can register any scopes but during update can change only defalut one ?

**Comment by worm333** [comment]
I've prepared [pull request](https://github.com/GluuFederation/oxAuth/pull/354) with fix.

**Comment by nynymike** [comment]
Should this be closed ?

**Comment by worm333** [comment]
Yes.
