### ISSUE TITLE
fix(oxauth): the `requestUriParameterSupported` and `requestParameterSupported` should be involved in request processing

### ISSUE THREAD

**Issue by mmrraju** [GluuFederation/oxAuth#1891]
Target [ticket-11696](https://support.gluu.org/authentication/11696/request_uri-and-request-parameters-using-jwt-for-passing-authentication-parameters-can-not-be-disabled/#at88367)
## Describe the issue
There  exist a configuration parameters under `OxAuth JSON` configuration - `requestUriParameterSupported` and `requestParameterSupported` (see https://gluu.org/docs/gluu-server/4.5/reference/JSON-oxauth-prop/#general-configuration )
If we set value to `false`, When RP still tries to use these. Gluu shoud returns  error codes and starts to handle the content of these parameters.
![Screenshot from 2024-02-16 20-15-56](https://github.com/GluuFederation/oxTrust/assets/43112579/e8eab7ae-cda0-49eb-9f41-531ead2e0544)

**Comment by yuriyz** [comment]
Fixed in 4.5.4 version.

**Comment by mmrraju** [comment]
Thanks.
