### ISSUE TITLE
fix(oxauth): Plaintext passwords logged from TokenRestWebServiceImpl with DEBUG log level

### ISSUE THREAD

**Issue by mmrraju** [GluuFederation/oxAuth#1910]
## Describe the issue
[Ticket-11878](https://support.gluu.org/authentication/11878/plaintext-passwords-logged-from-tokenrestwebserviceimpl-with-debug-log-level/)

User password prints on log. when `grant_type` is `passowd`.

`https://github.com/GluuFederation/oxAuth/blob/a40a882660e2468f640c85d0a814dd00f8c63dbd/Server/src/main/java/org/gluu/oxauth/token/ws/rs/TokenRestWebServiceImpl.java#L127. `

The "ExtraParams" will print out passwords for password_grant.

## Screenshots

![Screenshot from 2024-07-13 02-15-26](https://github.com/user-attachments/assets/f7d82478-ce66-4c81-b1be-0d3ba6b5ad67)

## Desktop (please complete the following information):
 - OS: [e.g. Ubuntu20.04LTS]
 - Gluu version(4.5)

**Comment by mmrraju** [comment]
Hi, @yuriyz any update?

**Comment by yuriyz** [comment]
I didn't check it yet

**Comment by yuriyz** [comment]
Fixed in master (4.5.6-SNAPSHOT).
