### ISSUE TITLE
bug(oxauth): UID became case sensitive for users after cache refresh in postgresql

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#1927]
Primary attribute, UID, by default case insensitive in Gluu Server. But we faced a different situation in postgresql equipped Gluu Server 4.5. If we pull users with Cache Refresh, those user's UID become case sensitive. As for example, if I have user whose uid is 'zico', I am unable to login as 'ZICO'. It has to be 'zico'. 

I tried to enable `citext` extension for postgresql server but it didn't help. 

Here is a full recorded screencast: https://us02web.zoom.us/clips/share/KZqFfL8fSXuM3PZWc6OomG27zL4sEl0YEwt264nXzKPfn9vkbw60snrDGeJAyqasgsxX9O4Fiuhj1wRRKvOuxD6w.XqofMIyTTMsfQnhW

**Comment by yurem** [comment]
Implemented
