### ISSUE TITLE
Revoke token endpoint

### ISSUE THREAD

**Issue by swapsheth** [GluuFederation/oxAuth#193]
I do not see a revocation_endpoint for revoking refresh/access tokens - /.well-known/openid-configuration? Am I missing something?

**Comment by yuriyz** [comment]
There are no `revocation_endpoint` defined in [Discovery specification](http://openid.net/specs/openid-connect-discovery-1_0.html). Are you referring to [Session management](http://openid.net/specs/openid-connect-session-1_0.html)? If yes, then you should see end_session_endpoint. Closing issue as invalid.
