### ISSUE TITLE
remove code duplication

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#195]
There are number of places where we have code duplication especially in tests. We have to avoid this error prone approach. 15 or 16 duplications indeed must be fixed.

![codeduplication](https://cloud.githubusercontent.com/assets/2013070/14102692/cb90dc0e-f5a4-11e5-867c-dee88c3bb0dd.png)

This can be the starting point. 
https://github.com/GluuFederation/oxAuth/blob/18f314421cc62b85d0ce064fd0e8f5d815f7b074/Client/src/test/java/org/xdi/oxauth/client/Asserter.java

However maybe it makes sense to really start very small test framework to avoid code duplication and as result increase stability of our tests.

**Comment by willow9886** [comment]
@worm333 maybe you can take a look at this?

**Comment by nynymike** [comment]
If this was an issue, it probably should be dealt with in a generic refactoring.
