### ISSUE TITLE
Every time I login to oxTrust, oxAuth asks me "Allow/Don't Allow"

### ISSUE THREAD

**Issue by dmogn** [GluuFederation/oxAuth#203]
I click "Allow" and it asks me again next time.

Ubuntu 14.04. v 2.4.3 1_1 Final

**Comment by aveekbu** [comment]
experienced the same on centos/rhl 6.x as well with firefox n chrome.

**Comment by mzico** [comment]
It's resolved... here is how you can disable that 'Popup'

- OpenID Connect --> Clients
- Pre-Authorization == Enabled
- Persist Client Authorizations == True

**Comment by zamilskhan** [comment]
Changing label to enhancement. maybe change the defaults so that it doesn't ask every time to be put in the next release

**Comment by yuriyz** [comment]
fixed. Tests are passed : https://ox.gluu.org/jenkins/job/oxAuth/589/
Now we need to test it manually.
