### ISSUE TITLE
Update bcprov library

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#205]
There is one problem with bcprov-jdk16-1.46.jar if both context are use this library. Only first context which initialized BC provider will work fine.
Example: indentity, oxauth.

For proper work in this case we need to put this library into:
tomcat_home/endorsed

But it's library is old and for jdk 1.6

I offer to upgrade to bcprov-jdk15on which supports JDK 1.5 - JDK 1.8.

**Comment by yurem** [comment]
If it's not in the scope of 2.4.4 we need to update setup to put this library to right place during setup.

**Comment by nynymike** [comment]
Tomcat starts oxTrust before oxAuth.  As result oxAuth can't use Bouncy Castle becuase both applications have this library.  We need to use in oxAuth/oxTrust instance of BC provider to avoid this. There is quick fix without oxAuthoxTrust update

```
# mkdrip -p /opt/tomcat/endorsed
# chwon -R tomcat.tomcat /opt/tomcat/endorsed
# cp -f /opt/tomcat/webapps/oxauth/WEB-INF/lib/bcprov-jdk16-1.46.jar /opt/tomcat/endorsed
# service tomcat restart

```

**Comment by yurem** [comment]
Also @dmogn told that there are problems related to this in other applications.

I think we should try to not use static library initialization:
https://github.com/GluuFederation/oxAuth/blob/master/Model/src/main/java/org/xdi/oxauth/model/util/SecurityProviderUtility.java#L26

Instead of this application should create BouncyCastleProvider() instance and pass reference to this object. Now we pass "BC" which require static initialization.

**Comment by dmogn** [comment]
Shib IDP V3 has bcprov-jdk15on-1.53.jar dependencies. 1.53 conflicts with 1.46. 
I cannot replace 1.53 with 1.46 because "class org.bouncycastle.asn1.ASN1Primitive not found".
I replaced v.1.46 with bcprov-jdk15on-1.53.jar in tomcat/endorsed and all work fine (at first look). No an exceptions in tomcat's logs.

**Comment by dmogn** [comment]
bcprov-jdk15on-154.jar - works well in tomcat/endorsed (latest version)
