### ISSUE TITLE
OpenID Connect Line Item Scope Approval

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#206]
It would be nice if the user could line item approve which scopes are released to an RP. This decision would also be persisted (if authorizations are being persisted).

**Comment by yurem** [comment]
It will be very nice future. Now most applications requires all permissions (scopes) even if they not needed them, just to gather more information about user.

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/73
