### ISSUE TITLE
New .well-known endpoint to publish acr configuration

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#208]
Delegate authentication method selection to RP is the good idea. But it requires additional resources to do that on RP side.

For me this issue requires changes on both sides: OP and RP.

1) There is one issue. According to the spec acr_values is an list. Now oxAuth uses first enabled method from this list. Why oxAuth can't handle this in better way? For example client specified acr_values=["duo", "super-gluu"]. As result oxAuth should give user choose which method to use.
This approach will be good for simple RP without investment into special login page in client application.

2) If someone not likes oxAuth auth method selector we can offer new simple oxAuth endpoint (https://ce-dev.gluu.org/.well-known/acr-configuration) with list of methods to simplify building this dialog on RP side.
Example result:
[{ acr:"duo",
  icon:"oxauth_url_to_acr_method_icon",
  additional_property1: "",
  additional_property2: ""
},
{ acr:"super-gluu",
  icon:"oxauth_url_to_acr_method_icon",
  additional_property1: "",
  additional_property2: ""
}]

With this JSON, RP can easily build own auth method chooser page.

**Comment by yuriyz** [comment]
To keep what we've discussed in skype and mails:

Main concern is mostly about user experience. When user click on selector icon it is not clear what are next steps. Nice idea that comes from @willow9886 is to add additional component on web page which would show current step and also all further steps.

**Comment by yuriyz** [comment]
As on image below, user on login page will see that next step is duo (or other possible many steps).
https://dailypost.files.wordpress.com/2013/06/2step.jpg

For this we would need to add additional method to custom authentication scripts to be able fetch description of step.

**Comment by nynymike** [comment]
I think we should back-burner this issue. There is a WG at OIDF that will address some of these issues I think:  http://openid.net/wg/eap/

**Comment by nynymike** [comment]
Jose, can you comment on this feature request? If this would not be helpful for Casa or application developers in general, then we should close the feature.

**Comment by jgomer2001** [comment]
I think most of responsability should lie on the OP. Any enhancements to user experience should be handled by oxauth, which in the future should offer means to define policies for authentication as described in https://github.com/GluuFederation/casa/issues/10 and https://github.com/GluuFederation/oxAuth/issues/1206

In the end, the SSO concept has a lot to do with centralization. The likelihood of developers trying to implement custom flows from their side is low. They actually will be more interested in reusing already defined flows.
