### ISSUE TITLE
  Update setup project template files to support authentication session

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#21]
Update https://github.com/GluuFederation/community-edition-setup template files in order to include authentication session changes.

I think authentication session lifetime should be bigger than 1 minute and less that 3 minutes.
What about 90 seconds - 2 minutes? I think it's enough for one authentication step. This time also allow to make few authentication attempts... or recieve DUO push notification..

**Comment by nynymike** [comment]
IMHO 120 seconds is ok

**Comment by yuriyz** [comment]
Lets put 120. unauthenticated session time is time from step 1 to last step (until session become authenticated)

**Comment by yuriyz** [comment]
Time increased 60->120 seconds with commit https://github.com/GluuFederation/community-edition-setup/commit/6615227d97bfff0b4e1c1ddefba793302b896bc6
