### ISSUE TITLE
oxauth login page is half rendered if client is not present in ldap (removed)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#210]
SEVERE: JSF1054: (Phase ID: RENDER_RESPONSE 6, View ID: /login.xhtml) Exception thrown during phase execution: javax.faces.event.PhaseEvent[source=com.sun.faces.lifecycle.LifecycleImpl@4133ff2e]
 SEVERE: Error Rendering View[/login.xhtml]
javax.faces.FacesException: javax.el.ELException: //localhost/oxauth/login.xhtml @62,89 rendered="#{!empty client.getLogoUri()}": //localhost/oxauth/login.xhtml @60,129 value="#{clientService.getClient(sessionAttributes['client_id'])}": org.gluu.site.ldap.persistence.exception.EntryPersistenceException: Failed to find entry: inum=@!40EA.D454.9D4F.E876!0001!ECE8.BBEF!0008!5A56.8C22,ou=clients,o=@!40EA.D454.9D4F.E876!0001!ECE8.BBEF,o=gluu

**Comment by yuriyz** [comment]
![ce-dev2](https://cloud.githubusercontent.com/assets/2013070/14883861/9024b35e-0d49-11e6-89ce-555b745fb2d3.png)

**Comment by yurem** [comment]
Fixed. Now oxAuth redirect to redirect_uri with error in URI: ?error=access_denied&error_description=The+resource
+owner+or+authorization+server+denied+the+request.
