### ISSUE TITLE
Process prompt=consent authorization request

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#212]
I've tried to fix oxAuth tests and find 2 problems in AuthorizeAction. Now there are 4 errors related to prompt=consent. They are similar: https://ox.gluu.org/jenkins/job/oxAuth/500/

Old code which not allow to process this param properly is:

    if (if (clientAuthorizations != null && clientAuthorizations.getScopes() != null &&...) {
        ....
    } else if (ConfigurationFactory.instance().getConfiguration().getTrustedClientEnabled()) {
        ...
    } else {
        consentRequired();
    }

As result we never execute else because in CE TrustedClientEnabled = True

In current code I fixed this bug.

But for next authorization request:

    https://ce-dev2.gluu.org/oxauth-rp/home.seam?error=consent_required&error_description=The+Authorization+Server+requires+End-User+consent.+This+error+MAY+be+returned+when+the+prompt+parameter+in+the+Authorization+Request+is+set+to+none+to+request+that+the+Authorization+Server+should+not+display+any+user+interfaces+to+the+End-User%2C+but+the+Authorization+Request+cannot+be+completed+without+displaying+a+user+interface+for+End-User+consent.&state=7eacfcc8-919e-4ecb-a375-f4414d2a6f7d

We get:

    https://ce-dev2.gluu.org/oxauth-rp/home.seam?error=consent_required&error_description=The+Authorization+Server+requires+End-User+consent.+This+error+MAY+be+returned+when+the+prompt+parameter+in+the+Authorization+Request+is+set+to+none+to+request+that+the+Authorization+Server+should+not+display+any+user+interfaces+to+the+End-User%2C+but+the+Authorization+Request+cannot+be+completed+without+displaying+a+user+interface+for+End-User+consent.&state=7eacfcc8-919e-4ecb-a375-f4414d2a6f7d

**Comment by yurem** [comment]
Are there bugs in these tests? Can you explain how oxAuth should work if there is authorization parameter  prompt=consent ?

**Comment by nynymike** [comment]
http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest 

"The Authorization Server SHOULD prompt the End-User for consent before returning 
information to the Client. If it cannot obtain consent, it MUST return an error, typically 
consent_required."

I see this like prompt=login... which forces re-authentication. If this is explicity requested by the client, I think the scope authorization consent dialog should be displayed, even if pre-authorization=true.

**Comment by yurem** [comment]
I committed fix:
https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeAction.java#L257

Lines: 257-278

Now if there is prompt=consent tit always shows Authorization dialog

All tests are fine now

@javier, please review these lines. It's not clear when we can use this method in AuthorizeAction: https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeAction.java#L691
