### ISSUE TITLE
Keeps getting "HTTP 403 (Forbidden)" in oxTrust log even if UMA authentication seems to have succeeded?

### ISSUE THREAD

**Issue by uboznikov** [GluuFederation/oxAuth#213]
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/service/UmaProtectionService.java#L202

`Construct response: HTTP 403 (Forbidden), entity: '{"ticket":"037f9751-19c6-40ba-9697-d239dfdb1fee"}'`

**Comment by yuriyz** [comment]
Please check oxTrust code. 
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/service/UmaAuthenticationService.java#L78

There is wrong RPT permission validation. I've posted separate issue for it : https://github.com/GluuFederation/oxTrust/issues/250

oxTrust must check whether RPT has permissions for given resourceId with exact scope. If permission is absent then ticket is registered and returned to RP. RP must authorize RPT with that ticket, so RPT will get correct permissions.

**Comment by yuriyz** [comment]
check also our UMA docs to better understand UMA protocol https://gluu.org/docs/integrate/uma/
