### ISSUE TITLE
entityID of SP didn't process after specific RP configuration

### ISSUE THREAD

**Issue by piphonom** [GluuFederation/oxAuth#214]
When I configure Trust Relationships for Salesforce SAML SSO this configuration doesn't apply totaly into _/opt/idp/conf/relying-party.xml_. For Relying Party configuration instead of _id="entityID of SP"_ I see _id="$trustRelationship.entityId"_. I have reinstalled Gluu server twice but result is the same.

I use Gluu 2.4.3 1-3 amd64. OS is Ubuntu 14.04.4 LTS (GNU/Linux 2.6.32-042stab113.11 x86_64).

Some addtional discussion, SP metadata and logs can be found [there](https://support.gluu.org/integrations/saml-sso-with-salesforce-2724)

**Comment by aliaksander-samuseu** [comment]
Hi, @piphonom. I remember your ticket. Thank you for spending your time creating the report. I want to add that I've just encounter this very issue yesterday on one of client's instance of version 2.3.x. I also used a metadata file method when creating TR. I spent a lot of time trying to resolve it, but even removing this TR and recreating it gave the same result. I tried to deactivate/activate it also, add and remove attributes. Then it's just resolved by itself after one of the update of this TR.

While I was trying to resolve it, I saw that often this TR was put into "Inactive"  state and there was a warning about preemptive end of metadata file, though metadata was 100% correct and the same file was used at another instance without issues. Now when this TR is working (with the same md) there is no such warnings in web UI, TR is in active state.

I tried to reproduce it in test 2.4.3 instance I have installed, with the same metadata file, but failed.
@piphonom , were you using some custom attributes for this affected TR, btw?

**Comment by aliaksander-samuseu** [comment]
@piphonom , it seems it's a tricky one. Could you please write down all your configuration steps which lead to a guaranteed reproduction of this issue and post here?

**Comment by piphonom** [comment]
Hi, Aliksander!

> were you using some custom attributes for this affected TR, btw?

No, I didn't use some custom attributes. Just attributes form [instruction](https://www.gluu.org/docs/integrate/salesforce-sso/)

> Could you please write down all your configuration steps 

I'm not sure that it will help you to reproduce this issue because I didn't do any special things. But there are steps that I did:

1. removed previous version of Gluu (2.4.2) (_apt-get remove ..._, then remove **/opt/gluu-server-2.4.2***)
2. apt-get install gluu-server-2.4.3
3. /etc/init.d/gluu-server-2.4.3 start
4. chroot into Gluu envirenment by _/etc/init.d/gluu-server-2.4.3 login_
5. configure Gluu and setup components. All except CAS and Asimba
6. Create few users in OpenDJ for tests
7. Configure TR for TestShib2 step by step as decribed [there](https://www.gluu.org/docs/integrate/test-shib2/)
8. Testing TestShib2
9. Configure Salesforce step by step from [there](https://www.gluu.org/docs/integrate/salesforce-sso/)

At first time I used cert Custom Script for authentication. But in the second time after Gluu reinstallation I used default auth metod.

I tried to remove TestShib2 TR but the same result.

**Comment by piphonom** [comment]
Aliaksander,

if you want I can give you ssh access to my server. This is jsut test VM and there is nothing secret. If it is needed ping me by email. I will send you credentials.

**Comment by aliaksander-samuseu** [comment]
@piphonom 

Thank you, but not sure it will help in any way. From my experience with it, there are little clues when this already has happened, and little can be done. Just one request: could you run this command from within the container and provide us output: `/opt/opendj/bin/ldapsearch -h localhost -p 4444 -Z -X -T -D 'cn=directory manager' -w 'YOUR_LDAP_PASSWORD' -b 'ou=appliances,o=gluu' '(objectclass=gluuSAMLconfig)' gluuEntityId displayName` ? You'll need to use your ldap password (it's the same as the password of default admin user right after running setup.py)

**Comment by piphonom** [comment]
Aliaksander, 

this is output for your request

`dn: inum=@!5302.FE40.EA53.038F!0002!F1A2.32D7!0006!EA45.98E4,ou=trustRelationships,inum=@!5302.FE40.EA53.038F!0002!F1A2.32D7,ou=appliances,o=gluu
gluuEntityId: 5302FE40EA53038F0002F1A232D70006EA4598E4
displayName: gluu SP on appliance

dn: inum=@!5302.FE40.EA53.038F!0002!F1A2.32D7!0006!3B37.FDDE,ou=trustRelationships,inum=@!5302.FE40.EA53.038F!0002!F1A2.32D7,ou=appliances,o=gluu
displayName: Salesforce

dn: inum=@!5302.FE40.EA53.038F!0002!F1A2.32D7!0006!4689.54CD,ou=trustRelationships,inum=@!5302.FE40.EA53.038F!0002!F1A2.32D7,ou=appliances,o=gluu
gluuEntityId: https://idp.testshib.org/idp/shibboleth
gluuEntityId: https://sp.testshib.org/shibboleth-sp
displayName: TestShib2 testing`

**Comment by nynymike** [comment]
Alex, can this issue be reproduced? I'm gathering from this thread that maybe it cannot...

**Comment by piphonom** [comment]
Mike,

I'm not sure because I don't know exactly steps how to reproduce it. But on my Gluu Server it was reproduced two times from two. First time I installed Gluu and configured Salesforce. And it was reproduced. Then I reinstalled Gluu and this issue reproduced again. Now any time I change one of RP I see  in _/opt/idp/conf/relying-party.xml_ that entityID for Salesforce has value _"$trustRelationship.entityId"_ instead of SP entityID.

**Comment by nynymike** [comment]
Yes, I asked Alex to try to reproduce. If cannot, I'm sending this back to https://support.gluu.org because it seems like it may be something with your deployment.

**Comment by aliaksander-samuseu** [comment]
@nynymike 

Mike, I've tried twice already, both with @piphonom 's metadata, and metadata of that SP I tried to configure, and couldn't.

**Comment by nynymike** [comment]
We can't reproduce this issue. It must be something with his deployment.
