### ISSUE TITLE
Client side method to load private key from JWKS

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#217]
In the latest code there is no method to load privateKey from JWKS. It's fine for oxAuth because it will store keys in oxEleven. But this raise few questions:

1. Is oxEleven open source or not?
2. Is oxAuth allows to work in 2 modes: oxEleven and JWKS (LDAP) store?
3. During setup we generate jwks for 2 UMA clients. And in order to obtain access_token client should know how to load private key from this file store, for example SCIM-Client. Are we planning to implement any replacement for this?

In order to repair current compilation issues in SCIM-Client, oxTrust, oxUmaDemo I added JwksUtil with method to load [private key](https://github.com/GluuFederation/oxAuth/commit/9310be7283ff5c8221c5df74cfa4357cbc7f214c) from jwks.

**Comment by yurem** [comment]
@nynymike can you check this?

**Comment by nynymike** [comment]
Yes, we should support both modes: oxEleven and JWKS (LDAP) store

**Comment by qbert2k** [comment]
1. oxElevan has The MIT License (MIT)

2. Yes, you can change the mode in oxAuth configuration:
```
dn: ou=oxauth,ou=configuration,inum=appliance_inum,ou=appliances,o=gluu
```

```
oxAuthConfDynamic: {
...
"webKeysStorage":"ldap",
or
"webKeysStorage":"pkcs11"
...
}
```

3. You cannot get the private key, instead you can call the sign function as follows:

```
CryptoProviderFactory.getCryptoProvider()
```

will return an instance of OxAuthCryptoProvider or OxElevenCryptoProvider depending on the configuration.

Then call the functions:

```
cryptoProvider.generateKey()
cryptoProvider.sign()
cryptoProvider.verifySignature()
cryptoProvider.deleteKey()
```

**Comment by yurem** [comment]
@qbert2k , thank you for clarifications
I've few new questions and ideas related to client applications:

1. In SCIM Client we uses CLIENT_CREDENTIALS grant with PRIVATE_KEY_JWT authentication method. This client code should know about key type, algorithm, etc
Can we simplify [this](https://github.com/GluuFederation/SCIM-Client/blob/master/src/main/java/gluu/scim2/client/auth/UmaScim2ClientImpl.java#L136)? For example we can add method to set key from JSON.

2. For demo purposes we generate jwks for client. But we only need one key. What do you think about adding new key generator which accept parameters like kty, alg, etcc and generate one key to use in point 1.

3. According to ce-dev2 configuration: "webKeysStorage":"ldap" . But SCIM-Client tests fails since 12 May: https://ox.gluu.org/jenkins/job/oxScimClient/
Can you check why it can't  obtain token?

**Comment by yurem** [comment]
It's related to point 3: https://github.com/GluuFederation/oxAuth/issues/224

**Comment by yurem** [comment]
Fixed
