### ISSUE TITLE
API's for U2F device management

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#226]
Currently, U2F devices are stored as a subentry under the person entry, in the `u2f_devices` organizational unit. See this diagram:

![image](https://cloud.githubusercontent.com/assets/3717101/15478056/aa65733c-20dd-11e6-8d0d-f19318b04d19.png)

The problem is these entries can't be managed via the SCIM API (or can they?)

We are building a cred management app, and we'd prefer the app not use LDAP to manage this data.

**Comment by yurem** [comment]
This is sample data:
[u2f_user_and_devices.zip](https://github.com/GluuFederation/oxAuth/files/418256/u2f_user_and_devices.zip)

**Comment by uboznikov** [comment]
Initial design:

This will be a new resource type in SCIM 2.0 named `FidoDevice`. Defining new resource types is [permitted](https://tools.ietf.org/html/rfc7643#section-3.2). The endpoint will be `<domain root>/identity/seam/resource/restv1/scim/v2/FidoDevices`.

`GET` all devices of all users:
![scim-fido-alldevices](https://cloud.githubusercontent.com/assets/16329085/17726103/310d6f96-6483-11e6-9675-288832db8de9.png)

`GET` all devices of a user: a new query string parameter `userId` is added to the API which is also [permitted](https://tools.ietf.org/html/rfc7644#section-3.4.2).
![scim-fido-userdevices](https://cloud.githubusercontent.com/assets/16329085/17726474/d3dbcb3a-6485-11e6-8a06-a27cf43a71f0.png)

`GET` device by id:
![scim-fido-devicebyid](https://cloud.githubusercontent.com/assets/16329085/17726500/0552b930-6486-11e6-841b-22c6834f8b40.png)

Test data:
![scim-fido-test-data](https://cloud.githubusercontent.com/assets/16329085/17726581/92b3c026-6486-11e6-8c82-c988a0200d23.png)

**Comment by uboznikov** [comment]
Committed core endpoint to oxTrust: [Added SCIM 2.0 FidoDevices](https://github.com/GluuFederation/oxTrust/commit/229411475d5d5e10819d7aa359cfdfe7de3c124b) (sorry wrong issue id in commit).

Remaining: add to Bulk and Schemas enpoints.

**Comment by yurem** [comment]
Hi Val,

 

New API looks fine. Even there are count limit in methods to get lists.

 

We only need methods to add/modify user devices.

 

It’s not related to this issue… User management application should knows how to do enrollment of new U2F user device. Probably this application should also support limited versions of custom script to avoid hardcoding this functionality in application.

 

Regards,

Yuriy

**Comment by uboznikov** [comment]
@yurem Thanks for the comment, creation on this resource has not been implemented; creation will be via the FIDO API (e.g., Super Gluu, etc.).

**Comment by nynymike** [comment]
Delete is really needed.

Also edit for  description and displayname is needed.

**Comment by uboznikov** [comment]
[Added FidoDevice to /Schemas endpoint](https://github.com/GluuFederation/oxTrust/commit/b6bb3a11a900847d68a8aaa29e1e2e356554d40d)

**Comment by nynymike** [comment]
Should this be closed?
