### ISSUE TITLE
Add more fields to U2F device regitration entry

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#228]
We should add "nickname" and "description." This would really help if a person has more then one U2F device. DeviceID is not visible to the person.

**Comment by jgomer2001** [comment]
@yurem @nynymike @willow9886 Currently [cred-manager](https://github.com/GluuFederation/cred-manager/wiki/Cred-Manager-Project-Doc) uses displayName for *nickname*
I consider we should not use a *description* attribute but only *nickname*.
I also think this can be left for an upcoming release, not 3.1.0

**Comment by worm333** [comment]
Added nickname field to U2F device entry in: [this](https://github.com/GluuFederation/community-edition-setup/pull/323), [this](https://github.com/GluuFederation/oxTrust/pull/673), and [this](https://github.com/GluuFederation/oxAuth/pull/622) pull requests.
