### ISSUE TITLE
Resource Owner Password Credential Grant Interception Script

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#230]
This interception script would provide a way to customize back channel authentication.

**Comment by nynymike** [comment]
This would be convenient.

**Comment by nynymike** [comment]
I'm moving this to 3.2. It could be convenient, but exposing the secret to the client is a bad thing, in general.

**Comment by yurem** [comment]
It's 2 years old issue. And I'm not sure that it's actual since we not implemented it already.

This grant type is not very popular.In this flow RP asks user for password and send it directly to RS
As far as I remember it uses endpoint without browser to get token.
The only one place which we can cover with scripts here is user and client password validation. oxAuth can call script with `service` type to validate user/password and client/password

**Comment by nynymike** [comment]
OpenID Connect CIBA from the MODRNA group also addresses back channel authentication, which would be preferred.

**Comment by yuriyz** [comment]
Implemented in 3.1.5 and merged into master (4.0).
