### ISSUE TITLE
Add version no in welcome message on home page.

### ISSUE THREAD

**Issue by shekhar16** [GluuFederation/oxAuth#231]

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/15631699/dfd0e85c-2593-11e6-9948-0111fd07aab9.png)

**Comment by shekhar16** [comment]
Fixed and code is committed.

**Comment by shekhar16** [comment]
![image](https://cloud.githubusercontent.com/assets/15937500/15631707/388c6368-2594-11e6-9cdb-c02164b65675.png)

**Comment by willow9886** [comment]
@yurem can you pull this update into our existing version?

**Comment by yurem** [comment]
Fixed
