### ISSUE TITLE
New iFrame implicit flow

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#233]
http://lists.openid.net/pipermail/openid-specs-ab/Week-of-Mon-20151116/005865.html

 In this document, we define a new architecture and flow for
   JavaScript clients on how to get access tokens and/or ID tokens from
   Identity providers (IDP).  Instead of getting these tokens from the
   IDP Authorization Endpoint (as defined in RFC 6749 [RFC6749] as the
   token flow), JavaScript clients now get these tokens from an IFrame
   provided by the IDP.  This change brings huge performance and
   security benefits.

**Comment by qbert2k** [comment]
https://tools.ietf.org/html/draft-ietf-oauth-v2-23#section-10.13

**Comment by nynymike** [comment]
Perhaps should be moved to 3.2...
