### ISSUE TITLE
Add ability to return custom header with authorization response

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#234]
We need to allow custom script to store list of headers in LDAP session to return them as header with authorization response.

**Comment by qbert2k** [comment]
Yuriy Movchan wrote:

It's old issue...
I planned to store these headers in special variable in LDAP session
https://github.com/GluuFederation/oxAuth/blob/master/Server/integrations/otp/OtpExternalAuthenticator.py#L112
session_attributes = context.get("sessionAttributes")
auth_response_headers = session_attributes.get("auth_response_headers")
auth_response_headers.set("XYZ", "zzz")
...
so, script controls this variable value
But I think there is better solution
We can add new method to this base authentication script type:
https://github.com/GluuFederation/oxCore/blob/master/oxService/src/main/java/org/xdi/model/custom/script/type/auth/PersonAuthenticationType.java
for example:
public Map<String, String> getAuthorizationHeaders();
Call it from Authorization action to get list of additional headers
example:
https://github.com/GluuFederation/oxAuth/blob/07a694d57b9392c7598f0fb690b915218eb150be/Server/src/main/java/org/xdi/oxauth/model/token/IdTokenFactory.java#L263
we also call this method from AuthorizationAction
if (apiVersion > 3) {
                Map<String, String> authorizationHeaders= externalAuthenticator.getAuthorizationHeaders();
                if (authorizationHeaders!= null) {
....
The purpouse of this idea is for integration with anther systems which expects specif headers on redirect.
