### ISSUE TITLE
Implement client JWKS key generator

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#235]
We need to implement client key generator which prepare 2 files:
1) JWKS with public keys to stoe in LDAP
2) JKS with private keys to use then in client code
3) Utility class to simplify key loading from JKS

**Comment by qbert2k** [comment]
The client generator is at:
https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/util/KeyGenerator.java

usage: KeyGenerator -algorithms RS256 RS384 RS512 ES256 ES384 ES512
                    -keystore /path_to/mykeystore.jks -keypasswd secret
                    -dnname "CN=oxAuth CA Certificate" -expiration 365
                    -algorithms <arg>   Algorithms.
                    -dnname <arg>       DN of certificate issuer.
                    -expiration <arg>   Expiration in days.
                    -h,--help           show help.
                    -keypasswd <arg>    Key Store password.
                    -keystore <arg>     Key Store file.

Example:

``
KeyGenerator -algorithms RS256 RS384 RS512 ES256 ES384 ES512 -keystore /Users/JAVIER/tmp/mykeystore.jks -keypasswd secret -dnname "CN=oxAuth CA Certificates" -expiration 365
``

If the JKS file does not exists, it will create it automatically. The JWKS is printed in the standard output.
