### ISSUE TITLE
Return Authentication Level in amr response claim

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#238]

**Comment by nynymike** [comment]
We need the "Authenticaiton Level" to be returned in the amr id_token claim. As its a JSON array of strings, it shoudl return something like ["1"].

**Comment by yuriyz** [comment]
https://github.com/GluuFederation/oxAuth/issues/227

**Comment by yuriyz** [comment]
AMR is encoded into ID Token as array based on ACR value which is read from custom authentication script.

Right now we are always using one particular acr, so amr would look as ["3"] (or any other level set in script).
