### ISSUE TITLE
Update authentication interception script to enable setting additional AMRs

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#244]
It would be nice if the the interception script allowed the return of additional amr claims. For example, maybe the script runs fraud detection, and wants to return a score to the client. It would be nice if there was a method in the authentication interception script, something like:

amrs = context.getCurrentAmrs()
amrs.append("fraud-score:500")
context.set(amrs)

The first amr should always be "level"...

**Comment by yurem** [comment]
Yes, it's simple approach is very good one to provides additional information:

In custom scripts we implemeneted functionality to allow extend scripts without breaking old scripts.

Please use next pattern to call this new method:

```
            int apiVersion = externalAuthenticationService.executeExternalGetApiVersion(customScriptConfiguration);
            if (apiVersion > 2) {
            	log.trace("According to API version script supports super puper method");
            	overridenNextStep = externalAuthenticationService.callThisNewMethod()
            	log.debug("Get next result... ");
            }
```

Current apiLevel for perosn authentication scripts is 2. You can use 3 to call your new method.

**Comment by yurem** [comment]
Change new custom script method to getAuthenticationMethodClaims and call it only if API > 3:
https://github.com/GluuFederation/oxAuth/commit/07a694d57b9392c7598f0fb690b915218eb150be
