### ISSUE TITLE
SuperGluu Interception Script Incorrectly Processess Registration

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#247]
There is a problem with the service that processes the QR code request from the phone. 

Here is the scenario we tested in a two step authentication

1) User mike: enroll phone 1.... logout
2) Login user mike 2nd time
3) Push notification goes to mike, but Will uses his phone to scan QR code.
4) Will's phone gets "Authentication Success" and the authentication proceeds.

The problem is this: post enrollment of a device, only the registered phone should be accepted. The phone should have been informed "Key does not match--authentication failed" And the oxAuth session should be terminated.

I think this should be a quick fix.

**Comment by yurem** [comment]
Now registration API not allow to start enrollment process if user has at least one device registered.
It's for case when application pass user_name and session-state only.
