### ISSUE TITLE
Remove Federation API endpoints

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#256]
The federation endpoint will not be used, let's remove it, the tests, and the [docs](https://github.com/GluuFederation/docs/issues/105)

**Comment by yuriyz** [comment]
removed in master branch

**Comment by yurem** [comment]
We also need to remove federation settings from JSON schema file:
https://github.com/GluuFederation/oxTrust/blob/master/static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

**Comment by yuriyz** [comment]
@yurem indeed, cleaned up oxTrust https://github.com/GluuFederation/oxTrust/commit/5b734244e1c5d88c209110ef9b885b8dc9e3a0b6
