### ISSUE TITLE
does not validate Custom Attribute Data Type

### ISSUE THREAD

**Issue by aveekbu** [GluuFederation/oxAuth#261]
To see the problem login into gluu and go to:

```
Configuration-Attributes -> Add Attribute

Define any attribute you like and set data type to anything (numeric,date, photo) but string/text.

Now go to Users -> Manage people and find any person that you have in gluu instance.

Edit that person and add custom attribute that we just have created. As a value set any value that violates type rules (for example type "stringinNuberic" as it is either date, number or photo).
```

![screenshot from 2016-07-23 08-55-07](https://cloud.githubusercontent.com/assets/641167/17075400/11916e34-50b4-11e6-881f-b98d95e7ff72.png)
![screenshot from 2016-07-23 08-55-56](https://cloud.githubusercontent.com/assets/641167/17075401/11985e4c-50b4-11e6-8077-684fa4ab2374.png)
![screenshot from 2016-07-23 08-56-20](https://cloud.githubusercontent.com/assets/641167/17075402/1199979e-50b4-11e6-9a96-5e37196d1f2d.png)

**Comment by aveekbu** [comment]
@shekhar16 can you take a look at this issue?

**Comment by nynymike** [comment]
This is an oxTrust issue, not oxAuth.
