### ISSUE TITLE
Move non-standard discovery parameters to .well-known/gluu-configuration

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#266]
We should move our non-standard OpenID Connect discovery metadata into
.well-known/gluu-configuration

Its hard for someone not familiar with the spec to realize they may be using a non-standard feature that may lead to Gluu Server lock-in.

A quick check, I see the following non-standard keys:
- id_generation_endpoint
- introspection_endpoint
- auth_level_mapping
- scope_to_claims_mapping

Perhaps we should leave the old values there, but deprecate them. It could be that client code may be referencing id_generation_endpoint and introspection_endpoint.

**Comment by worm333** [comment]
I created pull request (https://github.com/GluuFederation/oxAuth/pull/275) related with this issue. These params:
"clientinfo_endpoint",
"check_session_iframe",
"end_session_endpoint",
"validate_token_endpoint",
"federation_metadata_endpoint",
"federation_endpoint",
"id_generation_endpoint",
"introspection_endpoint",
"auth_level_mapping",
"scope_to_claims_mapping",
"http_logout_supported",
"logout_session_supported"

now available from /oxauth/seam/resource/restv1/oxauth/gluu-configuration. We'll also need to update apache config to redirect request to /.well-known/gluu-configuration

**Comment by yurem** [comment]
I think these are standart endpoints:
"clientinfo_endpoint",
"check_session_iframe",
"end_session_endpoint",
"validate_token_endpoint",

**Comment by worm333** [comment]
I used this link https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata as a guide for standard parameters. Do you think we should leave these params in /.well-known/openid-configuration ?

**Comment by nynymike** [comment]
Anything in the spec should stay!

**Comment by worm333** [comment]
I have not found any references in the specification for params: clientinfo_endpoint and validate_token_endpoint. Params: check_session_iframe and end_session_endpoint are mentioned in the specs but not presented in section https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata.

**Comment by yuriyz** [comment]
@nynymike @yurem @worm333 Specification directly says that response can contain "additional parameters" including those mentioned by other specs. 
`Additional OpenID Provider Metadata parameters MAY also be used. Some are defined by other specifications, such as OpenID Connect Session Management 1.0 [OpenID.Session]. `

Of course all session and logout stuff is "standard". New endpoint creation is not enough (pull request is far away from finish line), for me this issue means:
1) new endpoint creation
2) new client for new endpoint
3) update of "standard"/existing client
4) update of exiting tests  (client and server side)
5) creation of new test for new endpoint (client and server side)
6) this will lead to also oxd update.

Keeping in mind all this extra work does it really worth it if it's allowed by discovery specification to keep "additional parameters"?

**Comment by nynymike** [comment]
Can we quantify the impact? I'm troubled by the gluu proprietary parameters... and the longer we go, the greater the impact of the change will be in the future.

**Comment by yuriyz** [comment]
It's very nice idea. It will help to avoid points 2, 3, 6 which is basically in two times less work and will not effect existing client/RP code.

**Comment by worm333** [comment]
Here is the  related [pull request](https://github.com/GluuFederation/oxAuth/pull/279)
