### ISSUE TITLE
Update OP discovery JSON to latest claim for front channel logout

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#271]
Parameters are renames:
`logout_uri` -> `frontchannel_logout_uri`

http://openid.net/specs/openid-connect-frontchannel-1_0.html#History

Also, see client metadata `frontchannel_logout_session_required` and OP discovery info
`frontchannel_logout_supported`  and `frontchannel_logout_session_supported`

Also, oxAuthRP should be updated for new client registration metadata.

**Comment by nynymike** [comment]
Should this be closed?

**Comment by yuriyz** [comment]
I guess, no unless we don't want to stick to spec. Parameters are not renamed. https://github.com/GluuFederation/oxAuth/blob/master/Model/src/main/java/org/xdi/oxauth/model/configuration/ConfigurationResponseClaim.java#L59-59

**Comment by yuriyz** [comment]
Fixed in master branch for 3.0.0
