### ISSUE TITLE
Mitigate potential Clickjacking attack

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#272]
The remote web server does not set an X-Frame-Options response header
or a Content-Security-Policy 'frame-ancestors' response header in all
content responses. This could potentially expose the site to a
clickjacking or UI redress attack, in which an attacker can trick a
user into clicking an area of the vulnerable page that is different
than what the user perceives the page to be. This can result in a user
performing fraudulent or malicious transactions.

For more info see:

http://www.tenable.com/plugins/index.php?view=single&id=85582

**Comment by nynymike** [comment]
I wonder if this should be done in Apache HTTPD ...

**Comment by nynymike** [comment]
@ganesh-at-wiw Can you see if this can be done in apache httpd config?

**Comment by ganesh-at-wiw** [comment]
The article: https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet makes me believe that it's more of programming work than server stuff. I'm searching for more references if something from the server can control it.

**Comment by ganesh-at-wiw** [comment]
https://en.wikipedia.org/wiki/Clickjacking  tells me that perhaps I can.

**Comment by ganesh-at-wiw** [comment]
Okay added the below code suggested in site: https://geekflare.com/secure-apache-from-clickjacking-with-x-frame-options/. 

**_Header always append X-Frame-Options SAMEORIGIN_**

in file /etc/httpd/conf.d/000.conf.

Verified from this site.
https://tools.geekflare.com/results

**Comment by ganesh-at-wiw** [comment]
ooops forgot to mention.
I did this for www.gluu.org.

Now, will do in community edition as well.

**Comment by nynymike** [comment]
Ok, please proceed with CE.

**Comment by ganesh-at-wiw** [comment]
Added to CE inside https_gluu.conf in github.
Also did it on idp.gluu.org and tested.
