### ISSUE TITLE
Create feature for access token logout

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#274]
A customer was relying on a bug to enable the access token to logout. Can we introduce that as a feature with a property file that controls it...

**Comment by yurem** [comment]
I've created oxAuth branch "2.4.4_logout": https://github.com/GluuFederation/oxAuth/commits/2.4.4_logout
And reverted fix for logout

**Comment by yurem** [comment]
This is result war: http://ox.gluu.org/maven/org/xdi/oxauth-server/2.4.4.logout/oxauth-server-2.4.4.logout.war

**Comment by yuriyz** [comment]
Thanks @yurem
