### ISSUE TITLE
SAML script enrollment - check for duplicacy

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#280]
ATM, SAML script enrolling all users who are trying to use saml_script. 
For this situation... user 'admin' or whoever is there in Gluu Server admin group is losing admin priviledge due to duplicate entries in LDAP ( one real entry, one enrollment entry ) [ adding entries below, here is how it looks like after enrollment for user 'admin' ] 
It would be good check some unique entry among users and perform enrollment block if required. 

Here is what my saml script looks like: 

![saml_script_screenshot](https://cloud.githubusercontent.com/assets/7156097/17670899/b9746cc8-62d9-11e6-873c-e431c7245ef7.png)

```
dn: inum=@!807B.F8CF.5BAA.F37C!0001!46BC.F294!0000!A8F2.DE1E.D7FB,ou=people,o=@!807B.F8CF.5BAA.F37C!0001!46BC.F294,o=gluu
objectClass: gluuPerson
objectClass: top
objectClass: ox-807BF8CF5BAAF37C000146BCF294
memberOf: inum=@!807B.F8CF.5BAA.F37C!0001!46BC.F294!0003!60B7,ou=groups,o=@!807B.F8CF.5BAA.F37C!0001!46BC.F294,o=gluu
givenName: Admin
uid: admin
gluuStatus: active
sn: User
oxLastLogonTime: 20160815152815.098Z
mail: support@gluu.org
displayName: Default Admin User
inum: @!807B.F8CF.5BAA.F37C!0001!46BC.F294!0000!A8F2.DE1E.D7FB

dn: inum=@!807B.F8CF.5BAA.F37C!0001!46BC.F294!0000!7443.F98D,ou=people,o=@!807B.F8CF.5BAA.F37C!0001!46BC.F294,o=gluu
objectClass: gluuPerson
objectClass: top
uid: admin
gluuStatus: active
oxExternalUid: saml:_c7c54b1f57fba7629149de2c044e992c!https://sp.gluu.org/shibboleth
mail: support@gluu.org
inum: @!807B.F8CF.5BAA.F37C!0001!46BC.F294!0000!7443.F98D
```

**Comment by yurem** [comment]
Fixed in https://github.com/GluuFederation/oxAuth/issues/284
