### ISSUE TITLE
Logout with 2 clients problem

### ISSUE THREAD

**Issue by dollar007** [GluuFederation/oxAuth#285]
I have 2 test sites.
I am logining to first via gplus login, and second via basic. 
When I am doing logout from gplus and logout from basic, from basic logout is doing, but from gplus it is showing error.

URL: https://ce-dev2.gluu.org/oxauth/seam/resource/restv1/oxauth/end_session?id_token_hint=eyJraWQiOiI0OWU5ZjVhYy03ZDNkLTRiY2EtYjQ3ZS1lM2U5MzU0ZjA0MjMiLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2NlLWRldjIuZ2x1dS5vcmciLCJhdWQiOiJAITQwRUEuRDQ1NC45RDRGLkU4NzYhMDAwMSFFQ0U4LkJCRUYhMDAwOCFDNzZDLkFGQkQiLCJleHAiOjE0NzE2MDU2MzcsImlhdCI6MTQ3MTYwMjAzNywiYWNyIjoiZ3BsdXMiLCJhbXIiOiJbXSIsIm5vbmNlIjoibi0wUzZfV3pBMk1qIiwiYXV0aF90aW1lIjoxNDcxNjAyMDMzLCJhdF9oYXNoIjoiLWJzbDd1UkFfLWpzUFBYeUM3TkJBdyIsIm94VmFsaWRhdGlvblVSSSI6Imh0dHBzOi8vY2UtZGV2Mi5nbHV1Lm9yZy9veGF1dGgvb3BpZnJhbWUiLCJveE9wZW5JRENvbm5lY3RWZXJzaW9uIjoib3BlbmlkY29ubmVjdC0xLjAiLCJhZGRyZXNzIjp7fSwiZW1haWwiOiJ2bGFkLmthcmFwZXR5YW4uMTk4OEBnbWFpbC5jb20iLCJpbnVtIjoiQCE0MEVBLkQ0NTQuOUQ0Ri5FODc2ITAwMDEhRUNFOC5CQkVGITAwMDAhOTFFNS5EQUIwIiwiZmFtaWx5X25hbWUiOiJLYXJhcGV0eWFuIiwiZ2l2ZW5fbmFtZSI6IlZsYWQgS2FyYXBldHlhbiIsInN1YiI6IkAhNDBFQS5ENDU0LjlENEYuRTg3NiEwMDAxIUVDRTguQkJFRiEwMDAwITkxRTUuREFCMCJ9.NRxH_yS75Ua5GRlKSTtY_jM_cdD68v8GW5rAj4yeeHrPNn7GTauRSO5q7y_RdADaN4TqcLIqg4EMLsq6Nw9I6MT-elkf67M4OeGZILSx6XJkMaapFXw--P-d_QDbgOU5Av40GN3Q0rBMsFTbndRYadGYYCnV00QCl88-OfDmu2G3tQBOabs_WrScEM9B2iLwqLxp-bZefufg42DvhVgAe8GEMNdpsRhjBz-RSdsMn1ymB8O3QKxza0OD-ZEHF0cdvh85B57_bqHc-331msDyLvMMafn5uJZ01ZlMFCkQD44J0rqFF9B9hGrw2ovAf6kffLi6UJXPQRW_CWuSCoIvZw&post_logout_redirect_uri=https%3A%2F%2Fsuite.crm%2Fgluu_logout.php%3Fgluu_login%3DGluussos&state=af0ifjsldkj&session_state=a6079277-6659-42c8-8c88-cfc07bef317c

HTTP Status 500 - org.jboss.resteasy.spi.UnhandledException: java.lang.NullPointerException

type Exception report

message org.jboss.resteasy.spi.UnhandledException: java.lang.NullPointerException

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: org.jboss.resteasy.spi.UnhandledException: java.lang.NullPointerException
	org.jboss.seam.servlet.ContextualHttpServletRequest.run(ContextualHttpServletRequest.java:96)
	org.jboss.seam.resteasy.ResteasyResourceAdapter.getResource(ResteasyResourceAdapter.java:120)
	org.jboss.seam.servlet.SeamResourceServlet.service(SeamResourceServlet.java:80)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:83)
	org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:63)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
	org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.web.MultipartFilter.doFilter(MultipartFilter.java:90)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158)

root cause

org.jboss.resteasy.spi.UnhandledException: java.lang.NullPointerException
	org.jboss.resteasy.core.SynchronousDispatcher.handleApplicationException(SynchronousDispatcher.java:365)
	org.jboss.resteasy.core.SynchronousDispatcher.handleException(SynchronousDispatcher.java:233)
	org.jboss.resteasy.core.SynchronousDispatcher.handleInvokerException(SynchronousDispatcher.java:209)
	org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:557)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:126)
	org.jboss.seam.resteasy.ResteasyResourceAdapter$1.process(ResteasyResourceAdapter.java:145)
	org.jboss.seam.servlet.ContextualHttpServletRequest.run(ContextualHttpServletRequest.java:65)
	org.jboss.seam.resteasy.ResteasyResourceAdapter.getResource(ResteasyResourceAdapter.java:120)
	org.jboss.seam.servlet.SeamResourceServlet.service(SeamResourceServlet.java:80)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:83)
	org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:63)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
	org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.web.MultipartFilter.doFilter(MultipartFilter.java:90)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158)

root cause

java.lang.NullPointerException
	org.xdi.oxauth.session.ws.rs.EndSessionRestWebServiceImpl.endSession(EndSessionRestWebServiceImpl.java:155)
	org.xdi.oxauth.session.ws.rs.EndSessionRestWebServiceImpl.requestEndSession(EndSessionRestWebServiceImpl.java:80)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.jboss.seam.util.Reflections.invoke(Reflections.java:22)
	org.jboss.seam.intercept.RootInvocationContext.proceed(RootInvocationContext.java:32)
	org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:56)
	org.jboss.seam.resteasy.ResteasyContextInjectionInterceptor.aroundInvoke(ResteasyContextInjectionInterceptor.java:59)
	org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	org.jboss.seam.transaction.RollbackInterceptor.aroundInvoke(RollbackInterceptor.java:28)
	org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	org.jboss.seam.core.BijectionInterceptor.aroundInvoke(BijectionInterceptor.java:79)
	org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	org.jboss.seam.core.MethodContextInterceptor.aroundInvoke(MethodContextInterceptor.java:44)
	org.jboss.seam.intercept.SeamInvocationContext.proceed(SeamInvocationContext.java:68)
	org.jboss.seam.intercept.RootInterceptor.invoke(RootInterceptor.java:107)
	org.jboss.seam.intercept.JavaBeanInterceptor.interceptInvocation(JavaBeanInterceptor.java:196)
	org.jboss.seam.intercept.JavaBeanInterceptor.invoke(JavaBeanInterceptor.java:114)
	org.xdi.oxauth.session.ws.rs.EndSessionRestWebServiceImpl_$$_javassist_seam_63.requestEndSession(EndSessionRestWebServiceImpl_$$_javassist_seam_63.java)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	org.jboss.resteasy.core.ResourceMethod.invokeOnTarget(ResourceMethod.java:269)
	org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:227)
	org.jboss.resteasy.core.ResourceMethod.invoke(ResourceMethod.java:216)
	org.jboss.resteasy.core.SynchronousDispatcher.getResponse(SynchronousDispatcher.java:542)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
	org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:126)
	org.jboss.seam.resteasy.ResteasyResourceAdapter$1.process(ResteasyResourceAdapter.java:145)
	org.jboss.seam.servlet.ContextualHttpServletRequest.run(ContextualHttpServletRequest.java:65)
	org.jboss.seam.resteasy.ResteasyResourceAdapter.getResource(ResteasyResourceAdapter.java:120)
	org.jboss.seam.servlet.SeamResourceServlet.service(SeamResourceServlet.java:80)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:83)
	org.jboss.seam.web.RewriteFilter.doFilter(RewriteFilter.java:63)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.web.LoggingFilter.doFilter(LoggingFilter.java:60)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:73)
	org.jboss.seam.web.IdentityFilter.doFilter(IdentityFilter.java:40)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.web.MultipartFilter.doFilter(MultipartFilter.java:90)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.web.ExceptionFilter.doFilter(ExceptionFilter.java:64)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.web.RedirectFilter.doFilter(RedirectFilter.java:45)
	org.jboss.seam.servlet.SeamFilter$FilterChainImpl.doFilter(SeamFilter.java:69)
	org.jboss.seam.servlet.SeamFilter.doFilter(SeamFilter.java:158)

note The full stack trace of the root cause is available in the Apache Tomcat/7.0.65 logs.

**Comment by nynymike** [comment]
I noticed the same behavior in slightly different circumstances. In my case, I logged out of a basic site, and then tried to navigate back to oxTrust (which had U2F enabled), it threw an error, and I was not able to either login or even logout (if I had a session)--I had to clear the cookies in my broswer for the OP.

**Comment by yuriyz** [comment]
@nynymike After first logout all tokens are revoked and second logout is unable to validate id_token provided to /end_token endpoint. I think we need to silently redirect to post_logout_redirect_uri.

**Comment by nynymike** [comment]
Maybe we also need to clear the existing cookies in this case.

**Comment by yuriyz** [comment]
@nynymike cookies are already cleared after first call (client A). So during client B call session is already killed and id_token is revoked (which is actually the reason of exception.) In normal flow both client A and B must implement front-channel logout which automatically logout client B (on client A logout). In @dollar007 case it seems to be wrong implementation. Anyway I think we need    to silently redirect to post_logout_uri if id_token is revoked and session_state is not present in cookie.

**Comment by yuriyz** [comment]
fixed in master and version_2.4.4_sp1 branches
