### ISSUE TITLE
[Feature Request] Please add RADIUS as GLUU custom authentication script

### ISSUE THREAD

**Issue by ObscurityThroughSecurity** [GluuFederation/oxAuth#296]
Hello!
RADIUS is a very common-used protocol to authenticate users in a corporate environment. However, GLUU currently doesn't support is natively or as a custom-interceptor-auth-script.

In our environment we have RADIUS server that authenticates users with 2FA bultin (LDAP creds at first, Google Authenticator at second). 

So would be very nice to see RADIUS as a custom interceptor script in GLUU. Is there any plans or ETA?

Thanks a lot.

**Comment by nynymike** [comment]
We've considered it several times. No ETA.

**Comment by willow9886** [comment]
A RADIUS server is now included in Gluu Server 4.0: https://gluu.org/docs/ce/4.0/admin-guide/radius-server/gluu-radius/
