### ISSUE TITLE
Calling end_session endpoint before session expiration fails to render login page

### ISSUE THREAD

**Issue by benShoe12** [GluuFederation/oxAuth#297]
Given:
- User logged in to a OpenId Connect RP (or more) with a registered logout url at the OP
- Calling OpenID Connect end_session logout url with the id_token_hint BEFORE session timeout

Expected Result:
1. Each registered logout urls will be called by loading an iframe for each url
2. User is shown the login page

Actual Result:
1. Each registered logout urls will be called by loading an iframe for each url
2. Instead of a login page, user is shown a very plain page with the message: "Logout requests sent"

Notes:
- Bug does not occur when the session has already expired by the time logout url is called 
- No error is shown in the logs

Here's the screenshot:
![image](https://cloud.githubusercontent.com/assets/21226890/18021480/7df02da6-6b9c-11e6-9145-0f3557f96f4e.png)
Here is the HTML that is rendering the page:
`<!DOCTYPE html><html><head><title>Gluu Generated logout page</title></head><body>Logout requests sent.<br/><iframe height="0" width="0" src="http://99.99.99.99/application1/logout_super"></iframe><iframe height="0" width="0" src="http://11.11.11.11/application2/logout"></iframe></body></html>`

**Comment by benShoe12** [comment]
I just want to note that this is occurring on 2.4.4

**Comment by yuriyz** [comment]
@benShoe12 @nynymike closed issue. it's not bug, please provide post_logout_uri according to spec  .

**Comment by yuriyz** [comment]
in future it would be nice if you provide full request and oxauth.log, so it will save time on investigation what was on not provided request.

**Comment by yuriyz** [comment]
- http://openid.net/specs/openid-connect-session-1_0.html
- http://openid.net/specs/openid-connect-frontchannel-1_0.html
