### ISSUE TITLE
Check session iframe page throws error due to dead source CryptoJS link

### ISSUE THREAD

**Issue by benShoe12** [GluuFederation/oxAuth#298]
In 2.4.4, the op iframe page tries to load the CryptoJS library via this link:
`<script type="text/javascript" src="//crypto-js.googlecode.com/svn/tags/3.0.2/build/rollups/sha256.js"></script>`

The problem is that the link is now dead. Thus, check session functionality of OpenID Connect is broken as it throws undefined exception when using CryptoJS methods.

**Comment by aliaksander-samuseu** [comment]
@qbert2k 

I see that backport for 2.4.4 was done at some moment, but I can't actually find `oxauth/js/crypto-js-3.1.2/` neither in a newely installed 2.4.4.2 instance, nor in instance patched to SP3. Are we sure that fix actually made it to 2.4.4?
