### ISSUE TITLE
UMA 2: Implement Claims Gathering Endpoint

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#300]
The claims gathering endpoint should support multi-step authorizations. 

For example:

``` python
def gather_claims(self, authorizationContext, configurationAttributes, step):
    if step == 1:
        # check condition, perhaps skip step 2
        # present authorization page
    if step == 2: 
       # do something else

def getSteps(self):
    return 2
```

Claims gathered can be stored in the PCT entry in LDAP.

Need to register a new client for the AS Client Claims Gathering endpoint.

TODO: Make sequence diagram!!!

**Comment by willow9886** [comment]
related to: https://github.com/GluuFederation/oxAuth/issues/357

**Comment by yuriyz** [comment]
Implemented in master branch.
Sample scripts are located here:

1. https://github.com/GluuFederation/oxAuth/blob/master/Server/uma/sample/UmaRptPolicy.py
2. https://github.com/GluuFederation/oxAuth/blob/master/Server/uma/sample/UmaClaimsGathering.py
