### ISSUE TITLE
Confirm what happens for invalid scope: 400 or redirect to client?

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#305]
The AS should respond to an invalid scope with a 400 rather than a redirect back to the client. This is listed as a mitigation for the open redirector vulnerability in OAuth2.

**Comment by yuriyz** [comment]
@nynymike for Authorization Code Flow RP sends redirect, it means that RP doesn't have any control on it. If we just show 400 then RP will not be able to handle it. The only way for RP to handle error is when OP sends back redirect with error. We have similar problem with 2 clients that hits OP with different acr and RP needs to decide whether to append prompt=login or not.

**Comment by nynymike** [comment]
ok... we can revisit this later if it's a problem.
