### ISSUE TITLE
Hash Token Values for Refresh Tokens

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#306]
We should create an oxAuth configuration option to store hashes of tokens rather then plain text tokens in ldap. No need for salt. In this way, if the LDAP server is hacked, the attacker would not have the tokens, just the hash values. Simlilar to the requirement not to store passwords. Also, you could search for the hash value just as easily as you could search for the access token value. The best hash algorithm to use is bcrypt, which is available as via an LDAP operation.

**Comment by worm333** [comment]
Created the [pull request](https://github.com/GluuFederation/oxAuth/pull/358) with the following changes: access and refresh tokens are hashed with sha256 algorithm( without salt ).

**Comment by nynymike** [comment]
Is this issue closed?

**Comment by worm333** [comment]
We need to review and merge [this](https://github.com/GluuFederation/oxAuth/pull/358) pull request, before closing it.
