### ISSUE TITLE
Create OAuth2 Audit Log

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#307]
We need to improve auditing: which client, accessing which resource, for which scope, which resource owner, timestampt, network--this should be included in a special audit log.

Audit logging should be a configurable feature in oxauth json.

**Comment by worm333** [comment]
Here is the [pull request](https://github.com/GluuFederation/oxAuth/pull/359). The OAuth2AuditLogger is using [activemq](http://activemq.apache.org/) as a message broker and only produce messages, so there is need to be sure that [activemq](http://activemq.apache.org/) is added as a new gluu component and we need to decide how the message consumer should be implemented.

The audit logger sends message when one of the following events occurred:
    

-     CLIENT_REGISTRATION
-     CLIENT_UPDATE
-     CLIENT_READ
-     CLIENT_DELETE
-     USER_AUTHORIZATION
-     USER_INFO
-     TOKEN_REQUEST
-     TOKEN_VALIDATE

A few examples of log messages:
`{
  "ip" : "10.0.2.2",
  "timestamp" : 1475212701787,
  "clientId" : "@!7A06.6C73.B7D4.3983!0001!CFEA.2908!0008!13E4.C749",
  "action" : "USER_AUTHORIZATION",
  "username" : "admin",
  "scope" : "openid profile email user_name",
  "success" : true
}`

`{
  "ip" : "10.0.2.2",
  "timestamp" : 1475212863852,
  "clientId" : "@!7A06.6C73.B7D4.3983!0001!CFEA.2908!0008!6BD8.355C.DED5.D7EE",
  "action" : "CLIENT_READ",
  "username" : null,
  "scope" : "openid",
  "success" : true
}`

**Comment by yurem** [comment]
I've merged this pull request:

We only need to add missing new properties to  JSON schema: https://github.com/GluuFederation/oxTrust/blob/master/static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

Also we need to review OAuth2AuditLogger  send JMS message message. It's bottle neck

**Comment by yurem** [comment]
I think we can use PooledConnectionFactory:


```
   connectionFactory = new ActiveMQConnectionFactory(
            userId, 
            passWord, 
            brokerURL);
    log.info("Queueing service init: BrokerURL: " + brokerURL + "  UserId: " + userId + "   Paasword: " + passWord);

    pooledConnectionFactory = new PooledConnectionFactory(connectionFactory);

    pooledConnectionFactory.setIdleTimeout(5000);
    pooledConnectionFactory.setMaxConnections(10);
    pooledConnectionFactory.setMaximumActive(5000);
    pooledConnectionFactory.start();
```

This will allow us to remove synchronized sections from code and use asynchronous method to send  messages.
