### ISSUE TITLE
Sending the incorrect time value to oxd "register_client".

### ISSUE THREAD

**Issue by MalinImna** [GluuFederation/oxAuth#31]
This is Oxd log of "register_client" :
2015-04-09 04:58:48,212 TRACE [org.xdi.oxd.server.Processor] Send back response:
 {"status":"ok","data":{"client_id":"@!1111!0008!223B.70C3","client_secret":"79a
db8ec-8d40-40ce-862b-d9bacf74a6e4","registration_access_token":"b7cba86d-e546-4c
00-9cb7-9b98ab7d0c2e","client_secret_expires_at":1428613131000,"registration_cli
ent_uri":"https://seed.gluu.org/oxauth/seam/resource/restv1/oxauth/register?clie
nt_id=@!1111!0008!223B.70C3","client_id_issued_at":1428526731000}}

The extra zero (+000) is added in "client_secret_expires_at" and "client_id_issued_at" fields.
The correct value should be 1428613131, 1428526731

**Comment by yuriyz** [comment]
it's issue on oxd side, not oxauth.
