### ISSUE TITLE
Conform Client Update to OAuth2 Dynamic Registration Mgt Protocol

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#312]
Conform client update API with [OAuth2 Dynamic Registration Management Protocol](https://tools.ietf.org/html/rfc7591), which introduces a registration access token and registration uri.

**Comment by worm333** [comment]
According with [OAuth 2.0 Dynamic Client Registration Management Protocol](https://tools.ietf.org/html/rfc7592) I’ve made the following changes:

- Added support for HTTP DELETE requests:
    * If dynamic registration is disabled, then method returns HTTP 403 Forbidden.
    * If the client does not exist or the registration access token used to make this request is not valid, then server responds with HTTP 401 Unauthorized.
    * If a client has been successfully removed, then server responds with an HTTP 204 No Content message.

 
- Adjusted returned status codes for GET and PUT operations:
    * Changed the return status code from HTTP 400 Bad Request to HTTP 403 Forbidden, when dynamic registration is disabled.
    * Changed the return status code from HTTP 400 Bad Request to HTTP 401 Unauthorized, when the client does not exist or the registration access token is not valid.

However, there is still one inconsistency with the [specification](https://tools.ietf.org/html/rfc7591#section-3.2.1): after successful registration the server must respond with HTTP 201 Created status code, but now it responds with HTTP 200 OK. I've noticed that we have blocks of code that are expects status code to be exactly 200. 
```
if (response.getStatus() == 200) {
...
}
```
For example in [oxauth-rp](https://github.com/GluuFederation/oxAuth/blob/master/RP/src/main/java/org/xdi/oxauth/action/RegistrationAction.java#L132). I'm not sure what impact will have this change on the other clients who use this API and whether or not to change the returned status code to HTTP 201 Created. What do you think guys: @qbert2k, @yurem, @yuriyz, @nynymike?

**Comment by yurem** [comment]
I think these are right changes. The only one question is if we can use [RFC 7592](https://tools.ietf.org/html/rfc7592). The current spats of this spec is "EXPERIMENTAL".


Regarding client registration. yes, I think we need to return HTTP 201 according to [RFC 7591](https://tools.ietf.org/html/rfc7591) spec. Is spec status "PROPOSED STANDARD" means that it's final version?

**Comment by worm333** [comment]
Here is one more thing that needs to be updated conform with the [specification](https://tools.ietf.org/html/rfc7592#section-2.2):

> Omitted fields MUST be treated as null or empty values by the server,
   indicating the client's request to delete them from the client's
   registration.

I'll update pool request with necessary changes.

**Comment by nynymike** [comment]
This pull request has conflicts. Can you try to resolve?

**Comment by worm333** [comment]
Here is [the pull request](https://github.com/GluuFederation/oxAuth/pull/349) related with this issue. As I can see there is no conflicts.
