### ISSUE TITLE
Enable CR as it can pull binary attribute

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#32]
CR mechanism is not tested to pull and store binary attributes. 

Some customer require ObjectGUID ( a binary attribute in Active Directory ) to pull into their Gluu Server as this binary attribute can be released to Microsoft specific services ( i.e. Office365 ). 

I tried to create a custom attribute named 'ObjectGUID' ( format of attribute: photo ) and pulled AD's ObjectGUID. Seems like values are changing when it is coming into Gluu-LDAP. 

As for example: ObjectGUID in backend AD might be: 1+4wBZy0kqqGzsgU8tUvXw==
But when it is coming into Gluu-LDAP, it turns to 77+977+9MAXvv37vv37vv71B77+797+9OBTvv73vv70vXw==

**Comment by nynymike** [comment]
In the unboundid LDAP client API, you can signal to the DS that the attribute is already base64 encoded.

**Comment by yurem** [comment]
I think UnboundID SDK or our oxLDAP library should detect Base64 values automatically.
We are not using this functionality in other places. Hence we can try to fix this in CR script.

Can we try to implement workaround via CR script. Sample CR script:
<code>
from com.unboundid.util import Base64
import sys

....
....
....

for attribute in attributes:
    attrName = attribute.getName()
    attrValue = attribute.getValue()

    if (StringHelper.equalsIgnoreCase("testbinary", attribute.getValue()) and StringHelper.isNotEmpty(attrValue)):
        try:
            decodedAttrValue = Base64.decodeToString(attrValue)
            attribute.setValue("testbinary", decodedAttrValue);
        except java.text.ParseException, ex:
            print "Failed to decode Base64 attribute. Exception:", sys.exc_info()[1]
</code>

**Comment by yurem** [comment]
According to this we do base64 decode inside script to allow to do base64 during persisting it.

**Comment by yurem** [comment]
Our LDAP persistence layer supports binary attributes now.
