### ISSUE TITLE
acr name "internal" does not match Name

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#329]
As you can see in this screenshot, the name of the default password authn is "auth_ldap_sever"

![image](https://cloud.githubusercontent.com/assets/3717101/18555881/10bb3af8-7b2f-11e6-9075-b2300d2b63dd.png)

But the acr in the discovery metadata is showing "internal" 

```
"acr_values_supported": [
        "u2f",
        "duo",
        "basic",
        "mt",
        "oxpush2",
        "gplus",
        "internal"
    ],
```

![image](https://cloud.githubusercontent.com/assets/3717101/18555953/558cfb3a-7b2f-11e6-843e-d8ecfe1ab2c1.png)

**Comment by nynymike** [comment]
See also this issue in oxTrust: https://github.com/GluuFederation/oxTrust/issues/369

**Comment by nynymike** [comment]
Assigning Gene... this should be incorporated in 3.0.0

**Comment by yurem** [comment]
What "internal" method name should we use when admin decided to deactivate these authentication configuration?
![default](https://cloud.githubusercontent.com/assets/6104200/20600276/715622e8-b25b-11e6-8b09-8c6d59680256.png)

**Comment by yurem** [comment]
it's not mandatory configuration. By default oxAuth can use internal LDAP for authentication.

**Comment by yurem** [comment]
I like this idea of using LDAP authentication name as internal ACR. In this case we can add many LDAP configurations and select right one with ACR.

It's not clear only if there is no LDAP configs which name to use. Maybe the name will be "internal_ldap" for this case. What do you think?

**Comment by nynymike** [comment]
Pull request is sent.
