### ISSUE TITLE
Support logout with expired id_token

### ISSUE THREAD

**Issue by karapetyan88** [GluuFederation/oxAuth#332]
I have wordpress site and I have logged in into my site with the help of oxd server by my gluu server account,  
When I am doing logout in my site, I do logout from gluu_server too, but when session times out before the Wordpress session, I am getting error  invalid_grant error in gluu server logout page.
I need to add opportunity for returning me error from OP

**Comment by yuriyz** [comment]
It seems all errors from Authorization and End Session Endpoints must return error as redirect otherwise RP doesn't have any chance to handle the error.

**Comment by nynymike** [comment]
The RP can see the exp of the id_token. Therefore, the RP should know that the session is already ended, so there is not point calling logout at the OP.

**Comment by yuriyz** [comment]
We discussed it in skype and decided:
1) end_session endpoint must work even with expired id_token (remove id_token on session_state removing or otherwise save hashes in session)
2) add to oxd error if id_token is expired (however it may be redundant if we handle it centrally on OP side)

**Comment by yurem** [comment]
end_session endpoint not issue any information and tokens. Hence we can allow to call this endpoint with expired id_token.

Solution:
- On user authentication we can store it in user entry sha256(id_token).
- On end_session after id_token validation we can add additional code to check if in session exists hash code of specified id_token and allow logout using it.

**Comment by yuriyz** [comment]
I will take over and will fix it for both sp1 and master

**Comment by yuriyz** [comment]
done. Fixed in sp2 and master branches (not present in sp1).

**Comment by yurem** [comment]
Now according to the code end session endpoint ignores id_token_hint. It relay on our session_state which not part of the official spec. I think it should still use id_token_hint and if it expired try to end session using session_state.

**Comment by yuriyz** [comment]
We can add back id_token_hint but what is the advantage of this approach if we anyway ignore it if token expired? 

session_state is part of official spec, see http://openid.net/specs/openid-connect-session-1_0.html

according to RP-Initiated logout, non of the parameters are required: http://openid.net/specs/openid-connect-session-1_0.html#RPLogout (id_token_hint is recommended)

**Comment by nynymike** [comment]
Let's push this decision to 2.4.6.

**Comment by yurem** [comment]
I've updated oxTrust. Now it sends session_state instead of id_token_hint. But what about customers applications? I think we need to add property
```
"legacyIdTokenEndSession": false
```
 similar to [this ](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/oxauth-config.json#L235) to allow customers update their applications.

**Comment by yuriyz** [comment]
session_state is in cookie, so it should work without any changes. If session is not in cookie then there is something obviously wrong.

**Comment by yurem** [comment]
Is there example how to properly end session on RP session destroy. I mean case when server ends session on timeout.

**Comment by yuriyz** [comment]
Main use case is RP initiated end_session which invoke front_channel logout (that kills all RP's session from different clients with logout_uri's iframe). For case when OP decided to end_session we do nothing, there no browser in this case, means no iframe -> RP may think that session is still alive. I guess in this case RP should handle it with check_session_iframe (see http://openid.net/specs/openid-connect-session-1_0.html). @qbert2k  is it correct?

**Comment by nynymike** [comment]
There is a spec for back-channel logout, but we're not ready to implement it. Both front channel and back channel logout spects are a version 1 draft. Front channel has more of a chance of working as expected, although there will be changes still to come.

**Comment by yurem** [comment]
oxTrust uses front channel way as back channel to end session on session destroy:
https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/java/org/gluu/oxtrust/service/AuthenticationSessionService.java#L50

It can't use iframe, etc... because user might close browser but RP need to end oxAuth session anyway.


I wonder if there are customers who uses similar approach, That's why O offered to support id_token parameter via property:

```
"legacyIdTokenEndSession": false
```

**Comment by nynymike** [comment]
I think I better not comment anymore. I'm not sure I fully understand this issue.

**Comment by nynymike** [comment]
Is this issue closed ?

**Comment by yurem** [comment]
Implemented
