### ISSUE TITLE
Session has duplicate value: acr / acr_values

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#334]
![image](https://cloud.githubusercontent.com/assets/3717101/18755272/2e7dea40-80b1-11e6-8f7e-50a56c478d61.png)

The session should use `acr` not `acr_values`.

**Comment by yuriyz** [comment]
@nynymike done. @yurem I checked code and seems to not have side affects but just to make sure would you please double check external authentication code.

**Comment by yuriyz** [comment]
Fixed for sp2 and in master.
