### ISSUE TITLE
Upgrade oxauth to UMA 2.0

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#357]
https://docs.kantarainitiative.org/uma/ed/uma-core-2.0-05.html

**Comment by yuriyz** [comment]
remove GAT token during UMA 2.0 implementation

**Comment by yuriyz** [comment]
https://docs.kantarainitiative.org/uma/ed/

**Comment by yuriyz** [comment]
https://docs.kantarainitiative.org/uma/ed/oauth-uma-ticket-2.0-00.html

**Comment by nynymike** [comment]
Closing because this is too general a ticket.
