### ISSUE TITLE
Customizing Pages within /var/gluu/webapps/

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxAuth#365]
PNG and CSS files aren't being picked up by Tomcat when placed under /var/gluu/webapp/oxauth.
Custom login page changes are being picked up from /var/gluu/webapps/oxauth/pages/login.xhtml, But we do get 404 error for css files.

Steps to reproduce issue - 
- copy /opt/tomcat/webapps/oxauth/login.xhtml to /var/gluu/webapps/oxauth/pages/
- copy /opt/tomcat/webapps/oxauth/WEB-INF/incl/layout/template.xhtml to  /var/gluu/webapps/oxauth/pages/
- update login.xhtml to pick template from /var/gluu/webapps/oxauth/pages/
- use custom css file and a png logo, and place inside  /var/gluu/webapps/oxauth/pages/resources
- Access login page, you will see css changes are not reflected. 
Even when accessed the css file in browser https://idp.gluu.info/oxauth/resources/styelsheet/theme.css , it gives 404 error.

**Comment by yurem** [comment]
CE 2.4.3 during install creates next folders:
1)      /var/gluu/webapps/oxauth/{libs, pages, resources}
2)      /var/gluu/webapps/oxtrust/{libs, pages, resources}

/var/gluu/webapps/oxauth/libs we can use it to add custom 3-rd party libs which custom scripts uses in oxAuth.
/var/gluu/webapps/oxauth/pages we uses it to override/add new pages to oxAuth. Example: login.xhtml /var/gluu/webapps/oxauth/resources we can use to add images, styles, other resources. oxAuth maps them to /oxauth/ext/resources . Example: http://ce-dev.gluu.org/oxauth/ext/resources

**Comment by yurem** [comment]
@sahiliamsso, you need to add /oxauth/ext/resources to all resource URLs

**Comment by worm333** [comment]
In gluu-server-3.0.0, static resources should be placed in `/opt/web/jetty/oxauth/pages` for oxAuth project and in `/opt/web/jetty/identity/pages` for oxTrust project.

For instance, if you would place `sample.png` in `/opt/web/jetty/oxauth/pages`, then you can access the image using the following url: `/oxauth/ext/resources/sample.png`
