### ISSUE TITLE
auth_level_mapping discovery has double-array

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#366]
```
"auth_level_mapping": {
        "50": [["saml"]],
        "10": [["u2f"]],
        "-1": [["internal"]]
    },
```
Should be:
 "auth_level_mapping": {
        "50": ["saml"],
        "10": ["u2f"],
        "-1": ["internal"]
    },

**Comment by worm333** [comment]
Prepared the [pull request](https://github.com/GluuFederation/oxAuth/pull/367)
