### ISSUE TITLE
Athorization parameter acr_values should be space-separated string

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#37]
In current version acr_values paramter is JSON array. We need to update application to allow pass it as space-separated string.

**Comment by yurem** [comment]
I fixed acr_values in one place related to external authenticator code: https://github.com/GluuFederation/oxAuth/commit/e17c469eb677906b1f0fb4c3ab369e25f9da2d97
But there are other places like JwtAuthorizationRequest.java, RegisterRequest.java, etc.. In some place we expect this param as string separated list, but in some places as JSON  Array. We need to update not only server code. We also need to fix client code.

**Comment by yuriyz** [comment]
I will take over client part

**Comment by yurem** [comment]
From https://openid.net/specs/openid-connect-registration-1_0.html
default_acr_values
    OPTIONAL. Default requested Authentication Context Class Reference values. Array of strings that specifies the default acr values that the OP is ...

It looks like in dynamic client registration we should use JSON Array...

**Comment by yuriyz** [comment]
About space delimited acr_values for authorization request:
1. Server : Now it checks both space delimited values and json array. So we are on safe side and server will handle both.
https://github.com/GluuFederation/oxAuth/commit/d3246d73ad15098929811a5b1089043f20cfca68
2. Client: oxauth client sends space delimited value exactly as it's specified in specification.
https://github.com/GluuFederation/oxAuth/blob/master/Client/src/main/java/org/xdi/oxauth/client/AuthorizationRequest.java

We have other places where acr values are used. In Client Registration case it also looks to me as JSON Array and it's already coded on server side and client side as JSON Array. No code changes are required.
