### ISSUE TITLE
Better error handling for logout 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#371]
If you call end_session with an already ended session, oxAuth may return this message to the broswer. 
It would be better to redirect to the authorize endpoint if a session cannot be found.

```
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an unsupported parameter or parameter value, repeats a parameter, or is otherwise malformed."}
```

**Comment by qbert2k** [comment]
Actually, when calling to end_session with an already ended session or with an invalid id_token_hint parameter, oxAuth responds with 401 error:

```
HTTP/1.1 401
Content-Type: text/plain

{"error":"invalid_grant","error_description":"The provided access token is invalid, or was issued to another client."}
```

When a session ends, it is being removed from LDAP so it is not possible to build an authorization request to redirect to the authorization endpoint.
