### ISSUE TITLE
Show error page with time stamp on oxauth error

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#377]
![f731dcd7d3b2996fd86e8dfa17c85c538bb39e0667801ce620 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/6104200/20768316/218a62fc-b746-11e6-844b-47c2a19fdb66.png)

I've uncommented  default error.xhtml page in pages.xml: https://github.com/GluuFederation/oxAuth/commit/dee5c49829bac7a806b87da7334723ccae6d44ee

**Comment by yurem** [comment]
Implemented. Now instead of showing jetty/tomcat error page we show own error page.
We display it only if web services endpoints not catch all exceptions.

![default](https://cloud.githubusercontent.com/assets/6104200/21718746/14217814-d422-11e6-90a3-e38d0b42d350.png)

**Comment by yurem** [comment]
We need to review it after migration to CDI

**Comment by willow9886** [comment]
Re-evaluate after we migrate to weld:

https://github.com/GluuFederation/oxAuth/issues/221
