### ISSUE TITLE
Request / Resonse Audit Logging

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#378]
In SAML, there is a logging option to see the reqests and responses, and the unencrypted assertions. This would be really handy for oxAuth OpenID Connect also. Whether this feature is enabled should be controlled by a property.  It is really a debug setting--normally you wouldn't want it. But if you are trying to debug a client, it could be useful. It should maybe also go to a special log file.

**Comment by worm333** [comment]
Created [pull request](https://github.com/GluuFederation/oxAuth/pull/540/) which includes new http logging filter.

 Two params from [AppConfiguration](https://github.com/GluuFederation/oxAuth/blob/master/Model/src/main/java/org/xdi/oxauth/model/configuration/AppConfiguration.java): `httpLoggingEnabled`(if true enables logging) and  `httpLoggingExludePaths`(exclude requests from logging which URIs are matching one of the values) are controlling filter behavior.

Logs are writing in separate file `http_request_response.log`

**Comment by worm333** [comment]
Example of request:
