### ISSUE TITLE
Authenticator should not add default message if count of messages > 0

### ISSUE THREAD

**Issue by arvindsinghtomar** [GluuFederation/oxAuth#379]
Authenticator is adding the default message even if the count of message is more than 0.

Below is the screenshot of multiple messages displayed at same time
![twoerrorsatsametime](https://cloud.githubusercontent.com/assets/18719003/20805337/3943461c-b81c-11e6-8816-f078e3a0c20e.png)

**Comment by nynymike** [comment]
Unclear how you are getting this result. Please provide more context.

**Comment by arvindsinghtomar** [comment]
I have been working on custom authentication script for passport and I was trying to display custom message. I have aded the custom message but still the default message "Please use correct username and password" is been displayed. I have talked about this issue to Yuriy and he told that he would look at this.

**Comment by nynymike** [comment]
This is not a bug....
