### ISSUE TITLE
Attribute values as UTF-8 string

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxAuth#387]
The IDP can handle special characters, for example a customers last name (Gyllensvärd) is correctly stored in IDP record. 

Problem occurs in OAuth protocol. So after successful login, IDP returns user credentials to be synced with local record in Django app. That is where encoding fails. So it is not wrong everywhere, but at a very specific step in OAuth2 protocol.

In this workflow there are 3 parts: IDP, oxAuth and OpenID oxTrust library. Perhaps we don't handle the attribute values as UTF-8 string in one of these 3 parts.

**Comment by worm333** [comment]
Here is how I replicated this problem:
