### ISSUE TITLE
oxAuth should return more informative error message if acr is not sufficient

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#388]
When navigating from an app with basic --> u2f acr requirements, I got the error in oxAuth:

```
[org.xdi.oxauth.service.SessionStateService] Acr is changed. Session acr: internal(level: -1), 
current acr: u2f(level: 10)
```
But in oxTrust, I saw the message:

```
[org.gluu.oxtrust.action.Authenticator] No authorization code sent. Error: access_denied. Error 
description: The resource owner or authorization server denied the request.
```

Is there a way for oxAuth to return a more informative error message, so an app can understand the reason for the failure, and potentially use `prompt=login` and specify the stronger acr?

**Comment by willow9886** [comment]
Re-evaluate after we migrate to weld:

https://github.com/GluuFederation/oxAuth/issues/221
