### ISSUE TITLE
WebUI enhancements to provide a more flexible support.

### ISSUE THREAD

**Issue by Anikynetix** [GluuFederation/oxAuth#39]
I think we should slowly start working towards making our user interface codes a bit more developer friendly, if not user friendly. My main concern is about the fact that the css files and templates are inside the war files; this is causing the IDP's WebUI to revert back to its default state on every update.

What would be the ramifications of moving the WebUI files so that they remain unaffected by the updates?

We can start off with the following files and build up on it as we progress:

/opt/tomcat/webapps/oxauth/stylesheet/theme.css
/opt/tomcat/webapps/oxauth/WEB-INF/incl/layout/template.xhtml
/opt/tomcat/webapps/oxauth/login.xhtml

**Comment by mzico** [comment]
@rahatjaan is also working on oxTrust refurbishment. Assigning this ticket to him.

**Comment by yurem** [comment]
In oxauth-config.xml there are next options:
    <cssLocation>/oxauth/stylesheet</cssLocation>
    <jsLocation>/oxauth/js</jsLocation>
    <imgLocation>/oxauth/img</imgLocation>

Can you try to add them to check if oxauth will use files from specified folders.

**Comment by willow9886** [comment]
this issue is covered in another github request: https://github.com/GluuFederation/oxAuth/issues/62
