### ISSUE TITLE
Introspection API Docs: Missing Response

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#391]
https://gluu.org/docs/api/uma-rpt-status/ is missing the response details.

**Comment by yuriyz** [comment]
added response sample here https://github.com/GluuFederation/docs/commit/395417434947809cd631ea34ea5189368db988e4 but in addition to that we need better description updated based on response to this support ticket https://support.gluu.org/access-management/3568/introspection-endpoint-questions/#at17956

**Comment by nynymike** [comment]
Shouldn't API docs be handled with correct annotations so they can be auto-generated?

**Comment by shekhar16** [comment]
Added the documentation as per https://gluu.org/docs/ce/3.1.1/api-guide/uma-api/#token-introspection

**Comment by yurem** [comment]
Added docs to UMA token introspection endpoint
