### ISSUE TITLE
Audit logger thread is blocked under high load

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#399]
With 200 concurrent threads and enabled audit logger eventually thread is blocked. Audit event must be logged in asynchronous way without blocking current thread.

**Comment by yuriyz** [comment]
![audit_logger_1](https://cloud.githubusercontent.com/assets/2013070/21331444/23034c0c-c64b-11e6-82de-0eaae8f81d7d.png)

**Comment by yuriyz** [comment]
https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/BlockingQueue.html

**Comment by yurem** [comment]
We inject configuration into bean now

**Comment by yuriyz** [comment]
Next bottleneck would be sendMessage which is implemented in synchronous way while we need to work it in asynchrounous way. E.g. via Blocking queue.

**Comment by yurem** [comment]
sendMessage is not synchronous
```
	@Asynchronous
	public void sendMessage(OAuth2AuditLog oAuth2AuditLog) {
```

**Comment by yuriyz** [comment]
ah, right. Closing for now, we will check it with profiler.
