### ISSUE TITLE
Change interface of authz interception script to just return 'acr' and 'amr'

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#40]
The methods 
- Integer getAuthLevel();
- String getAuthMode();

Should just be  
- String getACR
- String[] getAMRs

According to the [spec](http://openid.net/specs/openid-connect-core-1_0.html#IDToken) ``amr`` is a list of strings, ``acr`` is just one string.

Perhaps the authz interception method should just have a way to retrieve the id_token.

**Comment by yuriyz** [comment]
renamed getAuthLevel() -> getAcrs(). Keep in mind that if there is any existing usages in custom scripts then those scrips has to be updated to use new getAcrs() method. Otherwise it will fail with jython exception.
