### ISSUE TITLE
Allow Seam to create componets with all injected componets

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#401]
1) Instead of pattern in non APPLICATION scope classes:
```
    @In
    private ConfigurationFactory configurationFactory
...
configurationFactory.getConfiguration()....
```
we need to use pattern:
```
    @In(value = "#{configurationFactory.configuration}")
    private Configuration configuration;
...
configuration.....
```

Example:
https://github.com/GluuFederation/oxAuth/commit/1abf9a3ad890d7ab4d7a606bf05e164c0510dd8c#diff-c86e72a99d6982ed1f01fc888b57236aR102

2) Access configuration in APPLICATION scope classes in next way:
```
	private Configuration configuration;
 
 	@Create
 	public void init() {
		updateConfiguration();
 	}
 
	@Observer( ConfigurationFactory.CONFIGURATION_UPDATE_EVENT )
	public void updateConfiguration() {
		this.configuration = configurationFactory.getConfiguration();
	}
...
configuration.....
```

Example:
https://github.com/GluuFederation/oxAuth/commit/1abf9a3ad890d7ab4d7a606bf05e164c0510dd8c#diff-182d24ac8186fea64803cca9f2fae67cR79

3) Replace in all classes where it's possible
```
Service.instance()
```
with
```
    @In
    private Service service;
```
Example:
https://github.com/GluuFederation/oxAuth/commit/81b0364b1922604bd5bc1f8832a1571c36d2ec0f#diff-62c2b9e5ec5974c46f59aeec6012972aL44

4) Fix facesContext and externalContext injection

Example:
https://github.com/GluuFederation/oxAuth/commit/cd86e3cf3603cbcc545106f790888f29767e3df3

**Comment by yuriyz** [comment]
Basically we need to avoid this line 
```
```
