### ISSUE TITLE
Add JSON property to control writing last update time to LDAP

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#410]
We temporary commented out 
https://github.com/GluuFederation/oxAuth/commit/4d96e46bb4c2f701793967b9f5784a88dbcfe09a
https://github.com/GluuFederation/oxAuth/commit/c21b81f46d26a401a411a1782539da6a986dbfd2

We need to add new configuration attribute to enable/disable these attributes update.
After that we need to revert back these commits and update to use new configuration option

**Comment by worm333** [comment]
See [this](https://github.com/GluuFederation/oxAuth/pull/435) pull request.
