### ISSUE TITLE
Update Jquery library

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#411]
JQuery is used in some xhthml authn pages.

It seems the Jquery library (v1.11.2) in use is affected by some publicly known vulnerabilities. Specifically it’s about this issue: https://github.com/jquery/jquery/issues/2432 . Can you provide insight if the affected feature is used? (If the vulnerable feature is not used, this alert can be consider as false positive.) If it is used, is it possible to upgrade the used Jquery library?

**Comment by yurem** [comment]
We uses JQuery v1.11.3: https://github.com/GluuFederation/oxAuth/tree/master/Server/src/main/webapp/js

Updated to v1.12.4: https://github.com/GluuFederation/oxAuth/commit/4c2c5ebf7f7416a96971ebef3555aa3c8b228f7e
