### ISSUE TITLE
Comment out text and hyperlinks from oxAuth login page

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#414]
Comment out the hyperlink and text for `Need an Account? Sign Up!` and `Forgot your password?` from oxAuth login page customization which we are shipping out of the box in 3.0.0. 
![screenshot_4](https://cloud.githubusercontent.com/assets/7156097/21503351/6e5034d2-cc1c-11e6-8ec4-f862b9dabcbd.png)

If the admin wants to display this text and links, they should be able to un-comment it out as needed.

**Comment by willow9886** [comment]
If you can also add the following note in the comment :

Registration and password reset need to be configured and enabled from the Gluu Server dashboard.

**Comment by yurem** [comment]
Fixed
