### ISSUE TITLE
Migrate from log4j 1.x to 2.x

### ISSUE THREAD

**Issue by dnorthup-ums** [GluuFederation/oxAuth#416]
The old but highly useful log4j 1.x code has numerous well documented performance problems which are claimed to have been fixed in log4j 2.x. Also, given that it was EOL'd over a year ago it is probably time to move on, as the original project masters will not be providing security updates for it either.

(This comes out of reading the patches attached to #283 and noticing that log4j 1.x was used and not the newer library.)

EOL Announcement: 
[https://blogs.apache.org/foundation/entry/apache_logging_services_project_announces](url)

**Comment by yurem** [comment]
https://github.com/GluuFederation/oxAuth/commit/0ad3a0e232726e7b0293b8c2793b52ae023af1ed

**Comment by yurem** [comment]
https://github.com/GluuFederation/oxAuth/commit/1566be1e796848f29d39bf92eb4840cc0ce18fb1

**Comment by yurem** [comment]
Done. I opened same issue in oxTrust: https://github.com/GluuFederation/oxTrust/issues/434
