### ISSUE TITLE
CleanUp timer should loads all expired entries using searchLimit =100

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#419]
On big loads oxAuth creates many session and token entries. On the other extrema all methods in cleanup timer loads all entries which conform search filter. We need to load them by portions of 100 entries to avoid CleanUp timer hangs. Now on our benchamrk server there are > 100k session and even more tokens.

The pattern should be next or anolog of this method:
exitFlag = False
while !exitFlag {
  entries_to_removal = load first 100 entries only
  remove(entries_to_removal)
  exitFlag = entries_to_removal < 100
}

**Comment by worm333** [comment]
Created pull request #424
