### ISSUE TITLE
Replace activemq-all jar with  only required libraries

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#425]
We need to replace activemq-all.jar which contains a loot of classes from other libraries: log4j, transaction-api, logging, etc.. with only required dependencies.

This jar with all libs can cause issues becuase we really don't know  which class version java will select to use.
Also this library size is 15 Mb

**Comment by yurem** [comment]
Now oxAuth depends on activemq-client and activemq-pool

**Comment by yurem** [comment]
@worm333 can you chekc if oxAuth sends JMS messages with this minimum dependencies

**Comment by worm333** [comment]
Sure, I'll check it out.
