### ISSUE TITLE
Client Secret is shown empty in first try

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxAuth#427]
OS: CentOS 6.6 (Final)
Pakcage: gluu-server-3.0.0.x86_64        2-BETA2.centos6

The client secret that needs to be given when adding a new client does not work the first time when the update button is pressed. A message that the client secret is empty is shown. There are no errors in the `oxtrust.log` and `oxauth.log`. The problem is shown in the link below.

* [Video Link](https://youtu.be/e1SoKqy4ACM)

**Comment by yurem** [comment]
I think it's fixed. Video link is not exists.
