### ISSUE TITLE
OpenId acr claim

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#43]
There are few TODO for ACR.
1. There is acr claim in IdToken.
   I used basic method for authentication
   This is result list of claim of IdToken
   {"iss":"https://seed22.gluu.org","aud":"@!D79B.BDA4.A74F.453F!0008!EC89.22E8","exp":1432733067,"iat":1432729467,"nonce":"nonce","auth_time":1432729466,"c_hash":"HzIUSO3TlYfTBj0lhBO8PA","oxValidationURI":"https://seed22.gluu.org/oxauth/opiframe","oxOpenIDConnectVersion":"openidconnect-1.0","user_name":"admin","inum":"@!D79B.BDA4.A74F.453F!0001!9573.5466!0000!A8F2.DE1E.D7FB","name":"Default Admin User","family_name":"User","given_name":"Admin"}
   it should contains acr
2. oxTrust was not updated to use acr instead of auth_mode
3. Also in sections 3.1.3.7, 5.5. 5.5.1.1, 16.20.  there are information that it's possible to request acr claim
   I'm not sure that these endpoints can return acr claim

**Comment by yuriyz** [comment]
@yurem would you be so kind to fix oxTrust and oxAuth custom authentication methods, so we can completely move to acr instead of misleading auth_mode and auth_level ? Then please reassign back to me for oxauth code update (token & apis)

**Comment by yurem** [comment]
We only need to make sure that we returns acr claim correctly and in right cases.

Yuriy, can you take a look on point 3 of this issue?

**Comment by GdotBdot** [comment]
Further, playing with the current Debian Version showed that acr_values only works when passed as JSON-Array, which contradicts the standard requiring a "Space-separated string"

**Comment by yurem** [comment]
CE 2.3 should be aligned with latest http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest spec:
acr_values
    OPTIONAL. Requested Authentication Context Class Reference values. Space-separated string that specifies the acr values that the Authorization Server is being requested to use for processing this Authentication Request, with the values appearing in order of preference....

**Comment by willow9886** [comment]
@yurem does this still need to be fixed or has it been addressed in a more recent version?

**Comment by yurem** [comment]
Implemented
