### ISSUE TITLE
Pairwise identifier still showing inum in id_token and Userinfo

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#430]
This client is set to pairwise identifiers, yet the inum is returned in both the id_token and from the Userinfo endpoint:

![image](https://cloud.githubusercontent.com/assets/3717101/21876298/6c4772f4-d847-11e6-8c27-34ae64e5f4b8.png)

![image](https://cloud.githubusercontent.com/assets/3717101/21876308/84801376-d847-11e6-8ce9-44ba48881315.png)

**Comment by qbert2k** [comment]
Fixed in CE commit:
https://github.com/GluuFederation/community-edition-setup/commit/dfc0d3122db416792175503937633239d6782d72
