### ISSUE TITLE
Any primaryKey other than UID doesn't work

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#436]
* Issue: If we want to use 'email_address' or any other attribute other than 'UID' as login attribute; it doesn't work. 
* Stack trace: http://pastebin.com/sBieYYH3
* oxAuth version:  2.4.4.sp2_openldap / Implementation-Build: b0a87663fa7b47f4c5bd720f486e55a3619d9af6

* How to reproduce: 

- Checked with one IDP which is using a remote LDAP which is storing user information. 
- 'Manage Authentication' 
   - Primary Key: email [ or any other attribute but uid / sAMAccountName ] 
   - Local Primary Key: email [ any attribute other than UID ]

**Comment by yurem** [comment]
Fixed in CE 3.0.0 and in 2.4.4 SP3. New builds in maven contains this fix

**Comment by mzico** [comment]
@yurem : Thanks; reassigning the issue to Zamil for quick testing.

**Comment by yurem** [comment]
@zamilskhan can you retest it?

**Comment by zamilskhan** [comment]
I am on it
