### ISSUE TITLE
Random errrors on high load

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#438]
Our authorization/token benchmarking test are showing that there are 30 errors per 10k requests when we run test with 400 threads,

We need to find out root case of them and fix. The more details in xeon log.

**Comment by yurem** [comment]
All errors related to LDAP update/remove operations in session and grant entries.

**Comment by yuriyz** [comment]
Run benchmarking test with 400 threads on xeon. 0% of errors, I tried it 5 times and all 5 times no errors. It seems to work now.

**Comment by yurem** [comment]
I've set status to 'QA'

**Comment by yurem** [comment]
All errors around this:
```
com.unboundid.ldap.sdk.LDAPException: Entry uniqueIdentifier=eabb2d47-0115-46fe-a65e-c4cc19ba9b1c,ou=session,o=@!E8F2.853B.1E7B.ACE2!0001!39A4.C163,o=gluu cannot be modified because an attempt was made to remove one or more values from attribute oxAuthUserDN but this attribute is not present in the entry
	at com.unboundid.ldap.sdk.LDAPConnection.modify(LDAPConnection.java:2754) ~[unboundid-ldapsdk-3.2.0.jar:3.2.0]
...
	at org.xdi.oxauth.service.SessionStateService.updateSessionState(SessionStateService.java:461) [classes/:?]
```

```
2017-01-25 09:16:27,458 ERROR [qtp1579526446-414] [org.gluu.site.ldap.OperationsFacade] (OperationsFacade.java:551) - Entry can't be modified
com.unboundid.ldap.sdk.LDAPException: modify/delete: oxAuthUserDN: no such attribute
...
	at org.xdi.oxauth.service.SessionStateService.updateSessionState(SessionStateService.java:461) [classes/:?]
```

**Comment by yuriyz** [comment]
It should be possible to avoid it with empty string, it's similar to this https://bugster.forgerock.org/jira/browse/OPENAM-3237?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by yuriyz** [comment]
Fixed.

**Comment by yuriyz** [comment]
uniqueIdentifier=180ec132-98c0-473c-8dde-3d195834ec7f,ou=session,o=@!E8F2.853B.1E7B.ACE2!0001!39A4.C163,o=gluu cannot be modified because it would have resulted in one or more duplicate values for attribute oxAuthUserDN: inum=@!E8F2.853B.1E7B.ACE2!0001!39A4.C163!0000!A8F2.DE1E.D7FB,ou=people,o=@!E8F2.853B.1E7B.ACE2!0001!39A4.C163,o=gluu

**Comment by yuriyz** [comment]
issue is workarounded with retries (3 times)
