### ISSUE TITLE
Persist authorizations throws NPE

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#442]
When client authorization is created, it's ok. But on second login, it throws an NPE.

Here's the error:
```
WARNING: #{authorizeAction.permissionGranted}: java.lang.NullPointerException
INFO   | jvm 1    | 2017/01/16 14:36:25 | javax.faces.FacesException: #{authorizeAction.permissionGranted}: java.lang.NullPointerException
```

Here is the session information:

INFO   | jvm 1    | 2017/01/16 23:30:09 | 2017-01-16 23:30:09,641 INFO  [org.xdi.oxauth.service.AuthenticationService] Attempting to redirect user: SessionUser: SessionState, dn='uniqueIdentifier=c3ddec95-67ec-4e32-a031-10ce5f81cda6,ou=session,o=@!281E.2A69.9D58.5507!0001!C4A2.021C,o=gluu', id='c3ddec95-67ec-4e32-a031-10ce5f81cda6', isJwt=false, lastUsedAt=Mon Jan 16 23:30:09 UTC 2017, userDn='inum=@!281E.2A69.9D58.5507!0001!C4A2.021C!0000!A8F2.DE1E.D7FB,ou=people,o=@!281E.2A69.9D58.5507!0001!C4A2.021C,o=gluu', authenticationTime=Mon Jan 16 23:30:09 UTC 2017, state=authenticated, **permissionGranted=null, permissionGrantedMap=null**, sessionAttributes={scope=openid profile email, response_type=code, nonce=DwFPDx77rY9EpQ2GWLa7t68WId4hcJ8DpTuTgyI342w, redirect_uri=https://badger.gluu.info/callback, remote_ip=192.168.88.1, state=uvlpYXRafFZaIgiLSQIlCGu6uAY, auth_step=2, client_id=@!281E.2A69.9D58.5507!0001!C4A2.021C!0008!2628.32C5, acr=u2f, auth_user=admin, auth_step_passed_1=true, session_custom_state=approved, oxpush2_u2f_device_id=1481132269735, oxpush2_u2f_device_user_inum=@!281E.2A69.9D58.5507!0001!C4A2.021C!0000!A8F2.DE1E.D7FB, oxpush2_u2f_device_enroll=false, oxpush2_u2f_device_one_step=false}, persisted=true}

**Comment by burcinbozkurt** [comment]
Hello,

I have encountered with the same problem, did you already fix the problem? we have been using Gluu 2.4.4.sp2 on Centos 7. We do not want to upgrade to 3.0.0 since we do not have experience on Jetty? 
It seems the milestone is added to 2.4.4.3 and modified to CE 3.0.0??
Is there a way to fix the problem in 2.4.4.sp2 with library upgrade or so??
