### ISSUE TITLE
Caution message should be open source

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#449]
![image](https://cloud.githubusercontent.com/assets/3717101/22136412/06cabfae-de9a-11e6-9779-46929f1c80dc.png)

This message is sort of baffling... 

Let's change it to:  

```
<A HREF="https://github.com/GluuFederation/oxAuth/blob/master/LICENSE">Use subject to MIT LICENSE</A>
```

**Comment by yurem** [comment]
![default](https://cloud.githubusercontent.com/assets/6104200/22207598/6b318af4-e188-11e6-9e0d-464a2cd68e78.png)
