### ISSUE TITLE
Issue with sessions

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxAuth#46]
Follow these steps to reproduce:
1) Restart browser
2) Log in using your credentials
3) Logout
4) Click Login again
5) You will log in without entering user/password

**Comment by qbert2k** [comment]
I think this issue is related to #34

**Comment by yuriyz** [comment]
ok, it's not related to oxauth at all. If test it with idp.gluu.org it works like a charm (together with oxTrust). 
But it fails on support.gluu.org because on logout there are no real logout (cookie is not cleared).
