### ISSUE TITLE
Under high load (400 concurrent threads) we got redirect back to login page after successfull login  in ~1-2% of requests

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#463]
success sample : 2017/01/26 11:22:25 INFO  - jmeter.extractor.JSR223PostProcessor: login post processor, code : f7889c8d-7428-452b-80d7-adb4d8613cd0, url:https://xeon.gluu.info/identity/authentication/authcode?code=f7889c8d-7428-452b-80d7-adb4d8613cd0&scope=openid+user_name+profile+email&state&session_state=17ac7c26-6496-4d66-b901-6f367034bb7a
fail sample : 2017/01/26 11:22:25 INFO  - jmeter.extractor.JSR223PostProcessor: login post processor, code : , url:https://xeon.gluu.info/oxauth/login

**Comment by yuriyz** [comment]
GLUU.root@xeon:/opt/gluu/jetty/oxauth/logs# cat oxauth.log | grep "Authentication success for User" | wc -l
400
jmeter shows that one time user was redirected to login page instead of redirect_uri
so now we can definitely say that user was successfully authenticated by redirected to login page again

**Comment by yurem** [comment]
I can't reproduce it after migration to Weld
