### ISSUE TITLE
Read memcached configuration from ldap

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#467]
Configuration must be read from ldap.
https://github.com/GluuFederation/oxAuth/blob/memcached/Server/src/main/java/org/xdi/oxauth/model/appliance/GluuAppliance.java#L46-46

**Comment by worm333** [comment]
I've applied changes in this commit: https://github.com/GluuFederation/oxAuth/commit/9b68a7cea596277ec9f7a36926a5536f31919bd9

Do we need to update: [appliance.ldif](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/appliance.ldif) to add oxMemcachedConfiguration attribute?

**Comment by yuriyz** [comment]
yes, did you add oxMemcachedConfiguration to schema ? please link commit

**Comment by worm333** [comment]
Here is the new [pull request](https://github.com/GluuFederation/community-edition-setup/pull/264) with new oxMemcachedConfiguration attribute.

**Comment by yuriyz** [comment]
did you add new attributes to new schema generation tool  (provided by Arun) ? https://github.com/GluuFederation/community-edition-setup/tree/master/schema

**Comment by worm333** [comment]
I've added new attribute to the generation tool and generated new schema, [take a look](https://github.com/GluuFederation/community-edition-setup/pull/265).
