### ISSUE TITLE
Can not Register 

### ISSUE THREAD

**Issue by jwilleke** [GluuFederation/oxAuth#475]
For the oxAuth/RP-Demo I read that:
  1. First of all you need to register your own client for your RP (Client):
     a) via Admin UI (Example: https://ce-dev2.gluu.org)
     b) via Dynamic Registration Endpoint

https://ce-dev2.gluu.org/oxauth/login only shows a Login and I see no method to register a client.

I assume I am missing something?

**Comment by nynymike** [comment]
oxAuth github is not the place to ask support questions. Please register and open an issue on https://support.gluu.org    If the issue is clearly a bug, we will move it to github.
