### ISSUE TITLE
Memcached provider should read configuration file with expiration setting for each region

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#477]
The problem that by default we put all objects in cache with expiration time 1 day.

We need to improve MemcachedProvider to put objects into cache with configurable lifetime per Region.

We can store each region setting in MemcachedConfiguration or inside war file in file in similar to EhCache way..

**Comment by nynymike** [comment]
Is this still an issue? for more complex cache deployments, should we just recommend Redis?

**Comment by yuriyz** [comment]
agreed, we should stick with redis since it does not bring random failures under high load. And for improving cache interface we have separate issue in oxCore https://github.com/GluuFederation/oxCore/issues/28. Closing it.
