### ISSUE TITLE
Integrate with Custom authentication provider

### ISSUE THREAD

**Issue by sankarbalu** [GluuFederation/oxAuth#478]
I have an existing web service from a legacy system that is used for authentication and it also provides some additional user based information as part of the response.

I would like to know the following

* Can Gluu be configured to use an existing authentication service ?
* Does Gluu provide options to capture this additional information returned in the response and return the additional information through /userinfo endpoint or even encode it within the JWT?

**Comment by nynymike** [comment]
yes and yes, but you'll need to register and post this question on https://support.gluu.org  Github is for confirmed software bugs only.
