### ISSUE TITLE
SuperGluu Script: add link to download app

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#479]
If the person is presented with the enrollment form, we should also provide a link on the bottom of the page to download the IOS and Android app.  If they load the enrollment form from their phone, they could click to download.  This should be configurable in the script properties, because a firm may have a custom branded version of Super Gluu.

**Comment by yurem** [comment]
It's generic logic page. We should avoid in generic page dependecy on one script variables like 'supergluu_android_download_url'

Can we do something like this:
```
<ui:repeat value="#{identity.getWorkingParameter('auth_download_url').entrySet().toArray()}" var="_links">
<ui:param name="app_name" value"#{_entry.key}"/>
<ui:param name="app_link" value"#{_entry.key}"/>

<h:outputLink value="#{app_link}" title="#{app_name}"><h:graphicImage value="img/#{app_name}png" /></h:outputLink>
</ui:repeat>
``

**Comment by willow9886** [comment]
@yurem I think we already do this now with the updated enrollment page, right? I'm closing for now. Please re-open if needed.
