### ISSUE TITLE
HTTP Basic Authentication wrong decoding

### ISSUE THREAD

**Issue by GdotBdot** [GluuFederation/oxAuth#48]
OAuth requires the client id to be encoded "using the 'application/x-www-form-urlencoded' encoding algorithm" (http://tools.ietf.org/html/rfc6749#section-2.3.1). This is obviously not respected when a OIDC-Client accesses the UserInfo Endpoint in the Authorization Code Flow, the missing decoding results in an "invalid_client" error response. You can reproduce this with the example client of connect2id (https://bitbucket.org/connect2id/openid-connect-dev-client), it's also discussed here: https://bitbucket.org/connect2id/oauth-2.0-sdk-with-openid-connect-extensions/issue/129/clientsecretbasic-incorrectly-url-encodes

**Comment by qbert2k** [comment]
Added a new test to verify the encoding.
https://github.com/GluuFederation/oxAuth/blob/master/Client/src/test/java/org/xdi/oxauth/ws/rs/ClientSecretBasicTest.java
http://ox.gluu.org/hudson/job/oxAuth/736/testReport/org.xdi.oxauth.ws.rs/ClientSecretBasicTest/
