### ISSUE TITLE
Support OpenID Connect Claims Languages

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#485]
Particular Claims MAY be requested by including Claim Names that contain #-separated BCP47 [RFC5646] language tags in the Claims request for example family_name#ja-Kana-JP

http://openid.net/specs/openid-connect-core-1_0.html#IndividualClaimsLanguages

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/71
