### ISSUE TITLE
Add Interception Script to enable Dynamic User Claim Generation

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#49]
When the id_token is returned from the user_info endpoint, the Gluu Server should expose one last interception script that enables you to massage the values for the attributes originating in LDAP. This dynamic attribute generation should only occur if the  oxAuthCustomScope type attribute == "dynamic"

The only method required is "update" similar to the dynamic attribute synchronization script. The current LDAP values should also be sent into the User object, so they are available in the script.

**Comment by yurem** [comment]
This is sample script: https://github.com/GluuFederation/oxExternal/blob/master/dynamic_scope/sample/SampleScript.py

**Comment by yurem** [comment]
Also I added client tests to cover this functionality.

**Comment by yurem** [comment]
Can you review this script?
