### ISSUE TITLE
Deprecate Authn Scripts: phonefactor, wikid, toopher, oneid, inwebo 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#490]
These scripts are not widely used and should be deprecated:
1. phonefactor
2. wikid
3. toopher
4. oneid
5. inwebo

**Comment by willow9886** [comment]
Add "deprecated" comment to each repo.

**Comment by yurem** [comment]
@willow9886 and @jschristie we need to add not to docs that deprecated (not tested in 3.1.0) scripts we moved to https://github.com/GluuFederation/oxAuth/tree/master/Server/integrations.deprecatred
