### ISSUE TITLE
Support Character Sets for username during authentication

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#491]
See [this issue](https://support.gluu.org/authentication/3872/unicode-username-unable-to-authentice-chinese/) on support.

**Comment by worm333** [comment]
I've tried to reproduce the problem described by Adam, and did the following:

- Created user with username `user雨涵`
<img width="639" alt="screen shot 2017-03-22 at 3 06 47 pm" src="https://cloud.githubusercontent.com/assets/5003491/24199236/73869a76-0f11-11e7-831b-086c66120caf.png">

- Logged in with created username

<img width="459" alt="screen shot 2017-03-22 at 3 07 03 pm" src="https://cloud.githubusercontent.com/assets/5003491/24199222/67038bce-0f11-11e7-93eb-6c2a4daffcca.png">

- And was able to view `user雨涵` profile

-<img width="388" alt="screen shot 2017-03-22 at 3 07 14 pm" src="https://cloud.githubusercontent.com/assets/5003491/24199245/7bb65eca-0f11-11e7-9cca-d8cfc6786501.png">


It seems to me that this problem could only be reproduced version in 2.4.4
