### ISSUE TITLE
Create mvn config for CLI Key Generation tool

### ISSUE THREAD

**Issue by iromli** [GluuFederation/oxAuth#495]
Is it possible to have a standalone KeyGenerator JAR with all of its dependencies?

The reason is one of Python app I've been working on requires KeyGenerator and it would be nice if I can download a single JAR instead of downloading several JAR files (KeyGenerator itself and its dependencies).

**Comment by nynymike** [comment]
This is needed for our cluster management application where oxEleven is not used.

**Comment by willow9886** [comment]
See this project for an example: https://github.com/mitreid-connect/json-web-key-generator

**Comment by qbert2k** [comment]
I have added a maven configuration in oxauth client pom file to package the jar file with all the required dependencies.

**Comment by qbert2k** [comment]
The following is an example of commands to get source from github, build the jar, and run the key generator:

```
git clone https://github.com/GluuFederation/oxAuth.git

cd oxAuth

mvn clean install -Dmaven.test.skip=true

cd Client/target

java -jar oxauth-client-jar-with-dependencies.jar -algorithms RS256 RS384 RS512 ES256 ES384 ES512 -keystore /PATH_TO_KEYSTORE/mykeystore.jks -keypasswd <PASSWD> -dnname "CN=oxAuth CACertificates" -expiration 365
```

**Comment by iromli** [comment]
@qbert2k Thanks.

Anyway, could you build the JAR and put it in our Maven repo? The thing is we are building Debian package that include this JAR and thinking that we want to avoid adding maven and run the mv command in the packaging.

**Comment by yurem** [comment]
http://ox.gluu.org/maven/org/xdi/oxauth-client/3.1.0-SNAPSHOT/oxauth-client-3.1.0-SNAPSHOT-jar-with-dependencies.jar

It's part of build process now.

**Comment by iromli** [comment]
@yurem Thanks.
