### ISSUE TITLE
Strip querystring from logout redirect URI comparison

### ISSUE THREAD

**Issue by ianalexr** [GluuFederation/oxAuth#498]
If there aren't any risks to allowing parameters to be passed through logout redirect URIs, it would be useful to have that ability. 

Currently login redirect URI validation strips querystring parameters prior to comparison, the same approach could be applied to the validation function for logout redirect URIs.

**Comment by nynymike** [comment]
I have to think about this one...

**Comment by nynymike** [comment]
As we are looking at OIDC logout conformance, now is a good time to consider this.

**Comment by yuriyz** [comment]
In 4.2 we compare `post_logout_redirect_uri` in the same way as `redirect_uri`. Thus parameters must be absent or match. Also validation can be skipped with `allowPostLogoutRedirectWithoutValidation` which is `false` by default.

**Comment by yuriyz** [comment]
https://github.com/GluuFederation/oxAuth/commit/94e2182ffe90b8c53200c7084435b72db8ac9139
