### ISSUE TITLE
Dynamic generation of acr_values_supported

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#5]
For OpenID Connect Discovery, oxAuth should return the acr_values_supported and am_values_supported according to the available authentication mechanisms. These values should correspond to the LDAP and custom authentication interception scripts that are configured by oxTrust for the domain.

**Comment by qbert2k** [comment]
The IOC 1.0 specs no longer publishes the AMR values in the configuration endpoint

**Comment by yurem** [comment]
Javier, can we close this issue?

**Comment by yuriyz** [comment]
I propose to close it when the tests will be passed on hudson ;)
