### ISSUE TITLE
Fix authorization test

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#50]
http://ox.gluu.org/hudson/job/oxAuth/297/testReport/junit/org.xdi.oxauth.ws.rs/AuthorizationCodeFlowHttpTest/authorizationCodeWithNotAllowedScopeFlow/

**Comment by nynymike** [comment]
Please proceed with a fix.

**Comment by yurem** [comment]
Fixed: https://github.com/GluuFederation/oxAuth/commit/f27a364d2d5767642e1bd32830980623990ebf95
