### ISSUE TITLE
need clear /end_session validation messages 

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#500]
oxauth has to provide specific log messages if request is rejected for any reason, otherwise it's is not clear from logs what is the exact reason of request reject.

Sample https://support.gluu.org/customization/3908/logout-error-after-adding-oxauth-customize-login-page/

**Comment by worm333** [comment]
Added more detailed messages in [this pull request](https://github.com/GluuFederation/oxAuth/pull/585).
