### ISSUE TITLE
Localization in 3.1.x

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#502]
The purpose of this issue is to discuss localization problems and implement solution which conforms oxAuth 3.1.0

@worm333 already done most part of this work.

Additionally we have next points:
1. Seam provided next bean:

    @In("org.jboss.seam.international.localeSelector")
    private LocaleSelector localeSelector;

It stored user locale in cookie. I think we need similar bean in oxAuth. We can use Seam 3 bean as reference for this.
In oxAuth code we commented out lines where we used it:
 - https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeAction.java#L112
- https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeAction.java#L172

2. Is it right that we shows dropdown on login page. According to authorizeAction we used OpenID connect request parameter "uiLocales" and tried to get locale from faces context. Now we have this:
![image](https://cloud.githubusercontent.com/assets/6104200/25176254/38e75422-2506-11e7-810d-db5168923fc7.png)

**Comment by worm333** [comment]
We definitely can use `uiLocales` to identify current locale, however as I can see it always null in my case (as admin). Do we actually need locale selector on login page? If yes, then of course it should be better styled and well placed. If no, then I'm not sure if we need to store locales in cookies, btw [LocaleSelector's](http://grepcode.com/file/repository.jboss.org/nexus/content/repositories/releases/org.jboss.seam/jboss-seam/2.1.2/org/jboss/seam/faces/Selector.java#Selector.isCookieEnabled%28%29) property `cookieEnabled` is false by default. @yurem what do you think ?

**Comment by yurem** [comment]
From my point of view RP is responsible which locale should we display in oxAuth.
I think we need to use authorization [uiLocales](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/authorize/ws/rs/AuthorizeRestWebService.java#L71) parameter and browser headers which it sends during request (if uiLocales not specified).

**Comment by worm333** [comment]
Created [pull request](https://github.com/GluuFederation/oxAuth/pull/522) in which I removed dropdown on login page and adjusted [LanguageBean](https://github.com/GluuFederation/oxAuth/blob/3a7bd9353347a63f80cd3c8d213a7c43097fa9ac/Server/src/main/java/org/xdi/oxauth/i18n/LanguageBean.java) in order to store locales in cookie.
Probably the same thing we should made also for oxTrust, @yurem what do you think ?
