### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by worm333** [GluuFederation/oxAuth#506]
### Translation guide.
oxAuth contains the following resource bundles: [messages_en.properties](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/resources/messages_en.properties), [messages_bg.properties](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/resources/messages_bg.properties), [messages_de.properties](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/resources/messages_de.properties), [messages_es.properties](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/resources/messages_es.properties), [messages_fr.properties](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/resources/messages_fr.properties), [messages_it.properties](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/resources/messages_it.properties), [messages_ru.properties](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/resources/messages_ru.properties), [messages_tr.properties](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/resources/messages_tr.properties)

These properties files store the translatable text of the messages to be displayed.
The default properties file, which is called [messages_en.properties](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/resources/messages_en.properties), contains the following lines:
```
.......
login.login=Login
login.register=Register
.......
```
Now that the messages are in a properties file, they can be translated into various languages. No changes to the source code are required. For example to use the French version of the oxAuth the [messages_fr.properties](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/resources/messages_fr.properties) should contains these lines:
```
.......
login.login=S'identifier
login.register=Registre
.......
```
Notice that the values to the right side of the equal sign have been translated but that the keys on the left side have not been changed. These keys must not change, because they will be referenced when oxAuth fetches the translated text.

To add translation for not yet supported languages, just create new properties file in [resource](https://github.com/GluuFederation/oxAuth/tree/master/Server/src/main/resources) folder and name it messages_[language_code].properties, then add language code as supported-locale to the [faces-config.xml](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/webapp/WEB-INF/faces-config.xml#L9).

**Comment by willow9886** [comment]
@worm333 can you remove the following authentication methods from all oxAuth files:

- oneid
- wikid
- inwebo 
- phone factor
- toopher

**Comment by worm333** [comment]
I just made pull request with required modifications, [take a look](https://github.com/GluuFederation/oxAuth/pull/507).

**Comment by willow9886** [comment]
@jschristie can we add instructions for oxTrust and oxAuth language translations in the `https://gluu.org/docs/ce/developer-guide/` ?

**Comment by willow9886** [comment]
added page here: https://github.com/GluuFederation/docs-ce-prod/blob/3.1.1/3.1.1/source/developer-guide/localization.md
