### ISSUE TITLE
Implement statistic gathering service

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#51]
There is missing part in oxAuth which gather statistic. For example oxAuth should count number of successful/failed authentications, active sessions, etc..

We need to implement serverStatistic service. It should have methods which allows to gather statistic for specified counter. Example:
serverStatistic.increaseCounter(counter_type_name, value);
serverStatistic.setCounter(counter_type_name, value);
...

In order to avoid performance decrease this service should persist statistic in LDAP asynchronously and withing hard-coded specified interval, example: 5 minutes.

The statistic model should be multi-level:

1) serverStatistic  should store data in:
    ou=statistic,o=[org_inum],o=gluu

2) Next level should be for specified server:
   ou=DNS_server_name,o=[org_inum],o=gluu

3) This is sample entry of next level (year+month+date):
   ou=YYYY-MM-DD,ou=DNS_server_name,o=[org_inum],o=gluu

4) uniqueIdentifier=XYZ,ou=YYYY-MM+DD,ou=DNS_server_name,o=[org_inum],o=gluu
    oxEventDate: 20150707165206.955Z
    oxEventApplicationType: oxAuth
    oxEventType: user_authentication_success
    oxEventCounterType: sum/average/etc..
    oxEventData: {counter_data in JSON format}

**Comment by yurem** [comment]
Also I think we should store this statistic in separate backend. What do you think? Is it needed?

**Comment by nynymike** [comment]
yes, but what backend? RDBMS?

**Comment by yurem** [comment]
LDAP

**Comment by nynymike** [comment]
Ok. That makes sense. So you can store it locally, or specify a remote server.

**Comment by rahatjaan** [comment]
Why should we have a separate backend to just store statistics? Why can't we store them in the same LDAP? I don't think it is going to add any noticeable overhead on performance.

**Comment by nynymike** [comment]
I think yura is just leaving the possibility open that there will be a different ldap server for stat collection. You wouldn't want reporting to effect the performance of authentications.

**Comment by yurem** [comment]
yes, correct. We will store it in LDAP, but in separate backend to avoid main DB performance decrease and DB grow up

**Comment by yurem** [comment]
I've commuted changes to git.

I've put some classes to oxCore to allow reuse in oxTrust and other applications.

oxAuth stores entries in DN like this:
uniqueIdentifier=id,ou=YYYY-MM,ou=application_type,ou=appliance_inum,ou=metric,ou=organization_name,o=gluu

Now this API supports 2 types of metrics: counter, timer.

**Comment by yurem** [comment]
These are sample entries:
version: 1

dn: ou=metric,o=@!6C2B.6E21.40DD.524A!0001!758E.0789,o=gluu
objectClass: top
objectClass: organizationalUnit
ou: metric

dn: ou=@!6C2B.6E21.40DD.524A!0002!577D.F64B,ou=metric,o=@!6C2B.6E21.40DD.524A!0001!758E.0789,o=gluu
objectClass: top
objectClass: organizationalUnit
ou: @!6C2B.6E21.40DD.524A!0002!577D.F64B

dn: ou=oxauth,ou=@!6C2B.6E21.40DD.524A!0002!577D.F64B,ou=metric,o=@!6C2B.6E21.40DD.524A!0001!758E.0789,o=gluu
objectClass: top
objectClass: organizationalUnit
ou: oxauth

dn: ou=201508,ou=oxauth,ou=@!6C2B.6E21.40DD.524A!0002!577D.F64B,ou=metric,o=@!6C2B.6E21.40DD.524A!0001!758E.0789,o=gluu
objectClass: top
objectClass: organizationalUnit
ou: 201508

dn: uniqueIdentifier=1438618472091,ou=201508,ou=oxauth,ou=@!6C2B.6E21.40DD.524A!0002!577D.F64B,ou=metric,o=@!6C2B.6E21.40DD.524A!0001!758E.0789,o=gluu
objectClass: top
objectClass: oxMetric
creationDate: 20150803161632.113Z
uniqueIdentifier: 1438618472091
id: 1438618472091
oxApplicationType: oxauth
oxdata: {"count":1}
oxEndDate: 20150803161632.112Z
oxMetricType: user_authentication_success
oxStartDate: 20150803161532.112Z

dn: uniqueIdentifier=1438618472092,ou=201508,ou=oxauth,ou=@!6C2B.6E21.40DD.524A!0002!577D.F64B,ou=metric,o=@!6C2B.6E21.40DD.524A!0001!758E.0789,o=gluu
objectClass: top
objectClass: oxMetric
creationDate: 20150803161632.113Z
uniqueIdentifier: 1438618472092
id: 1438618472092
oxApplicationType: oxauth
oxdata: {"count":1,"meanRate":0.3295530159671396,"oneMinuteRate":0.0,"fiveMinuteRate":0.0,"fifteenMinuteRate":0.0,"rateUnit":"second","min":50.834990999999995,"max":50.83499099
 9999995,"durationUnit":"milliseconds"}
oxEndDate: 20150803161632.112Z
oxMetricType: user_authentication_rate
oxStartDate: 20150803161532.112Z
