### ISSUE TITLE
UMA 1.0.1 (UMA 2 ? ) : Add validation for scope urls or otherwise support for plain scopes

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#512]
If send request to oxauth with resource set scope "view" then oxauth has to handle it as plain scope or otherwise send clear error message that only uri based scopes are supported.

https://support.gluu.org/customization/3744/uma-resource-set-gui-corrupts-the-scopes-field/

https://github.com/GluuFederation/oxTrust/issues/484

**Comment by nynymike** [comment]
This is not a bug. However plain scopes will be supported in Gluu Server 3.1.
