### ISSUE TITLE
Dynamic scope should contains list of allowed claims

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#519]
Javier: there is a way to request claims individually: http://openid.net/specs/openid-connect-core-1_0.html#IndividualClaimsRequests

According to this dynamic scopes should have list of scopes to allow request individual claims. Also we need to validate if requested claim belong to dynamic scope

**Comment by nynymike** [comment]
Yura, are you suggesting that dynamic scopes should be restricted to accessing certain claims?

**Comment by nynymike** [comment]
I'm moving this to 3.2 because I don't really understand the use case.

**Comment by nynymike** [comment]
I'm closing this issue. A dynamic scope should not have sub-claims.

**Comment by yurem** [comment]
Here is support ticket related to with this issue: https://support.gluu.org/access-management/5139/gluu-312-dynamic-scopes-missing-oxauthclaimss-values-on-scope/

We need to re-open issue again and move to 3.1.3 and try to fix solution for this.

**Comment by yurem** [comment]
I've alternative solution:
Instead of adding list of claims to dynamic scope we can make this more smarter.
We can add one additional method to dynamic scope script:
`List<String> getSupportedClaims()`
This will conform dynamic_scopes scopes idea. And not requires any GUI changes.

**Comment by yurem** [comment]
Implemented
