### ISSUE TITLE
Default CORS support in web.xml

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#523]
We should update the filter element in oxauth's web.xml to support CORS by default.

**Comment by qbert2k** [comment]
CORS must be configured in oxAuth Configuration (LDAP)

```
    "corsConfigurationFilters": [
        {
            "filterName": "CorsFilter",
            "corsAllowedOrigins": "*",
            "corsAllowedMethods": "GET,POST,HEAD,OPTIONS",
            "corsAllowedHeaders": "Origin,Authorization,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers",
            "corsExposedHeaders": "",
            "corsSupportCredentials": true,
            "corsLoggingEnabled": false,
            "corsPreflightMaxAge": 1800,
            "corsRequestDecorate": true
        }
    ]
```

**Comment by willow9886** [comment]
@qbert2k is this issue resolved?

**Comment by aliaksander-samuseu** [comment]
@nynymike @qbert2k 

CORS configuration is moved to LDAP in 3.0.2 and correct configuration is loaded by filter successfully now. Javier also updated default filter settings to include "Authorization" header ([commit](https://github.com/GluuFederation/community-edition-setup/commit/0fec4e9f3e708acc7346ad9199907e939852ad9c)). Default configuration is enough to support implicit flow out-of-the-box now, closing the issue.
