### ISSUE TITLE
Enforce Grant Type Client Restrictions

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#525]
If a client is not authorized for a certain grant type, it should not be able to request a token.

**Comment by aliaksander-samuseu** [comment]
@qbert2k @nynymike 

I've tested flow using refresh tokens recently, and I couldn't understand current purpose of "Refresh token" grant which can be assigned to client in web UI (see picture below):
![refresh_token_grant](https://cloud.githubusercontent.com/assets/11802046/26808083/28d3dc7c-4a63-11e7-8ce8-3aaa1eb2feb3.png)

Regardless of whether it was assigned to a particular client or not, refresh tokens still were issued for it, and could be used to renew access tokens. Either it's a bug, of purpose of this control needs to be clarified and documented better.

**Comment by yurem** [comment]
@qbert2k I think we can deprecated solution which we implemented for: https://github.com/GluuFederation/oxTrust/issues/523
Am I right?
