### ISSUE TITLE
Security error thrown using implicit flow when request the userinfo endpoint

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#529]
Security error thrown using implicit flow when request the userinfo endpoint

When following the implicit flow using the javascript client described here: https://gluu.org/docs/ce/integration/oauth-js-implicit/, the web browser throws a security error saying "the authorization is not allowed by Access-Control-Allow-Headers in preflight response" once the login-callback page is shown (right after giving user/pwd in the login form of Gluu server)

In version 3.0.1 the following CORS configs were tried unsuccessfully in web.xml of oxauth.war: see attached TXT file

In version 3.1.0, corsAllowedHeaders were set to "Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers, authorization", using web UI, with the same results.

Also attached there is a depiction of the error in Opera's developer console.
[528_xml.txt](https://github.com/GluuFederation/oxAuth/files/987263/528_xml.txt)
![getuserinfo_error_op36](https://cloud.githubusercontent.com/assets/5444180/25860812/5c3e4136-34a8-11e7-8936-46db5a22b03b.png)

**Comment by qbert2k** [comment]
Fix in version_3.0.2 and master branches,

Also there is a pull request at: https://github.com/GluuFederation/openid-implicit-client/pull/16
