### ISSUE TITLE
refresh_token must returns a jwt token

### ISSUE THREAD

**Issue by jbucar** [GluuFederation/oxAuth#530]
when try to refresh a jwt token with a valid refresh_token, it must return id_token attribute.

how test:
RESULT=`curl -q -s -X POST -H "Authorization: Basic ${AUTH}" -d "refresh_token=${REFRESH_TOKEN}&grant_type=refresh_token" ${BASE_URL}`

In the source code, 
Server/src/main/java/org/xdi/oxauth/token/ws/rs/TokenRestWebServiceImpl.java
we need add something like it:
    IdToken idToken = null;
                        if (authorizationCodeGrant.getScopes().contains("openid")) {
                            String nonce = authorizationCodeGrant.getNonce();
                            boolean includeIdTokenClaims = Boolean.TRUE.equals(
                            		appConfiguration.getLegacyIdTokenClaims());
                            idToken = authorizationCodeGrant.createIdToken(
                                    nonce, null, accToken, authorizationCodeGrant, includeIdTokenClaims);
                        }

**Comment by nynymike** [comment]
The refresh token is used to obtain a new access token. The [OpenID refresh response](http://openid.net/specs/openid-connect-core-1_0.html#RefreshTokenResponse) does not specify that it "MUST return id_token". Can you be more specific about what requirement you are referencing?

**Comment by jbucar** [comment]
Sorry, we need jwt for direct authorization checks against an access token.
Is that posible? We are using "Resource owner password credentials flow".
We check that gluu returns only jwt on id_token and not on access_token.
Can it be changed?
Thanks in advance
Javier

**Comment by nynymike** [comment]
1. You should not use RO PW cred grant 99.9% of the time.
2. You will never get an id_token via RO PW cred grant, because it is only defined in OAuth2, not OpenID Connect.
3. Requests for support are not handled through github, please register on https://support.gluu.org and post your question there with more details like what kind of client are you using, and we may be able to suggest a more secure design.
