### ISSUE TITLE
UMA 2 : Implement support for client "pushed claims" and PCT

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#533]
When a client requests an RPT, it may present an `id_token` from an OpenID Provider or a PCT token.  For this version, we should only support locally issued id_tokens (which are easier to validate). The claims pushed should be stored, and accessible via a PCT token. 

We need to add property `pct-expiration-time` in oxAuth JSON properties?).  Note SAML assertion will not be supported in version 3.1

**Comment by yuriyz** [comment]
done in master branch
