### ISSUE TITLE
Provide customization of front-channel generated html from /end_session 

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#535]
Initiated by
https://support.gluu.org/single-sign-on/4060/single-logout-is-using-hard-coded-html/
https://support.gluu.org/customization/6606/customization-of-the-logout-process/

**Comment by nynymike** [comment]
Related to https://github.com/GluuFederation/oxAuth/issues/1113 ?

**Comment by yuriyz** [comment]
Duplicate of https://github.com/GluuFederation/oxAuth/issues/1113
