### ISSUE TITLE
oxAuth filters configuration don't reload after changing settings

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#54]
CE 2.3.2 after changing oxauth-config.xml reloads configuration. Hence we can change next properties on the fly:
`
    <auth-filters-enabled>false</auth-filters-enabled>
    <client-auth-filters-enabled>false</client-auth-filters-enabled>
`
to
`
    <auth-filters-enabled>true</auth-filters-enabled>
    <client-auth-filters-enabled>true</client-auth-filters-enabled>
`
As result oxAuth reloads configuration but these filters still not work until tomcat restart.

It's bug.

**Comment by willow9886** [comment]
@yurem if this still applies since we've moved to LDAP config, go ahead and reopen the issue.

**Comment by nynymike** [comment]
Is this still an issue? If we change the JSON configuration, does it get effected without a restart?

**Comment by willow9886** [comment]
@yurem @qbert2k can either of you comment on this? Should we close this ticket?

**Comment by nynymike** [comment]
This file doesn't even exist anymore.
