### ISSUE TITLE
Validation URL incorrect in access token

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxAuth#547]
See: https://support.gluu.org/authentication/4113/validation-url-incorrect-in-access-token/

**Comment by willow9886** [comment]
Also need a patch for this for 2.4.4 sp2 and 3.0.1.

**Comment by qbert2k** [comment]
Fixed in branch version_2.4.4_sp2
Fixed in branch version_2.4.4_sp4
Fixed in branch version_3.0.2

Note: validate_token_endpoint was removed in branch version_3.1.0
https://github.com/GluuFederation/oxAuth/issues/510
