### ISSUE TITLE
oxAuth should check environment variables for ox-ldap.properties

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#550]
It would be good if oxAuth could check the environment variables first for oxLDAP.properties and then look to the file system.

**Comment by nynymike** [comment]
needed for container support

**Comment by yurem** [comment]
Merged from oxTrust: https://github.com/GluuFederation/oxAuth/commit/852fe8a5ce06861e856e5edac70e7f8683f2a992
