### ISSUE TITLE
Improve authorization display if client name missing

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxAuth#553]
At OxAuth > Request for Permission window , instead of seeing client name, I am getting 
#{client.getClientName()} is requesting permission to do the following:

**Comment by nynymike** [comment]
Is this for version 3.0 or 3.1 ?

**Comment by centroxy** [comment]
This is for 3.1

**Comment by nynymike** [comment]
Is this because the client name is not present?

**Comment by nynymike** [comment]
If client name is blank, cliend_id should be displayed.
