### ISSUE TITLE
UMA 2 : Move Id Generation REST Service protecttion from UMA 1.0.1 to UMA 2

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#555]
Id Generation REST Service protected by UMA 1.0.1. 

@nynymike do we still need this endpoint ? If yes then I will move protection from UMA 1.0.1 to UMA 2.

**Comment by nynymike** [comment]
No, we have a ticket open to remove the endpoint.

**Comment by yuriyz** [comment]
ok, I will remove it then.

**Comment by yuriyz** [comment]
we don't need it, Id Generation Endpoint is removed, see #484
