### ISSUE TITLE
Allow user to select authentication method from list of requested acr_values

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#56]
It's possible to pass requested acr_values to oxAuth. But oxAuth selects only one method. We need to show intermediary form to allow user select one of the methods specified in acr_values

**Comment by nynymike** [comment]
I would think that this is the responsibility of the client. If the client only passes one acr, oxauth won't have to decide which one to use.

**Comment by willow9886** [comment]
We haven't heard any requests for this feature. Going to close until we see greater demand.
