### ISSUE TITLE
utf-8 problem http response entity

### ISSUE THREAD

**Issue by sakitA** [GluuFederation/oxAuth#563]
Hi. In `HttpService` class you used the below code for converting byte array to String
```
public String convertEntityToString(byte[] responseBytes) {
	if (responseBytes == null) {
		return null;
	}

	return new String(responseBytes);
}
```
In this case if response entity contains non unicode character, this code snippet convert byte array is not the same as original one. The correct way for converting, adding encoding method as parameter. 
```
public String convertEntityToString(byte[] responseBytes) {
	if (responseBytes == null) {
		return null;
	}

	return new String(responseBytes, "UTF8");
}
```

Or more generic way
```
public String convertEntityToString(byte[] responseBytes, String encodeName) {
	if (responseBytes == null) {
		return null;
	}
        
        if(encodeName==null || encodeName.isEmpty())
                return new String(responseBytes)
	else
                return new String(responseBytes, encodeName);
}
```

**Comment by worm333** [comment]
Fixed in [this commit](https://github.com/GluuFederation/oxAuth/commit/c3e05f8017549711d21b19c27abafc6902974315).
