### ISSUE TITLE
Enabling asimba custom script results in error 

### ISSUE THREAD

**Issue by zamilskhan** [GluuFederation/oxAuth#567]
Steps to reproduce:
1. Install Gluu Server 3.0.2 with asimba
2. Enable Asimba custom script
3. Check `oxauth-script.log`

The full stack trace is available @ https://pastebin.com/392AJUGj

**Comment by aliaksander-samuseu** [comment]
@yurem @zamilskhan 

It probably has something to do with the fact we still use old set of properties for the script. For example, **"saml_idp_attributes_list"** and **"saml_local_attributes_list"** were substituted by a single mapping attribute long ago etc.
![asimba_script](https://user-images.githubusercontent.com/11802046/27509357-86916150-5903-11e7-9cfb-522c4f8d54ac.jpg)

**Comment by yurem** [comment]
It's old issue and we reviewed this issue during migration to 3.1.0 few times. Can you retest it in RC3 and re-open if needed.
