### ISSUE TITLE
Libs from /opt/gluu/jetty/oxauth/lib/ext can't access libs from oxauth.war/WEB-INF/libs

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#571]
It's opposite to tomcat behavior. We need to make small research to understand if jetty supports only this method.

Here is problem.
1) We have custom script: https://github.com/GluuFederation/oxAuth/blob/master/Server/integrations/twilio_sms/twilio2FA.py
2) It requires twilio SDK library.
3) After adding twilio-java-sdk-6.3.0.jar and commons-lang3-3.6.jar to /opt/gluu/jetty/oxauth/lib/ext  we will get error about missing httpclient libraries..
4) It's not clear situation because we have httpclient libs in oxauth.war
5) In order to fix this script error we have to copy httpcore-4.3.3.jar and httpclient-4.3.6.jar from oxauth.war to /opt/gluu/jetty/oxauth/lib/ext

Is it possible to get rid of duplicity in step 5?

**Comment by worm333** [comment]
I looked into `twilio-java-sdk-6.3.0` pom.xml and found out that it requires some dependencies which might conflict with those from oxauth.war. Here is the list of them:

  oxauth           |            twilio             
-------------------|:---------------------------
httpclient-4.2.6     | httpclient-4.5.3
httpcore-4.2.5       | httpcore-4.4.6
json-simple-1.1      | json-simple-1.1.1
jackson-core-asl-1.9.3|jackson-core-asl-1.9.11
jackson-mapper-asl-1.9.3|jackson-mapper-asl-1.9.11

At first glance it seems that different versions can lead to such behavior, however I'm not sure about this.

@yurem what do you think ?

**Comment by yurem** [comment]
I think twilio can work with oxauth libs versions too. These all have same major version number and have same API.

Honestly speaking I like current behavior because in this case we protect oxAuth from overriding libs. But from another side it's problem because it introduce duplicity.

I offer to do:
1) Keep it as us.
2) Add note to documentation that customers must put library and all dependencies in ./ext
3) Do small research to understand if it's configurable behavior.  It's needed for case when we need to use our library which depends on same libraries.

**Comment by yurem** [comment]
We put twilio-sdk, httpcore, httpclient, commons-lang3 into ./ext

In this case we get conflict between ./ext libs and oxauth.war/WEB-INF/lib
But we get strange error:
```
java.lang.ClassCastException: org.apache.http.message.BasicNameValuePair cannot be cast to org.apache.http.NameValuePair
        at org.apache.http.client.utils.URLEncodedUtils.format(URLEncodedUtils.java:218)
        at org.apache.http.client.entity.UrlEncodedFormEntity.<init>(UrlEncodedFormEntity.java:61)
        at com.twilio.sdk.TwilioClient.buildEntityBody(TwilioClient.java:282)
        at com.twilio.sdk.TwilioClient.generatePostRequest(TwilioClient.java:230)
        at com.twilio.sdk.TwilioClient.buildMethod(TwilioClient.java:197)
        at com.twilio.sdk.TwilioClient.setupRequest(TwilioClient.java:449)
        at com.twilio.sdk.TwilioClient.request(TwilioClient.java:347)
        at com.twilio.sdk.TwilioClient.safeRequest(TwilioClient.java:495)
        at com.twilio.sdk.resource.list.MessageList.create(MessageList.java:70)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

This shows that we have issue with ./ext libs which not allows us to add custom libs with dependencies.

**Comment by yurem** [comment]
Probably it's jython class loader issue.

- We need to add libs to ./ext to allow them to use in jython script.
- But when jython calls java methods from script we get conflict between ./ext and oxauth.war/WEB-INF/lib libs.

**Comment by worm333** [comment]
Most likely we can avoid conflicts between libs in `lib/ext` and libs from `oxauth.war/WEB-INF/lib` by telling [WebAppClassLoader](http://archive.eclipse.org/jetty/8.0.0.v20110901/apidocs/org/eclipse/jetty/webapp/WebAppClassLoader.html) which classes could not be replaced by the web application / could not be exposed to web application.

For example if we want to expose `org.apache.http` package from `lib/ext` and at the same time to prohibit overriding it from oxauth.war/WEB-INF/lib, then `jetty-web.xml` could be like this:

```
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
 <Call name="addSystemClass">
   <Arg>org.apache.http.</Arg>
 </Call>
 <Call name="addServerClass">
   <Arg>-org.apache.http.</Arg>
 </Call>
</Configure>
```

**Comment by worm333** [comment]
I've played with [twilio2FA.py](https://github.com/GluuFederation/oxAuth/blob/master/Server/integrations/twilio_sms/twilio2FA.py) script and here is workaround how to launch it avoiding exceptions:

1. Add all required dependencies for the twilio sdk to the `/opt/gluu/jetty/oxauth/lib/ext`: 
    - commons-codec-1.9.jar  
    - commons-logging-1.2.jar
    - httpcore-4.4.6.jar
    - jackson-mapper-asl-1.9.3.jar
    - twilio-java-sdk-6.3.0.jar
    - commons-lang3-3.0.jar
    - httpclient-4.5.3.jar
    - jackson-core-asl-1.9.3.jar
    - json-simple-1.1.jar

2. Add `org.apache.http.NameValuePair` class as a "system class" in [jetty-web.xml](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/webapp-jetty/WEB-INF/jetty-web.xml):
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Mort Bay Consulting//DTD Configure//EN"
   "http://www.eclipse.org/jetty/configure.dtd">
<Configure class="org.eclipse.jetty.webapp.WebAppContext">
	<Call name="prependServerClass">
		<Arg>-org.eclipse.jetty.</Arg>
	</Call>
	<Call name="addSystemClass">
		<Arg>org.apache.http.NameValuePair</Arg>
	</Call>
</Configure>
```
3. Restart oxauth: `service oxauth restart`

**Comment by nynymike** [comment]
Should this be a default for Gluu setup? If so, do we need to add this fixed template to community-edition-setup?

**Comment by yurem** [comment]
For jetty docs:
`
Classes contained within WEB-INF/lib or WEB-INF/classes have priority over classes on the parent classloader. This is the opposite of the normal behaviour of a Java 2 classloader.
`

Jetty loads libs from ./ext before loading webapp. As result these are system classes from webapp perspective.
As result we have to use:
```
	<Call name="addSystemClass">
		<Arg>org.apache.http.NameValuePair</Arg>
	</Call>
```
To allow access twilio external library from webapp context.

**Comment by yurem** [comment]
I've found another hack which also works but don't require configuration files update:
https://github.com/GluuFederation/oxCore/blob/master/oxService/src/main/java/org/xdi/service/custom/lib/CustomLibrariesLoader.java#L41

This service adds all custom libs from ./custom/libs at application startup.

There are other solution too:
- Extend jetty custom class loader. There are ideas [here](httte p://blog.markfeeney.com/2010/09/using-custom-webappclassloader-in-jetty.html) or [here](https://stackoverflow.com/questions/39508646/how-to-load-jars-dynamically-from-different-locations-into-current-class-loader).
- Write AppLifeCycle.Binding. Here is [example](https://stackoverflow.com/questions/26128278/managing-many-jars-via-webappcontext-extraclasspath)

We can create small library with custom class loader or AppLifeCycle.Binding and put it into ./ext to customize application classpath.

But for 3.1.0 I offer to use CustomLibrariesLoader because this hack works fine in jetty 9.3 and don't requires configuration changes. What do you think?
