### ISSUE TITLE
We need to use oxAuth functionality to simplify acr_router script

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#572]
This script we can use as sample in other scenarios where we need to redirect to other acr if needed:
https://github.com/GluuFederation/oxAuth/blob/master/Server/integrations/acr_router/acr_routerauthenticator.py

But it not uses oxAuth functionality which we added for this case. Instead of hacking internal session state it should just implement 2 methods:
```
    def isValidAuthenticationMethod(self, usageType, configurationAttributes):
        return False

    def getAlternativeAuthenticationMethod(self, usageType, configurationAttributes):
        # Put your custom logic to determine acr here...

        # Return new acr_values or None if the current acr is right
        return None
```

In this script first method return always 'False' which tell oxAuth to use getAlternativeAuthenticationMethod to get new authentication method name.

**Comment by yurem** [comment]
@aliaksander-samuseu

**Comment by nynymike** [comment]
Good idea. We can add some business logic into getAlternativeAuthenticationMethod

**Comment by yurem** [comment]
Closing it
