### ISSUE TITLE
No accept header allowed in UserInfo request (3.0.2 CE)

### ISSUE THREAD

**Issue by ghsnd** [GluuFederation/oxAuth#580]
I use the Spring Security library in combination with Gluu Server 3.0.2. When requesting user info, the library adds an `accept` header with value `application/json` to the UserInfo endpoint. This is not accepted by the Gluu Server. 

Example request, using curl:

```
curl -v -H 'Accept: application/json' https://some_host/oxauth/seam/resource/restv1/oxauth/userinfo?access_token=13d3dead-52e6-4141-bc83-48cd3adf2dd9

> GET /oxauth/seam/resource/restv1/oxauth/userinfo?access_token=13d3dead-52e6-4141-bc83-48cd3adf2dd9 HTTP/1.1
> Host: some_host
> User-Agent: curl/7.47.0
> Accept: application/json
> 
< HTTP/1.1 406 No match for accept header
< Server: Jetty(9.3.15.v20161220)
< X-Xss-Protection: 1; mode=block
...
```

It works when I remove the accept header. Shouldn't the endpoint allow `Accept: application/json` since the returned content is JSON?

**Comment by willow9886** [comment]
This needs to be moved to our support portal, https://support.gluu.org. We only use github to track bugs and feature enhancements. In addition, there are existing tickets on support about spring security. 

Thanks.
