### ISSUE TITLE
setAmrClaim() in IdTokenFactory.java only allows scripts with usage type of "Both methods", instead of allowing scripts of any type

### ISSUE THREAD

**Issue by anise-g** [GluuFederation/oxAuth#582]
After a few hours of headache, I think I found some code with unintentional behavior.

While trying to use getAuthenticationMethodClaims() to pass back some amr values in id tokens, I realized why my custom authentication script was returning an empty JSON for the amr field ("amr":"[]").

In IdTokenFactory.java, the following line is in setAmrClaim:

```
CustomScriptConfiguration script = externalAuthenticationService.getCustomScriptConfiguration(
    AuthenticationScriptUsageType.BOTH, acrValues);
```

Due to the usage of AuthenticationScriptUsageType.BOTH, "script" is set to null unless the usage type of your custom authentication script is set to "Both methods". I think the intention was to check for scripts of any usage type (Web, Native, or Both methods) corresponding to "acrValues", but the current code only accepts scripts that are specifically set to "Both methods". After changing the usage type of my script from "Web" to "Both methods", everything now works as intended (properly getting the amr field in id tokens), but this shouldn't be necessary (future users will run into the same issue if using "Web" or "Native" usage types).

**Comment by willow9886** [comment]
Can you post this as an issue on https://support.gluu.org ?

It is easier for our whole team if issues are reported and addressed on our
support portal.

Thank you,
Will

**Comment by anise-g** [comment]
Ok, I went ahead and posted this under Authentication on the support portal.

**Comment by willow9886** [comment]
Just saw it come through. Thank you! We will look into it asap.

**Comment by nynymike** [comment]
I agree this is a bug...
