### ISSUE TITLE
Fix DisplaysPolicyUriInLoginPage test

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#583]
DisplaysPolicyUriInLoginPage test fails because it can't find policy uri which is removed in this commit https://github.com/GluuFederation/oxAuth/commit/77453ed2a75d3d657a59499311041a1d50d6c757

**Comment by shekhar16** [comment]
the privacy url is added in login.xhtml page.

	<div class="foot_bor">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
				  <div class="padding_spc">
					<p><h:outputText value="#{msgs['common.gluuInc']}" />  | <a target="_blank" href="https://github.com/GluuFederation/oxAuth/blob/master/LICENSE"><h:outputText value="#{msgs['common.caution']}" escape="false" /></a>
					<h:panelGroup rendered='#{!empty client.policyUri}'>
					| <a target="_blank" href="#{client.policyUri}"><h:outputText value="#{msgs['common.privacyPolicy']}" escape="false" /></a>
					</h:panelGroup>
					<h:panelGroup rendered='#{!empty client.tosUri}'>
					| <a target="_blank" href="#{client.tosUri}"><h:outputText value="#{msgs['common.termsOfService']}" escape="false" /></a>
					</h:panelGroup>
					</p>
					</div>
				</div>
			</div>
		</div>
	</div>

**Comment by shekhar16** [comment]
https://github.com/GluuFederation/oxTrust/issues/596
