### ISSUE TITLE
Create oxAuth property to suppress session_state response param   

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#591]
The Session Mgt spec specifies that session_state be returned in the authentication response:
 http://openid.net/specs/openid-connect-session-1_0.html#CreatingUpdatingSessions

Applications using front channel logout don't need this information, and it would be better to not include it in the response. 

We should create an oxAuth config param:

```
return_session_state : False
```

Default value should be `False`, because very few implementations use the javascript logout mechanism.

**Comment by yuriyz** [comment]
we don't need it if we split session_id and session_state https://github.com/GluuFederation/oxAuth/issues/592

**Comment by nynymike** [comment]
Closed because https://github.com/GluuFederation/oxAuth/issues/592 will solve.
