### ISSUE TITLE
Add real session state support

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#592]
We have to provide "session state" support as described in specification http://openid.net/specs/openid-connect-session-1_0.html

In the past we had session_id which represents session for SSO. Instead of adding session_state support session_id was renamed to session_state which leads to misunderstanding and instead of two entities we have only one. It was done here:
https://github.com/GluuFederation/oxAuth/issues/103

1. we have to keep only one session_id cookie which MUST be HttpOnly=true (JS must not read it)
2. session_id has session lifetime, means value is not changed accross multiple requests from different clients (apps)
3. session_state has request lifetime. As said in specification “the value of the session state returned SHOULD vary with each request”. The value of session_state MUST be returned in Response from request. session_id must never be returned explicitly to RP (in response).
4. session_id and session_state values MUST NEVER match.
5. session_state must rely on client_id and origin.
6. we have to revisit opiframe page.
7. we need it in 3.1, 3.0 (latest) and 2.4.4 (sp4) versions

**Comment by qbert2k** [comment]
Fixed in 3.1 and 3.0
