### ISSUE TITLE
OIDC returning arrays incorrectly

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#600]
Corresponding ticket: https://support.gluu.org/single-sign-on/4368/oidc-returning-arrays-incorrectly/

Need evaluation and fix if it's a bug.

**Comment by nynymike** [comment]
Yes, this looks like a bug.

**Comment by qbert2k** [comment]
Fixed in commit: https://github.com/GluuFederation/oxAuth/commit/52a082483bf3e845e7d06fc17d7aebd8b945c380
