### ISSUE TITLE
Update client resets grant-types if it has no value

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxAuth#602]
Currently client application has to pass grant-types to Update client method. If not passed it resets  the value from the value provided during "setup client" to default value.

But in update client method, application should send those values user want to update

**Comment by willow9886** [comment]
@centroxy what do you mean by "update client method" ? Is this when you call the client registration api or via the oxTrust GUI?

**Comment by centroxy** [comment]
@willow9886  I am using update-site-registration method (oxd server) . This command should  only update the fields I want to update using update-site-registration . It should not reset other fields like **grant-types**

**Comment by yuriyz** [comment]
grant_types are changed based on response_types. It is coded by Javier in client registration service. I guess the way it works now is consistent because we reflect valid grant type based on response type. I think Javier can give more thoughts here.

**Comment by nynymike** [comment]
I agree with Jajati.

**Comment by qbert2k** [comment]
Hello @centroxy,  depending on the registration params: response_types and grant_types, oxAuth will automatically add the corresponding params to make consistent as @yuriyz  said.

For example:
If you send response_types=code then the param grant_types=authorization_code will be added automatically.
If you send response_types=code+id_token then the param grant_types=authorization_code+ implicit will be added automatically.

http://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata
