### ISSUE TITLE
Add attribute to Disable Client

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#612]
We can add the `status` attribute to the client objectclass. If set to "disabled", calls to `/authorize` should display an error message ("Sorry, something went wrong: invalid client") and the `/token` endpoints should fail.

**Comment by nynymike** [comment]
Closing issue: try workaround of removing grant types. If this doesn't work, re-open this.

**Comment by worm333** [comment]
Created `disabled` field in oxAuthClient. By default value of this field is set to `false`. When client is disabled, calls to `/authorize` and `/token` endpoints leads to 403 error: "The client is disabled and can't request an access token using this method".
The following pull requests are related with this issue:  [719](https://github.com/GluuFederation/oxTrust/pull/719), [337](https://github.com/GluuFederation/community-edition-setup/pull/337), [643](https://github.com/GluuFederation/oxAuth/pull/643).
