### ISSUE TITLE
Not able to register profile, email scope

### ISSUE THREAD

**Issue by ldeveloperl1985** [GluuFederation/oxAuth#624]
I passed scopes profile, email in dynamic client registration but it only registered with 3 scopes as in the below picture. So that I am not able to get user_info properly.

https://prnt.sc/gb40jx

**Comment by ldeveloperl1985** [comment]
As per discussion in QA team, we need to change the name, probably better name should be used there "Default" -> "Allow for dynamic registration"

**Comment by yuriyz** [comment]
@ldeveloper1985 please open issue for oxTrust since it's not oxauth issue.
