### ISSUE TITLE
Review oxAuth jar dependencies 

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#63]
In current war there are a lot of new jars. Example: json4s, swagger, etc..
Are they really need in final war?

**Comment by yuriyz** [comment]
swagger indeed is not needed, it must be excluded in final war.

**Comment by willow9886** [comment]
@yurem can you provide a list of all the jar files so we can eliminate the unnecessary ones?

**Comment by yurem** [comment]
Fixed
