### ISSUE TITLE
Create reusable login template

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#637]
We need to create one or two reusable templates to get rid of duplicity in custom script login forms. Now during changing login.xhml we not update custom login pages. As result we get pages like this:
![default](https://user-images.githubusercontent.com/6104200/29912950-35f53cee-8e3c-11e7-917b-520ffabdc2ac.png)

**Comment by willow9886** [comment]
@arvindsinghtomar do I need to provide a design and html/css for this login template?

**Comment by arvindsinghtomar** [comment]
@willow9886 can you please provide design and html/css for this login template?

**Comment by willow9886** [comment]
@arvindsinghtomar please ping me on skype to discuss

**Comment by arvindsinghtomar** [comment]
@willow9886 
ok

**Comment by yurem** [comment]
We have login/extended and simple templates in 4.x
