### ISSUE TITLE
Allow configuration of JWT for access token on a per client basis

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#638]
It would be nice if oxAuth could be configured to return a signed JWT access token from the `/token` endpoint that has the following claims (per https://tools.ietf.org/html/rfc7662#section-2.2)

1. `aud`
2. `sub`
3. `iat`
4. `scope`
5. `iss`
6. `exp`

We also need another client configuration parameter for `access_token_signing_alg`

Note this token should not be prefixed (see https://github.com/GluuFederation/oxAuth/issues/804)

**Comment by yuriyz** [comment]
Client have:
- `access_token_as_jwt` - boolean value to indicate whether return access_token as jwt or not;
- `access_token_signing_alg` - signing algorithm used to sign jwt.

**Comment by yuriyz** [comment]
JWT access_token are returned as bearer thus introspection `token_type=bearer`.
`Authorization: Bearer eyJhbGci...<snip>...yu5CSpyHI`. It will make client code consume jwt tokens as bearer and at the same time RP that cares about JWT can just parse it.

**Comment by yuriyz** [comment]
done in 3.1.4 and master
