### ISSUE TITLE
Authentication against LDAP backend fails.

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#64]
Environment:
Ubuntu x64 14.04.1 on VmWare Workstation 11.1.0 build-2496824, Gluu CE 2.3.3-1

Preconditions:
1) LDAP server configured so that it capable of playing ar role of backend directory with a test user account existing in it; the ones provided by MS AD is preferable, but most likely it can be reproduced for any backend directory.
2) Cache Refresh is configured and fully functional so that account mentioned in step one is successfully replicated to Gluu's internal LDAP db and can be used to log in.
3) Fresh installation of Gluu server

Steps to reproduce:
1) Login into oxTrust web UI using default admin account.
2) Move to the "Configuration -> Manage Authentication" page and configure oxAuth so it would use backend LDAP server for authentication; as you will most likely lose ability to log in to web UI after that, either make a dump of oxIDPAuthentication attribute of the inum=@!your_appliance_ID,ou=appliances,o=gluu node, or make a snapshot if you run it in vm possessing such capability.
3) Log out, then try to log in to web UI with some user account stored in backeend directory.

Result: it seems almost like login sequence is interrupted before it can be completed; user is taken to the home page, but regardless of that he can't access any protected functionality and even login page itself (until cookies storage is flushed); "Login failed" message is displayed; it seems it tries to search backend as it would have been its own internal LDAP db; moreover, authentication is actually happens at the very beginning of the log in session - a correct sequence of "LDAP request for subtree -> LDAP request for user object -> LDAP bind request with user's creds" happens and its result is success; but later on a second (and invalid) authentication attempt occurs (the one that results in invalid LDAP request), and it fails this time. See attached screenshot.

Here are log fragment and wireshark capture (limited to LDAP protocol conversations) created during failed login session:
[wrapper.log](https://drive.google.com/file/d/0B6Mqu38YJ8RcZkZoeEtULWpRRU0/view?usp=sharing)
[wireshark's .pcapng](https://drive.google.com/file/d/0B6Mqu38YJ8RcbHVKLVdDWEFCblU/view?usp=sharing)

**Comment by yurem** [comment]
Can you try to deploy this http://ox.gluu.org/maven/org/xdi/oxtrust-server/3.0.2-SNAPSHOT/oxtrust-server-3.0.2-SNAPSHOT.war identity war and re-check it.

**Comment by aliaksander-samuseu** [comment]
Uh-oh, that new UI's design is gorgeous, can't wait to start using it :)

**Comment by aliaksander-samuseu** [comment]
Btw, wasn't it a mistake that oxtrust.war was linked? Shouldn't it be oxauth.war?

**Comment by mzico** [comment]
@yurem: I just tried 3.0.2-SNAPSHOT of oxtrust.war. Seems like error has changed. Error which Alex reported ( regarding LDAP ) is not coming now but.. there is new error in oxtrust.log. We are getting below stack trace && the attached screenshot image where we are landing. 

Stack trace: http://pastebin.com/Gb966bbW
  
![ce234oxtrust302snapshot](https://cloud.githubusercontent.com/assets/7156097/10219954/f2596146-6808-11e5-8634-d95c3625074a.png)

**Comment by aliaksander-samuseu** [comment]
Hmm.. I pretty sure in my logs it appeared very similar to what I saw there before. Like, first attempt - successful, 2nd attempt - it tries to search one LDAP database why using the filter from other one, and fails. I'm not sure whether or not there was this error. May be I should try to install it again, too.

**Comment by aliaksander-samuseu** [comment]
Have you checked the oxauth log? I think that's where these strange LDAP searches are being reported.

**Comment by yurem** [comment]
It's different issue according to log which you put to pastebin. Now you can log in but this user don't have permissions to open home page:
org.jboss.seam.security.AuthorizationException: Authorization check failed for expression [#{s:hasPermission('configuration', 'access')}]
        at org.jboss.seam.security.Identity.checkRestriction(Identity.java:222)

According to: https://github.com/GluuFederation/oxTrust/blob/master/server/src/main/webapp/home.page.xml
we uses next instruction to limit access to this page:
restrict>#{s:hasPermission('configuration', 'access')}</restrict>

In security.drl this instrcution have next definition:
<code>
rule AccessConfiguration
  no-loop
  activation-group "permissions"
when
  check: PermissionCheck(target == "configuration", action == "access", granted == false)
  Role((name == "owner") || (name == "manager"))
then
  check.grant();
end
</code>

Hence only admin is able to access home page. Its' bug! We need to close this issue and open new one about problem in new GUI.

**Comment by yurem** [comment]
Also we need to update oxTrust TODO lsit on trello.

**Comment by mzico** [comment]
@yurem @aliaksander-samuseu: Added test user in oxTrust Gluu manager group + '3.0.2-SNAPSHOT oxtrust.war'  resolved the issue. Going to open a Trello card on 'permission issue' for generic user. 

Closing this ticket.
