### ISSUE TITLE
Support Custom Params

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#647]
http://openid.net/specs/openid-connect-core-1_0.html#AuthRequest

```
Other parameters MAY be sent.
```

Using the `state` param is useful where the client can't use additional params (like AppAuth). But sending additional params is cleaner in many cases.

**Comment by rajnikantsh** [comment]
code comitted. created pull request https://github.com/GluuFederation/oxAuth/pull/656

**Comment by nynymike** [comment]
I don't know why RK messed with the state. If a client wants to encode a value in the state, that's a different solution. In my request, I was saying that in the `/authorize` request, a client can add params not specified in the openid connect standard. for example:
```
/authorize?client_id=1111@redirect_uri=...&unicorn=pink
```
Now OpenID Connect doesn't define the `unicorn` parameter, so it's ok.

**Comment by nynymike** [comment]
Javier, I'm assigning this to you only.

**Comment by yurem** [comment]
To make this part more controlled we can add new configuration list property to specify list of accepted custom parameters like `unicorn`

**Comment by qbert2k** [comment]
1. There is a new entry in oxAuth configuration to add custom parameters, for example:
```
    "authorizationRequestCustomAllowedParameters" : [
        "customParam1",
        "customParam2",
        "customParam3"
    ]
```

2 . There is a test showing how to send custom param at org.xdi.oxauth.ws.rs.AuthorizationSupportCustomParams
```
        authorizationRequest.addCustomParameter("customParam1", "value1");
        authorizationRequest.addCustomParameter("customParam2", "value2");
        authorizationRequest.addCustomParameter("customParam3", "value3");
```

3. The custom parameters are available to use by custom python scripts and can be read from the session, see attached image.
<img width="1385" alt="screen shot 2017-11-23 at 10 06 41 pm" src="https://user-images.githubusercontent.com/2474616/33194409-36ce8e8e-d0a6-11e7-8f4b-d7b4c835a255.png">
