### ISSUE TITLE
Duplicate tokens after log into oxTrust

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#65]
After log in to CE(Example: https://ce-release.gluu.org) oxAuth adds 4 token entries for id_token, access_token, refresh_token, id_token. Why it adds 2 id_tokens? Should it replace existing id_token withing authorization_grant if needed?

**Comment by willow9886** [comment]
@qbert2k can you address this?

**Comment by yurem** [comment]
I think we fixed it. We only need to recheck it in 2.4.2. We need to use any custom authentication method to verify it.

**Comment by yurem** [comment]
Fixed. Can't reproduce in latest CE 2.4.2
