### ISSUE TITLE
Redis method of caching is slow and seems code is repeating tasks unnecesarrily.

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxAuth#652]
https://pastebin.com/dBBqnURV

While logging in to Gluu UI that is configured to use redis, the process is really slow. While monitoring the redis service on it's server, I noticed that their are many redundant tasks repeating for a long time slowing log in time. See paste-bin for login. Same thing happens for logout and "sign-in again"

**Comment by afroDC** [comment]
To accompany the logs from redis, here are logs from both Gluu servers.

Server 1:
https://pastebin.com/TKZW9VaW

Server 2:
https://pastebin.com/tTECGPyr

**Comment by yuriyz** [comment]
@nynymike @willow9886 @afroDC 

Under the hood we are using `ShardedJedis` which replicates also write operations. In classical redis configuration there is `master-slave` relationship which indeed is much faster for read operation. Should we remove `Sharded` behavior ?

Look here: https://github.com/xetorthio/jedis/wiki/AdvancedUsage#shardedjedis

**Redundancy**
Redis is cache provider, it get/put values. It is used by oxauth code, we have to check in detail why and where we have redundancy in oxauth code and how we can reduce it.

**Slow**
It would be nice to see logs with time, so we can see how much time is spend on each operation on redis side.

**Comment by yuriyz** [comment]
It would be interesting to see how much it slow down when we increase number of server, e.g. time with 2 servers, 4, 8.

**Comment by afroDC** [comment]
`Should we remove Sharded behavior ?`

I believe this is a good idea to remove shared, since the oxAuth service is essentially doing the writes to redis as a cluster, and not redis itself. Say you have multiple nodes of redis, they are still in-taking from multiple nodes of Gluu to each instance and therefore don't need to pass redundancy to each other.

I will set up a cluster today and get back to you on times. For administrator it's taking some 7-15 seconds to resolve the token, if I remember correctly.

**Comment by yuriyz** [comment]
I'm not sure I agree, sharded approach actually should increase performance because it splits data horizontally (not vertically.)
```
https://en.wikipedia.org/wiki/Shard_%28database_architecture%29
```

Also maybe we can measure it with `redis-benchmark`. https://redis.io/topics/benchmarks

**Comment by nynymike** [comment]
The question is why... what's going wrong?

**Comment by yuriyz** [comment]
I think we should move from client partitioning to standard redis cluster https://redis.io/topics/partitioning
I'm going to create branch and create experimental oxauth with cluster connection. Lets see how it goes. (For me it looks as some type of bug in jedis client sharding)

**Comment by yuriyz** [comment]
Test runs 1000 tasks, each task has 1 write operation and 2 get operations (3 operations in one task). It is run within 100 concurrent threads (so in average each threads handles ~10 tasks).


Stanalone:
1. 1000 - 278ms
2. 10000 - 2506ms

Cluster with 6 servers (made according to https://redis.io/topics/cluster-tutorial):
1. 1000 - 866ms
2. 10000 - 892ms


```
[admin.PCYURIYW7] ➤ ./redis-trib.rb create --replicas 1 127.0.0.1:7000 127.0.0.1:7001 \
> 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005
>>> Creating cluster
>>> Performing hash slots allocation on 6 nodes...
Using 3 masters:
127.0.0.1:7000
127.0.0.1:7001
127.0.0.1:7002
Adding replica 127.0.0.1:7003 to 127.0.0.1:7000
Adding replica 127.0.0.1:7004 to 127.0.0.1:7001
Adding replica 127.0.0.1:7005 to 127.0.0.1:7002
M: f0545e5e27b970e94e6852b34ce7f96dc8c92932 127.0.0.1:7000
   slots:0-5460 (5461 slots) master
M: 6461891c320990e7eccca679d2b677eaaac6abd3 127.0.0.1:7001
   slots:5461-10922 (5462 slots) master
M: 9e74b955595e8be9d1be107aa866d5c844f10d20 127.0.0.1:7002
   slots:10923-16383 (5461 slots) master
S: ed1d2af96846698282afc05012e685e13640606a 127.0.0.1:7003
   replicates f0545e5e27b970e94e6852b34ce7f96dc8c92932
S: 48113af9e75a285c58735eed117042d7730e12bd 127.0.0.1:7004
   replicates 6461891c320990e7eccca679d2b677eaaac6abd3
S: c69ef937b3953d56fb756fad9941cd72cfd71a74 127.0.0.1:7005
   replicates 9e74b955595e8be9d1be107aa866d5c844f10d20
Can I set the above configuration? (type 'yes' to accept): yes
>>> Nodes configuration updated
>>> Assign a different config epoch to each node
>>> Sending CLUSTER MEET messages to join the cluster
Waiting for the cluster to join...
>>> Performing Cluster Check (using node 127.0.0.1:7000)
M: f0545e5e27b970e94e6852b34ce7f96dc8c92932 127.0.0.1:7000
   slots:0-5460 (5461 slots) master
   1 additional replica(s)
S: ed1d2af96846698282afc05012e685e13640606a 127.0.0.1:7003
   slots: (0 slots) slave
   replicates f0545e5e27b970e94e6852b34ce7f96dc8c92932
M: 6461891c320990e7eccca679d2b677eaaac6abd3 127.0.0.1:7001
   slots:5461-10922 (5462 slots) master
   1 additional replica(s)
S: c69ef937b3953d56fb756fad9941cd72cfd71a74 127.0.0.1:7005
   slots: (0 slots) slave
   replicates 9e74b955595e8be9d1be107aa866d5c844f10d20
M: 9e74b955595e8be9d1be107aa866d5c844f10d20 127.0.0.1:7002
   slots:10923-16383 (5461 slots) master
   1 additional replica(s)
S: 48113af9e75a285c58735eed117042d7730e12bd 127.0.0.1:7004
   slots: (0 slots) slave
   replicates 6461891c320990e7eccca679d2b677eaaac6abd3
[OK] All nodes agree about slots configuration.
>>> Check for open slots...
>>> Check slots coverage...
[OK] All 16384 slots covered.
```

**Comment by afroDC** [comment]
@yuriyz is clustering limited to one server?

If not, I think this solution would be ideal.  I believe currently, if one redis server goes down on a replicated instance, oxAuth fails since the tokens are split.

I believe this is true as MEMCACHED handles failure when one of it's nodes is down.

**Comment by yuriyz** [comment]
@afroDC indeed redis cluster is not limited to one server. I will test redis cluster failover. I believe oxauth does not handle it correctly right now because it is using client sharded connection. If switch it to cluster connection then it must work. I will check and let you know.

**Comment by yuriyz** [comment]
@afroDC @nynymike @willow9886 
During failover testing I made following:

1. introduced new `RedisClusterProvider` in `oxcore` project (which is using cluster connection under the hood)
2. connected with it as.
```
127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005
```
3. For testing made redis cluster with following configuration
```
[admin.PCYURIYW7] ➤ /drives/c/Dev/Redis-x64-3.2.100/src/redis-trib.rb create --replicas 1 127.0.0.1:7000 127.0.0.1:7001 \
> 127.0.0.1:7002 127.0.0.1:7003 127.0.0.1:7004 127.0.0.1:7005
>>> Creating cluster
>>> Performing hash slots allocation on 6 nodes...
Using 3 masters:
127.0.0.1:7000
127.0.0.1:7001
127.0.0.1:7002
Adding replica 127.0.0.1:7003 to 127.0.0.1:7000
Adding replica 127.0.0.1:7004 to 127.0.0.1:7001
Adding replica 127.0.0.1:7005 to 127.0.0.1:7002
```
- Connected with cluster connection - works!
- killed replica `127.0.0.1:7005` - works!
- killed master `127.0.0.1:7000` - works!
- killed second master `127.0.0.1:7001` - works!
- killed third master `127.0.0.1:7002` - stops to works!

It means that redis cluster works if at least one master is alive. If all masters goes down then it stops to work.

**Comment by yuriyz** [comment]
@afroDC @nynymike @willow9886 
How should we proceed with redis connection ? 
Redis can run in standalone mode and in cluster. Client has to know to what kind of redis it connects. I propose to do following:
1. User specifies connection details (via oxtrust) in `servers` configuration property
2. Connection manager reads `servers` property and counts how must servers are specified in this configuration. If number of servers is **1** we open `standalone` connection. Otherwise if number of servers in property is more then one then we open `cluster` connection. I propose to not use sharded client connection and completely leave it to redis cluster itself, according to documentation it is standard redis approach and should work the best.

From docs https://redis.io/topics/partitioning
```
Redis Cluster is the preferred way to get automatic sharding and high availability. 
```

What do you think ? 
If we agreed on it I will start pushing it into `3.1.1`.

**Comment by yuriyz** [comment]
Now we have 3 types of redis cache provider:
- stanalone - redis standalone server
- cluster - redis clusteer
- sharded - client sharding

Configuration of redis now contains:
- redisProviderType - type of connection, valid values are : STANDALONE, CLUSTER, SHARDED
- servers - property with server connection string, example: `localhost:6379` (for tutorial cluster it will be `localhost:7000,localhost:7001,localhost:7002,localhost:7003,localhost:7004,localhost:7005`)
- defaultPutExpiration - default put expiration in seconds

**Comment by yuriyz** [comment]
Closing for now. @afroDC please test and reopen if you face any issues with redis connection on oxauth side.
