### ISSUE TITLE
Add support of "old" caching mode 'LDAP'

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#654]
For end user in oxTrust GUI it should be provided as another cache mechanism 'LDAP'.

**Comment by nynymike** [comment]
This is becoming high priority.

**Comment by yuriyz** [comment]
@nynymike @yurem In 3.1.4 we have ldap and this cache provider will stick to LDAP, so there is no need to add additional component for cache (like redis). However in 4.0.0 we can have LDAP or Couchbase. Depending on persistence manager this cache type is going to put cache entities into LDAP or Couchbase. How should we name it? I propose `Persistence` (or maybe `Native` cache). What do you think?

**Comment by yuriyz** [comment]
We will use `NativePersistence`.

**Comment by yuriyz** [comment]
done for 3.1.4 and integrated into 4.0.0
