### ISSUE TITLE
Synchronize CAS logout with OpenID Connect logout

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#657]
CAS session is not ended on OpenID Connect logout. Need a config option or other feature to enable the CAS endpoint to be called.

**Comment by dmogn** [comment]
Ok. Got it.

**Comment by yurem** [comment]
@dmogn for flow when customer call OpenId end_session endpoint first we can use [application_session](https://github.com/GluuFederation/community-edition-setup/blob/master/static/extension/application_session/SampleScript.py
) script type.

**Comment by dmogn** [comment]
@yurem 
I do not sure that we can implement it before this:
https://github.com/GluuFederation/oxShibboleth/issues/10
>> "We need rewrite Shib. IDP RemoteUser flow for ForceAuthn support."

It is planned for 3.2.0. At now our SAML/CAS filter does not keep any IDP-side session, so I cannot redirect logout to CAS SP.
But by default - CAS mast be server-side session in Shib IDP. So, with fully supported flow we can implement the issue.
