### ISSUE TITLE
Make implicit flow configurable and persist all related objects into cache (no ldap at all)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#658]
Make implicit flow configurable and persist all related objects into cache (no ldap at all)

**Comment by worm333** [comment]
Enhanced in [this](https://github.com/GluuFederation/oxAuth/pull/665) pull request.

**Comment by yuriyz** [comment]
Re-opened, as discussed in skype we have to avoid all ldap writes.

**Comment by yuriyz** [comment]
During benchmarking following was made:
1. logging was completely off
2. httpLoggingEnabled=false
3. useCacheForAllImplicitFlowObjects=true
4. updateUserLastLogonTime=false
5. updateClientAccessTime=false

As result average speed for implicit flow is ~170 req/s. There are a few bottlenecks :

1. more then 40% of time is wasted on ocp rewrite filter. We should check what we can do here.
2. security code blocking (this is natural due to usage of java security package), not sure how we can improve here.
3. faces blocking 
4. jetty resources blocking
5. ldap authenitcation - there are no interaction with ldap except actual authentication

![block_faces](https://user-images.githubusercontent.com/2013070/32738252-050702ae-c8a5-11e7-879f-cff09f7950e7.png)
![block_jettyresources](https://user-images.githubusercontent.com/2013070/32738253-05225d38-c8a5-11e7-820c-c856972724fa.png)
![block_ldapauthentication](https://user-images.githubusercontent.com/2013070/32738254-05407110-c8a5-11e7-9d9a-7e599d40a9d6.png)
![block_ocpsoftrewritefilter](https://user-images.githubusercontent.com/2013070/32738255-055c0ad8-c8a5-11e7-853f-098622797d26.png)
![block_securitygeneration](https://user-images.githubusercontent.com/2013070/32738256-057e18a8-c8a5-11e7-9169-2067883d814e.png)

**Comment by yuriyz** [comment]
One more finding, it seems we spend too much time on `getLogging` inside `weld`. I'm going to add in-memory lazy cache to not invoke reflection which is time consuming.

![block_getlogger](https://user-images.githubusercontent.com/2013070/32844592-82d56e14-ca2b-11e7-8f9e-17d7cf9d296a.png)

cc @nynymike @yurem

**Comment by yuriyz** [comment]
One more thing, when I dropped `org.xdi.oxauth.audit.debug.ServletLoggingFilter` from the war file it increased performance on 2-3 req/s. So even with `appConfiguration.getHttpLoggingEnabled()=false` it seems to invoke ocpsoft rewrite filter which delays execution a bit.

**Comment by yuriyz** [comment]
So far best result I got 
```
summary +   5173 in 00:00:30 =  176.4/s Avg:    32 Min:    14 Max:   333 Err:     0 (0.00%) Active: 800 Started: 800 Finished: 0
```

**Comment by yurem** [comment]
We can remove OCP rewrite filter to fix `more then 40% of time is wasted on ocp rewrite filter. We should check what we can do here.`

In oxuath we uses it to in very simple flow to map `./page.htm` to `./page`.
We can replace in web.xml url-pattern with:
```
	<servlet-mapping>
		<servlet-name>Faces Servlet</servlet-name>
		<url-pattern>/</url-pattern>
	</servlet-mapping>
```

And remove from pom.xml
```
		<!-- Pretty Faces -->
		<dependency>
			<groupId>org.ocpsoft.rewrite</groupId>
			<artifactId>rewrite-servlet</artifactId>
		</dependency>
		<dependency>
			<groupId>org.ocpsoft.rewrite</groupId>
			<artifactId>rewrite-config-prettyfaces</artifactId>
		</dependency>
```

**Comment by yurem** [comment]
Or we can write filter which should add `.htm` to custom HttpServletRequestWrapper and pass it next filter in chain,

**Comment by yuriyz** [comment]
Actually it's not RewriteFilter. Profiler shows time that is spent with all subsequent calls inside, because it's Servlet chain we see filter on top but what really takes time is /login.html and /authorize.htm page rendering (which is more than 50% of the time actually). I believe I know the reason, let me dig a bit deeper and I will show it.

**Comment by yuriyz** [comment]
![block_weld_el_](https://user-images.githubusercontent.com/2013070/32883746-de754f06-cac0-11e7-8d13-56d97a6f683c.png)
![block_weld_concurrentmap](https://user-images.githubusercontent.com/2013070/32883743-d99585c8-cac0-11e7-88ce-1d1029176317.png)

**Comment by yuriyz** [comment]
Closing this issue as fixed since main goal is reached. Opened specific ticket for weld performance
https://github.com/GluuFederation/oxAuth/issues/697

**Comment by yurem** [comment]
I think we need to open issue for point  #1 too: `Weld - 50% of the time is wasted on internal locks. We should investigate how to avoid/improve here`

Weld is powerful but it do what we requested from it. Now we uses in ApplicationScope, RequestScope, DefaultScope. We need to review all services `scope` type. I think for some stateless and frequently used services we can even Singelstone which not uses proxy method and interceptors at all.

I have ideas regarding authorize rendering page performance. AuthorizeAction has ReqeustScoped scope. And it has 20 injected services. As result on every browser request Weld, as  requested, have to create this service and probably 20 proxy to access required services. It's heavy process which can do blocking.

I created AuthorizeService and started to move stateless method from AuthorizeAction. Final AuthorizeAction  should has only properties and few dependencies which will take less time for instantiation.

Also it's not big improvement but can help. As far as I remember we pass all parameters from /authorize to /restv1/authorize and do same in reverse direction. We store request parameters in session at first request. I think we should not pass them again on each redirect.

**Comment by yurem** [comment]
This point "LDAP - for authentication we still use authenticate() method which is like 30% percent." I offer to review later after adding Couchbase support. I' think this delay caused by LDAP server and we can't improve our code for it.

**Comment by yuriyz** [comment]
Issue is already created as you can see from previous comment #697. Right, totally agree. All proxy must be avoided when possible. Most of our services are actually singleton by nature. Lets review all those. I'm sure that we should save here ˜30% of time. Lets see.

**Comment by sahiliamsso** [comment]
useCacheForAllImplicitFlowObjects is not showing up in oxAuth JSON configuration.

**Comment by yuriyz** [comment]
@sahiliamsso not sure where you checking it but here is screen from ce-dev4 where `useCacheForAllImplicitFlowObjects` is present.

![implicitallobj](https://user-images.githubusercontent.com/2013070/34250975-2b7d4190-e647-11e7-9156-9255dfac7cae.png)

**Comment by yuriyz** [comment]
Default value has to be added in order to render it by oxtrust. It was added here
https://github.com/GluuFederation/community-edition-setup/commit/6dc75bc707da485d0dfc3d4805c77831f5542ce1
