### ISSUE TITLE
Change RDN of authorization_code grant

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#66]
We should change RDN which we uses to store tokens:
Now we store them using next RDN: uniqueIdentifier=uuid,inum=client_id,ou=clients,o=org_inum,o=gluu
It’s better to use next RDN: uniqueIdentifier=uuid,oxAuthGrantId=uuid,inum=client_id,ou=clients,o=org_inum,o=gluu

**Comment by qbert2k** [comment]
The code changes were committed in the branch: "Change-RDN-of-authorization_code-grant" of the projects repo: oxAuth and community-edition-setup

**Comment by yurem** [comment]
I’ve merged this and pairwise_identifier branches into master. Both updates looks good for me. Even there is new LDAP index definition for oxSectorIdentifierURI J Thanks!

 

Regards,

Yura
