### ISSUE TITLE
Add enrollment_code query param to U2F RegistrationRequestService

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#660]
This [interface](https://github.com/GluuFederation/oxAuth/blob/master/Client/src/main/java/org/xdi/oxauth/client/fido/u2f/RegistrationRequestService.java#L24-L24) is missing the `enrollment_code` parameter, thus when obtaining a client to interact with the endpoint using [the corresponding factory method](https://github.com/GluuFederation/oxAuth/blob/79e86ed61bb4dad07f559da2d4f1ab7e2ea5130b/Client/src/main/java/org/xdi/oxauth/client/fido/u2f/FidoU2fClientFactory.java#L36-L36) there is no way to supply an enrollment code.

Currently one would have to manually send the GET request to be able to pass the code, and then parse the response.

**Comment by yurem** [comment]
Implemented
