### ISSUE TITLE
Improve oxAuth authz checking mechanism

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#662]
Environment:
Ubuntu 14.04, gluu-server-3.1.1-2.beta2~trusty+Ub14.04

For cases when Pre-Authorization is disabled for a certain client, oxAuth server needs to check list of scopes permitted to be released by an user each time an authz request from a certain client is served (not only at login/first time).

**Comment by nynymike** [comment]
If Alex is correct, then this is a bug.

**Comment by sahiliamsso** [comment]
@aliaksander-samuseu checked, and it seems not yet fixed.

**Comment by qbert2k** [comment]
The problem can be reproduced with a specific configuration when pre-authz is false and persist is also set to false. #441
