### ISSUE TITLE
Support extra parameters sent during UMA permission ticket request

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#664]
Take additional parameters from permission ticket request.  These keys/values would be available in the permission ticket context.

**Comment by yuriyz** [comment]
@nynymike shifted to 3.1.3. Let me know if it's top priority and we need to keep it in 3.1.2.

**Comment by yuriyz** [comment]
Extra parameter should be possible to sent via `params` json key, sample json
```json
{  
   "resource_id":"112210f47de98100",
   "resource_scopes":[  
      "view",
      "http://photoz.example.com/dev/actions/print"
   ],
   "params": {
      "key1":"value1"  
   }
}
```
```

**Comment by yuriyz** [comment]
done
