### ISSUE TITLE
UMA: require client requested scopes to be pre-registered

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#674]
![image](https://user-images.githubusercontent.com/3717101/31806225-3fdd5722-b51b-11e7-9ec3-b661ef6b8d40.png)

This diagram uses a Venn diagram to represent the relationship between scopes associated with a ticket, scopes requested by a client, and scopes registered by a client. You could express this as: ticket scopes ∪ (requested scopes ∩ registered scopes). 

We need to add a JSON property for oxAuth which specifies whether clients need to have scopes pre-registered.

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/68
