### ISSUE TITLE
Dynami Client Registration failed with error code 500 (Internal Server Error)

### ISSUE THREAD

**Issue by bahadorraha** [GluuFederation/oxAuth#683]
Hi,
I tried to dynamically register a client using [opneid-implicit-client](https://github.com/GluuFederation/openid-implicit-client) sample SPA. My request seems to be valid bit I received error code 500 (Internal Server Error).
I did not alter its code and just commented the client_id field in the `index.html` to enable dynamic client registration according to this [blog post](https://www.gluu.org/blog/openid-connect-implicit-client/).
This is the POST request header and body:
Header:
`Host: my-idp.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/json
Content-Length: 267
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache`

Body:
`{"redirect_uris":["http://localhost:8080/jsapp/login-callback.html"],
"application_type":"Web",
"client_name":"Dynamically Registered Client",
"subject_type":"public",
"grant_types":["implicit"],
"response_types":["token","id_token"],"scopes":["email","openid","profile"]}`

Unfortunately I could not found any related log records.
Thanks in advance.

**Comment by willow9886** [comment]
Hi there, please review existing tickets on https://support.gluu.org. If you don't see any relevant tickets, please register an account and open a ticket there. 

Thanks,
Will
