### ISSUE TITLE
UMA 2 : Allow access token for authentication at UMA token endpoint 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#686]
In the case where a mobile app obtains an UMA access token, the client may have already authenticated a user, and in the process, obtained an access token. The client should be able to re-use this access token in lieu of client client credentials at the UMA token endpoint. This is particularly important because in the mobile application, client creds cannot be securely stored. Eventually we may want to implement PKCE for UMA, but for now, this is a quick fix.

**Comment by yuriyz** [comment]
Note: app obtained access_token (via user authentication), now app should be able to present user access_token instead of client credentials to UMA RPT endpoint and obtain new RPT

**Comment by yuriyz** [comment]
@nynymike : During client authentication UMA Token Endpoint takes client that was used during `access_token` creation. `authentication_method` of the client is ignored in this case, means that it can have any value (even `authentication_method`=`none`). We can introduce new value for `authentication_method`, e.g. `access_token` however I'm not sure we need it. Please let me know.

**Comment by yuriyz** [comment]
It works as
```
POST /token HTTP/1.1
Host: server.example.com
Content-Type: application/x-www-form-urlencoded
Authorization: AccessToken czZCaGRSa3F0MzpnWDFmQmF0M2JW
```

**Comment by yuriyz** [comment]
Fixed.
