### ISSUE TITLE
UMA 2 : support "and", "or"  logical operations for scopes (including nested)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#688]
UMA 2 : support "and", "or"  logical operations for scopes (including nested);

**Comment by yuriyz** [comment]
https://github.com/GluuFederation/kong-plugins/issues/3

**Comment by yuriyz** [comment]
https://github.com/GluuFederation/uma-rs/issues/2

**Comment by yuriyz** [comment]
We should consider JsonLogic as evaluator for UMA.

https://github.com/deinspanjer/json-logic-java

**Comment by yurem** [comment]
We has org.xdi.service.el.ExpressionEvaluator.evaluateValueExpression which can evaluate EL expression like:
`${(guess < 10)  or (guess > 20)}` or more complex EL expressions

**Comment by yurem** [comment]
Here is method which you can call:
```
public <T> T evaluateValueExpression(String expression, Class<Boolean> expectedType, Map<String, Object> parameters) {
```

**Comment by yuriyz** [comment]
@yurem yes, there are many possibilities there but @nynymike proposed to use jsonlogic because it has built-in UI and is easy to integrate. So it's not question of evaluation itself.

**Comment by nynymike** [comment]
Correct... Meg already created the UI
![image](https://user-images.githubusercontent.com/3717101/32903198-09eb0f38-caba-11e7-9c82-c1a5cd80303c.png)

**Comment by yuriyz** [comment]
@nynymike We have to define in detail ticket registration is made and what expressions are valid and what not.

For example we have resource1 with expression `s1 and (s2 or s3)`. RS wants to allow access with expressions:
1. `s1 or s3` - is it valid ?
2. `s1 or s2` - is it valid ?
3. `s1 or s4` - is it valid ? (it's not mentioned during resource registration. If no then we have to traverse expression graph)
4. `s1 and (s2 or s3)` - exact match. It must be valid.
5. `s2 and (s1 or s3)` - is it valid?

I assume we should allow all kind of expressions that use same scopes but then why would we wish to keep expression during resource registration? 

**Version 1**
- Resource registration - Declare allowed scopes
- Ticket registration - allow any kind of expression with allowed scopes

**Version 2**
- Resource registration - Declare expression
- Ticket registration - present only `resource_id`. We don't need expression because it's already registered during resource registration, so we just evaluate it. No need to pass scopes as in spec https://docs.kantarainitiative.org/uma/wg/oauth-uma-federated-authz-2.0-09.html#rfc.section.4.1

**Comment by nynymike** [comment]
I think Version 2 makes sense. The expression is just a more organized way to express the required combination of scopes.

However, a client may still request specific additional scopes (as long as these are pre-registered during client registration). 

For example:

![image](https://user-images.githubusercontent.com/3717101/33287848-a7c96664-d37f-11e7-8b7f-5139470230cb.png)

**Comment by yuriyz** [comment]
@nynymike @ldeveloperl1985 
Here (https://github.com/GluuFederation/kong-plugins/issues/3) is mentioned format which is not jsonlogic valid expression

Invalid
```
"and": [{
						"or": ["http://photoz.example.com/dev/actions/all",
							"http://photoz.example.com/dev/actions/add"
						]
					},
					"http://photoz.example.com/dev/actions/internalClient"
				]
```

Valid expression is as following:

Rule
```json
{
    "and": [
      {
        "or": [
          {"var": 0},
          {"var": 1}
        ]
      },
      {"var": 2}
    ]
  }
```

Data 
```
[
    "http://photoz.example.com/dev/actions/all",
    "http://photoz.example.com/dev/actions/add",
    "http://photoz.example.com/dev/actions/internalClient"
  ]
```

We are combining it into single json object

UMA 2 implementation excepts json object as this
```json
{
  "rule": {
    "and": [
      {
        "or": [
          {"var": 0},
          {"var": 1}
        ]
      },
      {"var": 2}
    ]
  },
  "data": [
    "http://photoz.example.com/dev/actions/all",
    "http://photoz.example.com/dev/actions/add",
    "http://photoz.example.com/dev/actions/internalClient"
  ]
}
```

**Comment by yuriyz** [comment]
@nynymike Re: Version 2. We are proceeding with it but in addition we will pass also scopes, so we are consistent with UMA 2 spec. In JsonLogic case it would means pass "data" node which is array of scopes. It also helps to keep code cleaner which is nice.

**Comment by yuriyz** [comment]
Here is detailed description how this feature works

1. RS registers resource (note new `scope_expression` field, `resource_scopes` is ignored in this case)

```json
{  
   "resource_scopes":[],
   "description":"Collection of digital photographs",
   "icon_uri":"http://www.example.com/icons/flower.png",
   "name":"Photo Album",
   "type":"http://www.example.com/rsrcs/photoalbum",
   "scope_expression": {
      "rule": {
         "and": [
            {
               "or": [
                   {"var": 0},
                   {"var": 1}
               ]
            },
            {"var": 2}
         ]
      },
      "data": [
         "http://photoz.example.com/dev/actions/all",
         "http://photoz.example.com/dev/actions/add",
         "http://photoz.example.com/dev/actions/internalClient"
      ]
   }
}

```

2. RS registers tickets with all scopes mentioned in "data" (we need all scopes in order to evaluate expression, all or nothing principle)

```json

{  
   "resource_id":"112210f47de98100",
   "resource_scopes":[  
       "http://photoz.example.com/dev/actions/all",
       "http://photoz.example.com/dev/actions/add",
       "http://photoz.example.com/dev/actions/internalClient"
   ]
}
```

3. UMA Engine


Iterates over each scope and fetch ALL policies for each scope. Evaluate all policies.
a) not enough claims - return need_info error
b) enough claims - evaluate results from ALL policies with "AND" rule for ONE given scope.
   b1) `http://photoz.example.com/dev/actions/all` -  `policyA AND policyB` => false
   b2) `http://photoz.example.com/dev/actions/add` -  `policyA AND policyD` => true
   b3) `http://photoz.example.com/dev/actions/internalClient` - `policyD AND policyE and policyK` => true

Results in expression : `(false OR true) AND true` => `true`

**Comment by nynymike** [comment]
Nice solution!

**Comment by yuriyz** [comment]
Documentation is added with this link https://github.com/GluuFederation/docs-ce-prod/commit/c04a231691cf5328829aca0ea15637a30f57caf7
