### ISSUE TITLE
Performance : during high load and logging enabled (> 400 concurrent users) we got freeze for 10-17 seconds for some threads.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#691]
During high load jetty fails to load classes. As result some threads are frozen on 10-17 seconds.

![frozenon17seconds](https://user-images.githubusercontent.com/2013070/32659128-d424fdc0-c625-11e7-8a4f-e681026251e5.png)

**Comment by yuriyz** [comment]
@nynymike @yurem This is killing oxauth performance. Ideas how to fix it are welcome.

**Comment by nynymike** [comment]
`getUserByAttribute` ...so it's an LDAP call. It would be interesting if we could find out a little more about what search that is, and see if it's jetty or ldap that is hanging. My money is on LDAP.

**Comment by yuriyz** [comment]
@nynymike : it `authenticate()` method. Here is exactly 202 of `OperationsFacade`. 
```
https://github.com/GluuFederation/oxCore/blob/master/oxLdap/src/main/java/org/gluu/site/ldap/OperationsFacade.java#L202-202
```

As you can see it is logging issue. I asked Sahil to re-install CE on that machine, maybe it's some disk problem we run into or something. Otherwise I wonder why jetty ClassLoader fails here.

**Comment by nynymike** [comment]
Interesting... can we turn off logging? In a high performance deployment, we could optimize logging.

**Comment by yuriyz** [comment]
@nynymike yes, will do.

**Comment by yuriyz** [comment]
Added logger objects cache to weld resource injector, so now log object injection occurs much faster during high load. Next to avoid blocking on logging we should turn off loggings as:
1. provide OFF in log4j2.xml
2. make sure jdk logger is switched off too.

More details here https://github.com/GluuFederation/oxAuth/issues/658
