### ISSUE TITLE
Support redis failover in standalone

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxAuth#694]
Enable the admin to add more than one redis-server to the configuration. oxAuth should handle switching to another cache if one is not available for connection.

**Comment by yuriyz** [comment]
Is it really about standalone or it is meant to support redis sentinel with automatic promotion of slave to master ?

https://redis.io/topics/sentinel

**Comment by afroDC** [comment]
I'm not sure redis sentinel is what we want in this scenario, but if a user has multiple cache instances listed on Standalone, oxAuth should automatically switch to another instance if the first instance is non-responsive.

**Comment by yuriyz** [comment]
@afroDC @isman @nynymike Standalone connection connects to one single redis server. If we add failover then it will be implemented programatically on oxcore project and means following:
1. if connection is to server1 and server2 then oxcore will connect to server1 first. 
2. if server1 is unavailable then to server2.
3. if oxauth is connected to server1 during some time and then crashed then it means that all redis data on server1 are lost and we are switching to server2. It at least means that:
- all session data are lost and OP will start to send errors that sessions are invalid (from server1).
- all users needs to authn&authz again.

If we are ok with above points then I can go ahead and implement failover with redis standalone connection.

**Comment by nynymike** [comment]
Let's hold on this. I thought we were using a redis proxy, so we don't need failover. Can't this be handled at the network level (i.e. use a virtal IP for the redis proxy which can route to one or more servers).

**Comment by afroDC** [comment]
@nynymike giving cache redundancy by having some sort of replication topology requires a smarter jedis client to handle one of the servers throwing an error and refusing connections. As it stands, twemproxy can't route traffic to a redis-cluster topology and using something like dynomitedb for replicating data instead doesn't give twemproxy the necessary signals it needs to know a redis-server is down. 

We wouldn't need to use twemproxy if oxAuth could handle recognizing a server isn't responding and moving on to another in it's `oxCacheConfiguration` pool. For example, redis-cluster servers could be added to the configuration list. Or all dynomitedb proxies could be added. Any one that doesn't respond properly could be dropped for x amount of time.

There's currently not really any other option for giving a highly available cache system that I can find. The expectation seems to be that some client side error handling should be embedded.

**Comment by afroDC** [comment]
Alternatively, we could try to build something if we don't want to modify oxCore.
