### ISSUE TITLE
Performance : ˜40% of time is blocked by weld synchronization during high load (>800 threads). 

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#697]
Performance : ˜40% of time is blocked by weld

More verbose explanation can be found here https://github.com/GluuFederation/oxAuth/issues/658

![block_weld_concurrentmap](https://user-images.githubusercontent.com/2013070/32979898-464e94ba-cc66-11e7-9e08-e82958723997.png)

**Comment by yurem** [comment]
I think we can close it and open new open to check performance in 3.1.6/4.0 with max 200-300 threads.
800 threads is too many even for very quick server.
