### ISSUE TITLE
Add support for Client metadata: software_id, software_version, software_statement

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxAuth#704]
See OAuth 2.0 Dynamic Client Registration Protocol

https://tools.ietf.org/html/rfc7591#section-2

**Comment by syntrydy** [comment]
@qbert2k  the problem seems to been on the oxtrust side.

**Comment by syntrydy** [comment]
https://github.com/GluuFederation/oxTrust/issues/1451

**Comment by qbert2k** [comment]
Fixed in #1451, Thanks @syntrydy !

https://github.com/GluuFederation/oxTrust/issues/1451
