### ISSUE TITLE
TOTP/HOTP cust script using lookAheadWindow=1 always

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#706]
In [otp script L505](
https://github.com/GluuFederation/oxAuth/blob/version_3.1.1/Server/integrations/otp/OtpExternalAuthenticator.py#L505), is there any special reason  to use a *look ahead window* of 1 instead of that found in the config file `otp_configuration.json`?.  I think that a small look ahead will make server go out of sync with respect to HOTP device

**Comment by yurem** [comment]
`lookAheadWindow` in `otp_configuration.json` is also 1. We need to update script to use value from config file

**Comment by yurem** [comment]
It's configurable via: https://github.com/GluuFederation/community-edition-setup/blob/master/static/auth/conf/otp_configuration.json#L5
