### ISSUE TITLE
Allow to update oxDisabled attribute using Dynamic Client Registration endpoint

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxAuth#719]
1. Allow to update oxDisabled attribute using Dynamic Client Registration endpoint.
2. Add an automated test to validate the client is being disabled/enabled.

**Comment by yurem** [comment]
We have gluuStatus (active/inactive) in schema already. Can we use it?

**Comment by nynymike** [comment]
I don't think this is a good idea.
