### ISSUE TITLE
oxAuth is not presenting the default authentication mode from SAML

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#72]
A [community issue](https://support.gluu.org/view/customization/saml-sso-redirect-login-screen-not-the-google-plus-screen/2106) reported this problem, and I replicated the same by setting up a SAML SP. 

You can see when I login from oxTrust, it correctly displays the Google login screen:
![image](https://cloud.githubusercontent.com/assets/3717101/9827494/58e80dec-58a8-11e5-8ff8-acc221191e78.png)

But when I login from my Shibboleth SP it does not:

![image](https://cloud.githubusercontent.com/assets/3717101/9827504/711dc884-58a8-11e5-8969-f1fb4131f5af.png)

This is a very critical bug, because unless this works, there is no way to use even one of our strong authentication scripts from SAML.

**Comment by yurem** [comment]
Fixed: https://github.com/GluuFederation/oxAuth/commit/a0ae65c7787caa031c5d2ac1376c529f4f917549
