### ISSUE TITLE
Add support for DELETE request to OIDC Dynamic Registration endpoint

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#720]
(Created per Javier's suggestion)
At the moment the only way to delete some client's registration via DynReg protocol seems to be to set its "client_secret_expires_at" metadata property to some data in the past, what triggers its autoremoval shortly. Supporting officially defined flow of deleting it would probably be a more clean approach.

Related RFC's section is [here](https://tools.ietf.org/html/rfc7592#section-2.3).

**Comment by mtgluu** [comment]
Will this feature be something that can be disabled via oxtrust such that if disabled, it will throw a 403/405 back to the client? or, if dynamic registration is already disabled in whole would this already fail?

**Comment by yurem** [comment]
Here is PR for this. We can use it and update to latest scpe: https://github.com/GluuFederation/oxAuth/pull/349

**Comment by nynymike** [comment]
I think the PR referenced above is old, and now has too many conflicts. But this feature really would be nice to have. That way a script could add and cleanup client, which would faciliate testing.

**Comment by yuriyz** [comment]
Implemented in 4.1 and 4.2.
