### ISSUE TITLE
Gluu3.1.2 QA - Passport page is broken

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxAuth#722]
1. Enable Passport Authentication,
2. Setup Configuration > Manage Authentication to use passport and try to login

Page shows broken links, and facbook/google icons are missing
![image](https://user-images.githubusercontent.com/21104811/34278941-dcbb1fb8-e6d3-11e7-9085-c33a2c09b35d.png)

**Comment by willow9886** [comment]
@arvindsinghtomar the design for this page **should not be hardcoded**. 

1. if there are no external IDPs configured, the page should display the standard Gluu Server login page. 

2. Only if there are external IDPs configured and accessible should we show the `External Providers` widget. 

3. Only those external IDPs that are configured and accessible should be displayed in the External Providers widget.

**Comment by arvindsinghtomar** [comment]
![enable_passport](https://user-images.githubusercontent.com/18719003/34288909-d6ac1a04-e715-11e7-9110-37d42c0b214c.png)

that time i have make that page dynamic with Enable passport support can't be visible social Icon
