### ISSUE TITLE
UmaRptIntrospectionService returning expiration time different than umaRptLifetime

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#725]
Related to https://github.com/GluuFederation/SCIM-Client/issues/66

When doing

```
Token pat = UmaClient.requestPat("https://.../oxauth/restv1/token",
                        umaAatClientJksPath, umaAatClientJksPassword, umaAatClientId, umaAatClientKeyId);
UmaRptIntrospectionService rptStatusService=UmaClientFactory.instance().createRptStatusService(umaMetadata);
RptIntrospectionResponse rptStatus=rptStatusService.requestRptStatus("Bearer " + pat.getAccessToken(), rpt, "");
```

`rptStatus.getExpiresAt()` returns an offset of 300 seconds, but `oxAuthConfDynamic` LDAP entry has
"umaRptLifetime": 3600. May be returning the exp. time of PAT?

**Comment by yuriyz** [comment]
Fixed in https://github.com/GluuFederation/oxAuth/commit/6c673ac73f31c3670d5c083b9d61f5c6ad8b4c24#diff-d9c0f3b3f695faf7b36579468c706c9d
