### ISSUE TITLE
Gluu is not logging out if I call end_session endpoint

### ISSUE THREAD

**Issue by cstpraveen** [GluuFederation/oxAuth#736]
User logged in to a OpenId Connect RP (or more) with a registered logout url at the OP.

Calling OpenID Connect end_session logout url with the id_token_hint BEFORE session timeout

If I call the above URL still the gluu is logged in.

I've just tried to view the Gluu server. It is still logging in.

**Comment by nynymike** [comment]
Please move your issue to https://support.gluu.org 

Make sure you include the logout request and ldif for the client.
