### ISSUE TITLE
Allow user to select type of cookie used by oxAuth

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#745]
Type of cookie (its expiration method, specifically) used by oxAuth has been changed recently:
![cookies_type_select](https://user-images.githubusercontent.com/11802046/36050630-496fcbc2-0df8-11e8-8daf-779e6e06d71a.png)
This changes the way of how at least some of browsers treat it, and we've already had complaints from users who were relying on this behaviour in 2.4.4 Per Yuriy M's suggestion, would be useful to have a new setting for oxAuth allowing to select type of cookie it will use.

**Comment by yuriyz** [comment]
Session lifetime is specified via `sessionIdLifetime` oxauth configuration property. If it is set to 0 or -1 then we session_id cookie will not have expiration specified which browsers usually handles as browser "session" and which are valid until browser is not closed (session is not ended).

Done in 3.1.4 and master.

With sessionIdLifetime=0
![session_id_lifetime_not_specified](https://user-images.githubusercontent.com/2013070/44269271-4be38080-a234-11e8-89d6-1e4aaef44871.png)

With sessionIdLifetime specified.
![session_id_lifetime_specified](https://user-images.githubusercontent.com/2013070/44269276-51d96180-a234-11e8-9380-816064063b03.png)
