### ISSUE TITLE
UMA RPT Policy evaluator : if no policies it grants access. We have to make it configurable (e.g. deny instead of grant)

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#748]
Right now evaluator scans for policies associated with scopes. If there is no any policy (list is blank) then we do not invoke evaluator at all and grant access directly.

From one side it is ok because protection is made by policy. No policy - no protection -> Granted.
But from other side I guess we have to forbid access because we will grant access even if admin for forget to specify policy.

**Comment by yuriyz** [comment]
@nynymike what do you think ?

**Comment by nynymike** [comment]
Perhaps this should be configurable in the JSON properties?

**Comment by yuriyz** [comment]
Agreed, lets make it configurable.

**Comment by yuriyz** [comment]
done

**Comment by yuriyz** [comment]
https://support.gluu.org/access-management/6184/uma-my-previously-working-uma-deployment-in-313-stops-to-work-in-314/#at40294
