### ISSUE TITLE
Add description and oxdID to client metadata

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#754]
1. Add `description` and `oxdID` to LDAP objectclass `oxAuthClient`.
2. Add an optional `description` and `oxdID` parameter to client registration / client update API's
3. Add `description` and `oxdID` field to oxTrust form

**Comment by yurem** [comment]
1. Added new attributes to OC: https://github.com/GluuFederation/community-edition-setup/commit/8d2165c79e4da8cc588393846b92eb0a1e5e15b2
2. Client Registration API already supports custom attributes already. Here is example: https://github.com/GluuFederation/oxAuth/blob/master/Server/src/test/java/org/xdi/oxauth/ws/rs/ClientInfoRestWebServiceEmbeddedTest.java#L78

**Comment by yurem** [comment]
3. oxTrust changes: https://github.com/GluuFederation/oxTrust/commit/fc9bb465c25b1cc2a5f72bbb62906474bebe56c8
