### ISSUE TITLE
OAuth Scope Refactoring

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#756]
We should combine all scopes under `ou=scopes,o=(org-inum),o=gluu`

The current implementation results in an **Inconsistent primary key**--for OpenID scopes, the primary key is 'displayName'... in UMA scopes the primary key is `oxID`.  

`displayName` should not be the primary key for the scope... this is contrary to the meaning of the attribute's name, which implies that it is for display purposes only. OpenID scopes should probably move to `oxID` as the primary key.

* We should use objectclass `oxAuthCustomScope` for all scopes--or even better would is just `oxAuthScope`.  
* objectclass `oxAuthUmaScopeDescription` does not have that many attributes... we should just add them to `oxAuthCustomScope`
* oxTrust can exclude `oxScopeType=UMA` when displaying OpenID Connect clients
* We should require `oxID` uniqueness.  Within a domain, scope X should be unique. 
* We need to make a **todo** item for 3.1 --> 3.2 migration... this is a non-backwards compatible change. Entries under `ou=scopes,o=uma,o=(org-inum),o=gluu` will need to be migrated.

**Comment by yuriyz** [comment]
Summary of persistence changes (cc: @mbaser ):

```
renamed attribute: oxPolicyScriptDn -> oxUmaPolicyScriptDn
removed OC: oxAuthUmaScopeDescription 
oxAuthCustomScope OC is extended by  "oxId", "oxIconUrl", "oxUmaPolicyScriptDn" attributes (oxAuthCustomScope replaces oxAuthUmaScopeDescription).
UMA scope removed attributes: owner, oxRevision.
```

**Comment by yuriyz** [comment]
done in master branch (4.0)
