### ISSUE TITLE
Remove grantId if there is no token

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#76]
Application should remove grantId entry if there are no tokens.
Example:
oxAuthGrantId=32f02ffd-723f-42d1-b2d9-d3d6fea9642d,inum=@!0035.934F.1A51.77B0!0008!53FF.058C,ou=clients,o=@!0035.934F.1A51.77B0!0001!402D.66D0,o=gluu

**Comment by yurem** [comment]
We should not check if there is no tokens after token from grant removal.

We can do that in cleaner timer. This search allows to find all grants without tokens:
/opt/opendj/bin/ldapsearch --port 1389 --hostname localhost --bindDN "cn=Directory Manager" --baseDN "ou=clients,o=@\!0035.934F.1A51.77B0\!0001\!402D.66D0,o=gluu"  '(&(objectclass=oxAuthGrant)(numsubordinates=0))' inum

It uses internal OpenDJ attribute 'numsubordinates'.

Also I think we need to add createTimestamp to oxAuthGrant and don't delete grants with lifetime less than 10 ( or 60) seconds. This will cover case when we create grant and do token clean up simultaneously.

**Comment by yurem** [comment]
From: https://blogs.oracle.com/Ludo/entry/ldap_tip_counting_the_number

OpenDS and Sun Directory Server also implements another attribute : hasSubordinates, defined in X.501. hasSubordinates is a boolean and returns "true" or "false" depending on whether the entry is a branch or a leaf in the Directory Information Tree.

**Comment by nynymike** [comment]
I agree... keeping the data small saves both memory and disk space.
