### ISSUE TITLE
Audience passed via the request object during authorization is ignored

### ISSUE THREAD

**Issue by LorisBachert** [GluuFederation/oxAuth#760]
While parsing the request object in the constructor of `JwtAuthorizationRequest` the audience member of the object is ignored.
While building the user info response jwt the audience is set by using:
```java
jwt.getClaims().setAudience(authorizationGrant.getClientId());
```
Therefore it doesn't matter which audience i'd pass via the request object, i'd still get the client id as my audience.

**Comment by yuriyz** [comment]
Fixed in master (4.0).
