### ISSUE TITLE
Allow to provide list of possible claims bound to a specific dynamic scope in corresponding OP's metadata elements

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#763]
This is a suggestion from a customer. Prior to Gluu CE 3.x it was possible to easily add a static claim/attribute to the list of claims displayed on the properties page of dynamic scope in web UI. This static list wasn't used for actual claims' release (this still was handled by corresponding Jython script), but was adding all those claims to OP's metadata's "scope_to_claims_mapping" element in next manner:
```
        {"test_roles_dyn": [
        "t_role_dyn_1",
        "t_role_dyn_2"
        ]},
```
In addition, it was added to "claims_supported" element as well:
```
    "claims_supported": [

   ...

        "t_role_dyn_1",
        "t_role_dyn_2",

   ...

    ],
```

Apparently, some users were relying on this approach in their RP's designs, which allowed them to parse OP's metadata to acquire list of possible claims which can be returned by querying this dynamic scope, and easily update this list by managing list of static claims bound to the scope (though it seems more like a workaround than a planned feature)

In 3.x it's not possible anymore, though web UI still allows to add claims to the list (the control is still on the page), for dynamic scopes it's not persisted in LDAP tree (though by editing scope's entry in LDAP directly it's still possible to achieve the result from times of 2.4.x)

It was suggested for this functionality to return again, with certain enhancements:

1. For dynamic scopes specifically, a new control is displayed instead of "Claims/Add claim". It allows user to specify all possible claims which may be returned if this scope is used, which are then pushed to mappings in "scope_to_claims_mapping"  and to "claims_supported" list as they were in 2.4.x.

2. Unlike in case of static scopes, this control now should allow for direct manual input of arbitrary claims' names (not bound to any specific attribute registered at this Gluu instance); those names are just simple strings which are pushed to OP's metadata "as is". At the same time, it still should allow to add claims using the old approach (by searching the list of registered attributes), just for convenience (most of the claims still will correspond to some known standard attribute)

3. The page should provide a hint that purpose of this new control is different from a similar control displayed for static scopes (that it's just a list of possible claims for RP's information, and the actual release is handled by the script exclusively). There could be a floating hint displayed if user hovers its cursor over some exclamation sign, or just a warning displayed on the page somewhere near the control.

**Comment by yurem** [comment]
Implemented alternative solution which conform dynamic copes idea. New dynamic scope script should has new method `getSupportedClaims`. Example:
```
    def getSupportedClaims(self, configurationAttributes):
        return Arrays.asList("work_phone")
```
Plus to tell Script Manager that it's new script version you should increase version number in `getApiVersion` method. Example:
```
    def getApiVersion(self):
        return 2
```
