### ISSUE TITLE
Fields don't match in userinfo and entrospection endpoints' responses

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#770]
#Environment:

CentOS 7.4, gluu-server-3.1.2-1-4.centos7

Preconditions:

1. A test Gluu instance is deployed
2. A test OIDC RP is deployed
3. The RP is configured to use the Gluu Server and any OIDC flow which assumes `userinfo` endpoint will be contacted. Client's properties at Gluu are more or less standard.
4. Means to recover `access_token` and see full `userinfo` response  to use in subsequent test introspection request are required (any kind of traffic monitoring tool will do)

Steps to reproduce:

1. Initiate the flow and follow it to its completion. Copy the raw answer received from `userinfo` enpoint (JSON object)
2. Recover `access_token` related to this flow and issue an introspection request to Gluu server with it, copying its answer (JSON object). Example request's text is provided below
```
POST /oxauth/restv1/introspection HTTP/1.1
Host: idp.host.loc
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer d4829cc0-c722-4652-9a99-e78f71b56d95
Content-Length: 70

token=d4829cc0-c722-4652-9a99-e78f71b56d95&token_type=access_token
```
3. Compare values of claims `username` and `sub` between the 2 JSON objects.

Result:
The mentioned claims don't match. Apparently they should be the same regardless where a claim appears. Moreover, what `introspection` returns in `username` looks more like "displayName" atually, and what it returns in "sub" looks like "username"

Here are both JSONs:

Introspection:
```
{"active":true,"scopes":["openid","user_name","uma_protection","test_roles","my_test_dynscope","email"],"client_id":"@!A278.6E49.B09B.50FD!0001!4832.B48C!0008!ACEE.1C7C","username":"Default Admin User","token_type":"bearer","exp":1521771396,"iat":1521771096,"sub":"admin","aud":"@!A278.6E49.B09B.50FD!0001!4832.B48C!0008!ACEE.1C7C","iss":"https://idp.host.loc","jti":null,"acr_values":null}
```

Userninfo:
```
{"inum":"@!A278.6E49.B09B.50FD!0001!4832.B48C!0000!A8F2.DE1E.D7FB","sub":"a3f20e08-8126-4c05-bb41-01dec08cd880","user_name":"admin","email_verified":"true","email":"admin@idp.host.loc"}
```

**Comment by yuriyz** [comment]
Fixed in 3.1.3
