### ISSUE TITLE
School Dude Work Center Login

### ISSUE THREAD

**Issue by critchie55** [GluuFederation/oxAuth#774]
My Company uses School Dude to manage our work order and Pm's and I use the Work Center App on my Android phone to login. We'll at some point the Management Team added this SSO software and has been working fine until the other week. Now, I cannot login with my phone. The message I get is as follows; 

"SSL Error - Android detected a problem with the SSL certificate on your Single Sign-On page and is unable to proceed. Please correct the problem and try again."

I've contacted my IT Dept and they either don't care or don't know how to fix this issue. Can someone here help me?
Thanks in Advance,
Carl Ritchie - Facilities Technician

**Comment by willow9886** [comment]
Hi Carl,

We have no control over it... so there's not much we can do. Gluu publishes open source software, and organizations use it as they see fit. 

Best of luck!
