### ISSUE TITLE
Use of SHA-1 in JweEncrypterImpl.java and JweDecrypterImpl.java

### ISSUE THREAD

**Issue by ptsankov** [GluuFederation/oxAuth#780]
The above implementations use the older SHA-1 hash function:

```
MessageDigest sha = MessageDigest.getInstance("SHA-1");
``` 

SHA-1 is considered insecure and it is suggested to switch to a newer version.

**Comment by yurem** [comment]
@qbert2k can you review this update. I've changed SHA-1 -> SHA-256

**Comment by qbert2k** [comment]
@yurem: It's working fine.

**Comment by yurem** [comment]
@qbert2k Thank you for feedback.
