### ISSUE TITLE
Add new endpoints for FIDO 2 / W3C web authentication

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxAuth#781]
https://fidoalliance.org/specs/fido-v2.0-ps-20170927/fido-client-to-authenticator-protocol-v2.0-ps-20170927.html

**Comment by elukewalker** [comment]
@yurem let me know if there is anything I can do to help add FIDO2 support.

**Comment by yurem** [comment]
@elukewalker I'm planning to work on this on next week. Are there FIDO 2.0 spec? I only found out v 1.2.
Do you know what changed in FIDO since 1.x

**Comment by elukewalker** [comment]
Hi @yurem I consider FIDO2 to be composed of two open standards:
1. [FIDO Client To Authenticator Protocol 2.0 (CTAP2)](https://fidoalliance.org/specs/fido-v2.0-id-20180227/fido-client-to-authenticator-protocol-v2.0-id-20180227.html) and,
2. [W3C Web Authentication (WebAuthn)](https://www.w3.org/TR/webauthn/)

Note: I will refer to the FIDO U2F Client To Authenticator Protocol 1.2 as CTAP1.

The main differences between FIDO U2F and FIDO2 are:
1. W3C WebAuthn standardizes how browsers create and use attested, scoped, public key-based credentials. This is enabling broader adoption beyond just Chrome.
2. CTAP2 allows credentials to be stored in authenticators, like a YubiKey. These are called [resident keys](https://www.w3.org/TR/webauthn/#client-side-resident-credential-private-key).
3. CTAP2 allows user verification, e.g. a user can set a PIN which is required to unlock cryptographic operations
4. The combination of resident keys and user verification enables multifactor-authentication from a single authenticator. This can enable interesting use cases such as passwordless authentication.
5. CTAP2 also includes a hmac-secret extension which can be used to help implement offline authentication with an authenticator, e.g. YubiKey.
6. CTAP2 is backwards compatible with CTAP1.

Yubico has some[ videos](https://www.yubico.com/why-yubico/for-developers/developer-videos/) which go into more detail and a [java-webauthn-server](https://github.com/Yubico/java-webauthn-server) which implements the WebAuthn relying party operations.

Don't hesitate to reach out if you have any questions. I am happy to help.

**Comment by elukewalker** [comment]
Any update? Let me know when you have a branch I can spin up an test out.

**Comment by yurem** [comment]
![screenshot - 12_19_2018 11_46_49](https://user-images.githubusercontent.com/6104200/50209091-f820a980-0383-11e9-8f89-e894942adec0.png)

**Comment by yurem** [comment]
Configuration endpoint: https://<server>/oxauth/restv1/fido2/configuration
