### ISSUE TITLE
Add support for CacheProvider/Redis authentication

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#785]
Right now the CacheProvider(**) is only accepting `hostname:6379` to connect Redis server. 
A request came from customer to add authentication section for Redis server. 

(**) 

```
oxCacheConfiguration: {"cacheProviderType":"IN_MEMORY","memcachedConfiguration":{"servers":"localhost:11211","maxOperationQueueLength":100000,"bufferSize":32768,"defaultPutExpiration":60,"connectionFactoryType":"DEFAULT"},"inMemoryConfiguration":{"defaultPutExpiration":60},"redisConfiguration":{"redisProviderType":"STANDALONE","servers":"localhost:6379","defaultPutExpiration":60}}
```

**Comment by yurem** [comment]
According to the Redis library code it's possible to implement.
1. RedisStandaloneProvider should use constructor with password to create pool.
2. JedisShardInfo uses URI which contains password too. Example:
```
new JedisShardInfo(new URI("redis://:foobared@localhost:6379"))
```

What do you think to use this URI instead of server:port?

**Comment by mzico** [comment]
Noted... thanks @yuriyz

**Comment by mzico** [comment]
@yuriyz / @yurem  : Is this added in oxTrust Web UI or just 'mechanism' added in 3.1.3?

**Comment by yuriyz** [comment]
@mzico added ticket to get it covered in oxtrust https://github.com/GluuFederation/oxTrust/issues/1340

**Comment by yuriyz** [comment]
The workaround in 3.1.3 version is to set password directly in ldap.
E.g.
```
"redisConfiguration":{"servers":"localhost:6379", "defaultPutExpiration": 60, "password": "mypassword"}
```
