### ISSUE TITLE
Supply more external methods for client operations

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#787]
Allow to call external logic when client updates take place

Currently we have [ExternalDynamicClientRegistrationService](https://github.com/GluuFederation/oxAuth/blob/version_3.1.3/Server/src/main/java/org/xdi/oxauth/service/external/ExternalDynamicClientRegistrationService.java) but it’s only called upon client registration.

We should add more methods.

**Comment by yurem** [comment]
I've updated script in setup to conform new API: https://github.com/GluuFederation/community-edition-setup/commit/8f3dd1d214418cac5e31245d8944bf64861af17e
