### ISSUE TITLE
Add support for id token upon token refresh

### ISSUE THREAD

**Issue by leheljozsef** [GluuFederation/oxAuth#789]
It is not mandatory but it's used more and more by applications doing OIDC integration (example: Kubernetes). It would be a great addition to the oxAuth token refresh capability.

**Comment by nynymike** [comment]
There is discussion on OIDC mailing list about this issue. I'm not sure what I think about it yet.

**Comment by nynymike** [comment]
id_token should not be refreshed. It is a record of the authentication event, which did not change.
