### ISSUE TITLE
ID token's audience claim should be a string when there is only one value

### ISSUE THREAD

**Issue by bhammond604** [GluuFederation/oxAuth#790]
The value of the ID token's audience claim is currently represented as an array (['AUDTOKEN']), even if there is only one value, which has been causing errors when testing against OpenID's certification testing tool (https://github.com/openid-certification/oidctest).

Instead of an array, the value of the audience token should be a string ('AUDTOKEN') when there is only one value.

**Comment by qbert2k** [comment]
The specs says:

> In the general case, the aud value is an array of case sensitive strings. In the common special case when there is one audience, the aud value MAY be a single case sensitive string.

We can make this **configurable** to allow select the desired behavior because it can be complicated for some customers to make an implementation that handles both response cases.

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/67
