### ISSUE TITLE
User should be redirect to error page instead of login when an exception occurs during external authentication

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxAuth#796]
# Description

Currently user is redirected to login page when exception occurs during external authentication.
Normally, user should be redirected  to error page.

```
  public String executeExternalGetPageForStep(CustomScriptConfiguration customScriptConfiguration, int step) {
        try {
            log.debug("Executing python 'getPageForStep' authenticator method");
            PersonAuthenticationType externalAuthenticator = (PersonAuthenticationType) customScriptConfiguration.getExternalType();
            Map<String, SimpleCustomProperty> configurationAttributes = customScriptConfiguration.getConfigurationAttributes();
            return externalAuthenticator.getPageForStep(configurationAttributes, step);
        } catch (Exception ex) {
            log.error(ex.getMessage(), ex);
        }

        return null;
    }
```

https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/auth/Authenticator.java#L324

**Comment by mzico** [comment]
@yurem @syntrydy : Do you think it's possible to patch 2.4.4 sp3 ? We need that one customer's production.

**Comment by syntrydy** [comment]
For me yes, since the adjustment we have to do don't have touch their custom custom code. We can provide a patch.

Currently [this customer](https://support.gluu.org/identity-management/5085/redirect-to-oxauthloginhtm/#at32801) need the patch .

**Comment by yurem** [comment]
Fixed
