### ISSUE TITLE
Implemented migration password script from BCRYPT to SSHA

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#797]
User passwords migration from 3.0.x-3.1.2 isn't possible because OpenDJ 3.0 not supports BCRYPT passwords scheme.
We need to do next:
1. Add new custom script `pwd_migration`
2. I should check if user password in BCRUPT format.
3. If the password is bcrypted it should check submitted password with hash from LDAP.
4. Send user LDAP request to persist password to store it in new format.

**Comment by willow9886** [comment]
@yurem is this related or duplicate to https://github.com/GluuFederation/oxAuth/issues/753  ?

**Comment by yurem** [comment]
@willow9886 yes, it's about same issue

**Comment by yurem** [comment]
Done, we have updated OpenDJ and custom script. Both support BCRYPT now
