### ISSUE TITLE
Relax log level when claims gathering script name is blank

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#798]
In UMA, when the corresponding authz script returns an empty name in `getClaimsGatheringScriptName` method, we are [logging](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/uma/service/UmaNeedsInfoService.java#L87) an error statement.

Some users getting confused with this error when the interactive claims gathering does not apply as in the case of SCIM or passport (see this support [ticket](https://support.gluu.org/installation/5386/umaclientauthzrptpolicypy-unneeded-error-message-in-oxauthlog/) for more contextual info).

Can we use `warn` there?

The ticket points out something interesting about no errors appearing if the method simply returns an arbitrary string?. Can you verify this is so?

**Comment by yuriyz** [comment]
@jgomer2001 'getClaimsGatheringScriptName' returns script name which will be invoked when need_info error is returned. It means that it is runtime information. If we have situation when we don't neeed claims gathering maybe we can introduce constant, like 'NO_SCRIPT' which makes it very verbose to end-user that no claims gathering is involved. What do you think?

**Comment by jgomer2001** [comment]
I agree, it's a more expressive way

**Comment by yuriyz** [comment]
Done for 3.1.4 amd master. Added 'no_script' check. It is possible to return this value inlined or otherwise constant from 'UmaConstants'.
