### ISSUE TITLE
Getting NullPointerException whlie authorizing user

### ISSUE THREAD

**Issue by ashtexsolutions** [GluuFederation/oxAuth#801]
Hi,

I am trying to integrate oxd-https extension while authorizing the users from OP, but getting error when trying to authorize the user i.e I am using get-auhtorization-url endpoint but when click on login button on AS(Authorization Server) then it gives NullPointerException error.

Then i figured out that `skipAuthorizationForOpenIdScopeAndPairwiseId` configuration property on oxauth was set to false so i set it to true and it works fine.Now is it necessary to set this property true or not?

Here is the reference support ticket for that issue:
https://support.gluu.org/authentication/5436/getting-nullpointerexception-whlie-authorizing-user/

As per reference ticket this it is not necessary to set this property true.Please if you can have a look.

Regards, Usman

**Comment by nynymike** [comment]
Yuriy, can you take a look at this. I'm not sure if  it's a bug.

**Comment by yuriyz** [comment]
@nynymike fixed. @qbert2k Please make sure you check on null configuration properties otherwise we can get NPE as described in this ticket.
