### ISSUE TITLE
NPE during end_session if client is expired and does not exist in LDAP anymore

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#802]
The more information with stack trace is here: https://github.com/GluuFederation/gluu-gateway/issues/94

NPE occurs here:
https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/session/ws/rs/EndSessionRestWebServiceImpl.java#L203-203

**Comment by yuriyz** [comment]
Fixed in 3.1.4 and in master.
