### ISSUE TITLE
"acr_values" contains "null" in introspection endpoint's response

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#803]
Environment:

CentOS 6.9, gluu-server-3.1.3-final

Preconditions:

1. A fully configured OP(Gluu)+RP setup using authz code OIDC flow
2. "uma_protection" scope is amongst scopes requested by RP
3. Specific auth method is requested by RP with `acr_values=` parameter

Steps to reproduce:

1. After a successful OIDC flow harvest issued `access token`
2. Use `access token` at introspection endpoint. Below is an example of such request:
```
POST /oxauth/restv1/introspection HTTP/1.1
Authorization: Bearer 77d9f5ce-3c8c-4260-b460-3014f60fa564
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: mytrue.host.loc
Connection: close
User-Agent: Paw/3.1.5 (Macintosh; OS X/10.12.6) GCDHTTPRequest
Content-Length: 71

token=77d9f5ce-3c8c-4260-b460-3014f60fa564&token_type_hint=access_token
```

Results:
In the endpoint's response "acr_values" contains "null" instead of a name of a method used for authentication:
```
{"active":true,"scopes":["openid","user_name","profile","uma_protection","email"],"client_id":"@!84B1.7441.57C3.98B0!0001!76A2.0919!0008!DE0E.A0DC.FD5A.8B9D","username":"Default Admin User","token_type":"bearer","exp":1526068893,"iat":1526068593,"sub":"2rFr27ll8S5GOjYU6-4duf_efTfaVWMEoYvzHhhooow","aud":"@!84B1.7441.57C3.98B0!0001!76A2.0919!0008!DE0E.A0DC.FD5A.8B9D","iss":"https://mytrue.host.loc","jti":null,"acr_values":null}
```

**Comment by yuriyz** [comment]
Fixed for 3.1.4 and in master.
