### ISSUE TITLE
pre-fix value for access token

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#804]
A customer has two instances of Gluu (one employee and one for citizens & enterprise). For token validation and data retrieval from the backend, they need to know where the taken came from, so as not to duplicate every call. Can we create an oxAuth JSON property that enables a string to be prefixed to each access token?

When complete, update private support ticket 5444

**Comment by yuriyz** [comment]
@nynymike with #803 we always know what CE created access token (by `iss` claim from JWT). Do we really need separate handling by prefix?

**Comment by yuriyz** [comment]
Mike: Bearer tokens are still going to be the default. Prefix should only be for bearer tokens.

**Comment by yuriyz** [comment]
Mike: push the prefix issue to 4.0, and we’ll evaluate if it’s still necessary

**Comment by nynymike** [comment]
nice to have feature.... wait for customers to ask for it again?

**Comment by yuriyz** [comment]
Since now we have access_token as JWT customer can pass any information inside access token. So original use case in description is covered. Closing it.
