### ISSUE TITLE
OTP 2FA / enrollment page + login page

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxAuth#807]
see https://github.com/GluuFederation/oxTrust/issues/970

**Comment by syntrydy** [comment]
![screenshot from 2018-05-16 10-55-47](https://user-images.githubusercontent.com/7513418/40110499-01b44088-58f8-11e8-972d-8a68bcf5c9ae.png)

**Comment by syntrydy** [comment]
![screenshot from 2018-05-16 13-31-48](https://user-images.githubusercontent.com/7513418/40117015-8ec45f5c-590d-11e8-90c9-659d6dbb66d3.png)


I think it is okay for this page

**Comment by natt-tester** [comment]
@syntrydy, @yurem: it's not a priority now, but it would be nice to have everything centered to boost the UX. The red arrows and boxes show where to adjust the layout:

![gluu_otp](https://user-images.githubusercontent.com/38302725/44519262-e0a41d80-a70f-11e8-8443-28406cfd3430.png)
