### ISSUE TITLE
Add support for account switching

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxAuth#809]
Add support for prompt = select_account

See ticket: https://support.gluu.org/access-management/5403/authorize-with-select-account/

**Comment by mtgluu** [comment]
Javier is this related to account chooser? (http://openid.net/wg/ac/)

**Comment by yuriyz** [comment]
It's duplicate of https://github.com/GluuFederation/oxAuth/issues/1290 which is already implemented in 4.2.
