### ISSUE TITLE
Registered user but not yet active can retrieve authorization code

### ISSUE THREAD

**Issue by dejwsz** [GluuFederation/oxAuth#81]
Hi,
don't know if it is an intended feature. An user with gluuStatus 'register' (so not 'active') is able to request and retrieve open id authorization code. I think only active users should be able to do this. How do you think? If you check the code of the AuthenticationService class in the package org.xdi.oxauth.service then you can find there the checkUserStatus method which returns true for any value different from null or inactive.
Maybe this is the problem here? Wrong condition in this place in the mentioned class? Only gluuStatus 'active' should cause returning true value.

**Comment by yurem** [comment]
This development war: http://ox.gluu.org/maven/org/xdi/oxauth-server/3.0.2-SNAPSHOT/oxauth-server-3.0.2-SNAPSHOT.war
Contains this method update: https://github.com/GluuFederation/oxAuth/commit/9c87b39e0a42c33029042eb984fcde7baa097620

**Comment by dejwsz** [comment]
OK we've been testing only stable releases so far.
