### ISSUE TITLE
Add Opentracing support

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#810]
Check this out: http://opentracing.io/documentation/pages/instrumentation/instrumenting-frameworks
opentracing.io
Instrumenting Frameworks · Opentracing

**Comment by martynaslawinska** [comment]
Upon accessing the link, `404 Not Found` pops up.
Here is the updated link: https://opentracing.io/docs/best-practices/instrumenting-frameworks/

The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/66
