### ISSUE TITLE
Add startSession and endSession methods to application_session script

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#817]
`application_session` script. Here is [sample](https://github.com/GluuFederation/community-edition-setup/blob/master/static/extension/application_session/SampleScript.py#L35).

oxAuth calls it after getting `end_session` request. In 3.1.4 we can add additional method to this interface to call it on `authenticated` session creation. Both method will get SessionId object with all attributes including remote_ip.

This `application_session` script can store information about user sessions. Later authentication script can request data from  this store and check if there is active authenticated session.

We should add two methods:
 - startSession
 - endSession

Note there is an associated private gluu support issue: 5457

**Comment by yurem** [comment]
I've added new method and updated script in CE
