### ISSUE TITLE
Remove hardcoded code from passport page

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#821]
We have this problematic [line](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/webapp/auth/passport/passportlogin.xhtml#L313). I think instead of checking if there are only hard-coded methods it should just check if this is `idp` provide and use for it specif redirect url.

Also we can't use hard-coded image names [here](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/webapp/auth/passport/passportlogin.xhtml#L333). I think strategy should have optional field to specify image name/path.

There is more information about [this ](https://support.gluu.org/single-sign-on/5566/oidc-passport-strategy/#at34471) in issue.

**Comment by jgomer2001** [comment]
Fixed (see https://github.com/GluuFederation/gluu-passport/issues/34)
