### ISSUE TITLE
Authenitcator should not use "@!" to distingusih use/client credentials.

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#823]
In [this](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/auth/Authenticator.java#L145) line there is hardcore rule about client/user names convention. I think we can update code to avoid this hard coded convention.

**Comment by yurem** [comment]
@qbert2k Do you think it's possible to do?

**Comment by nynymike** [comment]
Don't see this line anymore in  `oxauth/auth/Authenticator.java#L145`
