### ISSUE TITLE
Client-specific access token expiration

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#830]
Enable client-specific access token expiration. 

Need a corresponding issue in [oxTrust](https://github.com/GluuFederation/oxTrust)

**Comment by natt-tester** [comment]
@qbert2k, when I try to add  Access Token Lifetime in oxtrust (leave it empty, 0 or, say, 123) and click Update, an error message says:
<img width="432" alt="obraz" src="https://user-images.githubusercontent.com/38302725/50361594-68862100-0564-11e9-9c61-e54186eb11fd.png">

There's an EntryPersistenceException in the log:
[oxtrust(2).log](https://github.com/GluuFederation/oxAuth/files/2704118/oxtrust.2.log)

**Comment by qbert2k** [comment]
There was a commit overriding my code changes in project community-edition-setup (LDAP Schema).

I have fixed it in commit: https://github.com/GluuFederation/community-edition-setup/commit/a77763641d4dc1a33afedcf94876cd39932b12eb
