### ISSUE TITLE
Support for spontaneous scopes

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#839]
There is a requirement for payments to send a transaction id as part of the scope. For example:
`pis:4685456787` (where 4685456787 is the id of a certain resource)
or 
`sign:MmU5OTc1ODU0ODk3MmE4ZTg4MjJhZDQ3ZmExMDE3ZmY3MmYwNmYzZmY2YTAxNjg1MWY0NWMzOTg3MzJiYzUwYw==,RXhhbXBsZSBDb250cmFjdA==`

Where the first parameter has a base64url encoded has value, second parameter after, is a label of the document to be signed.

The client should be configured to accept "spontaneous scopes"--as normally any non-registered scope should be rejected. 

We also need to add a "spontaneous scope interception script", and map this script in the client configuration.

**Comment by yuriyz** [comment]
It is good idea to design it while we are re-factoring scope handling within this ticket https://github.com/GluuFederation/oxAuth/issues/756.

**Comment by qbert2k** [comment]
@yuriyz @nynymike 
Please provide more details about the requirement.

**Comment by yuriyz** [comment]
I will take over this feature. Re-scheduling it on 4.1 since due date of 4.0 code freeze was yesterday.

**Comment by altexy** [comment]
> @yuriyz @nynymike
> Please provide more details about the requirement.

I agree that the requirements are not fully detailed.

One point:

As I understand from discussion here https://github.com/GluuFederation/oxAuth/issues/1133#issuecomment-521127138
we plan to persist spontaneous scopes.

If it used as transaction part in a real-life system the number of registered scoped would increase indefinitely, IMO it is unacceptable.
We should think about the TTL of spontaneous scopes.

**Comment by yuriyz** [comment]
Right, in client config we should give ability to specify lifetime of spontaneous scopes.

**Comment by altexy** [comment]
> Right, in client config we should give ability to specify lifetime of spontaneous scopes (if no lifetime specified then indefinite -> scope will not be cleaned up).

IMO we should have configurable default TTL instead of indefinite.

**Comment by yuriyz** [comment]
Global oxauth configuration:
- `spontaneousScopeLifetime` - spontaneous scope lifetime

Client :
- `allow_spontaneous_scopes` - boolean, whether to allow spontaneous scopes for client
- `spontaneous_scopes` - list of spontaneous scopes

New scope type : `spontaneous`.

**Comment by yuriyz** [comment]
Docs added https://github.com/GluuFederation/docs-ce-prod/commit/45011ef5d13911b1c37fde0f31994b54b8c3ac3f

**Comment by yuriyz** [comment]
Implemented in master (4.2)

**Comment by altexy** [comment]
@yuriyz at which time the "spontaneous scope interception script" is Invoked?
- when token with spontaneous scope is requested from GS?
- or when access token is introspected?

**Comment by yuriyz** [comment]
It is invoked during token request.

**Comment by altexy** [comment]
thanks

**Comment by sahiliamsso** [comment]
allowSpontaneousScopes and spontaneousScopes are not saved in client settings and reverted to default/blank after hitting save.

![image](https://user-images.githubusercontent.com/21104811/84215576-afd3da80-aa94-11ea-9a35-4cd25b07e564.png)

**Comment by yuriyz** [comment]
@sahiliamsso it's UI issue, so https://github.com/GluuFederation/oxTrust/issues/1890 should be reopened.

**Comment by yuriyz** [comment]
I will take over

**Comment by yuriyz** [comment]
I've checked it on latest 4.2. It perfectly works. Changes are saved (LDAP reflects changes as well as UI).
