### ISSUE TITLE
Bug: extra error string

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxAuth#841]
Please refer to the GIF: there's an extra string upon using invalid credentials in https://ce-dev6.gluu.org/oxauth/login.

![2018-07-03_20h05_31](https://user-images.githubusercontent.com/38302725/42214463-f3c8552c-7efe-11e8-8ab4-01865d339e8a.gif)
![2018-07-03_20h04_40](https://user-images.githubusercontent.com/38302725/42214493-084b3500-7eff-11e8-8c5d-b189fc8f2517.png)

**Comment by yurem** [comment]
![screenshot 2](https://user-images.githubusercontent.com/6104200/51673450-1b6ff180-1fdf-11e9-8a81-9281cd2f8ee4.png)

Fixed in 3.1.5
