### ISSUE TITLE
Broken server side test marked as successfull

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#845]
Out server side tests has many failure but due to bug (or incompatibility) in test suite they all marked as successful.

**Comment by yuriyz** [comment]
@yurem how is it possible? Is it something with testng reporting or is it jenkins plugin ?

**Comment by yurem** [comment]
This caused by bug/conflict between old Arquillian/TestNG
After Arquillian/TestNG and fixing libs conflicts tests works well.

But now we need to fix broken tests

**Comment by yurem** [comment]
Suite fixed in 3.1.4
