### ISSUE TITLE
Fixing broken server side tests for 3.1.4

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#851]
There are many broken server side tests for 3.1.4. They must be fixed before Token Binding feature is done.
https://github.com/GluuFederation/oxAuth/issues/845

**Comment by qbert2k** [comment]
Last failing test org.xdi.oxauth.comp.GrantServiceTest.testCleanUp

https://ox.gluu.org/jenkins/job/oxAuth_3.1.4/126/

**Comment by yuriyz** [comment]
all tests are successfully passed for 3.1.4 https://ox.gluu.org/jenkins/job/oxAuth_3.1.4/135/
