### ISSUE TITLE
CAS logout with oxAuth-session script ( application_session ) 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#853]
Can we write an application_session interception script that calls the CAS /logout page? Is it front channel? If so, can we render it in one of the iFrames?

**Comment by mzico** [comment]
@yurem @yuriyz @nynymike : what do you think?

**Comment by yurem** [comment]
In 3.1.4 application_session script there are 2 methods:
```
    def startSession(self, httpRequest, authorizationGrant, configurationAttributes):
    def endSession(self, httpRequest, authorizationGrant, configurationAttributes):
```
oxAuth calls them on authorization success and on end_session endpoint event.

In oxAuthRP there is demo [iframe](https://github.com/GluuFederation/oxAuth/blob/master/RP/src/main/webapp/rpiframe.xhtml). It waits for sesison update.

Hence oxAuth provides 2 ways to notify about session state update. Why do you think we should update oxAuth for this? From my point of view it's CAS issue.

@mzico can you share flow which are you going to implement?

**Comment by yurem** [comment]
@mzico I've changed milestone to 4.0 because it's not clear what do to with this issue now

**Comment by willow9886** [comment]
Closing this issue. Re-open or create new after further testing.
