### ISSUE TITLE
Update lock account to include expiration

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#863]
We should update this script to include a configurable lock time, for example 3 minutes by default. 
  https://github.com/GluuFederation/oxAuth/tree/master/Server/integrations/basic.lock.account

The script should check to see if the account is locked, and if there is a lock, when it expires. The lock can be written to the cache:

**Comment by natt-tester** [comment]
@sahiliamsso, please also take a look at #877.

**Comment by yurem** [comment]
@sahiliamsso 

Here is bean and sample which you can use for implementation:
```
from import org.xdi.service import CacheService

...

        cacheService= CdiUtil.bean(CacheService)

	object_to_store = "{'locked': true}"
	# First param is how long keep object in cache, second one is key, last one is any object to store
        cacheService.put(60, "user_lock_xyz", object_to_store);


        object_from_store = cacheService.get(null, "user_lock_xyz");
	if object_from_store != None:
		# User is still locked

```

**Comment by sahiliamsso** [comment]
@natt-tester - Please validate.

**Comment by yurem** [comment]
Can we use "lock_user_" + user_name key? This should help to avoid collisions in future

**Comment by sahiliamsso** [comment]
Done, Please check.
