### ISSUE TITLE
Customized logo should apply to every public facing pages

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxAuth#864]
# Description

When custom logo is defined in /opt/gluu/jetty/oxauth/custom/static/img/  is should apply automatically to public facing pages like the login page and passportlogin page.

**Comment by natt-tester** [comment]
@syntrydy, I've just changed the logo and it's shown on the login/passport login page, but it's missing from the user registration page:
<img width="732" alt="public_register" src="https://user-images.githubusercontent.com/38302725/45870991-a0e45a80-bdcf-11e8-96ed-44f0a74f32bb.png">

Please change it in all the user-facing pages.
