### ISSUE TITLE
token introspection interception script

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#868]
Clients may want to return dynamic claims or other information from token introspection. The most flexible way to accommodate this request is to expose an interception script for OAuth token introspection.

**Comment by yuriyz** [comment]
Moved to 4.0, if we will have time I will include it into 3.1.5.

**Comment by yuriyz** [comment]
Introspection interception scripts support is added to oxauth, oxtrust and in setup. Docs added as well. Changes made in both 3.1.5 and merged into 4.0 version.
@sahiliamsso please test it. Docs : https://gluu.org/docs/ce/3.1.5/admin-guide/custom-script/
