### ISSUE TITLE
Return custom client and user claims in access token introspection / JWT

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#869]
The client can be configured to return custom client claims (stored in the database)

We also need to specify that certain user claims should be returned.

GUI enhancement here: https://github.com/GluuFederation/oxTrust/issues/1134

**Comment by nynymike** [comment]
This can be accomplished in interception script, but should perhaps be standardized, to make it easier to configure in oxTrust.

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/64
