### ISSUE TITLE
Work with photo attributes

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#87]
There is problem with picture attributes when application request profile scope which contains photo claim. It process this attribute value as ordinary attribute value. As result id_token size is 340Kb. Hence after user authorization redirects not working properly.

I think in all places except user info we need to return path in images repo or picture GUID. But user info endpoint should allows return photo. This endpoint should works without changes.

We need to start work on this issue after resolving: https://github.com/GluuFederation/oxTrust/issues/135

**Comment by nynymike** [comment]
It wouldn't make sense to return a path to the user in the id_token. In fact, exposing file system details is problematic for security. Except in the user_info endpoint, we should just not return this user claim.

**Comment by nynymike** [comment]
Somehow, if it's been six years, I think it's ok.
