### ISSUE TITLE
OTP login failure -- 2 error messages

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxAuth#870]
Please refer to the picture: shouldn't we only show one error message in a visible manner? Right now there are two and the UX isn't great. 

Maybe we can get rid of the top one, but highlight the bottom one and make it a bit bigger?

<img width="1346" alt="two_fail_error" src="https://user-images.githubusercontent.com/38302725/44512386-aaf63900-a6fd-11e8-957f-83b9b2874763.png">

**Comment by yurem** [comment]
I will take a look on this

**Comment by natt-tester** [comment]
Also mentioned in #841.
