### ISSUE TITLE
SuperGluu screen throws error

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxAuth#874]
The very first step of SuperGluu QR verification throws an error when the user doesn't scan the code within the given time.

Tested in Ubuntu 16.04 with gluu-server-3.1.4_1.Beta1:

<img width="1372" alt="error_supergluu" src="https://user-images.githubusercontent.com/38302725/44563169-5788f700-a7a0-11e8-8230-56d5500968bd.png">

[oxauth.log](https://github.com/GluuFederation/oxAuth/files/2316899/oxauth.log)

**Comment by yurem** [comment]
Can you attach oxauth.log and oxauth_script.log?

**Comment by natt-tester** [comment]
I can't find the package in the repo anymore, but I have been testing Ubuntu 16.04 with **gluu-server-3.1.4_1.Beta2** and at least this issue seems to be fixed. The QR codes reload when the time is up.

Hovewer, I did encounter one proxy error. Please refer to the attached logs:
[oxauth_script.log.zip](https://github.com/GluuFederation/oxAuth/files/2322750/oxauth_script.log.zip)
[oxauth.log.zip](https://github.com/GluuFederation/oxAuth/files/2322751/oxauth.log.zip)

<img width="1145" alt="ubuntu16_gserver3 1 4_proxy_error" src="https://user-images.githubusercontent.com/38302725/44645764-1735ad00-aa1c-11e8-8778-91f0d9cf3e5a.png">

**Comment by yurem** [comment]
@natt-tester is it your local server or public available one? For proper Super Gluu work you should use real DNS server name instead of adding host name to hosts file.

If needed I can explain how to use fake DNS server like to test Super Gluu with local VM.

**Comment by willow9886** [comment]
@yurem it might make sense to add those instructions to our documentation to reduce confusion

**Comment by yurem** [comment]
@natt-tester please open `Keys` section in mobile app and remove old key for this server. Also if there is sub-entry `ou=fido` under user entry in LDAP please remove it. Old keys migh from previous install might led to issue.

**Comment by yurem** [comment]
Here is method how to test Super Gluu locally without public server.

This method allows to test super Gluu locally, but it's based on MITM attack type. It's for developement purpouse only!!!

1. In VM settings change Network Adapter connection type from NAT to Bridget // CE and Mobile phone connected to WiFi should be in same local network
2. Log into VM and run in terminal `ifconfig` to get IP address of CE.
3. Install CE as usual
4. Enable Super Gluu
5. Update hosts file on machine where you run browser to log in. Example:
192.168.1.232	c67.gluu.info
6. Run ipconfig/ifconfig on machine where you are plannign to run DNS server.
7. Create dns.config file in folder where there is dedserver.jar. Exmaple file content:
u144.gluu.info.=192.168.1.232
8. Run DNS server using command like this: java -jar dedserver.jar
9. On mobile phone open WiFi connection details and specify DNS server IP which you get in step 6

10. Now you can test super Gluu.
11. After end of Super Gluu testing don't forget to change WiFi connection type on mobile phone to use automatic settings.

**Comment by natt-tester** [comment]
@yurem, I followed the instructions, but couldn't get it to work properly. I used a default linux server instead, testing SG on an Android and iOS devices. It crashed in the iphone and failed in the Android, and the flow in oxtrust was the following. Could somebody else please check it?

https://ufile.io/6n53w

**Comment by natt-tester** [comment]
Tested yesterday with the QA team, works fine.
