### ISSUE TITLE
Add better handling for session expired events

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/oxAuth#875]
When an oxAuth session expires, the server should take action and display a page that explains the situation to the user (similar to Google example shown below). 

Currently when the session expires, it's only clear to the user after they try to sign in. And they get taken to a pretty unhelpful Error Encountered page. 

Our improvement should save the user a round trip by explicitly telling them when their session has expired. Some javascript to present this page (so no reload necessary) is ideal. 

![image](https://user-images.githubusercontent.com/5271048/44620121-bad46100-a854-11e8-9b52-024f8ff3148a.png)

**Comment by yurem** [comment]
![screenshot 2](https://user-images.githubusercontent.com/6104200/45759795-5fb64400-bc31-11e8-8b02-16b19a06e94d.png)
This is how this page looks like after @syntrydy and my changes

**Comment by willow9886** [comment]
@yurem this doesn't address the issue. The page looks better, but is not an improvement in the user experience for expired sessions. @syntrydy can you please add additional details about implementation, which we had discussed?

**Comment by willow9886** [comment]
OK, we're going to address this issue further via this new issue marked for next version: https://github.com/GluuFederation/oxAuth/issues/906
