### ISSUE TITLE
406 from .well-known/openid-configuration

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#876]
Oxd accepts only plain/text for .well-known/openid-configuration call.
OpenId connect docs states that it should be "application/json".
When I'm connecting to different then Gluu, more strict IDP I get 406 error code.
Class OpenIdConfigurationClient line 31

Originally posted here https://github.com/GluuFederation/oxd/issues/226
If we have time we should include it into 3.1.4.

**Comment by kepuss** [comment]
https://github.com/GluuFederation/oxAuth/pull/882

**Comment by willow9886** [comment]
@yuriyz can you check the PR above and see if this can be closed?

**Comment by yuriyz** [comment]
oxauth client is corrected with PR, now it can accept both plain and json media types. Closing it.
