### ISSUE TITLE
Dead link in Super Gluu login

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxAuth#878]
Please refer to the screenshot -- the marked link doesn't take the user to the Android app:

<img width="949" alt="ubuntu16_gserver3 1 4_dead_link" src="https://user-images.githubusercontent.com/38302725/44646495-7dbbca80-aa1e-11e8-9421-65a895ec4cfe.png">

**Comment by willow9886** [comment]
https://play.google.com/store/apps/details?id=gluu.org.super.gluu&hl=en_US

**Comment by willow9886** [comment]
@natt-tester this is also presented by oxTrust.

**Comment by willow9886** [comment]
opened on oxTrust: https://github.com/GluuFederation/oxTrust/issues/1144
