### ISSUE TITLE
Weird password reset message

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxAuth#879]
It's possible to get this weird message when you click on the reset link in the email when you've already used it:

<img width="1363" alt="ubuntu16_gserver3 1 4_wrong_password_success" src="https://user-images.githubusercontent.com/38302725/44651254-350b0e00-aa2c-11e8-8794-9996cad1d5aa.png">

**Comment by willow9886** [comment]
@natt-tester can you provide adjusted content for the page to better explain the situation to the user? (and also we should move it to [oxTrust](https://github.com/gluufederation/oxTrust/issues). Thanks!

**Comment by natt-tester** [comment]
@willow9886, @syntrydy, opened here with an example: https://github.com/GluuFederation/oxTrust/issues/1152
