### ISSUE TITLE
Implement token expiration logic for password reset

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxAuth#881]
Steps:

1. As a user I request a password reset several times ("Forgot your password?" flow)
2. I use the most recent one and change my password
3. I  click one of the older ones

Expected: I shouldn't be able to use any older token as the most recent one has already been used. Only the most recent token should be valid for security reasons.

Actual: I'm able to use all of the older tokens to change the password and log in to CE.

**Comment by yurem** [comment]
Config update in CE:
https://github.com/GluuFederation/community-edition-setup/commit/67a5f8c5dacfa6741592275d5f66ec7d15469a65
