### ISSUE TITLE
Turn off client expiration by default and remove ability to update expiration via endpoint

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#883]
Turn off client expiration by default and remove ability to update expiration via endpoint. It should be possible to turn on expiration back if needed.

Mike: turn off client expiration by default, because it’s not really protecting anyone, and it’s causing lots of problems. If a client wants it, let them explicitly enable it.

**Comment by yuriyz** [comment]
done in 3.1.5 and merged into 4.0

**Comment by natt-tester** [comment]
@yuriyz, is the value for non-expiring clients 0 or -1? Oxtrust still describes it as 0:
<img width="630" alt="obraz" src="https://user-images.githubusercontent.com/38302725/50132156-f7095280-0285-11e9-9361-4060e8467c26.png">

**Comment by yuriyz** [comment]
@natt-tester both 0 and -1 leads to non-expiring clients. But yes, I agree, default value and description should be consistent. Corrected description so now both default value and description refers to `-1`.

**Comment by yuriyz** [comment]
I'm not sure it's good idea to change it from 0 to -1 because it may break some client code. I will add clear not to docs that both `0` and `-1` means not expired client.

**Comment by yuriyz** [comment]
@natt-tester https://github.com/GluuFederation/docs-ce-prod/commit/5d8798a6cb15f4fce214bb16b49319262a3d0bdf
