### ISSUE TITLE
No info about blocked account

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/oxAuth#887]
Transferring the issue https://github.com/GluuFederation/oxTrust/issues/1145 here.

**Comment by natt-tester** [comment]
@syntrydy, @yurem, it seems the change isn't present in the RC1. Could you make sure it gets there?

**Comment by syntrydy** [comment]
Use the new script https://github.com/GluuFederation/oxAuth/blob/3c924a15ad577a8ceeb7701c1ead82f8f8916357/Server/integrations/basic.lock.account/BasicLockAccountExternalAuthenticator.py

**Comment by natt-tester** [comment]
@syntrydy the new script works, but the behavior needs improvement as reported in #897.
