### ISSUE TITLE
Support for Software Statement Protected Client Registration

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#89]
Software statements in OAuth2 enable an OP to issue a JWT token that authorizes a client to register. It provides a mechanism between open dynamic client registration, and manual client registration. See [OAuth2 dynamic registration software statements](https://tools.ietf.org/html/draft-ietf-oauth-dyn-reg-30#section-2.3).

Talk of software statements profile has been started at the MODRNA WG at the OIDF (a profile of openid connect for mobile operators). Its just an [outline](https://bitbucket.org/openid/mobile/src/b85fc1f0b9b862c79715fd52b0436cebe696d3f3/draft-mobile-registration-01.txt?at=default&fileviewer=file-view-default#draft-mobile-registration-01.txt-155), but could be useful.

In order to implement this, I think we'd need a few features:
1. Ability of an oxTrust admin to create and revoke software statements
2. An API to obtain software statements that is protect by UMA
3. A configuration option to restrict dynamic client registration only to clients that present a valid software statement
4. An async service to revoke client credentails if a software statement expires or is invalidated.

**Comment by simonpinkney** [comment]
Couple of comments to discuss on SSA, since its pretty relevant for PSD2, if your familiar ...

1 USER    - OIDC Dynamic Registration need to be a public endpoint with or without SSA
2 ADMIN - OIDC Dynamic Registration needs to have the ability to have SSA turned on / off , via UI and REST
3 UMA for me is optional currently, but mandatory is oauth2/oidc to start with.

Happy to discuss

**Comment by nynymike** [comment]
I'm closing this issue. Software statements can be handled in dynamic client registration interception script. Management of software statements needs to be addressed in a more detailed, customer driven requirment analysis.
