### ISSUE TITLE
'loginPage' value 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#894]
As we discussed internally.. if any customer want to 'change' their default login link from `https://[hostname]/oxauth/login` to something else ( i.e. `https://[hostname]/something/login` ); does our provided oxTrust feature ( Configuration > Json Configuration > tab (oxAuth Configuration) > Field (loginPage) ) work properly? 

According to our research, it doesn't. 

Now the question is: do we want to keep this button / feature available in oxTrust? 
If not, let's remove it. BUT, one of our customer is asking for this changes. What should be our best approach? 

Ref ticket: https://support.gluu.org/customization/5970/use-of-loginpage-field-at-gluu-server-configuration-json-configuration-tab-oxauth-configuration/

**Comment by nynymike** [comment]
I think there are two questions here.

#### What should be the default http config deployment for CE?
I this case, I think our approach is correct. The goal for CE deployment is "quick and easy". So hitting the hostname of the server makes sense after the initial deployment. 

#### What are the options for customers who want to do a deployment where the components are "broken apart" or "componentized"

For a componentized deployment, I think it should be possible to deploy oxAuth in a different URL path, or even at the root fo the server. For example, https://accounts.google.com

**Comment by yurem** [comment]
I agree. If someone need to change `oxauth` context to another one he need to rename oxauth.war and update oxAuth configuration to conform new context path. It's our of scope for CE.
