### ISSUE TITLE
Cache clean service remove active Unathenticated Sessions

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#899]
Authenticator call SessionId service to force session lastUsedAt update on authentication failure: https://github.com/GluuFederation/oxAuth/commit/3f19cb94bdc4667e0457509b5e32aa22e56ce064

But cache service still clean up these session after Unathenticated session lifetime.

@natt-tester Thank you that you found this issue.

**Comment by yurem** [comment]
I can't reproduce it on ce-dev3. I have issue locally only. I think cache works good and we close this issue

**Comment by yurem** [comment]
@natt-tester can you retest it in new RC build?

**Comment by natt-tester** [comment]
@yurem, the proxy error is not reproducible in RC4 (Ubuntu16+Firefox).
