### ISSUE TITLE
oxAuth client should support HTTP proxy

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#9]
This sample code allows to create HttpClient which works through proxy server

<pre>
    public static HttpClient createProxyHttpClient(String proxyHost, int proxyPort, String proxyUser, String proxyPassword) throws KeyManagementException, UnrecoverableKeyException, NoSuchAlgorithmException, KeyStoreException {
        SchemeRegistry registry = new SchemeRegistry();
        registry.register(new Scheme("http", 80, PlainSocketFactory.getSocketFactory()));
        registry.register(new Scheme("https", 443, SSLSocketFactory.getSystemSocketFactory()));

        ClientConnectionManager clientConnectionManager = new PoolingClientConnectionManager(registry);
        DefaultHttpClient httpClient = new DefaultHttpClient(clientConnectionManager);
        httpClient.getParams().setParameter(org.apache.http.conn.params.ConnRoutePNames.DEFAULT_PROXY,
                new HttpHost(proxyHost, proxyPort, "http"));

        // The proxy has optional authentication. The authentication information was set using the following code:
        if (StringHelper.isNotEmpty(proxyUser) && StringHelper.isNotEmpty(proxyPassword)) {
            httpClient.getCredentialsProvider().setCredentials(new AuthScope(proxyHost, proxyPort),
                    new UsernamePasswordCredentials(proxyUser, proxyPassword));
        }

        return httpClient;
    }
</pre>

Also all oxAuth clients allows to set specified executor. Hence in order to use proxy client we need to do next for example:

<pre>
        // Build client executor to use proxy
        HttpClient httpClient = createProxyHttpClient(proxyHost, proxyPort, proxyUser, proxyPassword);
        ClientExecutor clientExecutor = createClientExecutor(httpClient);
        authorizeClient.setExecutor(clientExecutor);
</pre>

I think we can do than automatically.

Base client can detect if there are system properties with proxy configuration and use it if needed : -Dhttp.proxyHost=proxy.server.com -Dhttp.proxyPort=80, etc...

**Comment by yurem** [comment]
Alternatively we can try to next:
1) Create default executor
2) get client
3) set client parameters
httpClient.getParams().setParameter(org.apache.http.conn.params.ConnRoutePNames.DEFAULT_PROXY, new HttpHost(proxyHost, proxyPort, "http"));
and 
httpClient.getCredentialsProvider().setCredentials(new AuthScope(proxyHost, proxyPort), new UsernamePasswordCredentials(proxyUser, proxyPassword));

**Comment by willow9886** [comment]
@yurem do we need to keep this issue open?

**Comment by yurem** [comment]
The is similar problem with oxAuth server when it not have access to internet

[org.xdi.oxauth.client.TokenClient] accounts.google.com INFO | jvm 1 | 2017/02/23 06:31:30 | java.net.UnknownHostException: accounts.google.com
...
redirect_uri=http://localhost/etc&grant_type=authorization_code&code=4/aCFOEvnbl-O53SoR1TV6e7F9_juaAtQjYPIxe0JvT9M" https://accounts.google.com/o/oauth2/token

**Comment by aliaksander-samuseu** [comment]
Quoting @yurem :
> oxAuth server should also be able to work with a web proxy

**Comment by aliaksander-samuseu** [comment]
@yurem @willow9886 

The reason we revisited it now after two years was because of [this ticket](https://support.gluu.org/authentication/3798/google-authentication/)
User didn't have issues when he was using the gplus custom auth script when machine where Gluu was installed was connected to Internet directly, but when it was placed in DMZ from where Internet could be only accessed through web proxy requiring user/pass authentication, it failed to access Google's servers. Setting default systems proxy settings didn't help, though with curl they could utilize them and traverse proxy successfully.

**Comment by nynymike** [comment]
No consensus on this after 5 years. Closing!
