### ISSUE TITLE
Basic login promp

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#90]
oxAuth display Basic login prompt after logout from one application and attempt to log into another application.

Steps to reproduce:
1) Install CE with oxAuth + oxTrust + oxIdp
2) Open oxTrust URL. Example: https://c65.gluu.info/identity
3) Log in
4) Log out
5) Open https://c65.gluu.info/idp/Authn/RemoteUser
6) Browser display Basic login prompt

In oxAuth logs there are next messages:
2015-11-05 13:14:29,538 TRACE [org.xdi.oxauth.service.SessionIdService] Found session_id cookie: '33bdb603-f1db-4ce3-a180-31f5b2678873'
2015-11-05 13:14:29,543 TRACE [org.xdi.oxauth.auth.AuthenticationFilter] Process Session Auth, sessionId = 33bdb603-f1db-4ce3-a180-31f5b2678873, requireAuth = true
2015-11-05 13:14:29,544 DEBUG [org.xdi.oxauth.model.error.ErrorResponseFactory] Looking for the error with id: invalid_client
2015-11-05 13:14:29,544 DEBUG [org.xdi.oxauth.model.error.ErrorResponseFactory] Found error, id: invalid_client

**Comment by mzico** [comment]
+1

**Comment by nynymike** [comment]
Was this issued resolved in 2.4.1 ?

**Comment by yuriyz** [comment]
This issue was discussed in skype at 24-25 November and fixed with these commits in oxauth side

https://github.com/GluuFederation/oxAuth/commit/7b84eb54d32a400b30eea1c00b6d18f969d0eb20
https://github.com/GluuFederation/oxAuth/commit/f9f75573dc43ac9bc1ade8b413fbfe73117b2d9c

Also there were some commits from @yurem side. Yura, please post commits here so we have history for the issue.

**Comment by yurem** [comment]
Yes Yuriy, we discussed it with you and Zico at 25 Nov.
2.4.0 doesn't contain these changes.
1) cat /opt/tomcat/webapps/identity/WEB-INF/components.xml |grep revisionDate
            <property name="revisionDate">17.11.2015 @ 13:56:11 EST</property>
2) cat /opt/tomcat/webapps/oxauth/META-INF/MANIFEST.MF | grep Implementation
Implementation-Title: oxAuth Server
Implementation-Version: 3.0.3-SNAPSHOT
Implementation-Vendor-Id: org.xdi
Implementation-Build: 7b84eb54d32a400b30eea1c00b6d18f969d0eb20

Zico, can you execute same command on server where you find this issue. We need to make sure that we deployed 2.4.1 wars with build time > 25 Now. We need to check if this is the same issue or not.

**Comment by mzico** [comment]
@nynymike: It's resolved in 2.4.1.
