### ISSUE TITLE
Remove sessionIdEnabled Property

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxAuth#900]
While testing `sessionIdEnabled` I've found that turning it to `false` will open a pop-up window where it is necessary to input credentials again. See the image below:

![screenshot from 2018-09-12 13-15-58](https://user-images.githubusercontent.com/30447907/45445693-8bb15280-b690-11e8-9527-69a3d1c7faa3.png)

**Comment by nynymike** [comment]
Please confirm if this is still a bug in latest release. Also, what is the point of this property?

**Comment by aliaksander-samuseu** [comment]
@yuriyz 
I still can reproduce it. Could you look?

**Comment by yuriyz** [comment]
@nynymike I'm not sure what `sessionIdEnabled=false` means. According to git history it comes from initial commit when we moved from svn. I propose to remove this property unless someone can explain what is the expected behavior of oxauth with `sessionIdEnabled=false`.

**Comment by yuriyz** [comment]
after checking property usages, it seems it turns off authentication by session_id in authenticator. Do we want to keep it ? If yes, then we can investigate why popup is shown if not then we can drop it.

**Comment by shmorri** [comment]
@yuriyz Is there a use case for this? If it doesn't add much value, let's not keep it.

**Comment by yuriyz** [comment]
I don't see usecase for `sessionIdEnabled=false`. I think we should remove this property.

**Comment by shmorri** [comment]
Ok. I'll update the issue name to reflect this.

**Comment by yuriyz** [comment]
Fixed in 4.3.1, master and jans.
