### ISSUE TITLE
Super Gluu created time needs time zone support

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#901]
The time zone of the server might be different from the time zone of the subject. For this reason, the server needs to specify the timezone in the QR code "created" field. See line 352:

https://github.com/GluuFederation/oxAuth/blob/master/Server/integrations/super_gluu/SuperGluuExternalAuthenticator.py#L352

Probably best to use the same time zone, like iat 
```
iat
      REQUIRED. Time at which the JWT was issued. Its value is a JSON 
      number representing the number of seconds from 1970-01-01T0:0:0Z
      as measured in UTC until the date/time.
```

**Comment by corriganjeff** [comment]
You guys may come up with a different solution but here was my fix for the immediate need:
Install pip's pytz
in the script:
`import pytz`
then down where the mt_auth_request_dictionary is build:
```
        .....
        pytztime = pytz.utc.localize(datetime.datetime.utcnow())
        .....
            mt_auth_request_dictionary = {
                                "aud": client_id,
                                "state": session_id,
                                "created": pytztime.strftime('%Y-%m-%dT%H:%M:%S%z'),
        .....
```

which in the qr code results give the following value:

```
{
....
,"created":"2018-10-01T16:33:47+0000"
....
}
```

This would require adding/including pytz to the chroot during install.

**Comment by yurem** [comment]
Fixed
