### ISSUE TITLE
OTP doesn't work in centos6

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxAuth#907]
Preconditions: At least 1 user and one admin account created.

Steps:

1. Follow the docs and set up OTP as your default auth in a fresh VM with centos6 (RC6, Firefox)
2. Scan the QR and enter the code as admin
3. Log in to oxtrust
4. Wait for several minutes (10-15)
5. Change the password of the user
6. Log out
7. Try to log in again

Neither user can log in again. The message always says the following:
<img width="646" alt="centos6_rc6final_otp" src="https://user-images.githubusercontent.com/38302725/45860668-c2cbe600-bdab-11e8-8169-2275c224a27e.png">

[2018_09_21.jetty.log.tar.gz](https://github.com/GluuFederation/oxAuth/files/2403925/2018_09_21.jetty.log.tar.gz)
[oxauth_logs.tar.gz](https://github.com/GluuFederation/oxAuth/files/2403926/oxauth_logs.tar.gz)
[oxtrust_logs.tar.gz](https://github.com/GluuFederation/oxAuth/files/2403927/oxtrust_logs.tar.gz)

**Comment by yurem** [comment]
It’s time based authentication method. Hence time on server and your mobile phone should be in sync.
Can you check if the time is the same on both devices before checking it?

**Comment by sahiliamsso** [comment]
@natt-tester - Please check on c6 instance

**Comment by natt-tester** [comment]
@sahiliamsso, @yurem, checked on c6, it works.
