### ISSUE TITLE
Add support for encrypting Request Objects sent to the OP

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxAuth#91]
Client Metadata (OpenID Connect Dynamic Client Registration):
request_object_encryption_alg
request_object_encryption_enc

**Comment by nynymike** [comment]
If this is not implemented, are these OP discovery claims incorrect?

```
 "request_object_encryption_alg_values_supported": [
        "RSA1_5",
        "RSA-OAEP",
        "A128KW",
        "A256KW"
    ],
    "request_object_encryption_enc_values_supported": [
        "A128CBC+HS256",
        "A256CBC+HS512",
        "A128GCM",
        "A256GCM"
    ],
```

**Comment by qbert2k** [comment]
oxAuth supports encrypted JWE Authorization Request Object.

This is a very old issue.
