### ISSUE TITLE
oxAuth Should "Round Robin" Or "Least Connected" LDAP Server List

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxAuth#916]
I'm under the impression that oxAuth attempts to connect to the LDAP servers in the list of LDAP servers based on the order of the list. It would be ideal if oxAuth would utilize multiple servers in a more performant manner and distribute the load.

**Comment by afroDC** [comment]
For example, Shibboleth can point to multiple LDAP URL's and has an attribute called `connectionStrategy` which has multiple methods when multiple servers are present:

```
If Multiple URLs were provided as the ldapURL this describes how each URL will be processed.

DEFAULT - Indicates that the default JNDI provider behavior will be used
ACTIVE_PASSIVE (default value) - Indicates that the first LDAP URL will be used for every request unless it fails and then the next LDAP URL will be used.
ROUND_ROBIN - Indicates that for each new connection the next LDAP url in the list (circling back to the start of the list when the end is reached) will be used
RANDOM - Indicates that for each new connection a random LDAP url will be selected
```

From [https://wiki.shibboleth.net/confluence/display/IDP30/LDAPConnector#LDAPConnector-Attributes](https://wiki.shibboleth.net/confluence/display/IDP30/LDAPConnector#LDAPConnector-Attributes)

**Comment by nynymike** [comment]
It should be configurable. For writes, there is no advantage to round robin, because all writes are replicated. There is an existing ticket to enable you to specify different servers for read and write operations, which would enable you to improve read performance.
