### ISSUE TITLE
Specify Minimum ACR for clients

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#920]
Customers want to be able to force a certain level of authentication to access certain clients. Is it possible to look at the `client_id`, and if the current session does not match the required acr, to force authentication with the requisite acr.

**Comment by yuriyz** [comment]
Session tracks all clients that take part in SSO. So indeed we can check whether required level of acr is set per client or not. Do we want to have it as relative level number as defined by `auth_level_mapping` (on well-known json), e.g. `50`  or set acr e.g. `otp`?
```
"auth_level_mapping": {
        "-1": ["auth_ldap_server"],
        "50": ["otp"],
        "100": ["basic"],
        "10": ["u2f"],
        "15": ["super_gluu"]
    }
````
I can take over it if needed.

**Comment by qbert2k** [comment]
There is already an array of default requested Authentication Context Class Reference values (default_acr_values) per client that can be override/forced by the request parameter acr_values.

**Comment by nynymike** [comment]
But only in the authentication phase. So if a person is already logged in, these are ignored. What we want to do is force reauthentication. For example, before a code is sent back to the client

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/63
