### ISSUE TITLE
Session Revocation

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#921]
Some customers want to be able to revoke sessions for a user. 

Mike: I think this feature was to enable an admin to kill a session for a user…
of course, how the application would be notified is a different question

**Comment by afroDC** [comment]
We talked about this before @yuriyz . A nice EE feature would be being able to somehow monitor the tokens that are distributed and have the ability to revoke them. I believe this would require storing that session and token data with identifiers in a way that makes it easy to identify what has access and the ability to revoke it.

**Comment by nynymike** [comment]
This is sort of related to logout....

**Comment by yuriyz** [comment]
Session Revocation is going to be implemented via separate endpoint (similar to Token Revocation):

Sample request:
```
POST /revoke_session HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW

userCriterionKey=uid&usercriterionValue=yuriy
```

Sample response:
```
HTTP/1.1 200 OK
```
Similar to Token Revocation, response is always 200 even if no sessions were found. Idea is to not disclose internal information.

cc @nynymike

**Comment by yuriyz** [comment]
Session Revocation endpoint requires `revoke_session` scope in token, otherwise request is rejected.

**Comment by yuriyz** [comment]
Done in 4.2
