### ISSUE TITLE
Encrypt oxAuth login information which are showing in HAR file

### ISSUE THREAD

**Issue by mzico** [GluuFederation/oxAuth#922]
A login request har file contain credential in almost text format. If possible let's encrypt that info in java script. I don't have much description to state here so please ping me if you want to know more. 

It might be possible to achieve by hashing that password with nonce.

**Comment by aliaksander-samuseu** [comment]
@yurem @mzico 

We also could consider using public key cryptography for encrypting credentials. As if we assume that TLS/SSL may fail, or HAR may end in wrong hands, hash may be re-used by a malicious user "as is", at least under certain conditions. In addition, we'll need to hash password in such way it's still can be processed by LDAP server (we need to use it in a bind operation to validate creds) - and in case when a backend LDAP server is used, this becomes *any* LDAP server existing in the world.. This also increases complexity, and may affect compatibility with other components.  We also won't be able to hide usernames like this, as we need them in plaintext to do searches in said directories.

If we encrypt creds with a asymmetric algorithm, we can recover plaintext later at backend, and proceed as if they never were altered (I guess, some kind of filter could be added to oxAuth which would strip this encryption and push the regular request "down the pipe")

I also think it should be an optional feature too. A lot of things it can interfere with. For example, custom login pages which may submit login form differently, with differently named fields etc.

**Comment by nynymike** [comment]
I don't understand this issue. What is a har file?
