### ISSUE TITLE
Allow users to edit list of released scopes on the fly on the authorization page

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#928]
As of 3.1.4, when an user is asked to approve release of their personal attributes, they are limited to only Allow or Deny the whole list of claims at once. It probably would be useful to allow them also interactively remove some claims they won't like this particular RP to have on the fly, by un-checking them on the authorization page, and release the rest.

I'm not perfectly sure, but [this enhancement](https://github.com/GluuFederation/oxAuth/issues/738) may suggest something similar to this already. There could be an additional per-scope control which would make it user-controllable in the manner described above.

**Comment by willow9886** [comment]
I don't know this is a valid enhancement request. The app asks for required user attributes..if the user doesn't want to share those attributes, they are not allowed yo access the app. I've never seen a scenario where the user can state what they want to share or not share. Closing this issue.
