### ISSUE TITLE
Update test jwks data to conform latest code

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#93]
In order to support old jwks I added method which try to load public key from jwks with old format and on null result it try load public key from jwks with new format: JwtUtil.getPublicKey

**Comment by yurem** [comment]
We need to remove this method:
private static org.xdi.oxauth.model.crypto.PublicKey getPublicKeyOldImpl(String jwksUri, String jwks, SignatureAlgorithm signatureAlgorithm, String keyId)

https://github.com/GluuFederation/oxAuth/blob/master/Model/src/main/java/org/xdi/oxauth/model/util/JwtUtil.java#L695

**Comment by yurem** [comment]
We have to use old method because there are test data with old jwks:
https://github.com/GluuFederation/oxAuth/blob/master/Server/src/test/resources/client/jwks.json

**Comment by willow9886** [comment]
@yurem has this been resolved? If not, should we leave it in 2.4.2 or move it?
