### ISSUE TITLE
Improve error page for Super Gluu denied authentication

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxAuth#935]
Please replace the marked string with:

**Authentication denied. If this was in error, please try again.**

<img width="1244" alt="replace" src="https://user-images.githubusercontent.com/38302725/48196574-06ec6780-e3a7-11e8-92b3-d77637ddd7ac.png">

**Comment by syntrydy** [comment]
@natt-tester this the general error page for the application. We can change that just to mach super  gluu  specific stuff.

Last time i remember i designed a more generic page but that was remove.

**Comment by natt-tester** [comment]
@syntrydy, if we can, let's make it as informative as possible. We can discuss changes for other authentication methods as well.

**Comment by syntrydy** [comment]
Moving this 4.1 as that require some time to define a strategy for each custom script to provide its own messages.
