### ISSUE TITLE
FIDO 2: Add support for multi facet app IDs for impl

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#936]
FIDO v1 has a mechanism consisting of a json file in order to aggregate applications using the same application ID.

For FIDO 2 we must ensure multiple apps can use the same app ID as well

**Comment by willow9886** [comment]
Shouldn't the app ID be the end IDP? @jgomer2001 @yurem

**Comment by willow9886** [comment]
It seems like we're unnecessarily hardcoding the app redirect URI.. the target app your logging into is not relevant to Super Gluu.

**Comment by yurem** [comment]
Sum up from chat about this issue:
1. From Facet Spec: `concept which does not attempt to strongly identify the calling application to a service across a network.`
2. Valid applications in FaceId json are applications which belong to same DNS which FacetId has.
Example from spec:
```
Example 4

{
  "trustedFacets" : [{
    "version": { "major": 1, "minor" : 0 },
    "ids": [
        "https://register.example.com",              // DISCARD, does not share  "companyA.hosting.example.com" label
        "https://fido.companyA.hosting.example.com", // VALID, shares "companyA.hosting.example.com" label
        "https://xyz.companyA.hosting.example.com",  // VALID, shares "companyA.hosting.example.com" label
        "https://companyB.hosting.example.com"       // DISCARD, "companyB.hosting.example.com" does not match 
     ]
  }]
}
For this policy, "https://fido.companyA.hosting.example.com" would have access to the keys registered for this AppID, and "https://register.example.com" and "https://companyB.hosting.example.com" would not as a public-suffix exists between these DNS names and the AppID's. 
```

Our application_id provides the same what these 2 points have. And not requires to update U2F code:

**Comment by yurem** [comment]
In 4.2. there is new `Fido2 Server Configuration` tab in JSON Configuration tab.
On this page you can define `requestedParties`. Each RP should have name and multiple domains.
