### ISSUE TITLE
Change error message and string in twiliosms page

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxAuth#939]
As reported [here](https://support.gluu.org/authentication/6294/twilio-2fa-error-message-for-an-incorrect-verification-code/#at41329), we should have an error message for wrong credentials and another one for entering an incorrect Twilio code displayed right under the code field. I suggest:

**Incorrect Twilio code. Please try again.**

Also, I think we're missing the phone number in the second marked string:
<img width="989" alt="twilio" src="https://user-images.githubusercontent.com/38302725/48525198-1d992f80-e87b-11e8-8842-c1c20a50adfb.png">

Let's discuss it and unify the layout for all error pages.

**Comment by natt-tester** [comment]
@syntrydy, we need either a full stop + space after **Incorrect Twilio code**, or a comma + space and **please try again.**:

- Incorrect Twilio code. Please try again.
**_or_** 
- Incorrect Twilio code, please try again.

**Comment by syntrydy** [comment]
hmm

**Comment by maximerouillard** [comment]
Thank you for fixing this quickly. What about adding the phone number?
From business and security perpectives it should be great if we can add the
phone with some masked numbers. For example :  *A text message with a
verification code was send to +41 78 xxx xx 12*

Sometimes users have several mobile : often one professional and one
personal.

Regards,
Maxime

**Comment by syntrydy** [comment]
![image](https://user-images.githubusercontent.com/7513418/48671764-8576a100-eb2d-11e8-89b9-3d94211741e7.png)

![image](https://user-images.githubusercontent.com/7513418/48671791-ca023c80-eb2d-11e8-932a-56d9dc132fac.png)
