### ISSUE TITLE
Fix ClientAuthenticationFilterEmbeddedTest

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#94]
I've disabled this test before 2.4.0 release, since after security issue fix in oxauth it starts to fail. All other tests are passed.

https://github.com/GluuFederation/oxAuth/commit/55b5bbaeb6d134da2b7cde78c3aa81ea083c685d

**Comment by willow9886** [comment]
@yuriyz @yurem what is the impact of this test failing? can you add some more details?

**Comment by yuriyz** [comment]
@willow9886 it's better to address this question to Javier but briefly we got regression with client authentication that uses custom attributes. @qbert2k is it correct?
