### ISSUE TITLE
Allow to return custom parameters to RP

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#940]
It's related to https://github.com/GluuFederation/oxAuth/issues/647
We need to add `boolean` option near to each custom parameter name in JSON configuration. When this option is `true` oxAuth should return custom parameter back to RP.

Today we fixed collision between Gluu IDP and passport-saml. Both of them send in state jwt with additional custom parameters. We added workaround. But this new option will help to resolve this issue.

**Comment by yurem** [comment]
Also we return AuthZ custom parameters as headers which led to clean up them on redirect. I think we need to return them in response: https://github.com/GluuFederation/oxAuth/blob/b33ad60927f21dad9648f453c45d82341bbc3350/Client/src/test/java/org/xdi/oxauth/ws/rs/AuthorizationResponseCustomHeaderTest.java#L81

**Comment by martynaslawinska** [comment]
The issue has been moved to Janssen: https://github.com/JanssenProject/jans-auth-server/issues/62

**Comment by yurem** [comment]
Since date when we opened this issue we developed more poverfull tools to allow implement this. For example we can use idToken script to return them as claims, etc.. Hence this update is not required now.
