### ISSUE TITLE
Support  OAuth MTLS Client Authentication and Certificate Bound Access                                  Tokens

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#946]
See https://www.ietf.org/id/draft-ietf-oauth-mtls-12.txt

This may also impact client registration and the oxTrust OpenID cliet configuration form... open more issues as necessary.

Client Authentication details should also be included in the token introspection response.

**Comment by yuriyz** [comment]
I've added documentation about MTLS itself. However we also need documentation how to configure apache for PKI and self-signed certificate validation. Opened separate ticket for it here:

https://github.com/GluuFederation/docs-ce-prod/issues/148

**Comment by yuriyz** [comment]
Re-open, MTLS should go as separate module (FE, Enterprise). Right now it's in main codebase.

**Comment by yuriyz** [comment]
MTLS is FE/Enterprise feature, therefore it is extracted into separate maven module which is build separately and should be dropped into CE (for now put under `WEB-INF/lib` of `oxauth.war` file untill we have better approach.). Artifact can be found here: https://ox.gluu.org/maven/org/xdi/oxauth-mtls
