### ISSUE TITLE
Review Jboss embedded in authentication filter

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#95]
In order to fix test Yuriy Z applied: https://github.com/GluuFederation/oxAuth/commit/a460c1dea462d3d44eddc23033c17f991032ae08
It's right approach.

We need to review this approach in 2.4.1. I also updated test profile:
https://github.com/GluuFederation/community-edition-setup/commit/100ea157af5280e3eb9488f2ee433b0031d35de5

**Comment by willow9886** [comment]
@yurem is this going to make into 2.4.2 or should we push it into a later milestone?

**Comment by yurem** [comment]
Fixed
