### ISSUE TITLE
Remove completely authorization by `access_token` from Authorization Endpoint 

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#957]
We deprecated this functionality here https://github.com/GluuFederation/oxAuth/issues/911

In 4.0 we plan to completely remove it.

**Comment by yuriyz** [comment]
@nynymike @qbert2k @yurem I'm going to remove `access_token` parameter from Authorization Endpoint as it was discussed a few months ago. This is incompatible change but we have to do it since exchange token by `access_token` doesn't seem to be use case we want to support. What do you think? Any objections?

**Comment by yuriyz** [comment]
I consider silence as consent ).

**Comment by nynymike** [comment]
I don't see access_token as parameter in [OAuth 4.1.1](https://tools.ietf.org/html/rfc6749#section-4.1.1), so it's ok with me. And I don't understand why you would pass the access token to the authoriztion endpoint, as it is not a protected endpoint.

**Comment by yuriyz** [comment]
Done in master.
