### ISSUE TITLE
More flexibilty to set audience on a per client basis

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#958]
During client registration, allow specification of additional values as audience for a client. The claim should be called `additional_audience` and the value should be a list of string. This should be present in the id_token and access_token as the actual value of `aud`. Note: if only one value is present, the `aud` value in the token should be a string. Otherwise a list of strings.

**Comment by yuriyz** [comment]
@willow9886 told that you guys (@nynymike @yurem ) already discussed this ticket, so if there anything that should be added to ticket please add.

**Comment by yuriyz** [comment]
Implemented in 4.2. Added `additional_audience` to docs and swagger spec.
