### ISSUE TITLE
Authenticator should not depend on any ACR methods

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#959]
We need to move this code to script and avoid adding script specifc code to oxAuth:
https://github.com/GluuFederation/oxAuth/blame/e7249b0f9ccb1578a971e52dec04dd361f7af9ae/Server/src/main/java/org/xdi/oxauth/auth/Authenticator.java#L711

**Comment by syntrydy** [comment]
**Authenticator should not depend on any ACR methods** but the **Authenticator error messahe should depend on ACR methods**
We can't just use **Username or password incorrect** for each ACR.

For **Twilio for example** the error message should be **Invalid code** .

**Comment by syntrydy** [comment]
Okay, Agreed.

I think we can move this to 4.0, the time to decide how each ACR can make his **messages(error messages/success messages)**  available from Authenticator class.
