### ISSUE TITLE
UMA Optimization : user JWT as RPT.

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#96]
Use a signed JWT as the RPT token signed to enable the RS to avoid calling the introspection API. 

There is an issue for this in UMA:  https://github.com/KantaraInitiative/wg-uma/issues/51

Eve pointed out  "that we’ve just been waiting for someone to want it badly enough to write a profile for us to consider. A locally inspectable token would be attractive for some IoT use cases (though maybe a JWT wouldn’t be the best format for those — there are other candidates).  There are the usual tradeoffs: entitlement freshness vs. ability for the RS to be disconnected at run time (with attendant performance benefits throughout the ecosystem). If you do this and want us to consider standardizing it, by all means submit it!"

**Comment by yuriyz** [comment]
This one is already implemented in uma2 branch and is duplicate of #111.

**Comment by yuriyz** [comment]
One remark about this request that it makes perfect sense for Gluu invented OAuth2 access management using GAT. Since during token creation we also authorize the token, so GAT as JWT makes perfect sense. At the same time RPT as JWT is not really useful since during token creation RPT is not yet authorized and therefore JWT will not contain any useful information.

**Comment by nynymike** [comment]
yes, I think it only makes sense in lieu of the final bearer token
