### ISSUE TITLE
Not getting Super Gluu push notification 

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxAuth#964]
Enable Super Gluu, and register device on first attempt,
Try to login again, and you will see following message "A Super Gluu push notification has been sent to your registered device. Approve the push to login"

But not getting any push notification on the registered device.

**Comment by yurem** [comment]
Can you check if there is key associated with this server in mobile authenticator? I suspect it's mobile application issue. It not store enrolled keys.

**Comment by willow9886** [comment]
yes, @sahiliamsso is there a key generated inside your super gluu "keys" page?

**Comment by yurem** [comment]
@sahiliamsso I can't reproduce it. Issue with keys is gone after all keys removal from Super Gluu mobile app
