### ISSUE TITLE
Store missing IDP name for passport inbound

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#968]
> In passport, when a user is provisioned, we store in oxExternalUid the remote uid of the user like this:
passport-github:theuser, however, if the external provider is a SAML IDP, it just does passport-saml:theuser.

For casa integration, I need a way to know the actual IDP 

> Actually the passport-saml:... thing is bad because there can be two different people with the same uid at 2 distinct IDPs, but our cust script thinks it’s the same person

We agreed on using a separate attribute to preserve backwards compatibility instead of changing the format of `oxExternalUid`

```
oxExternalUid: passport-saml:myuser1
oxExternalUid: passport-saml:myuser2
separateAttr: myuser1:SAMLIDP1
separateAttr: myuser2:SAMLIDP2
```

this is a person with two accounts at two IDPs, for instance

**Comment by yurem** [comment]
I offer to use oxExternalId only. We can store inside it more attributes if needed.

**Comment by jgomer2001** [comment]
New format will be `passport-saml:provider:externalUid`. Script migrates old format to newer
