### ISSUE TITLE
RPT customization interception script

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#97]
Right now the RPT contains permissions, but if we are passing the RPT as a signed JWT, it may be convenient to enable an organization to extend the JWT schema to include other information. This enhancement would allow an organization to use an interception script to populate additional RPT values.

**Comment by yurem** [comment]
Let me give you quick HOWTO add new custom script type. It's based on UMA authorization script type. Here are steps to update oxService (sub project of oxCore):
1. Add interface which you are planning to use in workflow:
https://github.com/GluuFederation/oxCore/blob/master/oxService/src/main/java/org/xdi/model/custom/script/type/uma/AuthorizationPolicyType.java
2. Add dummy implementation of interface from step 1: https://github.com/GluuFederation/oxCore/blob/master/oxService/src/main/java/org/xdi/model/custom/script/type/uma/DummyAuthorizationPolicyType.java
3. Add line like this to allow use it in service classes: https://github.com/GluuFederation/oxCore/blob/master/oxService/src/main/java/org/xdi/model/custom/script/CustomScriptType.java#L49
4. If there is no special properties for this script type step 3 is enough. If you need to display dropdown, etc.. use class AuthenticationCustomScript for reference. By default we uses CustomScript. It's enough for most cases.

**Comment by yurem** [comment]
Here are steps to update oxAuth (sub project of oxCore):
1. Notify oxAuth CustomScriptManager that it should load new script type. You should add your new script typy to array in method appInitializer.postInitialization: https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/service/AppInitializer.java#L122
2. Copy https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/service/external/ExternalUmaAuthorizationPolicyService.java to new class. This will be pattern for new script type service
3. Use pattern like this to call your new script type service:
<code>
        final CustomScriptConfiguration customScriptConfiguration = externalUmaAuthorizationPolicyService.getAuthorizationPolicyByDn(authorizationPolicyDn);
        if (customScriptConfiguration != null) {
            final boolean result = externalUmaAuthorizationPolicyService.executeExternalAuthorizeMethod(customScriptConfiguration, authorizationContext);
            log.trace("Policy '{0}' result: {1}", authorizationPolicyDn, result);
...
        } else {
            log.error("Unable to load custom script dn: '{0}'", authorizationPolicyDn);
        }
</code>

**Comment by yurem** [comment]
Here are steps to update oxTrust:
1. Add new script type to array in method ApplianceService.getCustomScriptTypes to allow edit script in GUI

**Comment by yurem** [comment]
Using this new API it's it's possible to add new script quickly, withing few hours. The main problem is an interface. We need to prepare object which we should pass to script to allow custom changes. Example:
<code>
	public boolean authorize(Object authorizationContext, Map<String, SimpleCustomProperty> configurationAttributes);
</code>
We need to prepare something like authorizationContext for this new script type.

**Comment by nynymike** [comment]
UMA 2.0 re-design will make this issue moot.
