### ISSUE TITLE
Empty postlogin page

### ISSUE THREAD

**Issue by natt-tester** [GluuFederation/oxAuth#972]
In 3.1.5_4, when they fail to scan the QR code for OTP withing the given time, the user is redirected to an empty postlogin page. 
@syntrydy  reports it occurs for passport_social as well, so it might be a common case for social scripts. 

<img width="789" alt="obraz" src="https://user-images.githubusercontent.com/38302725/50275118-fec02700-043e-11e9-9668-6dee03f7650a.png">

**Comment by yurem** [comment]
@natt-tester Can you try to deploy into this VM https://ox.gluu.org/maven/org/xdi/oxauth-server/3.1.5-SNAPSHOT/oxauth-server-3.1.5-SNAPSHOT.war  ant test on it?

**Comment by yurem** [comment]
Fixed in recent oxauth.war build
