### ISSUE TITLE
Markup bug in Fido u2f xhtml page 

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#973]
Latest commit on this file /auth/u2f/login.xhtml breaks JSF EL expressions: https://github.com/GluuFederation/oxAuth/commit/a4ea59a3219ff21aa20c3017d71c92326e9aecfd#diff-2eb9ec2b281389ead88206ccc19f6312R25

leading to javascript errors...

Please check if other files involved in the commit are not suffering from the same formatting problem

**Comment by yurem** [comment]
Fixed @jgomer2001 Thank you for checking this
