### ISSUE TITLE
Unable to Enroll device - 404 Error in oxtrust

### ISSUE THREAD

**Issue by sfright** [GluuFederation/oxAuth#976]
After a fresh install of gluu using the steps described in https://github.com/GluuFederation/gluu-docker/tree/3.1.4/examples/single-host

I enabled super gluu as described https://gluu.org/docs/ce/authn-guide/supergluu/

I installed the latest version of the app as shown in the app store 3.9 (android), however upon enrollment i receive an error visually on the screen saying "Failed to get Fido U2F metadata"

The server logs indicate that the app is calling out to a URL that does not exist as part of oxauth but i am unsure if this is expected and/or ive done something wrong along the way:

```
2018-12-28 14:03:42,891 ERROR [qtp1514322932-21] [org.xdi.oxauth.exception.UncaughtException] (UncaughtException.java:41) - Jersey error.
javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path: http://my-public-url.com/oxauth/restv1/fido-u2f-configuration
```

**Comment by willow9886** [comment]
Please open as an issue on gluu support : 

https://support.gluu.org 

Thanks in advance.
