### ISSUE TITLE
oxAuth throws error for unsupported ui_locales 

### ISSUE THREAD

**Issue by centroxy** [GluuFederation/oxAuth#978]
As per OpenID Standard
**ui_locales** is defined like below.

OPTIONAL. End-User's preferred languages and scripts for the user interface, represented as a space-separated list of BCP47 [RFC5646] language tag values, ordered by preference. For instance, the value "fr-CA fr en" represents a preference for French as spoken in Canada, then French (without a region designation), followed by English (without a region designation). An error SHOULD NOT result if some or all of the requested locales are not supported by the OpenID Provider.

However in oxAuth is throwing error if Client application does not pass proper locale expected by oxAuth

The Expected result is, it should not throw error if the locales are not supported. And whatever is passed to the ui_locales as parameter should go to the AS ( Correct me if I am wrong)

Working locales - en, fr, ru , it etc
Errors for  -  fr-CA, en-US , el-GR, or any string 

https://idp/oxauth/restv1/authorize?client_id=%40%21F94C.8845.6EB5.B574%210001%21FB0D.FB04%210008%21E1F8.503E.153E.C2E7&redirect_uri=https%3A%2F%2Fclient.example.com%3A44394%2Fcallback&response_mode=form_post&response_type=code%20id_token&scope=openid%20profile&state=OpenIdConnect.AuthenticationProperties%3Dt2FzxsMYyzZQZG7p5rAlLSrpJ1lF1HmqLJPOzMTfRkhdRfxdMZZvTrclW-FfVOfCPuNxoGTUpP_gNbX-RJtLcB-xW4zZE7CBpkxGU9E5sQoPLBczrceoHHk9pe_oSPXtKkSqkCq0BTmyw1Dt3wDfl-Ix2tMuVEY76iJFTqKL7SUCDc7pU-gwGxKdRHfN7TsW&nonce=636820247511639844.MGRjN2IxMmYtYzU4Mi00NzEzLWEzYmQtZjcwNjI2NDE4OTE3MjEwMGY3MTQtNjZlZC00ZmQ5LTg2NDUtNTJlZDJiOWY3MWY5&ui_locales=fr-CA%20fr%20en&x-client-SKU=ID_NET451&x-client-ver=5.2.2.0

**Comment by syntrydy** [comment]
@centroxy Which gluu version?

**Comment by centroxy** [comment]
Gluu 3.1.4 version

**Comment by syntrydy** [comment]
This is already fixed.
