### ISSUE TITLE
Group similar non-searchable attributes to reduce schema size

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#979]
I think we need to try to make schema minimal. We need new attribute only if we do LDAP search.

We can store oxSoftwareId, oxSoftwareVersion, oxSoftwareStatement as JSON in one attribute only. Our Persistence layer supports automatic JSON <-> Bean conversion.

Example:
	@LdapAttribute(name = "oxSmtpConfiguration")
	@LdapJsonObject
	private SmtpConfiguration smtpConfiguration;

**Comment by nynymike** [comment]
Already did something similar.
