### ISSUE TITLE
Revisit dirty trick with identity.logout()

### ISSUE THREAD

**Issue by yuriyz** [GluuFederation/oxAuth#98]
https://github.com/GluuFederation/oxAuth/commit/f9f75573dc43ac9bc1ade8b413fbfe73117b2d9c

**Comment by willow9886** [comment]
@yuriyz do we need to keep this open? Please don't reference customer accounts on Github.

**Comment by yuriyz** [comment]
@willow9886 lets close it. We need wider refactoring and it has to be scheduled separately. Closing it.
