### ISSUE TITLE
Update session AuthZ parameters on ACR change

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#984]
Here s flow which used @jgomer2001 for testings:

- Loginto oxTrust as admin
- Set the oxtrust openid client with persist_client_authz = true and pre_authz = false
- Logout
- Log in to an app A (using an acr of level value 1)
- Try to hit oxTrust /identity
- In this case, no login form is shown. That’s OK
- The consent screen is displayed, press “allow”
- You are taken to app A! not to oxTrust.

**Comment by yurem** [comment]
The issue is here: https://github.com/GluuFederation/oxAuth/blob/version_3.1.5/Server/src/main/java/org/xdi/oxauth/service/SessionIdService.java#L159
This exception break the flow

**Comment by jgomer2001** [comment]
Just to add a bit more of context to interested parties:
If the consent to oxTrust was allowed before attempting to login to app A, there is no problem, the following happens:
- Login to app A
- Login to oxTrust (success and no login form shown)

**Comment by yurem** [comment]
@jgomer2001 I opened another issue because it's another problem

**Comment by jgomer2001** [comment]
I'm sorry, but still facing the same problem described at the [top](https://github.com/GluuFederation/oxAuth/issues/984#issue-400851518) with latest 3.1.6 oxtrust/oxauth war

**Comment by jgomer2001** [comment]
https://github.com/GluuFederation/oxAuth/commit/8b6892535777dcd8c56d3638029e988adbf9fbb9
https://github.com/GluuFederation/oxAuth/commit/4e933eb8e5c6c51f8ae24798193f3012fe13d497

Solved with yura's commits
