### ISSUE TITLE
Consent form not shown when second client start authorization

### ISSUE THREAD

**Issue by yurem** [GluuFederation/oxAuth#986]
Just to add a bit more of context to interested parties:
If the consent to oxTrust was allowed before attempting to login to app A, there is no problem, the following happens:
- Login to app A
- Login to oxTrust (success and no login form shown)

_Originally posted by @jgomer2001 in https://github.com/GluuFederation/oxAuth/issues/984#issuecomment-455795640_

**Comment by jgomer2001** [comment]
I think you misunderstood my comment on 984 issue. I was simply describing a proper behavior. I'm closing this
