### ISSUE TITLE
invalid_grant_and_session, wrong description?

### ISSUE THREAD

**Issue by orditeck** [GluuFederation/oxAuth#995]
Hi,

Looking at [the contexts](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/session/ws/rs/EndSessionRestWebServiceImpl.java) where `INVALID_GRANT_AND_SESSION` is used, I feel like [this line](https://github.com/GluuFederation/oxAuth/blob/14f8004eed2049c0818469e961e8c3de19a47e89/Server/conf/oxauth-errors.json#L104) should be 
```js
"description": "The provided id token and session state are invalid or were issued to another client.",
```
instead of
```js
"description": "The provided access token and session state are invalid or were issued to another client.",
```

`id token` instead of `access token`. Otherwise it makes the `error_description` misleading.
Can PR if needed.

**Comment by yuriyz** [comment]
done in master (4.0)
